Particular/docs.particular.net

README.md

@Particular/docs-maintainers documenting https://github.com/Particular/DocsEngine/pull/341 in README.

Document sample inline download option

---

samples/hosting/docker/Core_7/Docker.sln
samples/hosting/docker/Core_7/Docker.sln.DotSettings
samples/hosting/docker/Core_7/Receiver/Dockerfile
samples/hosting/docker/Core_7/Receiver/Program.cs
samples/hosting/docker/Core_7/Receiver/Receiver.csproj
samples/hosting/docker/Core_7/Receiver/RequestMessageHandler.cs
samples/hosting/docker/Core_7/Sender/Dockerfile
samples/hosting/docker/Core_7/Sender/Program.cs
samples/hosting/docker/Core_7/Sender/ResponseMessageHandler.cs
samples/hosting/docker/Core_7/Sender/Sender.csproj
samples/hosting/docker/Core_7/Shared/RabbitHelper.cs
samples/hosting/docker/Core_7/Shared/RequestMessage.cs
samples/hosting/docker/Core_7/Shared/ResponseMessage.cs
samples/hosting/docker/Core_7/Shared/Shared.csproj
samples/hosting/docker/Core_7/docker-compose.yml
samples/hosting/docker/sample.md

This is a minimum viable sample to show how to run endpoints in Docker containers.

Hosting endpoints in Docker containers

---

Snippets/ASB/ASB_8/MultipleNamespaces.cs
transports/azure-service-bus/multiple-namespaces-support.md
transports/azure-service-bus/multiple-namespaces-support_alias_asb_[7,).partial.md
transports/azure-service-bus/multiple-namespaces-support_registered-endpoint_asb_[8,).partial.md

Describes the new API introduced in https://github.com/Particular/NServiceBus.AzureServiceBus/pull/623
The package hasn't been released so this build is expected to fail.

Send over namespace

---

samples/containers/index.md
samples/index.md

Added DI to distinguish DI containers from os containers

---

nservicebus/pipeline/message-mutators.md

We are moving away from providing DI for mutators in the future, see https://github.com/Particular/NServiceBus/pull/4978#issuecomment-332515975

Guiding users needing DI for mutators towards the pipeline

---

nservicebus/upgrades/6to7/index.md

See https://github.com/Particular/NServiceBus/issues/3921 for details

Upgrade guide entry for the namespace move of StorageType

---

Snippets/ASB/ASB_8/MultipleNamespaces.cs
transports/azure-service-bus/multiple-namespaces-support_registered-endpoint_asb_[8,).partial.md

Describes cross namespace subscriptions for endpoint oriented topology

cross namespace subscriptions

---

Snippets/Testing/Testing_6/UpgradeGuides/6to7/ExpectSagaCompleted.cs
Snippets/Testing/Testing_7/Saga/MyResponse.cs
Snippets/Testing/Testing_7/Saga/Tests.cs
Snippets/Testing/Testing_7/UpgradeGuides/5to6/UsingWhen.cs
Snippets/Testing/Testing_7/UpgradeGuides/6to7/ExpectSagaCompleted.cs
menu/menu.yaml
nservicebus/upgrades/testing-6to7.md

documents the breaking changes made by https://github.com/Particular/NServiceBus.Testing/issues/100

Add testing upgrade guide

---

samples/pubsub/sample.md

Sounds like this sample is going to be used as a landing page for @indualagarsamy's monoliths blog post.
@dbelcham please take a look.

Make Pub/Sub sample a better landing page

---

Snippets/SqlPersistence/SqlPersistence_3/Usage.cs

fixes https://github.com/Particular/docs.particular.net/issues/3287

Fixes #3287 - Include required subscription setting in SQL usage

---

Snippets/Wormhole/Wormhole.sln
Snippets/Wormhole/Wormhole_2/EndpointSide.cs
Snippets/Wormhole/Wormhole_2/Wormhole_2.csproj

WIP until there is a beta nuget

WIP: wormhole to nsb v7

---

samples/pipeline/dispatch-notifications/Core_6/DispatchNotification.sln
samples/pipeline/dispatch-notifications/Core_6/DispatchNotification.sln.DotSettings
samples/pipeline/dispatch-notifications/Core_6/SampleApp/ConfigExtensions.cs
samples/pipeline/dispatch-notifications/Core_6/SampleApp/DispatchNotificationBehavior.cs
samples/pipeline/dispatch-notifications/Core_6/SampleApp/DispatchNotificationFeature.cs
samples/pipeline/dispatch-notifications/Core_6/SampleApp/IWatchDispatches.cs
samples/pipeline/dispatch-notifications/Core_6/SampleApp/Program.cs
samples/pipeline/dispatch-notifications/Core_6/SampleApp/SampleApp.csproj
samples/pipeline/dispatch-notifications/Core_6/SampleApp/SampleDispatchWatcher.cs
samples/pipeline/dispatch-notifications/Core_6/SampleApp/SomeMessage.cs
samples/pipeline/dispatch-notifications/Core_6/SampleApp/SomeMessageHandler.cs
samples/pipeline/dispatch-notifications/Core_7/DispatchNotification.Core.sln
samples/pipeline/dispatch-notifications/Core_7/DispatchNotification.Core.sln.DotSettings
samples/pipeline/dispatch-notifications/Core_7/DispatchNotification.sln
samples/pipeline/dispatch-notifications/Core_7/DispatchNotification.sln.DotSettings
samples/pipeline/dispatch-notifications/Core_7/SampleApp/ConfigExtensions.cs
samples/pipeline/dispatch-notifications/Core_7/SampleApp/DispatchNotificationBehavior.cs
samples/pipeline/dispatch-notifications/Core_7/SampleApp/DispatchNotificationFeature.cs
samples/pipeline/dispatch-notifications/Core_7/SampleApp/IWatchDispatches.cs
samples/pipeline/dispatch-notifications/Core_7/SampleApp/Program.cs
samples/pipeline/dispatch-notifications/Core_7/SampleApp/SampleApp.Core.csproj
samples/pipeline/dispatch-notifications/Core_7/SampleApp/SampleApp.csproj
samples/pipeline/dispatch-notifications/Core_7/SampleApp/SampleDispatchWatcher.cs
samples/pipeline/dispatch-notifications/Core_7/SampleApp/SomeMessage.cs
samples/pipeline/dispatch-notifications/Core_7/SampleApp/SomeMessageHandler.cs
samples/pipeline/dispatch-notifications/sample.md

Shows how to extend the pipeline to get notifications of every dispatch in a generic way.
Could be used to do this https://github.com/Particular/NServiceBus.AmazonSQS/issues/147

[WIP] Dispatch Notifications Sample

---

nservicebus/messaging/delayed-delivery.md
nservicebus/messaging/delayed-delivery_handlecurrentmessagelater_core_[,6].partial.md
nservicebus/upgrades/6to7/index.md

relates to https://github.com/Particular/NServiceBus/pull/4991

Deprecate HandleCurrentMessageLater

---

Snippets/Core/Core_6/CriticalErrors.cs
Snippets/Core/Core_7/CriticalErrors.cs
nservicebus/hosting/critical-errors.md
nservicebus/hosting/critical-errors_default_core_[3,4).partial.md
nservicebus/hosting/critical-errors_default_core_[4,5).partial.md
nservicebus/hosting/critical-errors_default_core_[5,6).partial.md
nservicebus/hosting/critical-errors_default_core_[6,7).partial.md
nservicebus/hosting/critical-errors_default_core_[7,].partial.md
nservicebus/hosting/windows-service.md
nservicebus/upgrades/6to7/index.md

Related to https://github.com/Particular/NServiceBus/pull/4994

Doco and upgrade guide for new v7 critical error default

---

nservicebus/upgrades/acs-host-7to8.md
nservicebus/upgrades/host-7to8.md
nservicebus/upgrades/host-deprecate.include.md

Fixes https://github.com/Particular/docs.particular.net/issues/3260.

Clarify NuGet behavior.

---

persistence/upgrades/ravendb-3to4.md

Connects to https://github.com/Particular/PlatformDevelopment/issues/1443

RavenDB upgrade guide: Migrate saga data if using AllowStaleSagaReads

---

samples/azure/self-host/Core_6/HostWorker/HostWorker.csproj
samples/azure/self-host/Core_6/HostWorker/VerificationLogger.cs
samples/azure/self-host/Core_6/HostWorker/app.config
samples/azure/self-host/Core_7/HostWorker/HostWorker.csproj
samples/azure/self-host/Core_7/HostWorker/VerificationLogger.cs
samples/azure/self-host/Core_7/HostWorker/app.config
samples/azure/shared-host/CloudServicesHost_7/HostWorker/HostWorker.csproj
samples/azure/shared-host/CloudServicesHost_7/HostWorker/app.config
samples/azure/shared-host/CloudServicesHost_7/Receiver/Receiver.csproj
samples/azure/shared-host/CloudServicesHost_7/Receiver/app.config
samples/azure/shared-host/CloudServicesHost_7/Sender/Sender.csproj
samples/azure/shared-host/CloudServicesHost_7/Sender/app.config
samples/azure/shared-host/CloudServicesHost_7/Shared/Shared.csproj
samples/azure/shared-host/CloudServicesHost_8/HostWorker/HostWorker.csproj
samples/azure/shared-host/CloudServicesHost_8/HostWorker/app.config
samples/azure/shared-host/CloudServicesHost_8/Receiver/Receiver.csproj
samples/azure/shared-host/CloudServicesHost_8/Receiver/app.config
samples/azure/shared-host/CloudServicesHost_8/Sender/Sender.csproj
samples/azure/shared-host/CloudServicesHost_8/Sender/app.config
samples/azure/shared-host/CloudServicesHost_8/Shared/Shared.csproj

* update app.config
* made VerificationLogger more resilient

Locking down to Azure storage 8.5

---

persistence/azure-storage/index.md

Fixes #3052 
@weralabaj how about this?

Correlation property restrictions

---

Snippets/Core/Core_6/Scanning/ScanningPublicApi.cs
Snippets/Core/Core_7/Scanning/ScanningPublicApi.cs

Only used in the 5 to 6 upgrade guide so its safe to remove
Closes https://github.com/Particular/docs.particular.net/issues/3340

Remove incorrect snippets

---

platform/servicecontrol.include.md

Fixes https://github.com/Particular/docs.particular.net/issues/3243

Clarify sc vs sc instances 2

---

transports/msmq/operations-scripting.md

Fixes https://github.com/Particular/docs.particular.net/issues/3305

Added a clarifying note for powershell scripts.

---

persistence/sql/index.md

Add info about what max object name length is supported for each DB engine.

supported object/identifier name lengths

---

transports/msmq/troubleshooting.md

Based on https://eu1.salesforce.com/apex/Case?num=00031575

Guidance on MessageQueueException (0x80004005): Message Queue service is not available.

---

Snippets/Core/Core_7/Hosting/StartUpDiagnostics.cs
nservicebus/hosting/index.md
nservicebus/hosting/index_diagnostics_core_[7,).partial.md

This documents the [startup diagnostics](https://github.com/Particular/NServiceBus/pull/5004) that will be emitted on startup as of core v7

Startup diagnostics doco

---

nservicebus/recoverability/index.md

Typo. retricted should be restricted

Typo in index.md

---

nservicebus/bridge/index.md

@SzymonPobiega I'd like to add this clarification to the doco

Clarification

---

transports/azure-storage-queues/delayed-delivery.md
transports/upgrades/asq-7to8.md

Closes https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/284
@Particular/azure-maintainers please review

ASQ upgrade guide update - turning off delayed delivery

---

Snippets/Metrics/Metrics.sln
Snippets/Metrics/Metrics_1.1/Configuration.cs
Snippets/Metrics/Metrics_1.1/Metrics_1.1.csproj
Snippets/Metrics/Metrics_1/Configuration.cs
Snippets/Metrics/Metrics_1/Metrics_1.csproj
Snippets/Metrics/Metrics_2/Configuration.cs
Snippets/Metrics/Metrics_2/Metrics_2.csproj
Snippets/Metrics/Metrics_3/Configuration.cs
Snippets/Metrics/Metrics_3/Metrics_3.csproj

This PR introduces `NServiceBus.Metrics 3.0` aligned to `v7` of the core.
The prerequisite to merge this is:

Metrics 3.0 snippets

---

nservicebus/hosting/index_diagnostics_core_[7,).partial.md

Clarify that the structure of the json diagnostics data isn't stable

---

Snippets/CloudServicesHost/CloudServicesHost_8/AzureConfigurationSourceReplacement.cs
Snippets/CloudServicesHost/CloudServicesHost_8/CloudServicesHost_8.csproj
Snippets/CloudServicesHost/CloudServicesHost_8/Usage.cs
nservicebus/upgrades/acs-host-7to8.md

Closes https://github.com/Particular/NServiceBus.Host.AzureCloudService/issues/88
Documents how users can achieve behavior similar to the original azure configuration source. How to retrieve config settings from either roleenvironment if available, or from xml config otherwise.

Azure configuration source replacement

---

Snippets/MsmqTransport/Core_6/ConfigureTransport.cs
Snippets/MsmqTransport/MsmqTransport_1/ConfigureTransport.cs
samples/index.md
samples/routing/data-distribution/sample.md
samples/routing/fair-distribution/sample.md
samples/routing/file-based-routing/sample.md
samples/routing/instance-mapping-file/sample.md
samples/scaleout/senderside-and-distributor/sample.md
transports/msmq/index.md
transports/msmq/index_default_core_(,6].partial.md
transports/msmq/index_default_core_5.partial.md
transports/msmq/index_default_core_6.partial.md
transports/msmq/index_default_msmqtransport_[1,).partial.md

Fixes https://github.com/Particular/docs.particular.net/issues/3334
- Added configuration snippet
- Added advantages and disadvantages of the transport.

Improvement to the MSMQ transport page

---

Snippets/MetricsServiceControl/MetricsServiceControl_2/MetricsServiceControl_2.csproj
Snippets/MetricsServiceControl/MetricsServiceControl_3/MetricsServiceControl_3.csproj
nservicebus/operations/metrics-service-control.md
nservicebus/operations/metrics-service-control_interval_metricsservicecontrol_[1,).partial.md

This PR upgrades snippets to new versions of `NServiceBus.Metrics.ServiceControl` betas and provides documentation for `interval` parameter.

NServiceBus.Metrics.ServiceControl updated to new betas

---

nservicebus/messaging/callbacks_route_callbacks_[1,).partial.md

@andreasohlund @danielmarbach I made a few revisions to the text from #3385.

Tweak wording of callbacks route partial

---

samples/logging/application-insights/Metrics_2/Endpoint/Endpoint.csproj
samples/logging/application-insights/Metrics_2/Endpoint/Program.cs

This have been smoke tested on my Azure account.

Metrics Azure App Insights sample updated to 2.0

---

nservicebus/upgrades/6to7/index.md

Based on comment by @weralabaj on Slack.

Added exception info when passing MSMQ connection string

---

nservicebus/operations/metrics.md

ping @Particular/metrics-maintainers

Retry metric definition

---

nservicebus/upgrades/6to7/index.md

Closes https://github.com/Particular/docs.particular.net/issues/3402

Clarify that messages can't be routed to send only endpoints

---

tutorials/intro-to-nservicebus/2-sending-a-command/Solution/ClientUI/Program.cs
tutorials/intro-to-nservicebus/3-multiple-endpoints/Solution/ClientUI/Program.cs
tutorials/intro-to-nservicebus/3-multiple-endpoints/tutorial.md

Hi,
Small changes proposal.
Regards
Michał

small changes proposal

---

samples/saga/migration/Core_6/Server.New/DrainTempQueueSatelliteFeature.cs
samples/saga/migration/Core_6/Server.New/Server.New.csproj
samples/saga/migration/Core_6/Server.New/TestSaga.cs
samples/saga/migration/Core_6/Server/TestSaga.cs
samples/saga/migration/Core_7/Server.New/DrainTempQueueSatelliteFeature.cs
samples/saga/migration/Core_7/Server.New/Program.cs
samples/saga/migration/Core_7/Server.New/TestSaga.cs
samples/saga/migration/Core_7/Server/Program.cs

Fixes https://github.com/Particular/docs.particular.net/issues/3411

Fixed the saga migration sample

---

nservicebus/messaging/uniformsession.md

An attempt to better state the behavior of IUniformSession and what it represents.
Removed the list about the different behavior, as https://docs.particular.net/nservicebus/messaging/send-a-message gives a better and completer explanation.

Clarify IUniformSession behavior

---

nservicebus/hosting/nservicebus-host/logging-configuration.md
nservicebus/hosting/nservicebus-host/logging-configuration_customize_host_[,4].partial.md
nservicebus/hosting/nservicebus-host/logging-configuration_customize_host_[5,].partial.md
nservicebus/logging/index.md

https://github.com/Particular/docs.particular.net/issues/3054

Fix for #3054 

---

nservicebus/operations/tuning.md

As per a discussion with @rensvind

Clarify that restart is needed for tuning to take effect

---

nservicebus/azure/azure-storage-performance-tuning.include.md
persistence/azure-storage/configuration.md

Improve doco for AssumeSecondaryIndicesExist setting

---

samples/dependency-injection/unity/Unity_9/Sample/MyHandler.cs
samples/dependency-injection/unity/Unity_9/Sample/MyMessage.cs
samples/dependency-injection/unity/Unity_9/Sample/MyService.cs
samples/dependency-injection/unity/Unity_9/Sample/Program.cs
samples/dependency-injection/unity/Unity_9/Sample/Sample.csproj
samples/dependency-injection/unity/Unity_9/UnitySample.sln
samples/dependency-injection/unity/Unity_9/UnitySample.sln.DotSettings

Adds a V9 sample for the net core project

Add v9 sample for unity

---

Snippets/Testing/Testing_6/UpgradeGuides/6to7/WhenHandling.cs
Snippets/Testing/Testing_7/UpgradeGuides/6to7/WhenHandling.cs
nservicebus/upgrades/testing-6to7.md

Upgrade guide changes for https://github.com/Particular/NServiceBus.Testing/pull/121

NSB.Testing - Add override to upgrade guide

---

tools/setStartup.linq

since in 1.4 of SetStartupProjects the "StartupProjects.txt" convention is built in
Note that this change can also be applied to the docs engine

remove redundant GetStartupProjects

---

persistence/msmq/index.md

This page is only accessible via search, but contained incorrect and very little data.

Fixed 'index' page for MSMQ Subscription storage

---

samples/dependency-injection/unity/Unity_8/Sample/Program.cs
samples/dependency-injection/unity/Unity_8/Sample/Sample.csproj

Chnages the V8 sample to point to the now-new v8 release

Update unity sample to v8

---

menu/menu.yaml

Fixes https://github.com/Particular/docs.particular.net/issues/3453

Expose Monitoring instances

---

transports/sql/transactions_ambient-core-warning_sqltransport_[4,).partial.md

Based on https://github.com/Particular/NServiceBus.SqlServer/issues/417

Made the .net core 2.0 incompatibility more discoverable

---

nservicebus/operations/dotnet-framework-version-requirements.md

based on http://eu1.salesforce.com/apex/Case?num=00033069

Added 'atleast' to identity that that is the minimal version requirement

---

nservicebus/operations/metrics/index.md

Connects to https://github.com/Particular/LaunchWave.DevOpsAdvancedMonitoring/issues/321

Note on some QueueLength estimation limitations

---

Snippets/MetricsServiceControl/MetricsServiceControl.sln
Snippets/MetricsServiceControl/MetricsServiceControl_1.1/Configuration.cs
Snippets/MetricsServiceControl/MetricsServiceControl_1.1/MetricsServiceControl_1.1.csproj

Snippets for NServiceBus.Metrics.ServiceControl 1.1

NServiceBus.Metrics.ServiceControl 1.1

---

Snippets/MsLogging/nuget.config
samples/endpoint-configuration/Core_7/nuget.config
samples/hosting/windows-service/Core_7/nuget.config
samples/hosting/windows-service/sample_netcore_core_[7.0,).partial.md

Related to https://github.com/Particular/docs.particular.net/issues/3141

Bump ServiceController

---

Snippets/ASB/ASB_7/AddressingStrategies/NamespacePartitioning.cs
Snippets/ASB/ASB_8/AddressingStrategies/NamespacePartitioning.cs
Snippets/ASB/ASB_8/Upgrade7to8.cs
samples/azure/custom-partitioning-asb/ASB_7/Publisher/Publisher.csproj
samples/azure/custom-partitioning-asb/ASB_7/Publisher/ReplicatedNamespacePartitioningStrategy.cs
samples/azure/custom-partitioning-asb/ASB_7/Subscriber1/Subscriber1.csproj
samples/azure/custom-partitioning-asb/ASB_7/Subscriber2/Subscriber2.csproj
samples/azure/custom-partitioning-asb/ASB_8/Publisher/ReplicatedNamespacePartitioningStrategy.cs
transports/azure-service-bus/multiple-namespaces-support.md
transports/azure-service-bus/multiple-namespaces-support_caching_asb_[7,).partial.md
transports/azure-service-bus/multiple-namespaces-support_caching_asb_[8,).partial.md
transports/upgrades/asb-7to8.md

- Namespace partitioning strategies caching (`ICacheSendingNamespaces`)
- Upgrade guide
- Code snippets
- custom-partitioning-asb sample update

ASB 7.2.10/8.0.0 namespace partitioning doco updates

---

menu/menu.yaml
nservicebus/outbox/index.md
persistence/sql/outbox.md

Related to https://github.com/Particular/docs.particular.net/issues/3383

Add basic info about Outbox in SQL persistence

---

Snippets/Core/Core_5/Handlers/DataAccess/Managed.cs
Snippets/Core/Core_5/Handlers/DataAccess/MyOrmExtensions.cs
Snippets/Core/Core_6/Handlers/DataAccess/Managed.cs
Snippets/Core/Core_6/Handlers/DataAccess/MyOrmExtensions.cs
Snippets/Core/Core_7/Handlers/DataAccess/Managed.cs
Snippets/Core/Core_7/Handlers/DataAccess/MyOrmExtensions.cs

Clarify that users must provide the idempotency check

---

transports/azure-service-bus/configuration/full.md
transports/azure-service-bus/configuration/full_queues_asb_[,8).partial.md
transports/azure-service-bus/configuration/full_subscriptions_asb_[,8).partial.md
transports/azure-service-bus/configuration/full_subscriptions_asb_[8,).partial.md
transports/upgrades/asb-7to8.md

~~**DO NOT** merge until PR https://github.com/Particular/NServiceBus.AzureServiceBus/pull/688 is merged.~~

ASB documentation changes related to v8

---

samples/azure/shared-host/CloudServicesHost_8/Receiver/EndpointConfig.cs
samples/azure/shared-host/CloudServicesHost_8/Sender/EndpointConfig.cs

Serialization for endpoints must be configured.
@Particular/azure-maintainers please review and merge

Azure shared host sample fix (NServiceBus v7)

---

persistence/upgrades/asp-6to1.md

Based on https://discuss.particular.net/t/facing-issue-while-upgrading-nservicebus-5-x-to-6-x/231

Mentioning exceptions

---

samples/performance-counters/PerfCounters_3/PerfCounters.sln
samples/performance-counters/PerfCounters_3/PerfCounters.sln.DotSettings
samples/performance-counters/PerfCounters_3/Sample/MyHandler.cs
samples/performance-counters/PerfCounters_3/Sample/MyMessage.cs
samples/performance-counters/PerfCounters_3/Sample/Program.cs
samples/performance-counters/PerfCounters_3/Sample/Sample.csproj
samples/performance-counters/PerfCounters_3/Sample/app.manifest

This PR introduces a sample for 3.0 of `NServiceBus.Metrics.PerformanceCounters`

Performance counters 3 - sample

---

samples/nhibernate/custom-mappings/NHibernate_6/Sample.Fluent/Program.cs
samples/nhibernate/custom-mappings/NHibernate_7/Sample.Fluent/Program.cs
samples/nhibernate/custom-mappings/NHibernate_8/Sample.Fluent/Program.cs

FYI @Particular/nhibernate-persistence-maintainers

Use correct name for CustomNhMappings.Fluent sample

---

tutorials/monitoring-demo/index.md

Building as a PR to check whether the build server will like it

Switch Monitoring demo to direct download

---

samples/pipeline/session-filtering/Core_6/Receiver/Program.cs
samples/pipeline/session-filtering/Core_6/Receiver/Receiver.csproj
samples/pipeline/session-filtering/Core_6/Sender/Program.cs
samples/pipeline/session-filtering/Core_6/Sender/Sender.csproj
samples/pipeline/session-filtering/Core_6/SessionFilter.sln
samples/pipeline/session-filtering/Core_6/SessionFilter.sln.DotSettings
samples/pipeline/session-filtering/Core_6/SessionFilter/ApplySessionFilterHeader.cs
samples/pipeline/session-filtering/Core_6/SessionFilter/ConfigExtensions.cs
samples/pipeline/session-filtering/Core_6/SessionFilter/FilterIncomingMessages.cs
samples/pipeline/session-filtering/Core_6/SessionFilter/ISessionKeyProvider.cs
samples/pipeline/session-filtering/Core_6/SessionFilter/RotatingSessionKeyProvider.cs
samples/pipeline/session-filtering/Core_6/SessionFilter/Shared.csproj
samples/pipeline/session-filtering/Core_6/SessionFilter/SomeMessage.cs
samples/pipeline/session-filtering/Core_7/Receiver/Program.cs
samples/pipeline/session-filtering/Core_7/Receiver/Receiver.csproj
samples/pipeline/session-filtering/Core_7/Sender/Program.cs
samples/pipeline/session-filtering/Core_7/Sender/Sender.csproj
samples/pipeline/session-filtering/Core_7/SessionFilter.sln
samples/pipeline/session-filtering/Core_7/SessionFilter.sln.DotSettings
samples/pipeline/session-filtering/Core_7/SessionFilter/ApplySessionFilterHeader.cs
samples/pipeline/session-filtering/Core_7/SessionFilter/ConfigExtensions.cs
samples/pipeline/session-filtering/Core_7/SessionFilter/FilterIncomingMessages.cs
samples/pipeline/session-filtering/Core_7/SessionFilter/ISessionKeyProvider.cs
samples/pipeline/session-filtering/Core_7/SessionFilter/RotatingSessionKeyProvider.cs
samples/pipeline/session-filtering/Core_7/SessionFilter/Shared.csproj
samples/pipeline/session-filtering/Core_7/SessionFilter/SomeMessage.cs
samples/pipeline/session-filtering/sample.md

Only contains v6 version for now

Session Filter Sample

---

Snippets/Heartbeats/Heartbeats6_3/UpgradeGuide/DisablePlugin.cs
nservicebus/upgrades/nservicebus.heartbeat.md

Heartbeats feature internal

---

get-started.md

As part of https://github.com/Particular/LaunchWave.DevOpsAdvancedMonitoring/issues/388

Added section about monitoring demo

---

samples/nhibernate/simple/NHibernate_7/Server/Program.cs

I ran the sample and it didn't result in the schema to be created.

NHibernate simple sample EnableInstallers added to have the schema created.

---

samples/azure/custom-partitioning-asb/ASB_7/Publisher/CircularBuffer.cs
samples/azure/custom-partitioning-asb/ASB_7/Publisher/DataDistributionPartitioningStrategy.cs
samples/azure/custom-partitioning-asb/ASB_7/Publisher/Instruction.cs
samples/azure/custom-partitioning-asb/ASB_7/Publisher/NamespaceOutageEmulator.cs
samples/azure/custom-partitioning-asb/ASB_7/Publisher/Program.cs
samples/azure/custom-partitioning-asb/ASB_7/Publisher/RoundRobinWithFailoverPartitioningStrategy.cs
samples/azure/custom-partitioning-asb/ASB_8/Publisher/CircularBuffer.cs
samples/azure/custom-partitioning-asb/ASB_8/Publisher/DataDistributionPartitioningStrategy.cs
samples/azure/custom-partitioning-asb/ASB_8/Publisher/Instruction.cs
samples/azure/custom-partitioning-asb/ASB_8/Publisher/NamespaceOutageEmulator.cs
samples/azure/custom-partitioning-asb/ASB_8/Publisher/Program.cs
samples/azure/custom-partitioning-asb/ASB_8/Publisher/RoundRobinWithFailoverPartitioningStrategy.cs
samples/azure/custom-partitioning-asb/sample.md
transports/azure-service-bus/multiple-namespaces-support.md

Connects to https://github.com/Particular/docs.particular.net/pull/3541
Fixes https://github.com/Particular/NServiceBus.AzureServiceBus/issues/505
Sample updated to demonstrate two custom strategies
1. Data distribution strategy
1. Round-Robin with failover

ASB custom namespace partitioning sample with 2 strategies

---

nservicebus/gateway/httpvnext-channel.md

@welshdave rearranged the docs slightly. Please review

HttpVNext cleanup

---

servicepulse/index.md

Added section Real-time Monitoring, showing the announcement video and referencing the tutorial and metric definitions.
Signed-off-by: Ramon Smits <ramon.smits@gmail.com>

Added ServicePulse section for Real-time Monitoring

---

samples/sqs/simple/Sqs_2/Sample/Program.cs
samples/sqs/simple/Sqs_3/Sample/Program.cs

Closes https://github.com/Particular/docs.particular.net/pull/3548

SQS Read region from ENV variable

---

samples/manual-unsubscribe/Core_7/ManualUnsubscribe.sln
samples/manual-unsubscribe/Core_7/ManualUnsubscribe.sln.DotSettings
samples/manual-unsubscribe/Core_7/Messages/ManualUnsubscribe.cs
samples/manual-unsubscribe/Core_7/Messages/Messages.csproj
samples/manual-unsubscribe/Core_7/Messages/SomethingHappened.cs
samples/manual-unsubscribe/Core_7/Publisher/ManualUnsubscribeHandler.cs
samples/manual-unsubscribe/Core_7/Publisher/Program.cs
samples/manual-unsubscribe/Core_7/Publisher/Publisher.csproj
samples/manual-unsubscribe/Core_7/Subscriber/Program.cs
samples/manual-unsubscribe/Core_7/Subscriber/SomethingHappenedHandler.cs
samples/manual-unsubscribe/Core_7/Subscriber/Subscriber.csproj
samples/manual-unsubscribe/Core_7/SubscriptionManager/Program.cs
samples/manual-unsubscribe/Core_7/SubscriptionManager/SubscriptionManager.csproj

This sample is full framework only since it's based on MSMQ

manual unsubscribe V7 sample (full framework only)

---

samples/routing/command-routing/Core_6/CommandRouting.sln
samples/routing/command-routing/Core_6/CommandRouting.sln.DotSettings
samples/routing/command-routing/Core_6/Receiver/CancelOrderHandler.cs
samples/routing/command-routing/Core_6/Receiver/PlaceOrderHandler.cs
samples/routing/command-routing/Core_6/Receiver/Program.cs
samples/routing/command-routing/Core_6/Receiver/Receiver.csproj
samples/routing/command-routing/Core_6/Sender/Program.cs
samples/routing/command-routing/Core_6/Sender/Sender.csproj
samples/routing/command-routing/Core_6/Shared/CancelOrder.cs
samples/routing/command-routing/Core_6/Shared/PlaceOrder.cs
samples/routing/command-routing/Core_6/Shared/Shared.csproj
samples/routing/command-routing/Core_7/CommandRouting.sln
samples/routing/command-routing/Core_7/CommandRouting.sln.DotSettings
samples/routing/command-routing/Core_7/Receiver/CancelOrderHandler.cs
samples/routing/command-routing/Core_7/Receiver/PlaceOrderHandler.cs
samples/routing/command-routing/Core_7/Receiver/Program.cs
samples/routing/command-routing/Core_7/Receiver/Receiver.csproj
samples/routing/command-routing/Core_7/Sender/Program.cs
samples/routing/command-routing/Core_7/Sender/Sender.csproj
samples/routing/command-routing/Core_7/Shared/CancelOrder.cs
samples/routing/command-routing/Core_7/Shared/PlaceOrder.cs
samples/routing/command-routing/Core_7/Shared/Shared.csproj
samples/routing/command-routing/sample.md

Shows how to use `RouteToEndpoint`

Basic command routing sample

---

samples/azure/azure-service-bus-msmq-bridge/ASB_8/Bridge/Program.cs

From breaking change in NServiceBus.Bridge

Fix azure-service-bus-msmq-bridge sample 

---

Snippets/Core/Core_5/Logging/BuiltInConfig.cs
Snippets/Core/Core_6/Logging/BuiltInConfig.cs
Snippets/Core/Core_7/Logging/BuiltInConfig.cs

I copy this snippet almost daily and never want to set the directory. Probably lots of our customers too.

Reordering logger config

---

menu/menu.yaml
nservicebus/upgrades/host-4to5.md

Addresses https://github.com/Particular/docs.particular.net/issues/3506

Host 4to5 upgrade guide.

---

transports/msmq/distributor/configuration.md

Added remark on that Outbox works in combination with MSMQ Distributor

---

samples/servicecontrol/adapter-asb-multi-namespace/SCTransportAdapter_2/Adapter/Adapter.csproj
samples/servicecontrol/adapter-asb-multi-namespace/SCTransportAdapter_2/Adapter/Program.cs
samples/servicecontrol/adapter-asb-multi-namespace/SCTransportAdapter_2/AsbTransportAdapter.sln
samples/servicecontrol/adapter-asb-multi-namespace/SCTransportAdapter_2/AsbTransportAdapter.sln.DotSettings
samples/servicecontrol/adapter-asb-multi-namespace/SCTransportAdapter_2/Sales/OrderShippedHandler.cs
samples/servicecontrol/adapter-asb-multi-namespace/SCTransportAdapter_2/Sales/Program.cs
samples/servicecontrol/adapter-asb-multi-namespace/SCTransportAdapter_2/Sales/Sales.csproj
samples/servicecontrol/adapter-asb-multi-namespace/SCTransportAdapter_2/Shared/AdapterSpecificHeaders.cs
samples/servicecontrol/adapter-asb-multi-namespace/SCTransportAdapter_2/Shared/ChaosGenerator.cs
samples/servicecontrol/adapter-asb-multi-namespace/SCTransportAdapter_2/Shared/ConsoleHelper.cs
samples/servicecontrol/adapter-asb-multi-namespace/SCTransportAdapter_2/Shared/OrderShipped.cs
samples/servicecontrol/adapter-asb-multi-namespace/SCTransportAdapter_2/Shared/Shared.csproj
samples/servicecontrol/adapter-asb-multi-namespace/SCTransportAdapter_2/Shared/ShipOrder.cs
samples/servicecontrol/adapter-asb-multi-namespace/SCTransportAdapter_2/Shipping/Program.cs
samples/servicecontrol/adapter-asb-multi-namespace/SCTransportAdapter_2/Shipping/ShipOrderHandler.cs
samples/servicecontrol/adapter-asb-multi-namespace/SCTransportAdapter_2/Shipping/Shipping.csproj
samples/servicecontrol/adapter-asb-multi-namespace/sample.md

Sample for SC ASB transport adapter with NServiceBus v7
**Blocked** until ASB PR https://github.com/Particular/NServiceBus.AzureServiceBus/pull/696 is merged

SC TransportAdapter for ASB and Core v7

---

servicepulse/install-servicepulse-in-iis.md

Note on reverting SC hostname to localhost

---

security-advisories/asq-alias-for-default-connectionstring.md

Connects to https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/309
Related to https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/312
@Particular/azure-maintainers please review

ASQ vulnerability advisory

---

nservicebus/bridge/index.md

Document talks about samples but doesn't link to the samples that are scattered through various transports. Adding links to the document.

Adding sample links

---

persistence/ravendb/index.md

@bording be my 2nd set of eyes?

Raven netcore

---

samples/endpoint-configuration/sample.md

fixes https://github.com/Particular/docs.particular.net/issues/3586

Remove duplicate sentence

---

Snippets/SqlPersistence/SqlPersistence_4/Usage.cs
persistence/sql/install.md
persistence/sql/install_script-runner_sqlpersistence_[4,).partial.md

Doco for https://github.com/Particular/NServiceBus.Persistence.Sql/pull/252. WIP until released to myget so that snippets can be added

Add doco for ScriptRunner

---

samples/dependency-injection/spring/Spring_8/Sample/Sample.csproj

Doesn't seem like this dependency is need on this sample as far as I can tell?

Remove Common.Logging dependency

---

nservicebus/operations/auditing.md

Clarifying audit filtering after a chat with @SimonCropp

Clarify filtering of audit messages and individual properties

---

nservicebus/upgrades/6to7/index.md

Replace exception name with proper configuration option for v7 auditing

Update auditing upgrade details for v6 to v7

---

samples/consumer-driven-contracts/Core_6/Consumer1/Consumer1.csproj
samples/consumer-driven-contracts/Core_6/Consumer1/Program.cs
samples/consumer-driven-contracts/Core_6/Consumer2/Consumer2.csproj
samples/consumer-driven-contracts/Core_6/Consumer2/Program.cs
samples/consumer-driven-contracts/Core_6/Producer/Producer.csproj
samples/consumer-driven-contracts/Core_6/Producer/Program.cs
samples/consumer-driven-contracts/Core_6/Producer/PublishFullTypeNameOnlyBehavior.cs
samples/consumer-driven-contracts/Core_7/Consumer1/Consumer1.csproj
samples/consumer-driven-contracts/Core_7/Consumer1/Program.cs
samples/consumer-driven-contracts/Core_7/Consumer2/Consumer2.csproj
samples/consumer-driven-contracts/Core_7/Consumer2/Program.cs
samples/consumer-driven-contracts/Core_7/Producer/Producer.csproj
samples/consumer-driven-contracts/Core_7/Producer/Program.cs
samples/consumer-driven-contracts/Core_7/Producer/PublishFullTypeNameOnlyBehavior.cs
samples/consumer-driven-contracts/sample.md

Consumer driven contracts for json

---

nservicebus/operations/installers.md

Based on discussion on installers in https://discuss.particular.net/t/is-there-a-connection-retry-for-the-transport/388

NServiceBus Core - Added note about running least privilege and running installers

---

nservicebus/messaging/callbacks.md
nservicebus/messaging/callbacks_route_callbacks_[1,).partial.md

/cc @Particular/callback-maintainers

clarified unique instance ID's when using callbacks with brokers

---

nservicebus/outbox/index.md

Outbox - Section about concurrency and deduplication

---

persistence/ravendb/outbox.md

Based on discussion on Slack https://particularsoftware.slack.com/archives/C0327U5RG/p1519766430000462

Added note on cleanup task when scaled out

---

tutorials/monitoring-demo/index.md

auto start download and hide button coming from monitoring demo landing page

auto start download and hide button coming from landing page

---

nservicebus/messaging/routing_commands_core_[6,).partial.md

Remove in partial instead

---

samples/pipeline/multi-serializer/Core_6/Shared/MultiSerializerFeature.cs
samples/pipeline/multi-serializer/Core_7/Shared/MultiSerializerFeature.cs

fixes https://github.com/Particular/docs.particular.net/issues/3657

Specify correct step id for replacing connectors

---

nservicebus/upgrades/supported-platforms.md

Connects to https://github.com/Particular/DotNetCoreLaunch/issues/108

.NET Core what isn't supported

---

persistence/sql/index.md

A highlights section bringing together the most important features of the persister.

SqlP Highlights section

---

persistence/ravendb/index.md

https://ravendb.net/docs/article-page/4.0/csharp/client-api/net-client-versions#net-client-versions

Ravendb4 client requires .net version 4.6+

---

nservicebus/upgrades/supported-platforms.md

FYI @Particular/dotnetcore-launch-squad

Tweak list of packages that don't support .NET core

---

transports/sqs/index.md

Connects to https://github.com/Particular/NServiceBus.AmazonSQS/pull/204
Do **NOT** merge until SQS PR https://github.com/Particular/NServiceBus.AmazonSQS/pull/204 is merged and released.

Note about AWS SDK bug

---

nservicebus/messaging/routing.md
nservicebus/messaging/routing_commands_core_[,6).partial.md
nservicebus/messaging/routing_commands_core_[6,7).partial.md
nservicebus/messaging/routing_commands_core_[7,).partial.md

link to MessageEndpointMappings doco

---

tutorials/quickstart/VS2015Solution/Billing/Billing.csproj
tutorials/quickstart/VS2015Solution/Billing/OrderPlacedHandler.cs
tutorials/quickstart/VS2015Solution/Billing/Program.cs
tutorials/quickstart/VS2015Solution/Billing/app.config
tutorials/quickstart/VS2015Solution/Billing/packages.config
tutorials/quickstart/VS2015Solution/ClientUI/ClientUI.csproj
tutorials/quickstart/VS2015Solution/ClientUI/Program.cs
tutorials/quickstart/VS2015Solution/ClientUI/packages.config
tutorials/quickstart/VS2015Solution/Messages/Messages.csproj
tutorials/quickstart/VS2015Solution/Messages/OrderPlaced.cs
tutorials/quickstart/VS2015Solution/Messages/PlaceOrder.cs
tutorials/quickstart/VS2015Solution/Messages/packages.config
tutorials/quickstart/VS2015Solution/RetailDemo.sln
tutorials/quickstart/VS2015Solution/RetailDemo.sln.DotSettings
tutorials/quickstart/VS2015Solution/Sales/PlaceOrderHandler.cs
tutorials/quickstart/VS2015Solution/Sales/Program.cs
tutorials/quickstart/VS2015Solution/Sales/Sales.csproj
tutorials/quickstart/VS2015Solution/Sales/packages.config

Ports the quickstart solution to VS2015

Port of quickstart for VS2015

---

servicepulse/install-servicepulse-in-iis.md

@Particular/servicecontrol-maintainers please review and advise

Configuring monitoring reverse proxy in IIS

---

tutorials/quickstart/tutorial.md

Related to https://github.com/Particular/PlatformDevelopment/issues/1709

Add extra quickstart download for VS2015

---

tutorials/quickstart/create-vs2015-archive.linq

LINQPad script with copied DocsEngine code for creating a zip containing QuickStart VS2015 solution with .suo file.

QuickStart VS2015 solution zipper LINQPad script

---

Snippets/Sqs/Sqs_4/Sqs_4.csproj
Snippets/Sqs/Sqs_All/ClientFactory.cs
Snippets/Sqs/Sqs_All/ErrorQueue/ErrorQueue.cs
Snippets/Sqs/Sqs_All/ErrorQueue/Tests.cs
Snippets/Sqs/Sqs_All/NativeSend/Tests.cs
Snippets/Sqs/Sqs_All/QueueCreation/CloudFormationHelper.cs
Snippets/Sqs/Sqs_All/QueueCreation/CreateEndpointQueues.cs
Snippets/Sqs/Sqs_All/QueueCreation/CreateEndpointQueues.json
Snippets/Sqs/Sqs_All/QueueCreation/CreateEndpointQueuesCloudFormation.cs
Snippets/Sqs/Sqs_All/QueueCreation/QueueCreation.ps1
Snippets/Sqs/Sqs_All/QueueCreation/QueueCreationUtils.cs
Snippets/Sqs/Sqs_All/QueueCreation/QueueCreationUtilsCloudFormation.cs
Snippets/Sqs/Sqs_All/QueueCreation/Tests.cs
Snippets/Sqs/Sqs_All/QueueDeletion/DeleteEndpointQueues.cs
Snippets/Sqs/Sqs_All/QueueDeletion/DeleteEndpointQueuesCloudFormation.cs
Snippets/Sqs/Sqs_All/QueueDeletion/QueueDeletion.ps1
Snippets/Sqs/Sqs_All/QueueDeletion/QueueDeletionUtilsCloudFormation.cs
Snippets/Sqs/Sqs_All/QueueDeletion/Tests.cs
Snippets/Sqs/Sqs_All/QueueNameHelper.cs
Snippets/Sqs/Sqs_All/SqsTransportConfigurationExtensions.cs
Snippets/Sqs/Sqs_All/Sqs_All.csproj
transports/sqs/configuration-options_delayeddelivery_sqs_[2,3).partial.md
transports/sqs/configuration-options_delayeddelivery_sqs_[4,).partial.md
transports/sqs/delayed-delivery.md
transports/upgrades/amazonsqs-3to4.md

SQS Delayed Delivery

---

Snippets/AttachmentsSql/AttachmentsSql_1/AttachmentsSql_1.csproj
Snippets/AttachmentsSql/AttachmentsSql_1/TestingIncoming.cs
Snippets/AttachmentsSql/AttachmentsSql_1/Usage.cs
components/components.yaml
nservicebus/messaging/attachments-sql.md
samples/attachments-sql/AttachmentsSql_1/Endpoint/Endpoint.csproj
samples/attachments-sql/AttachmentsSql_1/Endpoint/Program.cs

- Updated SqlAttachments to the new version of NuGet and made appropriate changes to the snippets and docs according to the changes. 
- Fixed the components yaml to point to the correct GH project URLs for all the repositories under NServiceBusExtensions

Update SQL attachment docs

---

nservicebus/operations/transactions-message-processing.md

Fixes https://github.com/Particular/docs.particular.net/issues/3682

Clarify transaction scope timeouts

---

samples/pipeline/multi-serializer/Core_6/Shared/MultiSerializerFeature.cs
samples/pipeline/multi-serializer/Core_7/Shared/MultiSerializerFeature.cs

To make sure that we actually replace the connector

Use correct connector id

---

samples/hosting/docker/Core_7/Docker.sln
samples/hosting/docker/Core_7/Receiver/Host.cs
samples/hosting/docker/Core_7/Receiver/Program.cs
samples/hosting/docker/Core_7/Receiver/Receiver.csproj
samples/hosting/docker/Core_7/Receiver/license.xml
samples/hosting/docker/Core_7/Sender/Host.cs
samples/hosting/docker/Core_7/Sender/Program.cs
samples/hosting/docker/Core_7/Sender/Sender.csproj
samples/hosting/docker/Core_7/Sender/license.xml
samples/hosting/docker/Core_7/Shared/Shared.csproj
samples/hosting/docker/sample.md

related to https://github.com/Particular/DotNetCoreLaunch/issues/144

Update docker sample to use new project template

---

servicecontrol/servicecontrol-instances/distributed-instances.md

Raised as a result of executing https://github.com/Particular/ServiceControl/pull/1124

Add limitation for plugins for SC distributed scenario

---

nservicebus/hosting/critical-errors_override_core_[3,7).partial.md
nservicebus/hosting/critical-errors_override_core_[7,].partial.md

Cleanup proposal to address https://github.com/Particular/docs.particular.net/pull/3711#pullrequestreview-110387587

Cleanup the critical error override section

---

samples/nhibernate/custom-mappings/NHibernate_8/Shared/Shared.csproj
samples/nhibernate/simple/NHibernate_8/Client/Client.csproj
samples/nhibernate/simple/NHibernate_8/Server/Server.csproj
samples/sqltransport-nhpersistence/Core_7/Receiver/Program.cs
samples/sqltransport-nhpersistence/Core_7/Receiver/Receiver.csproj
samples/sqltransport-nhpersistence/Core_7/Sender/Program.cs
samples/sqltransport-nhpersistence/Core_7/Sender/Sender.csproj
samples/sqltransport/native-integration/SqlTransport_4/Receiver/Program.cs
samples/sqltransport/native-integration/SqlTransport_4/Receiver/Receiver.Core.csproj
samples/sqltransport/simple/SqlTransport_4/Receiver/Program.cs
samples/sqltransport/simple/SqlTransport_4/Sender/Program.cs
samples/sqltransport/simple/SqlTransport_4/Sender/Sender.Core.csproj
samples/web/asp-mvc-application/Core_6/AsyncPagesMVC/Web.config
samples/web/asp-mvc-application/Core_7/AsyncPagesMVC/AsyncPagesMVC.csproj
samples/web/asp-mvc-application/Core_7/AsyncPagesMVC/Web.config
samples/web/asp-mvc-application/Core_7/Server/Server.csproj
samples/web/asp-mvc-application/Core_7/Shared/Shared.csproj
samples/web/asp-web-application/Core_6/WebApplication/WebApplication.csproj
samples/web/asp-web-application/Core_7/Server/Server.csproj
samples/web/asp-web-application/Core_7/Shared/Shared.csproj
samples/web/asp-web-application/Core_7/WebApplication/WebApplication.csproj
samples/web/send-from-mvc-controller/Core_7/WebApplication/Web.config

Connects to https://github.com/Particular/DotNetCoreLaunch/issues/156

Verifying samples

---

Snippets/SagaAudit/SagaAudit6_1/SagaAudit.cs
Snippets/SagaAudit/SagaAudit6_2/SagaAudit.cs
Snippets/SagaAudit/SagaAudit6_3/SagaAudit.cs
Snippets/SagaAudit/SagaAudit_1/API.cs
Snippets/SagaAudit/SagaAudit_2/API.cs
Snippets/SagaAudit/SagaAudit_3/API.cs

Update SagaAudit plugins for consistency

---

nservicebus/sagas/index.md
samples/sql-persistence/saga-rename/sample.md

Closes #3727 
@mauroservienti saw that you where working on a saga tutorial so adding you as a reviewer FYI

Clarify section on saga completion

---

nservicebus/messaging/callbacks-disclaimer.include.md
samples/callbacks/sample.md
samples/web/wcf-callbacks/sample.md

Fix the gap in the documentation.

Add disclaimers to callbacks samples

---

Snippets/Core/Core_6/Audit/AddAuditData.cs
Snippets/Core/Core_7/Audit/AddAuditData.cs
nservicebus/operations/auditing.md
nservicebus/operations/auditing_additional-data_core_[6,).partial.md

fixes https://github.com/Particular/docs.particular.net/issues/3748
cc @SimonCropp

AddAuditData documentation

---

persistence/nhibernate/outbox.md

Copied from the RavenDB doco page.

NHibernate outbox cleanup disable doco

---

transports/azure-service-bus/message-lock-renewal.md

Highlight the connection between LockLostException, message auto-renewal, and prefetching.

---

transports/sql/sql-native.md

@SimonCropp can you check if this is accurate?

Add more info about intended usage scenarios

---

samples/azure/self-host/Core_6/HostWorker/HostWorker.csproj
samples/azure/shared-host/CloudServicesHost_7/Receiver/Receiver.csproj
samples/azure/shared-host/CloudServicesHost_7/Sender/Sender.csproj

@Particular/azure-maintainers please review and merge.

Bump to ASP 1.5.0

---

Snippets/Core/Core_6/Handlers/AsyncHandler.cs
Snippets/Core/Core_7/Handlers/AsyncHandler.cs
nservicebus/handlers/async-handlers.md
tutorials/intro-to-nservicebus/1-getting-started/tutorial.md

After internal discussions we decided to remove the section since we can't really add any value to the guidance provided by MS
Closes https://github.com/Particular/docs.particular.net/issues/3775

Remove configurewawait guidance

---

Snippets/SqlPersistence/SqlPersistence_4/OutboxSettings.cs
persistence/sql/outbox.md
persistence/sql/outbox_settings_sqlpersistence_[4.1,].partial.md

Related to https://github.com/Particular/NServiceBus.Persistence.Sql/issues/210

Document the new outbox settings

---

servicepulse/install-servicepulse-in-iis.md

Update IIS instructions

---

samples/serializers/newtonsoft/Newtonsoft_2/Sample/Sample.Core.csproj

To avoid build error when we NServiceBus.Newtonsoft.Json that depends on json 11

Remove explicit json ref

---

samples/serializers/multiple-deserializers/Core_7/ExternalNewtonsoftBsonEndpoint/ExternalNewtonsoftBsonEndpoint.Core.csproj
samples/serializers/multiple-deserializers/Core_7/ExternalNewtonsoftBsonEndpoint/ExternalNewtonsoftBsonEndpoint.csproj
samples/serializers/multiple-deserializers/Core_7/ExternalNewtonsoftJsonEndpoint/ExternalNewtonsoftJsonEndpoint.Core.csproj
samples/serializers/multiple-deserializers/Core_7/ExternalNewtonsoftJsonEndpoint/ExternalNewtonsoftJsonEndpoint.csproj
samples/serializers/multiple-deserializers/Core_7/ReceivingEndpoint/ReceivingEndpoint.Core.csproj
samples/serializers/multiple-deserializers/Core_7/ReceivingEndpoint/ReceivingEndpoint.csproj
samples/serializers/newtonsoft-bson/Newtonsoft_2/Sample/Sample.Core.csproj
samples/serializers/newtonsoft-bson/Newtonsoft_2/Sample/Sample.csproj
samples/serializers/newtonsoft/Newtonsoft_2/Sample/Sample.csproj
samples/serializers/transitioning-formats/Core_7/SamplePhase1/SamplePhase1.Core.csproj
samples/serializers/transitioning-formats/Core_7/SamplePhase1/SamplePhase1.csproj
samples/serializers/transitioning-formats/Core_7/SamplePhase2/SamplePhase2.Core.csproj
samples/serializers/transitioning-formats/Core_7/SamplePhase2/SamplePhase2.csproj
samples/serializers/transitioning-formats/Core_7/SamplePhase3/SamplePhase3.Core.csproj
samples/serializers/transitioning-formats/Core_7/SamplePhase3/SamplePhase3.csproj
samples/serializers/transitioning-formats/Core_7/SamplePhase4/SamplePhase4.Core.csproj
samples/serializers/transitioning-formats/Core_7/SamplePhase4/SamplePhase4.csproj

Should make master green again

Switch to transitive refs for json

---

samples/serializers/bond/Bond_2/Sample/Sample.Core.csproj
samples/serializers/bond/Bond_2/Sample/Sample.csproj

To make the master build green

Fix bond refs

---

servicecontrol/installation.md

Fixes #3483 
Detail how to uninstall ServiceControl and what may get left behind.

Uninstallation Instructions for SC

---

transports/sqs/index_credentials_sqs_[,4).partial.md
transports/sqs/index_credentials_sqs_[4,).partial.md

Customer forgot to add (mandatory) region code. Added link and short explanation to make it clearer.

Added link to region codes and to the configuration options page

---

servicecontrol/upgrades/1to2.md

Fixes https://github.com/Particular/ServiceControl/issues/1167

Describe new setting

---

tutorials/nservicebus-sagas/1-getting-started/Solution/Shipping/ShipOrderHandler.cs
tutorials/nservicebus-sagas/1-getting-started/tutorial.md

Started addressing TODOs in lesson 1

Saga tutorial - lesson 1 polishing

---

nservicebus/compliance/gdpr.md

Add appropriate values for placeholders.

Replace placeholders

---

persistence/ravendb/index.md

Based on short conversation on Slack. Feel free to change at will and merge.

Added supported RavenDB clustering configurations

---

servicecontrol/servicecontrol-in-practice.md

Fixes https://github.com/Particular/docs.particular.net/issues/3881

Mention audit filter in capacity planning section

---

tutorials/nservicebus-sagas/1-getting-started/tutorial.md

@mauroservienti especially interested for you to compare this to the [intro page introduction](https://github.com/Particular/docs.particular.net/blob/saga-tutorial-intro/tutorials/nservicebus-sagas/index.md) which I did not change. That first paragraph doesn't seem **so bad** if we just replace "In the Introduction to NServiceBus we created a functioning demo of a retail system that" with "When you build a system with asynchronous messaging, you can..."

Optimize saga tutorial lesson 1 for new visitors

---

Snippets/ABSDataBus/ABSDataBus_1/Usage.cs
Snippets/ABSDataBus/ABSDataBus_2/Usage.cs
Snippets/ABSDataBus/Azure_6/Usage.cs
nservicebus/messaging/databus/azure-blob-storage.md

Document disabling blob cleanup in Azure BlobStorage DataBus

Document disabling cleanup in Azure BlobStorage DataBus

---

nservicebus/hosting/windows-service.md
nservicebus/hosting/windows-service_bootstrapper_core_[5,6].partial.md

Addresses https://github.com/Particular/docs.particular.net/issues/3879 by scoping the bootstrapping nuget page to supported versions (v5 + v6).

Windows service hosting

---

servicecontrol/installation-powershell.md

* Fixes the sample script to JustWork (TM)
* Removes the no-longer-supported Unattended Install

Update SC powershell installation

---

nservicebus/dotnet-templates.md

Moves dotnet-new information beginning of the page

---

monitoring/heartbeats/install-plugin.md

The linked section mentions the default value.

Add link to SC queue doco

---

tutorials/nservicebus-step-by-step/1-getting-started/tutorial.md

add link to ConfigureAwait material in step by step tutorial

---

tutorials/nservicebus-step-by-step/2-sending-a-command/tutorial.md

Clarify what's a marker interface

---

samples/header-manipulation/Core_7/Sample/MyHandler.cs

revert unintentional changes from PR 3946

---

tutorials/nservicebus-step-by-step/3-multiple-endpoints/tutorial.md

Add note about C# 7.1 features

---

tutorials/nservicebus-step-by-step/5-retrying-errors/tutorial.md

remove "In systems programming" from step-by-step 5

---

samples/logging/serilog-custom/Serilog_2/Sample/MyHandler.cs
samples/logging/serilog-custom/Serilog_3.0/Sample/MyHandler.cs
samples/logging/serilog-custom/Serilog_4/Sample/MyHandler.cs
samples/logging/serilog-seq/SerilogTracing_2/Sample/CreateUserHandler.cs
samples/logging/serilog-seq/SerilogTracing_2/Sample/CreateUserSaga.cs
samples/logging/serilog-seq/SerilogTracing_2/Sample/UserCreatedHandler.cs
samples/logging/serilog-seq/SerilogTracing_3.0/Sample/CreateUserHandler.cs
samples/logging/serilog-seq/SerilogTracing_3.0/Sample/CreateUserSaga.cs
samples/logging/serilog-seq/SerilogTracing_3.0/Sample/UserCreatedHandler.cs
samples/logging/serilog-seq/SerilogTracing_4/Sample/CreateUserHandler.cs
samples/logging/serilog-seq/SerilogTracing_4/Sample/CreateUserSaga.cs
samples/logging/serilog-seq/SerilogTracing_4/Sample/UserCreatedHandler.cs
samples/scheduling/hangfire/Core_6/Receiver/MyHandler.cs
samples/scheduling/hangfire/Core_6/Receiver/Receiver.csproj
samples/scheduling/hangfire/Core_7/Receiver/MyHandler.cs
samples/scheduling/hangfire/Core_7/Receiver/Receiver.csproj
samples/scheduling/quartz/Core_6/Scheduler/SendMessageJob.cs
samples/scheduling/quartz/Core_7/Scheduler/SendMessageJob.cs

related to https://github.com/NServiceBusExtensions/NServiceBus.Serilog/issues/18

when using serilog should use ILogger for logging

---

nservicebus/upgrades/supported-platforms.md

Since 2.0 is no longer supported by MS

Update wording to mention netcore 2.1 instead of 2.0

---

samples/azure-service-bus-netstandard/index.md
samples/azure-service-bus-netstandard/native-integration/ASBS_1/MessageGenerator/MessageGenerator.Core.csproj
samples/azure-service-bus-netstandard/native-integration/ASBS_1/MessageGenerator/MessageGenerator.csproj
samples/azure-service-bus-netstandard/native-integration/ASBS_1/MessageGenerator/SerializedMessageGenerator.cs
samples/azure-service-bus-netstandard/native-integration/ASBS_1/NativeIntegrationASBS.Core.sln
samples/azure-service-bus-netstandard/native-integration/ASBS_1/NativeIntegrationASBS.Core.sln.DotSettings
samples/azure-service-bus-netstandard/native-integration/ASBS_1/NativeIntegrationASBS.sln
samples/azure-service-bus-netstandard/native-integration/ASBS_1/NativeIntegrationASBS.sln.DotSettings
samples/azure-service-bus-netstandard/native-integration/ASBS_1/NativeSender/NativeSender.Core.csproj
samples/azure-service-bus-netstandard/native-integration/ASBS_1/NativeSender/NativeSender.csproj
samples/azure-service-bus-netstandard/native-integration/ASBS_1/NativeSender/Program.cs
samples/azure-service-bus-netstandard/native-integration/ASBS_1/Receiver/NativeMessageHandler.cs
samples/azure-service-bus-netstandard/native-integration/ASBS_1/Receiver/Program.cs
samples/azure-service-bus-netstandard/native-integration/ASBS_1/Receiver/Receiver.Core.csproj
samples/azure-service-bus-netstandard/native-integration/ASBS_1/Receiver/Receiver.csproj
samples/azure-service-bus-netstandard/native-integration/ASBS_1/Shared/NativeMessage.cs
samples/azure-service-bus-netstandard/native-integration/ASBS_1/Shared/Shared.Core.csproj
samples/azure-service-bus-netstandard/native-integration/ASBS_1/Shared/Shared.csproj
samples/azure-service-bus-netstandard/native-integration/sample.md
transports/azure-service-bus-netstandard/index.md

Sample similar to ASB native integration, except
- Supports .NET Core
- Does not require message body encoding
- Uses new ASB client to send native messages

ASBS native integration sample

---

nservicebus/pipeline/manipulate-with-behaviors.md

@Particular/nservicebus-maintainers please have a look, very simple link addition I think will help with discoverability.

Link from behavior page to stages page

---

monitoring/custom-checks/install-plugin.md

Aligns the custom checks installation page with the changes made to https://docs.particular.net/monitoring/heartbeats/install-plugin

Update custom checks installation page

---

samples/servicecontrol/adapter-asb-multi-namespace/sample.md
samples/servicecontrol/adapter-asq-multi-storage-account/sample.md
servicecontrol/installation.md
servicecontrol/transport-adapter/incompatible-features.md

Connects to https://github.com/Particular/ServiceControl/issues/1350
Note that I didn't make mention of the learning transport as we aren't 100% certain it'll be explicitly supported yet.

Adjust docs to accommodate newly supported transports

---

samples/fluent-validation/FluentValidation_1/Endpoint/Endpoint.Core.csproj
samples/fluent-validation/FluentValidation_1/Endpoint/Endpoint.csproj
samples/fluent-validation/FluentValidation_1/Endpoint/MyHandler.cs
samples/fluent-validation/FluentValidation_1/Endpoint/MyMessage.cs
samples/fluent-validation/FluentValidation_1/Endpoint/MyMessageValidator.cs
samples/fluent-validation/FluentValidation_1/Endpoint/Program.cs
samples/fluent-validation/FluentValidation_1/FluentValidation.Core.sln
samples/fluent-validation/FluentValidation_1/FluentValidation.Core.sln.DotSettings
samples/fluent-validation/FluentValidation_1/FluentValidation.sln
samples/fluent-validation/FluentValidation_1/FluentValidation.sln.DotSettings
samples/fluent-validation/sample.md

Sample for https://docs.particular.net/nservicebus/messaging/validation-fluentvalidation

Adding a sample for fluent validation

---

servicecontrol/installation.md

Ping @Particular/servicecontrol-maintainers

Remove silverlight pre-requisites

---

samples/azure/blob-storage-databus-cleanup-function/ABSDataBus_2/SenderAndReceiver/SenderAndReceiver.Core.csproj
samples/azure/blob-storage-databus-cleanup-function/ABSDataBus_2/SenderAndReceiver/SenderAndReceiver.csproj
samples/azure/blob-storage-databus/ABSDataBus_2/Receiver/Receiver.Core.csproj
samples/azure/blob-storage-databus/ABSDataBus_2/Receiver/Receiver.csproj
samples/azure/blob-storage-databus/ABSDataBus_2/Sender/Sender.Core.csproj
samples/azure/blob-storage-databus/ABSDataBus_2/Sender/Sender.csproj

Azure databus update

---

samples/azure/storage-persistence/ASP_2/Client/Client.Core.csproj
samples/azure/storage-persistence/ASP_2/Client/Client.csproj
samples/azure/storage-persistence/ASP_2/Server/Server.Core.csproj
samples/azure/storage-persistence/ASP_2/Server/Server.csproj
samples/azure/storage-persistence/ASP_2/StorageReader/StorageReader.Core.csproj
samples/azure/storage-persistence/ASP_2/StorageReader/StorageReader.csproj
samples/azure/storage-queues/ASQ_8/Endpoint1/Endpoint1.Core.csproj
samples/azure/storage-queues/ASQ_8/Endpoint1/Endpoint1.csproj
samples/azure/storage-queues/ASQ_8/Endpoint2/Endpoint2.Core.csproj
samples/azure/storage-queues/ASQ_8/Endpoint2/Endpoint2.csproj
samples/azure/storage-queues/ASQ_8/StorageReader/StorageReader.Core.csproj
samples/azure/storage-queues/ASQ_8/StorageReader/StorageReader.csproj
samples/servicecontrol/adapter-asq-multi-storage-account/SCTransportAdapter_2/Adapter/Adapter.Core.csproj
samples/servicecontrol/adapter-asq-multi-storage-account/SCTransportAdapter_2/Adapter/Adapter.csproj
samples/servicecontrol/adapter-asq-multi-storage-account/SCTransportAdapter_2/Sales/Sales.Core.csproj
samples/servicecontrol/adapter-asq-multi-storage-account/SCTransportAdapter_2/Sales/Sales.csproj
samples/servicecontrol/adapter-asq-multi-storage-account/SCTransportAdapter_2/Shipping/Shipping.Core.csproj
samples/servicecontrol/adapter-asq-multi-storage-account/SCTransportAdapter_2/Shipping/Shipping.csproj
samples/showcase/cloud-azure/Core_7/Store.ECommerce/Store.ECommerce.csproj
samples/showcase/cloud-azure/Core_7/Store.ECommerce/Web.config
samples/showcase/cloud-azure/Core_7/Store.Shared/Store.Shared.csproj

Asp samples update

---

samples/azure/storage-persistence/ASP_2/Client/Client.Core.csproj
samples/azure/storage-queues/ASQ_8/Endpoint1/Endpoint1.Core.csproj
samples/azure/storage-queues/ASQ_8/Endpoint1/Endpoint1.csproj
samples/azure/storage-queues/ASQ_8/Endpoint2/Endpoint2.Core.csproj
samples/azure/storage-queues/ASQ_8/Endpoint2/Endpoint2.csproj
samples/azure/storage-queues/ASQ_8/StorageReader/StorageReader.Core.csproj
samples/azure/storage-queues/ASQ_8/StorageReader/StorageReader.csproj
samples/servicecontrol/adapter-asq-multi-storage-account/SCTransportAdapter_2/Adapter/Adapter.Core.csproj
samples/servicecontrol/adapter-asq-multi-storage-account/SCTransportAdapter_2/Adapter/Adapter.csproj
samples/servicecontrol/adapter-asq-multi-storage-account/SCTransportAdapter_2/Sales/Sales.Core.csproj
samples/servicecontrol/adapter-asq-multi-storage-account/SCTransportAdapter_2/Sales/Sales.csproj
samples/servicecontrol/adapter-asq-multi-storage-account/SCTransportAdapter_2/Shipping/Shipping.Core.csproj
samples/servicecontrol/adapter-asq-multi-storage-account/SCTransportAdapter_2/Shipping/Shipping.csproj

Bump azure storage version to 9.*

updated azure storage reference for packages using asq only

---

samples/azure/self-host/Core_7/HostWorker/HostWorker.csproj
samples/azure/self-host/Core_7/HostWorker/app.config
samples/azure/shared-host/CloudServicesHost_8/HostWorker/HostWorker.csproj
samples/azure/shared-host/CloudServicesHost_8/HostWorker/app.config
samples/azure/shared-host/CloudServicesHost_8/Receiver/Receiver.csproj
samples/azure/shared-host/CloudServicesHost_8/Sender/Sender.csproj
samples/azure/shared-host/CloudServicesHost_8/Shared/Shared.csproj

updated azure storage reference for azure host samples

Azure host update

---

servicecontrol/installation.md

Closes https://github.com/Particular/ServiceControl/issues/1447

Mention requirements for SC .net framework dependency

---

persistence/sql/index.md

reviewed persistence/sql/index.md

---

nservicebus/security/property-encryption.md

This is the other tweak I suggested for #4054

tweak grammar in property-encryption.md

---

samples/servicecontrol/events-subscription/sample.md

Came from a support case where a customer was using ASQ transport.
/cc @indualagarsamy

Clarify SC instance queue name requirements

---

nservicebus/handlers/handler-ordering.md

Context: https://twitter.com/SimonCropp/status/1054245447550689280
ping @Particular/nservicebus-maintainers and @Particular/docs-maintainers

Clarified that this isn't recommended anymore

---

persistence/order.md

fixes https://github.com/Particular/docs.particular.net/issues/4069

clarify examples for persistence configuration order

---

servicecontrol/servicecontrol-instances/index.md

Document ServiceControl built-in custom checks

---

Snippets/ServiceControlContracts/ServiceControlContracts_1/MessageFailedHandler.cs
Snippets/ServiceControlContracts/ServiceControlContracts_1/ServiceControlEventsConfig.cs
Snippets/ServiceControlContracts/ServiceControlContracts_1/ServiceControlPublisherConfig.cs
servicecontrol/contracts.md

Attempt to highlight difference between MEM, V6+ and native pubsub

---

Snippets/ASB/ASB.sln
Snippets/ASB/ASB_9/ASB_9.csproj
Snippets/ASB/ASB_9/AddressingStrategies/Composition.cs
Snippets/ASB/ASB_9/AddressingStrategies/CompositionExtension.cs
Snippets/ASB/ASB_9/AddressingStrategies/Individualization.cs
Snippets/ASB/ASB_9/AddressingStrategies/IndividualizationExtensions.cs
Snippets/ASB/ASB_9/AddressingStrategies/NamespacePartitioning.cs
Snippets/ASB/ASB_9/AddressingStrategies/NamespacePartitioningExtension.cs
Snippets/ASB/ASB_9/AddressingStrategies/Sanitization.cs
Snippets/ASB/ASB_9/AddressingStrategies/SanitizationExtension.cs
Snippets/ASB/ASB_9/Composition.cs
Snippets/ASB/ASB_9/ConnectionString.config.xml
Snippets/ASB/ASB_9/CustomOversizedBrokeredMessageHandler.cs
Snippets/ASB/ASB_9/DeadLetterQueueForwarding.cs
Snippets/ASB/ASB_9/GettingStarted.cs
Snippets/ASB/ASB_9/MultipleNamespaces.cs
Snippets/ASB/ASB_9/OversizedMessages.cs
Snippets/ASB/ASB_9/Performance.cs
Snippets/ASB/ASB_9/Sanitization.cs
Snippets/ASB/ASB_9/SecureCredentials.cs
Snippets/ASB/ASB_9/TokenProvider.cs
Snippets/ASB/ASB_9/Upgrade7to8.cs
Snippets/ASB/ASB_9/Usage.cs

@Particular/azure-maintainers FYI. This was missed during v9 release.

Add ASB v9 snippets

---

nservicebus/operations/management-using-powershell.md

* Removed doco for versions < 5 (over 3 years old)

Legacy doco review for NServiceBus.PowerShell

---

menu/menu.yaml
nservicebus/hosting/index.md

@mauroservienti I think these are the final couple changes needed!

More templates tweaks

---

nservicebus/recoverability/subscribing-to-error-notifications.md

Reverting modified doco as a result of #4080 (commit bbf18b87df776a1be0fb91471ead33405ca5527d).

Revert "Remove incorrect information (#4079)"

---

nservicebus/upgrades/support-policy.md

Connects to https://github.com/Particular/CustomerSuccess/issues/857

Making ext support specific to v5

---

servicecontrol/import-failed-audits.md
servicecontrol/servicecontrol-instances/index.md

Connects to: https://github.com/Particular/ServiceControl/issues/1483

Add link to check description

---

transports/msmq/distributor/index.md

cc / @Particular/msmq-transport-maintainers 
Please review and merge.

add warning for distributor usage in Version 7

---

samples/outbox/sql/Core_7/Receiver/Receiver.Core.csproj
samples/outbox/sql/Core_7/Receiver/Receiver.csproj
samples/outbox/sql/Core_7/Sender/Sender.Core.csproj
samples/outbox/sql/Core_7/Sender/Sender.csproj

Update more SqlP related samples to Newtonsoft.Json 12.x

---

samples/azure/azure-service-fabric-routing/Core_7/CandidateVoteCount/CandidateVoteCount.csproj
samples/azure/azure-service-fabric-routing/Core_7/Shared/Shared.csproj
samples/azure/azure-service-fabric-routing/Core_7/Voter/Voter.csproj
samples/azure/azure-service-fabric-routing/Core_7/ZipCodeVoteCount/ZipCodeVoteCount.csproj
samples/azure/storage-persistence/ASP_2/Client/Client.Core.csproj
samples/azure/storage-persistence/ASP_2/Client/Client.csproj
samples/azure/storage-persistence/ASP_2/Server/Server.Core.csproj
samples/azure/storage-persistence/ASP_2/Server/Server.csproj
samples/azure/storage-persistence/ASP_2/StorageReader/StorageReader.Core.csproj
samples/azure/storage-persistence/ASP_2/StorageReader/StorageReader.csproj
samples/showcase/cloud-azure/Core_7/Store.Shared/Store.Shared.csproj

Connects to https://github.com/Particular/PlatformDevelopment/issues/2494

Updating azure samples to use latest json package

---

nservicebus/messaging/discard-old-messages.md

Based on feedback https://github.com/Particular/docs.particular.net/issues/4099

Clarifying PurgeMessagesAtStartup

---

samples/servicecontrol/events-subscription/sample.md

@Particular/azure-maintainers could you confirm that the added comment on ASQ name shortening is correct?

Service Control integration - review

---

samples/hosting/multi-hosting/Core_7/Sample/Program.cs

Changed preprocessor directive to NETCOREAPP2_1 as the project target framework is netcoreapp2.1

Fixed incorrect preprocessor directive in multi-host sample

---

nservicebus/upgrades/support-policy.md

Resolves Particular/CustomerSuccess#1137

Extended support policy enumeration with table

---

tutorials/nservicebus-sagas/1-getting-started/Snippets/Core_7/Lesson1/OrderProcessing/Lesson1.cs
tutorials/nservicebus-sagas/1-getting-started/Solution/Shipping/ShipOrderHandler.cs
tutorials/nservicebus-sagas/1-getting-started/tutorial.md

This just replaces succesful with successful.

Fix typo on word successful

---

menu/menu.yaml
persistence/nhibernate/index.md
persistence/sql/migrating-from-nhibernate.md

Table naming and schema difference between NHibernate and SQL Persistence.

Schema compatibility NHibernate and SQL Persistence

---

Snippets/Core/Core_5/Installers.cs
Snippets/Core/Core_6/Installers.cs
Snippets/Core/Core_7/Installers.cs

Updated to not start the instance when running installers

---

transports/azure-storage-queues/configuration.md
transports/azure-storage-queues/configuration_batchsize_asq_[7,].partial.md
transports/azure-storage-queues/configuration_parallelismdegree_asq_[7,].partial.md
transports/azure-storage-queues/configuration_parallelismoverrides_asq_[7,].partial.md

Describe new fetching behavior with examples

---

nservicebus/serialization/index.md

Based on our conversation earlier today.

Clarify supported/community persisters

---

menu/menu.yaml
transports/azure-service-bus/compatibility.md
transports/azure-service-bus/configuration.md
transports/azure-service-bus/index.md
transports/azure-service-bus/operational-scripting.md
transports/azure-service-bus/transaction-support.md
transports/transactions.md
transports/transactions_matrix_core_[4,5).partial.md
transports/transactions_matrix_core_[5,6).partial.md
transports/transactions_matrix_core_[6,).partial.md
transports/transactions_matrix_core_[7,).partial.md

- Updated transport transaction mode matrix with legacy/new ASB
- Added transaction support doco page to the new ASB documenting default mode and lock duration

ASB doco updates

---

persistence/sql/install.md
persistence/sql/installer-workflow.md

Based on a discussion with @SzymonPobiega

Guide towards scripting instead of installers for SqlPersitence

---

Snippets/Log4Net/Log4Net_3/Log4NetFiltering.cs

When accepting, all following filters will be ignored, which is not what you usually want when you just want to remove certain messages. There could still be following filters that want to remove other messages

Change filter decision to FilterDecision.Neutral

---

persistence/sql/installer-workflow.md

Clarify SQL installers

---

nservicebus/hosting/index.md

Based on https://github.com/Particular/NServiceBus/issues/5164 we should consider documenting requirements to the hosting environment.
Is there anything missing?
Thoughts @Particular/nservicebus-maintainers @Particular/host-maintainers

Document hosting environment requirements

---

monitoring/metrics/install-plugin.md

related to https://github.com/Particular/docs.particular.net/issues/4264
ping @Particular/metrics-maintainers

Mention send-only incompatibility

---

servicecontrol/servicecontrol-instances/distributed-instances.md

Ran across this today, not a good look.
@Particular/servicecontrol-maintainers 	can you ensure this is still technically correct?

Master/slave -> primary/secondary

---

Snippets/SqlTransport/SqlTransport_3/DelayedDelivery.cs
Snippets/SqlTransport/SqlTransport_4/DelayedDelivery.cs
transports/sql/native-delayed-delivery.md

Clarified doco to make it clear that the default interval is 1 sec

Update SQL-T native delayed delivery doco

---

menu/menu.yaml
persistence/index.md
persistence/selecting.md
tutorials/nservicebus-sagas/1-getting-started/tutorial.md

This contains guidance on selecting a persister and some changes to align the content with the transport selection guidance.

Guidance on selecting a persister

---

samples/near-realtime-clients/sample.md

Clarify SignalR scaleout

---

nservicebus/messaging/headers.md

give that we don't set this header anymore.

Remove FLR header doco

---

samples/near-realtime-clients/sample.md

Based on live chat where customer requested info on usage of SignalR.

Added links to SignalR tutorials and samples

---

Snippets/ABSDataBus/ABSDataBus.sln
Snippets/ABSDataBus/ABSDataBus_3/ABSDataBus_3.csproj
Snippets/ABSDataBus/ABSDataBus_3/Usage.cs
nservicebus/messaging/databus/azure-blob-storage.md
nservicebus/messaging/databus/azure-blob-storage_cleanup-options_ABSDataBus_[1.0,3.0).partial.md
nservicebus/messaging/databus/azure-blob-storage_cleanup-options_ABSDataBus_[3.0,).partial.md
nservicebus/messaging/databus/azure-blob-storage_cleanup-options_Azure_[6.0,).partial.md
nservicebus/messaging/databus/azure-blob-storage_disable-built-in-cleanup_ABSDataBus_[3.0,).partial.md
nservicebus/upgrades/absdatabus-2to3.md
samples/azure/blob-storage-databus/ABSDataBus_3/AzureBlobStorageDataBus.Core.sln
samples/azure/blob-storage-databus/ABSDataBus_3/AzureBlobStorageDataBus.Core.sln.DotSettings
samples/azure/blob-storage-databus/ABSDataBus_3/AzureBlobStorageDataBus.sln
samples/azure/blob-storage-databus/ABSDataBus_3/AzureBlobStorageDataBus.sln.DotSettings
samples/azure/blob-storage-databus/ABSDataBus_3/Receiver/MessageWithLargePayloadHandler.cs
samples/azure/blob-storage-databus/ABSDataBus_3/Receiver/Program.cs
samples/azure/blob-storage-databus/ABSDataBus_3/Receiver/Receiver.Core.csproj
samples/azure/blob-storage-databus/ABSDataBus_3/Receiver/Receiver.csproj
samples/azure/blob-storage-databus/ABSDataBus_3/Sender/Program.cs
samples/azure/blob-storage-databus/ABSDataBus_3/Sender/Sender.Core.csproj
samples/azure/blob-storage-databus/ABSDataBus_3/Sender/Sender.csproj
samples/azure/blob-storage-databus/ABSDataBus_3/Shared/MessageWithLargePayload.cs
samples/azure/blob-storage-databus/ABSDataBus_3/Shared/Shared.Core.csproj
samples/azure/blob-storage-databus/ABSDataBus_3/Shared/Shared.csproj

- Doco update
- Upgrade guide from v2 to v3
- Snippets for v3
- Sample for v3

[WIP] Azure DataBus 3.0

---

nservicebus/upgrades/6to7/index.md

Added note about msmq routing with link to docs

---

nservicebus/logging/usage.md

Added warning making sure to setup/init logging before resolving logger

---

nservicebus/handlers/index.md

Add links to relevant testing pages

---

transports/msmq/sender-side-distribution.md

Clarification of behavior for pubsub with MSMQ sender side distribution

---

transports/transactions_native_core_[6,).partial.md

Based on short conversation on Slack. Triggered me to review the info provided at the ReceiveOnly mode.

ReceiveOnly, batching & immediate dispatch

---

Snippets/Json/Core_5/JsonSerializerUsage.cs
Snippets/Json/Core_6/JsonSerializerUsage.cs
Snippets/Newtonsoft/Newtonsoft_1/Usage.cs
Snippets/Newtonsoft/Newtonsoft_2/Usage.cs
nservicebus/serialization/newtonsoft.md

Update doco to indicate how to remove BOM with the newtonsoft.Json serializer

Document how to remove BOM

---

menu/menu.yaml
nservicebus/messaging/headers.md
nservicebus/messaging/message-type-detection.md
samples/azure-service-bus-netstandard/native-integration/ASBS_1/NativeSender/Program.cs
samples/azure-service-bus-netstandard/native-integration/sample.md
samples/azure/native-integration-asb/sample.md
samples/rabbitmq/native-integration/sample.md
samples/sqltransport/native-integration/sample.md
transports/azure-service-bus/legacy/brokered-message-creation.md
transports/azure-service-bus/legacy/brokered-message-creation_bodyformat_asb_[7,).partial.md
transports/azure-service-bus/legacy/brokered-message-creation_header_asb_[,7).partial.md
transports/azure-service-bus/legacy/brokered-message-creation_header_asb_[7,).partial.md
transports/azure-service-bus/legacy/native-integration.md
transports/rabbitmq/native-integration.md

@bording @ramonsmits like discussed earlier. I'll go and link to this from all our native integration samples/doco once we're happy with the wording?

Add message type detection doco

---

nservicebus/messaging/messages-events-commands.md

Figured that making this version dependant is overkill?

Remove struct limitation

---

Snippets/ASBS/ASBS_1/Usage.cs
transports/azure-service-bus/configuration.md

Related to https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/issues/63

Clarify prefetching doco for ASB

---

persistence/msmq/subscription.md
samples/msmq/persistence/Core_6/Sample/Program.cs
samples/msmq/persistence/MsmqTransport_1/Sample/Program.cs
samples/msmq/persistence/sample.md

Part of the weekly doco review

Fix race condition in msmq sub sample

---

servicepulse/host-config.md

re-enabling the port when changing it

---

nservicebus/sagas/index.md

Based on a support case from a few weeks ago.

Explanation of saga state read/write behavior

---

samples/serializers/change-message-type/Core_6/SamplePhase2/MessageIdentityMutator.cs

The above code is technically wrong. The bool parameter passed is false and it means if case sensitive search should be done. (In case the message is from another assembly this above does not work.)

Wrong code

---

servicepulse/host-config.md

_Relates to https://github.com/Particular/docs.particular.net/pull/4403._

review ServicePulse URL reservation

---

nservicebus/sagas/index.md

_Relates to https://github.com/Particular/docs.particular.net/pull/4369._

Editorial review of saga state read write behavior

---

samples/azure/self-host/Core_6/HostWorker/app.config
samples/azure/self-host/Core_7/HostWorker/app.config

For Azure Cloud Host self-hosting sample

Update binding redirects for Azure Host self-hosting sample

---

servicepulse/intro-pending-retries.md

Connected to https://github.com/Particular/ServicePulse/pull/763

Update showPendingRetry setting doco based on latest changes

---

samples/router/switch-vs-backplane.include.md
transports/sql/transactions.md

Elastic transactions

---

nservicebus/hosting/selecting.md

editorial review of nservicebus/hosting/selecting.md

---

components/components.yaml

Update components.yaml to include a new component

Azure Functions component addition

---

persistence/mongodb/migrating-from-tekmaven.md

add a script which allows to migrate the data so that no compatibility mode has to be used.

Document saga data migration script

---

menu/menu.yaml
samples/azure/functions/service-bus/ASBFunctions_0.1/AzureFunctions.ASBTrigger/AzureFunctions.ASBTrigger.csproj
samples/azure/functions/service-bus/ASBFunctions_0.1/AzureFunctions.ASBTrigger/AzureServiceBusTriggerFunction.cs
samples/azure/functions/service-bus/ASBFunctions_0.1/AzureFunctions.ASBTrigger/FollowupMessageHandler.cs
samples/azure/functions/service-bus/ASBFunctions_0.1/AzureFunctions.ASBTrigger/TriggerMessageHandler.cs
samples/azure/functions/service-bus/sample.md
samples/azure/functions/storage-queues/ASQFunctions_0.1/AzureFunctions.ASQTrigger/AzureFunctions.ASQTrigger.csproj
samples/azure/functions/storage-queues/ASQFunctions_0.1/AzureFunctions.ASQTrigger/AzureStorageQueueTriggerFunction.cs
samples/azure/functions/storage-queues/ASQFunctions_0.1/AzureFunctions.ASQTrigger/FollowupMessageHandler.cs
samples/azure/functions/storage-queues/ASQFunctions_0.1/AzureFunctions.ASQTrigger/TriggerMessageHandler.cs
samples/azure/functions/storage-queues/sample.md

- Update functions samples to the latest NSB.AzureFunctions
- Remove hosting doco from the menu
- Link samples to the hidden constraints document
- Update samples to show how to create endpoint configuration with auto-wired settings from attributes

Azure Functions update

---

Snippets/Testing/Testing_6/Logging/LoggingTest.cs
Snippets/Testing/Testing_7/Logging/LoggingTest.cs
nservicebus/testing/index_content_testing_[6,).partial.md

Alternative to https://github.com/Particular/docs.particular.net/pull/4474

Hopefully better approach for testing logger

---

persistence/index.md

Add MongoDB to the supported persisters list.

Add MongoDB to supported persisters

---

servicecontrol/plugins/saga-audit_config_SagaAudit4_[1,).partial.md
servicecontrol/plugins/saga-audit_config_SagaAudit5_[1,).partial.md
servicecontrol/plugins/saga-audit_config_SagaAudit6_(,2).partial.md
servicecontrol/plugins/saga-audit_config_SagaAudit6_[2,].partial.md

Fixes #4491
Every partial had Configuration section title duplicated.
This PR removes the duplicates
/cc @aleksandr-samila

Remove duplicated Configuration section title

---

nservicebus/recoverability/index.md
nservicebus/recoverability/lru-memory-consumption.md

editorial review of LRU memory usage changes

---

samples/dependency-injection/autofac/Autofac_6/Sample/Program.cs
samples/dependency-injection/autofac/Autofac_7/Sample/Program.cs
samples/dependency-injection/autofac/sample.md
samples/dependency-injection/autofac/sample_assignment_autofac_[6,).partial.md

Remove unnecessary snippet for Autofac sample

---

servicecontrol/installation.md

Improvement after helping @dbelcham with a support case on updating ServiceControl

Update SC update doco as these days we have different SC types to install

---

tutorials/quickstart/tutorial.md

Tweak warning about vs2017

---

servicecontrol/installation-powershell.md

Removing the empty callout that is blank

Removing empty callout

---

persistence/azure-storage/index.md
persistence/in-memory.md
persistence/learning/index.md
persistence/mongodb/index.md
persistence/nhibernate/saga-concurrency.md
persistence/ravendb/saga-concurrency.md
persistence/sql/saga-concurrency.md
persistence/sql/saga-concurrency_implementation_sqlpersistence_[,4).partial.md
persistence/sql/saga-concurrency_implementation_sqlpersistence_[4,).partial.md
persistence/sql/saga-concurrency_updating_deleting_sqlpersistence_[4,).partial.md

@ramonsmits let's discuss on Monday.

edits to details of concurrency exceptions for each persister

---

persistence/selecting.md

Merge contingent upon release of MongoDB storage.

Adding MongoDB to the persistence selection guidance

---

Snippets/Core/Core_7.2/Core_7.2.csproj
Snippets/Core/Core_7.2/PublishSubscribe/DisablePublishing.cs
nservicebus/messaging/publish-subscribe/index.md
nservicebus/messaging/publish-subscribe/index_disable-publishing_core_[7.2,).partial.md

related to https://github.com/Particular/NServiceBus/pull/5430

Document DisablePublishing API

---

servicecontrol/installation.md
servicecontrol/monitoring-instances/installation/index.md

Document transport seam options in SC

---

Snippets/Core/Core_7.2/Core_7.2.csproj
Snippets/Core/Core_7.2/Notifications/SubscribeToNotifications.cs
nservicebus/recoverability/subscribing-to-error-notifications.md
nservicebus/recoverability/subscribing-to-error-notifications_unsubscribing_core_[,6.0).partial.md
nservicebus/recoverability/subscribing-to-error-notifications_unsubscribing_core_[6.0,).partial.md

Documenting the new async notifications in 7.2 (see https://github.com/Particular/NServiceBus/issues/5393)

Add documentation for async notifications

---

nservicebus/recoverability/notificationThread.include.md
nservicebus/recoverability/subscribing-to-error-notifications.md

Some tweaks which hopefully also show the correct snippet for 7.2

Notifications tweaks

---

samples/entity-framework-core/Core_7/Endpoint.SqlPersistence/CompleteOrder.cs
samples/entity-framework-core/Core_7/Endpoint.SqlPersistence/CompleteOrderHandler.cs
samples/entity-framework-core/Core_7/Endpoint.SqlPersistence/CreateOrderHandler.cs
samples/entity-framework-core/Core_7/Endpoint.SqlPersistence/CreateShipmentHandler.cs
samples/entity-framework-core/Core_7/Endpoint.SqlPersistence/Endpoint.SqlPersistence.csproj
samples/entity-framework-core/Core_7/Endpoint.SqlPersistence/Order.cs
samples/entity-framework-core/Core_7/Endpoint.SqlPersistence/OrderAcceptedHandler.cs
samples/entity-framework-core/Core_7/Endpoint.SqlPersistence/OrderLifecycleSaga.cs
samples/entity-framework-core/Core_7/Endpoint.SqlPersistence/OrderLifecycleSagaData.cs
samples/entity-framework-core/Core_7/Endpoint.SqlPersistence/OrderTimeout.cs
samples/entity-framework-core/Core_7/Endpoint.SqlPersistence/Program.cs
samples/entity-framework-core/Core_7/Endpoint.SqlPersistence/ReceiverDataContext.cs
samples/entity-framework-core/Core_7/Endpoint.SqlPersistence/Sender.cs
samples/entity-framework-core/Core_7/Endpoint.SqlPersistence/Shipment.cs
samples/entity-framework-core/Core_7/Endpoint.SqlPersistence/SqlHelper.cs
samples/entity-framework-core/Core_7/Endpoint.SqlPersistence/UnitOfWork/EntityFrameworkUnitOfWork.cs
samples/entity-framework-core/Core_7/Endpoint.SqlPersistence/UnitOfWork/EntityFrameworkUnitOfWorkContextExtensions.cs
samples/entity-framework-core/Core_7/Endpoint.SqlPersistence/UnitOfWork/UnitOfWorkSetupBehavior.cs
samples/entity-framework-core/Core_7/EntityFrameworkCoreUnitOfWork.sln
samples/entity-framework-core/Core_7/EntityFrameworkCoreUnitOfWork.sln.DotSettings
samples/entity-framework-core/Core_7/Messages/Messages.csproj
samples/entity-framework-core/Core_7/Messages/OrderAccepted.cs
samples/entity-framework-core/Core_7/Messages/OrderSubmitted.cs
samples/entity-framework-core/sample.md

Shows how to integrate the UoW approach with Entity Framework Core

Entity Framework Core UoW Sample

---

servicecontrol/creating-config-file.md
servicecontrol/self-monitoring.include.md

Documentation updates for [ServiceControl 4.4.1](https://github.com/Particular/ServiceControl/milestone/166)

ServiceControl 4.4.1

---

Snippets/mongodb/MongoDB_2/Usage.cs
menu/menu.yaml
persistence/mongodb/document-version.md
persistence/mongodb/index.md
persistence/mongodb/migrating-from-sbmako.md
persistence/mongodb/migrating-from-tekmaven.md

Updating the mongodb doco and migration guide based on the observations from the migration walkthrough done with Kyle, Michal and Hadi.

Mongodb walk-through feedback

---

servicecontrol/installation.md

Fix https://github.com/Particular/docs.particular.net/issues/4539

Add a reference to puppet module

---

Snippets/ASBS/ASBS_1/AccessToNativeMessage.cs
menu/menu.yaml
transports/azure-service-bus/native-message-access.md

The change in `master` and would need to be released as a new minor to allow this change to doco.

ASB native message access

---

nservicebus/licensing/index.md

Slightly more helpful licensing troubleshooting hint

---

nservicebus/messaging/delayed-delivery.md
nservicebus/messaging/timeout-manager.md

Remove SQL and mention only MSMQ

---

samples/manual-unsubscribe/sample.md

Trying to clarify the note a bit based on feedback from a support case.

Update note on manual unsubscribe sample

---

tutorials/nservicebus-sagas/2-timeouts/tutorial.md

Previously: If batch job fails then what?
Now: but what if batch job fails?

Changed languange of description

---

persistence/in-memory/gateway-deduplication.md

scheduled review of https://github.com/Particular/docs.particular.net/pull/4627

fix casing of in-memory gateway deduplication persistence

---

samples/servicecontrol/adapter-asq-multi-storage-account/SCTransportAdapter_2/Adapter/Program.cs
samples/servicecontrol/adapter-asq-multi-storage-account/SCTransportAdapter_2/Sales/Program.cs
samples/servicecontrol/adapter-asq-multi-storage-account/SCTransportAdapter_2/Shipping/Program.cs

fixes #4653 
By sanitizing queue names

Fix ServiceControl Transport Adapter sample for ASQ

---

Snippets/SqlPersistence/SqlPersistence_3/Usage.cs
Snippets/SqlPersistence/SqlPersistence_4/Usage.cs
persistence/sql/dialect-mssql.md
persistence/sql/dialect-mssql_connection_[3,).partial.md
persistence/sql/dialect-mssql_connection_sqlpersistence_[3,).partial.md

Fixes https://github.com/Particular/docs.particular.net/issues/4646

Add note about sqlp and sqlt connection sharing

---

nservicebus/messaging/headers.md

@indualagarsamy this what was the user mentioned in the support case right?

Clarify that changing conversation id is not supported

---

persistence/msmq/subscription_timeouts_core_[5,7).partial.md
persistence/msmq/subscription_timeouts_msmqtransport_[1,).partial.md

Small update to MSMQ persistence

---

Snippets/Core/Core_5/Hosting/Hosting.cs
Snippets/Core/Core_6/Hosting/Hosting.cs
Snippets/Core/Core_7/Hosting/Hosting.cs

Mention other necessary configuration to make it more clear that the example cannot be simply copy pasted

---

servicepulse/installation.md

Mention monitoring and important config links

---

servicepulse/index.md

Disable auto play of monitoring video

---

nservicebus/upgrades/all-versions.include.md
nservicebus/upgrades/supported-versions-downstreams.include.md
nservicebus/upgrades/supported-versions-nservicebus.include.md
servicecontrol/upgrades/supported-versions-servicecontrol.include.md
tools/supportedVersions.linq

Supported versions link to nuget packages

---

samples/dependency-injection/autofac/Extensions.DependencyInjection_1/Sample/Program.cs
samples/dependency-injection/structuremap/Extensions.DependencyInjection_1/Sample/Program.cs
samples/dependency-injection/unity/Extensions.DependencyInjection_1/Sample/Program.cs

Fixes some formatting + removes some autofac sample configuration code which wasn't being used at all.

Minor DI sample changes

---

Snippets/ASP/ASP_2/Usage.cs
persistence/azure-storage/configuration.md
persistence/azure-storage/configuration_timeouts_asp_[1,2.4).partial.md
persistence/azure-storage/configuration_timeouts_asp_[2.4,).partial.md

Related to: https://github.com/Particular/NServiceBus.Persistence.AzureStorage/pull/248

ASP 2.4.0 timeout persistence obsolete doco 

---

menu/menu.yaml

Rearrange a bit transaction support for azure

---

samples/errorhandling/Core_6/PlatformLauncher/PlatformLauncher.csproj
samples/errorhandling/Core_7/PlatformLauncher/PlatformLauncher.csproj
samples/message-error-handling/Core_6/PlatformLauncher/PlatformLauncher.csproj
samples/message-error-handling/Core_7/PlatformLauncher/PlatformLauncher.csproj
samples/pipeline/fix-messages-using-behavior/Core_7/PlatformLauncher/PlatformLauncher.csproj
samples/servicecontrol/adapter-mixed-transports/SCTransportAdapter_2/PlatformLauncher/PlatformLauncher.csproj
samples/servicecontrol/events-subscription/ServiceControlContracts_1/PlatformLauncher/PlatformLauncher.csproj
samples/servicecontrol/fix-messages/Core_7/PlatformLauncher/PlatformLauncher.csproj
samples/servicecontrol/monitoring3rdparty/CustomChecks_3/PlatformLauncher/PlatformLauncher.csproj
tutorials/message-replay/Solution/PlatformTools/PlatformTools.csproj
tutorials/quickstart/Solution/Platform/Platform.csproj

Related to https://github.com/Particular/Particular.PlatformSample/pull/36

Prepare for platform package sample update

---

README.md
samples/hosting/docker/Core_7/Receiver/Dockerfile
samples/hosting/docker/Core_7/docker-compose.yml
samples/hosting/docker/sample.md

Requires https://github.com/Particular/DocsEngine/pull/453
Also documents the other extensions that are supported

Switch to snippets in compose and dockerfile

---

security-advisories/index.md
security-advisories/servicepulse-directorytraversal.md

Security advisory for https://github.com/Particular/ServicePulse/pull/831

Security Advisory: ServicePulse Directory Traversal

---

persistence/upgrades/nhibernate-8to8.1.md

Exception name was incorrect,
added exception message, 
improved page for SEO,
improved the structure of the document for readability

NHibernate StaleObjectStateException upgrade guidance improvements

---

servicecontrol/import-failed-messages.md

Closes https://github.com/Particular/ServiceControl/issues/1952

Slight tweak of SC import failed messages

---

menu/menu.yaml
nservicebus/upgrades/support-policy.md
previews/index.md
previews/support-policy.md

This PR documents the support policy for the upcoming unannounced platform Previews program.
In addition, it establishes "Previews" as a top-level menu item for previews, to be further fleshed out in future PRs.

[Staged] Previews docs

---

servicecontrol/audit-instances/creating-config-file.md

Add ServiceControl Audit config documentation for TimeToRestartAuditIngestionAfterFailure

---

Snippets/ASBS/ASBS.sln
Snippets/ASBS/ASBS_1.5/ASBS_1.5.csproj
Snippets/ASBS/ASBS_1.5/AccessToNativeMessage.cs
Snippets/ASBS/ASBS_1.5/Usage.cs
transports/azure-service-bus/configuration.md
transports/azure-service-bus/configuration_custom-retry-policy_asbs_[1.5,].partial.md

Related to https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/122

ASB custom retry policy doco

---

Snippets/Core/Core_5/Sagas/Timeouts/MultipleTimeouts.cs
Snippets/Core/Core_6/Sagas/Timeouts/MultipleTimeouts.cs
Snippets/Core/Core_6/Sagas/Timeouts/MySaga.cs
Snippets/Core/Core_7/Sagas/Timeouts/MultipleTimeouts.cs
Snippets/Core/Core_7/Sagas/Timeouts/MySaga.cs
nservicebus/sagas/timeouts.md

Pinging you as we did the saga timeouts tutorial. There was a bug in the sample for the last few years :-) and added info on how to set multiple timeouts.

Saga fix reply to originator and how to set multiple timeouts

---

nservicebus/messaging/routing.md

Documentation on the usage of MakeInstanceUniquelyAddressable and RouteToSpecificInstance

MakeInstanceUniquelyAddressable and RouteToSpecificInstance

---

samples/logging/prometheus-grafana/Metrics_3/Endpoint/Endpoint.csproj
samples/logging/prometheus-grafana/Metrics_3/Endpoint/PrometheusFeature.cs

@danielmarbach as discussed on https://discuss.particular.net/t/metrics-with-prometheus-missing-counters/1368 here is the change.

Correct prometheus sample for summary with v3.*

---

nservicebus/recoverability/index.md

Connects to https://github.com/Particular/docs.particular.net/issues/4104

Immediate retries guarantees clarified

---

persistence/mongodb/index.md

Based on some research we thought we needed to add this.

Added pessimistic locking remarks

---

samples/logging/application-insights/Metrics_1/Endpoint/Endpoint.csproj
samples/logging/application-insights/Metrics_1/Endpoint/ProbeCollector.cs
samples/logging/application-insights/Metrics_2/Endpoint/Endpoint.csproj
samples/logging/application-insights/Metrics_2/Endpoint/ProbeCollector.cs
samples/logging/application-insights/Metrics_3/Endpoint/ApplicationInsightsConfigurationExtensions.cs
samples/logging/application-insights/Metrics_3/Endpoint/ApplicationInsightsFeature.cs
samples/logging/application-insights/Metrics_3/Endpoint/Endpoint.Core.csproj
samples/logging/application-insights/Metrics_3/Endpoint/Endpoint.csproj
samples/logging/application-insights/Metrics_3/Endpoint/ProbeCollector.cs
samples/logging/application-insights/Metrics_3/Endpoint/Program.cs

Fixes #4806
Updated one of the code samples to the latest version. Haven't updated the text or the older samples yet.

Update to latest Application Insights

---

samples/dependency-injection/aspnetcore/Core_7.2/SampleAutofac/Startup.cs

Removed a duplicate snippet causing the snippet content to appear twice on the website

Fix duplicate snippet content on di-aspnetcore sample

---

transports/azure-service-bus/index.md

Submitted in response to a customer inquiry on LiveChat.

Only standard and premium tier is supported for ASB

---

transports/azure-service-bus/legacy/error-handling.md

Based on support question on LiveChat

Improvement on MessageSizeExceededException

---

Snippets/Core/Core_7/Persistence/PersistenceOrder.cs
persistence/order.md

- Gateway Persistence has been deprecated

NSB 7.3 Update

---

nservicebus/dependency-injection/extensions-dependencyinjection.md

Add lifetime mapping

---

samples/aws/lambda/sqs/SQSLambda_0.1/AwsLambda.SQSTrigger/AwsLambda.SQSTrigger.csproj
samples/aws/lambda/sqs/SQSLambda_0.1/AwsLambda.SQSTrigger/Function.cs
samples/aws/lambda/sqs/SQSLambda_0.1/AwsLambda.SQSTrigger/Properties/launchSettings.json
samples/aws/lambda/sqs/SQSLambda_0.1/AwsLambda.SQSTrigger/aws-lambda-tools-defaults.json
samples/aws/lambda/sqs/SQSLambda_0.1/AwsLambda.SQSTrigger/serverless.template
samples/aws/lambda/sqs/SQSLambda_0.1/AwsLambda.Sender/AwsLambda.Sender.csproj

@boblangley Take a look and let me know what you think.

AWSLambda sample to netcoreapp3.1

---

menu/menu.yaml
persistence/upgrades/sql-4.0to4.1.1.md

_Connected to https://github.com/Particular/DeveloperExperience/issues/858_

Pessimistic concurrency warning upgrade guide

---

samples/azure-service-bus-netstandard/native-integration/ASBS_1/NativeSender/Program.cs
samples/azure-service-bus-netstandard/native-integration/ASBS_1/Receiver/NativeMessageHandler.cs
samples/azure-service-bus-netstandard/native-integration/ASBS_1/Shared/NativeMessage.cs
samples/azure/native-integration-asb/ASB_10/MessageGenerator/SerializedMessageGenerator.cs
samples/azure/native-integration-asb/ASB_10/NativeSender/Program.cs
samples/azure/native-integration-asb/ASB_10/Receiver/NativeMessageHandler.cs
samples/azure/native-integration-asb/ASB_10/Shared/NativeMessage.cs
samples/azure/native-integration-asb/ASB_7/MessageGenerator/SerializedMessageGenerator.cs
samples/azure/native-integration-asb/ASB_7/NativeSender/Program.cs
samples/azure/native-integration-asb/ASB_7/Receiver/NativeMessageHandler.cs
samples/azure/native-integration-asb/ASB_7/Shared/NativeMessage.cs
samples/azure/native-integration-asb/ASB_9/MessageGenerator/SerializedMessageGenerator.cs
samples/azure/native-integration-asb/ASB_9/NativeSender/Program.cs
samples/azure/native-integration-asb/ASB_9/Receiver/NativeMessageHandler.cs
samples/azure/native-integration-asb/ASB_9/Shared/NativeMessage.cs

As a sanity check, from https://docs.particular.net/samples/azure-service-bus-netstandard/native-integration/

"sent on" not "send on"

---

transports/upgrades/asb-10toasbs-1.md

Had a support case where a customer got stuck during the upgrade process because we lack firewall changes in our upgrade guide.

List port changes from ASBL to ASBS

---

servicecontrol/license.md

Related to feedback raised at https://github.com/Particular/ServiceControl/issues/2014

Clarify import location of SC license files

---

.github/workflows/build-projects.yml
.github/workflows/verify-master.yml
platform/contributing.md

* Docstool shouldn't do an update check when it was JUST installed, we don't want a PR to fail because MyGet was down or slow. (Although, then the install might not work, but…)
* Notify Slack if something fails on master

Workflow updates

---

tutorials/nservicebus-sagas/2-timeouts/Snippets/Core_7/BuyersRemorseTimeoutHandling/BuyersRemorseTimeoutHandling.cs
tutorials/nservicebus-sagas/2-timeouts/tutorial.md

Fixes https://github.com/Particular/docs.particular.net/issues/4865

Remove incorrect TODO remark from tutorial

---

nservicebus/hosting/index.md

Behavior is version dependent so remove incorrect note

---

menu/menu.yaml

Adding migration timeout tool to the menu

---

Snippets/MsmqTransport/MsmqTransport_All/QueueCreation/QueueCreation.ps1
Snippets/MsmqTransport/MsmqTransport_All/QueueCreation/QueueCreationUtils.cs
samples/msmq/dlq-customcheck/Core_6/SampleEndpoint/MsmqUtils.cs
samples/msmq/dlq-customcheck/MsmqTransport_1/SampleEndpoint/MsmqUtils.cs

Merge with https://github.com/Particular/NServiceBus.Transport.Msmq/pull/144

Modify queue permissions for MSMQ queue creation

---

persistence/transport-transaction-scope.include.md
transports/msmq/index.md
transports/transactions.md
transports/transactions_scope-options_core_[4,6).partial.md
transports/transactions_scope-options_core_[6,).partial.md

Addresses https://github.com/Particular/DeveloperExperience/issues/778

Add note about PS scripts to MSMQ page

---

Snippets/MsmqTransport/MsmqTransport_1/InstanceMapping.cs
transports/msmq/routing.md
transports/msmq/routing_schema-validation_msmqtransport_[1,).partial.md

Documentation for https://github.com/Particular/NServiceBus.Transport.Msmq/pull/146
Alternate version of https://github.com/Particular/docs.particular.net/pull/4892

MSMQ Instance Mapping Schema Validation

---

nservicebus/upgrades/all-versions.include.md
nservicebus/upgrades/supported-versions-downstreams.include.md
servicecontrol/upgrades/supported-versions-servicecontrol.include.md

Result of running the supportVersions.linq script. Other packages were updated as part of this as well.

Update supported version for NServiceBus.Transport.Msmq 1.1.0 

---

menu/menu.yaml
nservicebus/upgrades/third-party-license-data.include.md
nservicebus/upgrades/third-party-licenses.md
tools/3rd-party-licenses.linq

Scripts 3rd-party license info by inspecting NuGet metadata for each of our packages' dependencies.

3rd party licenses page

---

components/components.yaml

Requires #4477 and new version of DocsEngine

Switch Azure Functions components to Preview

---

samples/web/send-from-aspnetcore-webapi/Core_7.2/WebApplication/Program.cs

According to https://github.com/Particular/docs.particular.net/pull/4598 this structure is incorrect.

UseNServiceBus should be specified before ConfigureWebHostDefaults

---

samples/azure/azure-service-fabric-routing/Core_7/CandidateVoteCount/CandidateVoteCount.csproj
samples/azure/azure-service-fabric-routing/Core_7/CandidateVoteCount/app.config
samples/azure/azure-service-fabric-routing/Core_7/Shared/EndpointConfigurationExtensions.cs
samples/azure/azure-service-fabric-routing/Core_7/Shared/ReceiverSideDistribution/Configuration/ReceiverSideDistributionExtensions.cs
samples/azure/azure-service-fabric-routing/Core_7/Shared/Shared.csproj
samples/azure/azure-service-fabric-routing/Core_7/Shared/app.config
samples/azure/azure-service-fabric-routing/Core_7/Voter/Program.cs
samples/azure/azure-service-fabric-routing/Core_7/Voter/Voter.csproj
samples/azure/azure-service-fabric-routing/Core_7/Voter/app.config
samples/azure/azure-service-fabric-routing/Core_7/ZipCodeVoteCount/ZipCodeVoteCount.csproj
samples/azure/azure-service-fabric-routing/Core_7/ZipCodeVoteCount/app.config

Upgrade SF routing

---

nservicebus/dependency-injection/extensions-dependencyinjection.md
nservicebus/hosting/extensions-hosting.md

Adds the reference sample to the appropriate net core package documentation

Add references to sample

---

Snippets/SqlTransport/SqlTransport_6/RuntimeScripts/CreateQueueText.sql

Based on user feedback https://github.com/Particular/NServiceBus.SqlServer/issues/642

Updated based on release 6.0.1

---

home.md

Addresses the first part of https://github.com/Particular/DeveloperEducation/issues/3052

Hide quickstart banner on home page

---

servicecontrol/servicecontrol-instances/hardware.md

Added SC storage recommendations

---

Snippets/Core/Core_7/Forwarding/Usage.cs

This is a short term fix while we update the documentation

Ignore obsolete from NServiceBus 7.4

---

persistence/sql/saga.md
samples/sql-persistence/simple/SqlPersistence_3/MsSqlServer_JsonQuery.sql
samples/sql-persistence/simple/SqlPersistence_4/MsSqlServer_JsonQuery.sql
samples/sql-persistence/simple/SqlPersistence_5/MsSqlServer_JsonQuery.sql
samples/sql-persistence/simple/SqlPersistence_6/MsSqlServer_JsonQuery.sql
samples/sql-persistence/simple/sample.md

Closes https://github.com/Particular/DeveloperExperience/issues/325

Document sqlp storageformat

---

nservicebus/recoverability/index_retrycount_core_[6.0,).partial.md

Remove duplicate in table of total number of retries.

Remove duplicate in table of total number of retries

---

monitoring/metrics/performance-counters.md

Closes https://github.com/Particular/NServiceBus/issues/5711

Document the perfcounters are not supported for send-only endpoints

---

Snippets/SqlTransport/SqlTransportLegacySystemClient_5/UpgradeGuides/CreateSubscriptionTableText.sql

Endpoint should be non-null - SQL assumes this anyway due to PK

---

nservicebus/dependency-injection/index_ownership_core_[8.0,).partial.md
nservicebus/upgrades/7to8/dependency-injection.md

https://github.com/Particular/docs.particular.net/pull/4999

Editorial review of update to latest core alpha

---

previews/cosmosdb/migration-from-azure-storage.md

- Updated export tool installation and use instructions. 
- Added command to update the tool while in preview.

Update export tool instructions

---

servicecontrol/installation.md

Connects to https://github.com/Particular/ServiceControl/issues/2137

ServiceControl ASB `TopicName` option

---

Snippets/SagaAudit/SagaAudit_2/API.cs
Snippets/SagaAudit/SagaAudit_3/API.cs
nservicebus/sagas/saga-audit.md
servicecontrol/servicecontrol-in-practice.md
servicecontrol/servicecontrol-instances/index.md
serviceinsight/index.md

Documentation for [this PR](https://github.com/Particular/ServiceControl/pull/2156)

Document saga audit support in audit instance

---

nservicebus/upgrades/7to8/dependency-injection.md

Resolves https://github.com/Particular/docs.particular.net/issues/5029

fixed the broken link

---

samples/previews/cosmosdb/transactions/CosmosDB_0/Server/ShipOrderHandler.cs

editorial review of https://github.com/Particular/docs.particular.net/pull/5021
/cc @danielmarbach

CosmosDB transaction sample editorial review

---

transports/upgrades/sqlserver-4to5.md

Connected to https://github.com/Particular/docs.particular.net/issues/5035

Note on when it's safe to remove persister level pub-sub data

---

nservicebus/outbox/index.md

Related to https://github.com/Particular/DeveloperExperience/issues/421

Rewrite Outbox docs

---

menu/menu.yaml
nservicebus/best-practices.md

https://github.com/Particular/DeveloperExperience/issues/547

Best practices / do-dont-consider article

---

Snippets/Core/Core_8/Core_8.csproj
Snippets/Core/Core_8/Pipeline/BehaviorRegistration.cs
nservicebus/pipeline/manipulate-with-behaviors.md
nservicebus/pipeline/manipulate-with-behaviors_registerorreplace_core_[8.0,).partial.md

Beware that this PR bumps the alpha for v8 used

Extend documentation with RegisterOrReplace api for behaviors and connectors

---

menu/menu.yaml
nservicebus/messaging/troubleshooting.md
nservicebus/troubleshooting/index.md
nservicebus/troubleshooting/message-loss.md

After many of such incidents recently it seems we need to document the most causes for message loss.

Troubleshooting message loss

---

nservicebus/upgrades/7to8/index.md

Related to https://github.com/Particular/NServiceBus/pull/5770

V8: Meaningful exception when the endpoint instance is stoped

---

README.md

I don't really know what "and any other text" refers to, and it may be redundant, but I wanted to stay focused on the two line thing in this PR.

one line before headers

---

servicecontrol/troubleshooting.md

Solution provided by customer to resolve SC startup issue.
Method not found: 'Void System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.set_SerializerSettings(Newtonsoft.Json.JsonSerializerSettings)'

Solution to resolve SC startup issue

---

nservicebus/upgrades/7to8/dependency-injection.md

Properly reflecting https://github.com/Particular/NServiceBus/pull/5741 in the upgrade guide

Reflect DI changes in the upgrade guide

---

servicecontrol/installation.md

Based on support case, first draft in adding this information to the docs.

Moving / migrating SC instances to another server

---

transports/sql/transactions.md
transports/sql/transactions_ambient-core-warning_sqltransport_[6,).partial.md
transports/upgrades/sqlserver-31to4.md

Explanation of https://github.com/Particular/NServiceBus.SqlServer/pull/715

Explain warn for TransactionScope in netcore

---

nservicebus/outbox/index.md

editorial review of https://github.com/Particular/docs.particular.net/pull/5034

Outbox editorial review

---

README.md
Snippets/ABSDataBus/ABSDataBus_5/ABSDataBus_5.csproj
Snippets/Core/Core_8/Core_8.csproj
Snippets/NonDurablePersistence/NonDurablePersistence_1/NonDurablePersistence_1.csproj
Snippets/mongodb/MongoDB_2/DocumentVersion.cs
Snippets/mongodb/MongoDB_2/Usage.cs
Snippets/mongodb/MongoDB_3/DocumentVersion.cs
Snippets/mongodb/MongoDB_3/MongoDB_3.csproj
Snippets/mongodb/MongoDB_3/Usage.cs
samples/dependency-injection/externally-managed-mode/Core_8/Sample/Sample.csproj
samples/encryption/encryption-conventions/PropertyEncryption_3/Endpoint1/Endpoint1.csproj
samples/encryption/encryption-conventions/PropertyEncryption_3/Endpoint2/Endpoint2.csproj
samples/encryption/encryption-conventions/PropertyEncryption_3/Shared/Shared.csproj
samples/logging/metrics/Metrics_4/Endpoint/Endpoint.csproj
samples/mongodb/simple/MongoDB_3/Server/Server.csproj
samples/mongodb/simple/MongoDB_3/Shared/Shared.csproj
samples/rabbitmq/simple/Rabbit_7/Receiver/Receiver.csproj
samples/rabbitmq/simple/Rabbit_7/Sender/Sender.csproj
samples/rabbitmq/simple/Rabbit_7/Shared/Shared.csproj
samples/saga/simple/Core_8/Sample/Sample.csproj
samples/sqltransport-sqlpersistence/Core_8/Receiver/Receiver.csproj
samples/sqltransport-sqlpersistence/Core_8/Sender/Sender.csproj
samples/sqltransport-sqlpersistence/Core_8/Shared/Shared.csproj
tests/IntegrityTests/ValidatePrerelease.cs

Prevent prereleases from using wildcards to avoid samples breaking

---

menu/menu.yaml
tutorials/nservicebus-sagas/2-timeouts/tutorial.md
tutorials/nservicebus-sagas/3-integration/Snippets/Core_7/2-ShipWithMaple.cs
tutorials/nservicebus-sagas/3-integration/Snippets/Core_7/3-ShipWithAlpine.cs
tutorials/nservicebus-sagas/3-integration/Snippets/Core_7/4-AcceptedByAlpine.cs
tutorials/nservicebus-sagas/3-integration/Snippets/Core_7/5-EdgeCases.cs.cs
tutorials/nservicebus-sagas/3-integration/Solution/Shipping/Integration/ShipWithAlpineHandler.cs
tutorials/nservicebus-sagas/3-integration/Solution/Shipping/Integration/ShipWithMapleHandler.cs
tutorials/nservicebus-sagas/3-integration/Solution/Shipping/ShipOrderWorkflow.cs
tutorials/nservicebus-sagas/3-integration/tutorial.md
tutorials/nservicebus-sagas/index.md

Added run the solution section

Saga tutorial 3 integration - supplements 

---

transports/upgrades/asb-6to7.md
transports/upgrades/asb-7to8.md
transports/upgrades/asb-8to9.md
transports/upgrades/asb-9to10.md
transports/upgrades/asb-9to9.1.md

Got suspicious because I know there is no NServiceBus Core V9.

Fix ASBL upgrade guide core versions & add Legacy to titles

---

samples/hosting/generic-host/sample.md

wasn't properly fixed during the enhancement release as it seems. Discovered by @agross

Fix sample

---

samples/hosting/generic-host/sample.md

relates to https://github.com/Particular/docs.particular.net/pull/5149

editorial review of snippet description in generic host sample

---

nservicebus/outbox/index.md

Based on https://discuss.particular.net/t/outbox-outgoing-messages-dispatch-phase/2212/3

Outbox dispatching of each transport operations happens in isolation

---

servicecontrol/troubleshooting.md

Based on https://github.com/Particular/ServicePulse/issues/995

SmartScreen blocks installer guidance

---

transports/azure-service-bus/configuration.md

_Related to https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/issues/213_

Clarify ASB shorteners documentation

---

Snippets/Sqs/Sqs_5/Usage.cs
menu/menu.yaml
transports/sqs/native-integration.md

Native SQS message can be accessed by injecting a behavior

Document how to access the native sqs message

---

Snippets/ASBFunctions/ASBFunctions_0/ASBFunctions_0.csproj
Snippets/ASBFunctions/ASBFunctions_0/FakeFunctionsSdk.cs
Snippets/ASBFunctions/ASBFunctions_0/FunctionsHostBuilderUsage.cs
Snippets/ASBFunctions/ASBFunctions_0/StaticUsage.cs
Snippets/ASQFunctions/ASQFunctions_0/ASQFunctions_0.csproj
Snippets/ASQFunctions/ASQFunctions_0/FakeFunctionsSdk.cs
Snippets/ASQFunctions/ASQFunctions_0/FunctionsHostBuilderUsage.cs
Snippets/ASQFunctions/ASQFunctions_0/StaticUsage.cs
previews/azure-functions-service-bus.md
previews/azure-functions-storage-queues.md
samples/previews/azure-functions/service-bus/ASBFunctions_0/AzureFunctions-ASB.StartupProjects.txt
samples/previews/azure-functions/service-bus/ASBFunctions_0/AzureFunctions-ASB.sln
samples/previews/azure-functions/service-bus/ASBFunctions_0/AzureFunctions.ASBTrigger.FunctionsHostBuilder/AzureFunctions.ASBTrigger.FunctionsHostBuilder.csproj
samples/previews/azure-functions/service-bus/ASBFunctions_0/AzureFunctions.ASBTrigger.FunctionsHostBuilder/HttpSender.cs
samples/previews/azure-functions/service-bus/ASBFunctions_0/AzureFunctions.ASBTrigger.Static/AzureFunctions.ASBTrigger.Static.csproj
samples/previews/azure-functions/service-bus/ASBFunctions_0/AzureFunctions.ASBTrigger.Static/AzureServiceBusTriggerFunction.cs
samples/previews/azure-functions/service-bus/ASBFunctions_0/AzureFunctions.ASBTrigger.Static/HttpSender.cs
samples/previews/azure-functions/service-bus/sample.md
samples/previews/azure-functions/storage-queues/sample.md

Dispatching outside a message handler

---

Snippets/ASP/ASTP_3/Behaviors.cs
Snippets/ASP/ASTP_4/Behaviors.cs
persistence/azure-table/configuration_code_astp_[3,).partial.md

relates to https://github.com/Particular/docs.particular.net/pull/5148

Review configuration code astp

---

transports/sqs/native-integration.md

relates to https://github.com/Particular/docs.particular.net/pull/5165

editorial review of SQS native integration

---

samples/platformtools-docker-compose/sample.md

Review of Docker Compose sample

---

nservicebus/tools/migrate-to-native-delivery.md

Timeoutmigration updates

---

nservicebus/tools/migrate-to-native-delivery.md

Do we plan to have an example of commands for every permutation?

Adding documentation for NHibernate

---

nservicebus/upgrades/supported-platforms.md
platform/nservicebus.include.md

Update related to https://github.com/Particular/Exploration/issues/482

update references to net standard where required

---

transports/sqs/configuration-options-policy-intro.include.md
transports/sqs/configuration-options_policy_sqs_[5,5.2).partial.md
transports/sqs/configuration-options_policy_sqs_[5.3,).partial.md

relates to https://github.com/Particular/docs.particular.net/pull/5182

editorial review of recent SQS config options changes

---

.github/workflows/build-projects.yml

has no effect in this workflow

remove redundant env var in build-projects.yml

---

samples/azure-service-bus-netstandard/native-integration-pub-sub/ASBS_2/NativeIntegrationPubSubASBS.sln
samples/azure-service-bus-netstandard/native-integration-pub-sub/ASBS_2/NativeShared/NativeShared.csproj
samples/azure-service-bus-netstandard/native-integration-pub-sub/ASBS_2/NativeShared/TopologyManager.cs
samples/azure-service-bus-netstandard/native-integration-pub-sub/ASBS_2/NativeSubscriberA/NativeSubscriberA.csproj
samples/azure-service-bus-netstandard/native-integration-pub-sub/ASBS_2/NativeSubscriberA/Program.cs
samples/azure-service-bus-netstandard/native-integration-pub-sub/ASBS_2/NativeSubscriberB/NativeSubscriberB.csproj
samples/azure-service-bus-netstandard/native-integration-pub-sub/ASBS_2/NativeSubscriberB/Program.cs
samples/azure-service-bus-netstandard/native-integration-pub-sub/ASBS_2/Publisher/Program.cs
samples/azure-service-bus-netstandard/native-integration-pub-sub/ASBS_2/Publisher/Publisher.csproj
samples/azure-service-bus-netstandard/native-integration-pub-sub/ASBS_2/Shared/EventOne.cs
samples/azure-service-bus-netstandard/native-integration-pub-sub/ASBS_2/Shared/EventTwo.cs
samples/azure-service-bus-netstandard/native-integration-pub-sub/ASBS_2/Shared/Shared.csproj
samples/azure-service-bus-netstandard/native-integration/ASBS_2/NativeIntegrationASBS.sln
samples/azure-service-bus-netstandard/native-integration/ASBS_2/NativeSender/NativeSender.csproj
samples/azure-service-bus-netstandard/native-integration/ASBS_2/NativeSender/Program.cs
samples/azure-service-bus-netstandard/native-integration/ASBS_2/Receiver/NativeMessageHandler.cs
samples/azure-service-bus-netstandard/native-integration/ASBS_2/Receiver/Program.cs
samples/azure-service-bus-netstandard/native-integration/ASBS_2/Receiver/Receiver.csproj
samples/azure-service-bus-netstandard/native-integration/ASBS_2/Shared/NativeMessage.cs
samples/azure-service-bus-netstandard/native-integration/ASBS_2/Shared/Shared.csproj
samples/azure-service-bus-netstandard/send-reply/ASBS_2/Endpoint1/Endpoint1.csproj
samples/azure-service-bus-netstandard/send-reply/ASBS_2/Endpoint1/Message2Handler.cs
samples/azure-service-bus-netstandard/send-reply/ASBS_2/Endpoint1/Program.cs
samples/azure-service-bus-netstandard/send-reply/ASBS_2/Endpoint2/Endpoint2.csproj
samples/azure-service-bus-netstandard/send-reply/ASBS_2/Endpoint2/Message1Handler.cs
samples/azure-service-bus-netstandard/send-reply/ASBS_2/Endpoint2/Program.cs
samples/azure-service-bus-netstandard/send-reply/ASBS_2/SendReply.sln
samples/azure-service-bus-netstandard/send-reply/ASBS_2/Shared/Message1.cs
samples/azure-service-bus-netstandard/send-reply/ASBS_2/Shared/Message2.cs
samples/azure-service-bus-netstandard/send-reply/ASBS_2/Shared/Shared.csproj

Adding samples for the ASBS transport version 2 that is targeting Core v8

ASBS v2 samples

---

nservicebus/tools/migrate-to-native-delivery.md

relates to:
- https://github.com/Particular/docs.particular.net/pull/5206
- https://github.com/Particular/docs.particular.net/pull/5207

editorial review of recent changes to migrating to native delivery

---

nservicebus/recoverability/index.md

To align with https://github.com/Particular/Platform/pull/24/files
Related to https://github.com/Particular/KeepTheLightsOn/issues/633

Updated delayed retries max limit

---

samples/azure-service-bus-netstandard/lock-renewal/ASBS_1/LockRenewal/Program.cs
samples/azure-service-bus-netstandard/lock-renewal/ASBS_2/LockRenewal/Program.cs
samples/azure-service-bus-netstandard/lock-renewal/sample.md

Closes https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/issues/270

Add information about lock duration longer than 10 minutes

---

Snippets/Raven/Raven.sln
Snippets/Raven/Raven_6.5/Raven_6.5.csproj
Snippets/Raven/Raven_6.5/Session/HandlerThatUsesSession.cs
Snippets/Raven/Raven_6.5/Session/MyDocument.cs
Snippets/Raven/Raven_6.5/Session/MyMessage.cs
Snippets/Raven/Raven_6.5/Session/SagaThatUsesSession.cs

Add documentation on how to inject the raven session

---

transports/upgrades/asb-10toasbs-1.md

relates to https://github.com/Particular/docs.particular.net/pull/5231

editorial review of message lock renewal in asb-10toasbs-1.md

---

persistence/sql/outbox_modes_sqlpersistence_[6,).partial.md

relates to https://github.com/Particular/docs.particular.net/pull/5229

editorial review of recent changes to docs for customized outbox isolation level

---

samples/azure-service-bus-netstandard/lock-renewal/ASBS_1/LockRenewal/Program.cs
samples/azure-service-bus-netstandard/lock-renewal/ASBS_2/LockRenewal/Program.cs
samples/azure-service-bus-netstandard/lock-renewal/sample.md

relates to https://github.com/Particular/docs.particular.net/pull/5227

editorial review of lock renewal sample

---

servicecontrol/maintenance-mode.md

relates to https://github.com/Particular/docs.particular.net/pull/5255

editorial review of SC maintenance mode

---

nservicebus/hosting/index.md

relates to https://github.com/Particular/docs.particular.net/pull/5252

typos and grammar

---

nservicebus/upgrades/support-policy.md

NServiceBus 5 extended support ended October 2020

Update NServiceBus 5 extended support status

---

nservicebus/messaging/publish-subscribe/index.md

Based on https://discuss.particular.net/t/missing-queue-retry-behavior/2353/2

Clarify that events are copied into each subscribers input queue

---

samples/hosting/generic-multi-hosting/Core_7/Sample.MultiHosting/Program.cs

Might read a bit nicer. Unfortunately we don't use C# 8 language features yet for [using statements](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-statement)

Use using blocks in multi-hosting sample

---

nservicebus/messaging/send-a-message.md

Fixes https://github.com/Particular/docs.particular.net/issues/5268

Move note to the correct section

---

nservicebus/upgrades/7to8/dependency-injection.md

Use the correct Unity package and API in the externally managed snippet.

Fix the Unity snippet in the DI upgrade guide

---

nservicebus/upgrades/7to8/index.md

Replaces https://github.com/Particular/docs.particular.net/pull/5292

Add shutdown behaviour section to cancellation token upgrade guide

---

servicecontrol/troubleshooting.md

relates to https://github.com/Particular/docs.particular.net/pull/5245

editorial review of SC troubleshooting

---

samples/throttling/sample.md

_relates to https://github.com/Particular/docs.particular.net/pull/5316_

editorial review of recent changes to throttling sample

---

Snippets/Rabbit/Rabbit_7/MyRoutingTopology.cs
Snippets/Rabbit/Rabbit_7/QuorumQueues.cs
Snippets/Rabbit/Rabbit_7/Rabbit_7.csproj
Snippets/Rabbit/Rabbit_7/Usage.cs
transports/rabbitmq/cluster_quorumqueues_rabbit_[7,).partial.md

Some suggestions and snippets for quorum queue configuration. Targeting @WilliamBZA PR: https://github.com/Particular/docs.particular.net/pull/5313

Quorum queues doc suggestions

---

nservicebus/cancellation-and-catching-exceptions.md

alternative to https://github.com/Particular/docs.particular.net/pull/5350
as discussed with @andreasohlund

cancellation and catching exceptions

---

menu/menu.yaml
transports/azure-storage-queues/troubleshooting.md

Azure Storage Queues troubleshooting page

---

nservicebus/licensing/index.md

Adds a note about license minification with a parameter added to the download link

license minification

---

servicecontrol/audit-instances/index.md

Linking to the Audit Filtering sample from the ServiceControl Audit instances documentation.
https://particularsoftware.slack.com/archives/C9KHXNF9C/p1624612708075400

Link to Audit-filter sample

---

nservicebus/handlers/index.md

After doing a minor editorial tweak, I started finding more ways to improve the guidance in this section, resulting in this PR.
I'm hoping I didn't change any of the substance of the guidance. Please confirm one way or the other.

More significant rework of the "multiple handlers" section

---

Snippets/Gateway/Gateway.sln

relates to https://github.com/Particular/docs.particular.net/pull/5381

fix sln config for gateway snippets

---

nservicebus/outbox/index.md

relates to https://github.com/Particular/docs.particular.net/pull/5372
Regarding the Mermaid diagram:
The rendering of the subgraph titles isn't ideal, but I guess we can tackle that separately as an issue for the entire site.

editorial review of recent outbox changes

---

transports/azure-service-bus/operational-scripting.md

Provide some example for ASB CLI

---

menu/menu.yaml
nservicebus/upgrades/azure-functions-service-bus-1to2.md

Document API changes for the next major release

Azure Functions with Azure Service Bus 2.0 Upgrade Guide

---

nservicebus/handlers/index.md

relates to https://github.com/Particular/docs.particular.net/pull/5386

editorial review of multiple handlers for a single message

---

Snippets/Core/Core_8/Headers/WriteSaga.cs
nservicebus/sagas/index.md

This PR documents how to set headers when using `ReplyToOriginator`.

Document setting headers for ReplyToOriginator

---

nservicebus/messaging/immutable-messages.md

The current wording did not make sense to me, reworded for clarity

Rephrase immutable messages

---

Snippets/Core/Core_8/Sagas/SimpleSaga/OrderSagaData.cs
nservicebus/sagas/index.md
nservicebus/sagas/index_disable-shared-state-check_core_[8,].partial.md

Adds explanation for not sharing saga state.
Connects to https://github.com/Particular/NServiceBus/issues/4811 and https://github.com/Particular/NServiceBus/pull/5783

Explain shared state problem

---

menu/menu.yaml
nservicebus/messaging/moving-handlers.md

fixes https://github.com/Particular/EnhancementReleases/issues/67

Adding documentation about moving handlers between the endpoints

---

menu/menu.yaml
nservicebus/tools/index.md

relates to https://github.com/Particular/docs.particular.net/pull/5427
/cc @lailabougria @andreasohlund @mauroservienti @WilliamBZA

editorial review of nservicebus/tools

---

nservicebus/hosting/azure-functions-service-bus/index_assembly-scanner_ASBFunctions_[2.0,).partial.md

relates to https://github.com/Particular/docs.particular.net/pull/5426
/cc @HEskandari @mikeminutillo @timbussmann

editorial review of Azure Functions with Azure Service Bus assembly scanning

---

nservicebus/logging/usage.md

As part of doing the docs review I figured that this page should guide users towards the MS logging since that's where we're heading

Recommend using Microsoft logging for new endpoints

---

nservicebus/logging/usage.md
nservicebus/operations/dotnet-framework-version-requirements.md
samples/immutable-messages/sample.md
samples/logging/commonlogging/sample.md
samples/logging/custom-factory/sample.md
samples/logging/default/sample.md
samples/logging/hostcustom/sample.md
samples/logging/notifications/sample.md
samples/outbox/rabbit/sample.md
servicecontrol/upgrades/3to4/index.md

_Solves https://github.com/Particular/DeveloperExperience/issues/1779_

Weekly legacy docs review

---

servicecontrol/upgrades/index.md

Several tips targeting operators/sysadmins when upgrading ServiceControl instances.

ServiceControl upgrade tips

---

nservicebus/operations/tuning.md

Based on feedback by @DavidBoike https://github.com/Particular/docs.particular.net/pull/5518/files#r736935618

Reordering and mentioning the importance of system monitoring

---

servicecontrol/audit-instances/creating-config-file.md
servicecontrol/creating-config-file.md

Closes #5548
The feature was introduced in https://github.com/Particular/ServiceControl/pull/2516/files

Document EnableFullTextSearchOnBodies

---

servicecontrol/troubleshooting.md
servicecontrol/upgrades/3to4/index.md

Added documentation for the new Saga audit data retention custom check.

Saga audit retention check

---

nservicebus/hosting/azure-functions-service-bus/index.md

Adds package and Visual Studio requirements for In-process AF.

Add package requirements for Azure Functions - In Process

---

nservicebus/upgrades/release-policy.md

Following up the discussion about taking package dependencies in minors or majors.

Improve wording around semver

---

nservicebus/sagas/index.md
nservicebus/sagas/index_disable-shared-state-check_core_[8,].partial.md

Based on https://github.com/Particular/NServiceBus.NHibernate/issues/701

Guidance that indicate to avoid sharing types between saga types

---

nservicebus/serialization/newtonsoft.md

Based on your input on https://github.com/Particular/NServiceBus.Newtonsoft.Json/pull/215

Add more details on TypeNameHandling setting

---

nservicebus/upgrades/7to8/index.md

Documentation update for Particular/NServiceBus#6224

Add implicit usings to upgrade guide

---

tutorials/quickstart/Solution/ClientUI/wwwroot/Content/app.js
tutorials/quickstart/tutorial-extending-the-system.md

This update has the following changes.
1.  Add kissmetrics to quickstart tutorial to capture the following events 
- when solution runs 
- when a message is sent
2. Fix the ordering of the steps mentioned in Page 3 of the quickstart tutorial

Add kissmetrics to quickstart

---

monitoring/custom-checks/in-servicepulse.md
monitoring/heartbeats/in-servicepulse.md
monitoring/heartbeats/notification-events.md
nservicebus/hosting/cloud-services-host/critical.md
platform/platform-sample-package.md
transports/msmq/distributor/troubleshooting.md
tutorials/nservicebus-sagas/2-timeouts/tutorial.md

Result of https://github.com/Particular/DeveloperExperience/issues/1997

Docs review as part of non-critical support

---

nservicebus/messaging/evolving-contracts.md
nservicebus/messaging/messages-events-commands.md
nservicebus/messaging/sharing-contracts.md
nservicebus/upgrades/7to8/message-contracts.md

relates to https://github.com/Particular/docs.particular.net/pull/5634

editorial review of shared message contracts docs

---

samples/logging/extensions-logging/Extensions.Logging_1/Extensions.Logging.DotSettings
samples/logging/extensions-logging/Extensions.Logging_1/Extensions.Logging.sln
samples/logging/extensions-logging/Extensions.Logging_1/Extensions.Logging.sln.DotSettings
samples/logging/extensions-logging/Extensions.Logging_1/Sample/MyHandler.cs
samples/logging/extensions-logging/Extensions.Logging_2/Extensions.Logging.sln
samples/logging/extensions-logging/Extensions.Logging_2/Sample/MyHandler.cs
samples/logging/extensions-logging/Extensions.Logging_2/Sample/MyMessage.cs
samples/logging/extensions-logging/Extensions.Logging_2/Sample/Program.cs
samples/logging/extensions-logging/Extensions.Logging_2/Sample/Sample.csproj

Also changes the log level for the handler message to warn since we're using a colored logger which isn't clear at all as long as we're only logging info/debug messages.

Add sample for NServiceBus.Extensions.Logging v2

---

samples/logging/datadog/Core_7/Datadog.sln.DotSettings
samples/logging/datadog/Core_8/Datadog.sln
samples/logging/datadog/Core_8/Endpoint/DataDogMetrics.cs
samples/logging/datadog/Core_8/Endpoint/Endpoint.csproj
samples/logging/datadog/Core_8/Endpoint/LoadSimulator.cs
samples/logging/datadog/Core_8/Endpoint/Program.cs
samples/logging/datadog/Core_8/Endpoint/SomeCommand.cs
samples/logging/datadog/Core_8/Endpoint/SomeCommandHandler.cs
samples/logging/datadog/sample.md

needs some refactoring since the `Feature` isn't required anymore to get to the metrics options.

Add Datadog sample for NSB v8

---

samples/sql-persistence/injecting-services/SqlPersistence_6/InjectingServices.sln.DotSettings
samples/sql-persistence/injecting-services/SqlPersistence_7/Endpoint/ConnectionHolder.cs
samples/sql-persistence/injecting-services/SqlPersistence_7/Endpoint/DataService.cs
samples/sql-persistence/injecting-services/SqlPersistence_7/Endpoint/Endpoint.csproj
samples/sql-persistence/injecting-services/SqlPersistence_7/Endpoint/Program.cs
samples/sql-persistence/injecting-services/SqlPersistence_7/Endpoint/SqlConnectionBehavior.cs
samples/sql-persistence/injecting-services/SqlPersistence_7/Endpoint/SqlHelper.cs
samples/sql-persistence/injecting-services/SqlPersistence_7/Endpoint/TestMessageHandler.cs
samples/sql-persistence/injecting-services/SqlPersistence_7/Endpoint/TestMsg.cs
samples/sql-persistence/injecting-services/SqlPersistence_7/InjectingServices.sln

Sql di sample for NSB v8

---

samples/routing/fowarding-address/Core_7/MessageForwarding.sln.DotSettings
samples/routing/fowarding-address/Core_8/MessageForwarding.sln
samples/routing/fowarding-address/Core_8/Messages/ImportantMessage.cs
samples/routing/fowarding-address/Core_8/Messages/Messages.csproj
samples/routing/fowarding-address/Core_8/NServiceBus.ForwardingAddress/ForwardMessagesWithForwardingAddress.cs
samples/routing/fowarding-address/Core_8/NServiceBus.ForwardingAddress/ForwardingAddressDirectory.cs
samples/routing/fowarding-address/Core_8/NServiceBus.ForwardingAddress/IncomingPhysicalMessageContextExtensions.cs
samples/routing/fowarding-address/Core_8/NServiceBus.ForwardingAddress/LeaveForwardingAddressFeature.cs
samples/routing/fowarding-address/Core_8/NServiceBus.ForwardingAddress/MessageForwardingState.cs
samples/routing/fowarding-address/Core_8/NServiceBus.ForwardingAddress/NServiceBus.ForwardingAddress.csproj
samples/routing/fowarding-address/Core_8/NServiceBus.ForwardingAddress/RerouteMessagesWithForwardingAddress.cs
samples/routing/fowarding-address/Core_8/NServiceBus.ForwardingAddress/RoutingExtensions.cs
samples/routing/fowarding-address/Core_8/NServiceBus.ForwardingAddress/UnicastRouteResolver.cs
samples/routing/fowarding-address/Core_8/NewDestination/ImportanMessageHandler.cs
samples/routing/fowarding-address/Core_8/NewDestination/NewDestination.csproj
samples/routing/fowarding-address/Core_8/NewDestination/Program.cs
samples/routing/fowarding-address/Core_8/OriginalDestination/ImportantMessageHandler.cs
samples/routing/fowarding-address/Core_8/OriginalDestination/OriginalDestination.csproj
samples/routing/fowarding-address/Core_8/OriginalDestination/Program.cs
samples/routing/fowarding-address/Core_8/Sender/Program.cs
samples/routing/fowarding-address/Core_8/Sender/Sender.csproj

Forwarding sample for NSB v8

---

nservicebus/router/index.md

The links to samples were confusing. One didn't even use router. And many others that we have weren't even mentioned.

Added router samples & removed one non-router sample

---

transports/azure-service-bus/topology.md

Addresses https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/issues/509

Asb topology clarifications

---

samples/azure-service-bus-netstandard/azure-service-bus-long-running/sample.md
samples/azure-service-bus-netstandard/azure-service-bus-msmq-bridge/sample.md
samples/azure/includes/asb-transport.include.md
transports/azure-service-bus/legacy/message-lock-renewal.md

Warning is hinting at ASBL but sample is targeting ASBS.

Removed warning on ASBS long running tasks sample

---

nservicebus/hosting/cloud-services-host/critical.md
platform/platform-sample-package.md
transports/msmq/distributor/troubleshooting.md
tutorials/nservicebus-sagas/2-timeouts/tutorial.md

relates to https://github.com/Particular/docs.particular.net/pull/5659

editorial review of #5659

---

nservicebus/messaging/databus/custom_content_core_[6.0,).partial.md
nservicebus/messaging/databus/file-share.md
nservicebus/messaging/databus/index.md

Databus docs did not mention how the TTBR attribute/convention is passed to databus implementation.

Databus usage regarding time to be received

---

servicecontrol/installation.md

Make powershell guidance more discoverable. Based on tweet of @Jaykul  https://twitter.com/Jaykul/status/1511012099023122437

Added link to ServiceControl Management PowerShell module guidance

---

samples/pipeline/header-propagation/Core_7/HeaderPropagation.sln
samples/pipeline/header-propagation/Core_7/Messages/Messages.csproj
samples/pipeline/header-propagation/Core_7/Messages/ProcessOrder.cs
samples/pipeline/header-propagation/Core_7/Messages/ShipOrder.cs
samples/pipeline/header-propagation/Core_7/Receiver/MyMessageHandler.cs
samples/pipeline/header-propagation/Core_7/Receiver/Program.cs
samples/pipeline/header-propagation/Core_7/Receiver/PropagateCustomerIdHeaderBehavior.cs
samples/pipeline/header-propagation/Core_7/Receiver/Receiver.csproj
samples/pipeline/header-propagation/Core_7/Sender/Program.cs
samples/pipeline/header-propagation/Core_7/Sender/Sender.csproj
samples/pipeline/header-propagation/Core_8/HeaderPropagation.sln
samples/pipeline/header-propagation/Core_8/Messages/Messages.csproj
samples/pipeline/header-propagation/Core_8/Messages/ProcessOrder.cs
samples/pipeline/header-propagation/Core_8/Messages/ShipOrder.cs
samples/pipeline/header-propagation/Core_8/Receiver/MyMessageHandler.cs
samples/pipeline/header-propagation/Core_8/Receiver/Program.cs
samples/pipeline/header-propagation/Core_8/Receiver/PropagateCustomerIdHeaderBehavior.cs
samples/pipeline/header-propagation/Core_8/Receiver/Receiver.csproj
samples/pipeline/header-propagation/Core_8/Sender/Program.cs
samples/pipeline/header-propagation/Core_8/Sender/Sender.csproj
samples/pipeline/header-propagation/sample.md

Demonstrates how to use a pipeline behavior to copy headers from incoming to outgoing messages

Create header propagation sample

---

.markdownlint.json
nservicebus/upgrades/support-policy.md

prevent Version wrapping in major version table

---

nservicebus/upgrades/supported-platforms_content_core_7.partial.md
nservicebus/upgrades/supported-platforms_content_core_8.partial.md

adding .NET 7 Preview to supported platforms

adding .NET 7 Preview to supported platforms

---

Snippets/Sqs/Sqs_All/NativeSend/Tests.cs
Snippets/Templates/Templates_2/NServiceBusDockerContainer.cs
Snippets/Templates/Templates_3/NServiceBusDockerContainer.cs
Snippets/Templates/Templates_4/NServiceBusDockerContainer.cs

PR https://github.com/Particular/docs.particular.net/pull/5749 didn't contain all required NewtonsoftJsonSerializer migrations based. The migrations in this PR are based on https://github.com/Particular/docs.particular.net/actions/runs/2585818486

Missed NewtonsoftJsonSerializer migrations in #5749

---

nservicebus/upgrades/7to8/index.md

Adds a section about upgrading from a v7 endpoint using the community packages.

Add OpenTelemetry section for the upgrade guide

---

samples/azure-functions/service-bus/sample.md

Remove warning for static option

---

samples/transactional-session/cosmosdb/Core_8/Backend/Backend.csproj
samples/transactional-session/cosmosdb/Core_8/Backend/OrderReceivedHandler.cs
samples/transactional-session/cosmosdb/Core_8/Backend/Program.cs
samples/transactional-session/cosmosdb/Core_8/Frontend/Frontend.csproj
samples/transactional-session/cosmosdb/Core_8/Frontend/Program.cs
samples/transactional-session/cosmosdb/Core_8/Frontend/Worker.cs
samples/transactional-session/cosmosdb/Core_8/Shared/Configuration.cs
samples/transactional-session/cosmosdb/Core_8/Shared/OrderDocument.cs
samples/transactional-session/cosmosdb/Core_8/Shared/OrderReceived.cs
samples/transactional-session/cosmosdb/Core_8/Shared/Shared.csproj
samples/transactional-session/cosmosdb/Core_8/TransactionalSessionWithCosmos.sln
samples/transactional-session/cosmosdb/sample.md

Sample using TransactionalSession with CosmosDB transactions

---

samples/servicecontrol/fix-messages/Core_8/FixMalformedMessages.sln
samples/servicecontrol/fix-messages/Core_8/MessageRepairingEndpoint/MessageRepairingEndpoint.csproj
samples/servicecontrol/fix-messages/Core_8/MessageRepairingEndpoint/Program.cs
samples/servicecontrol/fix-messages/Core_8/MessageRepairingEndpoint/SimpleMessageHandler.cs
samples/servicecontrol/fix-messages/Core_8/PlatformLauncher/PlatformLauncher.csproj
samples/servicecontrol/fix-messages/Core_8/PlatformLauncher/Program.cs
samples/servicecontrol/fix-messages/Core_8/Receiver/Program.cs
samples/servicecontrol/fix-messages/Core_8/Receiver/Receiver.csproj
samples/servicecontrol/fix-messages/Core_8/Receiver/SimpleMessageHandler.cs
samples/servicecontrol/fix-messages/Core_8/Sender/Program.cs
samples/servicecontrol/fix-messages/Core_8/Sender/Sender.csproj
samples/servicecontrol/fix-messages/Core_8/Shared/Shared.csproj
samples/servicecontrol/fix-messages/Core_8/Shared/SimpleMessage.cs

V8 sample for fix message , remove other frameworks

V8 sample for fix message

---

samples/servicecontrol/monitoring3rdparty/CustomChecks_4/3rdPartySystem/3rdPartySystem.csproj
samples/servicecontrol/monitoring3rdparty/CustomChecks_4/3rdPartySystem/Program.cs
samples/servicecontrol/monitoring3rdparty/CustomChecks_4/Monitoring3rdParty.sln
samples/servicecontrol/monitoring3rdparty/CustomChecks_4/PlatformLauncher/PlatformLauncher.csproj
samples/servicecontrol/monitoring3rdparty/CustomChecks_4/PlatformLauncher/Program.cs
samples/servicecontrol/monitoring3rdparty/CustomChecks_4/Sample/Monitor.cs
samples/servicecontrol/monitoring3rdparty/CustomChecks_4/Sample/Program.cs
samples/servicecontrol/monitoring3rdparty/CustomChecks_4/Sample/Sample.csproj

V8  sample for monitoring 3rd party

V8  sample for monitoring 3rd party

---

menu/menu.yaml
nservicebus/upgrades/gateway-3to4.md

add doc to upgrade gateway from 3-4

added upgrade gateway3-4

---

platform/installer/offline.md

Update prerequisites for Platform installation

---

servicecontrol/audit-instances/creating-config-file.md
servicecontrol/creating-config-file.md

Documentation for https://github.com/Particular/ServiceControl/issues/2623

Document the InternalQueueName setting for ServiceControl and ServiceControl Audit

---

Snippets/ASQ/ASQN_12/ASQN_12.csproj
nservicebus/upgrades/third-party-license-data.include.md
samples/azure/native-integration-asq/ASQN_12/Receiver/Receiver.csproj
samples/azure/storage-queues/ASQN_12/Endpoint1/Endpoint1.csproj
samples/azure/storage-queues/ASQN_12/Endpoint2/Endpoint2.csproj

Updated third party license page

Update ASQ samples to use latest major release

---

transports/sqs/index.md

Issue raised by customer - have checked with them to ask if this is accurate and complete.

Document kms:GenerateDataKey requirement for encrypted SQS

---

samples/azure-service-bus-netstandard/hierarchy-migration/ASBS_3/Endpoint1/Endpoint1.csproj
samples/azure-service-bus-netstandard/hierarchy-migration/ASBS_3/Endpoint1/Event2Handler.cs
samples/azure-service-bus-netstandard/hierarchy-migration/ASBS_3/Endpoint1/Program.cs
samples/azure-service-bus-netstandard/hierarchy-migration/ASBS_3/Endpoint2/Endpoint2.csproj
samples/azure-service-bus-netstandard/hierarchy-migration/ASBS_3/Endpoint2/Event1Handler.cs
samples/azure-service-bus-netstandard/hierarchy-migration/ASBS_3/Endpoint2/Program.cs
samples/azure-service-bus-netstandard/hierarchy-migration/ASBS_3/HierarchyMigration.sln
samples/azure-service-bus-netstandard/hierarchy-migration/ASBS_3/Migration/Hierarchy.cs
samples/azure-service-bus-netstandard/hierarchy-migration/ASBS_3/Migration/Migration.csproj
samples/azure-service-bus-netstandard/hierarchy-migration/ASBS_3/Migration/Program.cs
samples/azure-service-bus-netstandard/hierarchy-migration/ASBS_3/Migration/Visualize.cs
samples/azure-service-bus-netstandard/hierarchy-migration/ASBS_3/Shared/Event1.cs
samples/azure-service-bus-netstandard/hierarchy-migration/ASBS_3/Shared/Event2.cs
samples/azure-service-bus-netstandard/hierarchy-migration/ASBS_3/Shared/Shared.csproj
samples/azure-service-bus-netstandard/hierarchy-migration/sample.md

Introduces a sample that demonstrates a live migration from on topic to another

Hierarchy migration

---

components/components.yaml
previews/index.md

_connected to https://github.com/Particular/GeneralPlatformExperience/issues/2283_
This removed preview from Bridge component

Adopting Bridge

---

Snippets/Bridge/Bridge_1/Configuration.cs
menu/menu.yaml
nservicebus/bridge/bridge-to-router-note.include.md
nservicebus/bridge/configuration.md
nservicebus/bridge/index.md
nservicebus/bridge/migrating-from-router.md
nservicebus/bridge/performance.md

relates to https://github.com/Particular/docs.particular.net/pull/5705

editorial review of bridge docs

---

nservicebus/hosting/azure-functions-service-bus/index.md
nservicebus/hosting/azure-functions-service-bus/isolated-worker.md

Related code: https://github.com/Particular/NServiceBus.AzureFunctions.Worker.ServiceBus/pull/190

how to opt-out CS8032 to be treated as error

---

nservicebus/tools/migrate-to-native-delivery.md

Had a case where the customer wasn't sure how to structure the command so I've added some examples of it to the docs.

AddExamplesForToolUsage

---

menu/menu.yaml

This document was publicly available but missing from the menu

Add MSMQ delayed delivery to menu

---

servicepulse/install-servicepulse-in-iis.md

Describes the process for deploying in a SubFolder within IIS.
Documentation for https://github.com/Particular/ServicePulse/issues/1375.
Must only be merged once 1.34.0 of ServicePulse is released

Describe how to deploy in a subfolder

---

servicecontrol/powershell.md

Add powershell installation troubleshooting section

---

nservicebus/upgrades/7to8/transport.md

Related to https://github.com/Particular/docs.particular.net/issues/6022, pointing out that queue creation configuration is handled by the installers API.

Add note about installers

---

samples/transactional-session/aspnetcore-webapi/sample.md

relates to https://github.com/Particular/docs.particular.net/pull/6077

editorial tweaks to "Using TransactionalSession with Entity Framework and ASP.NET Core

---

nservicebus/messaging/reply-to-a-message.md
nservicebus/security/index.md
servicecontrol/license.md
servicecontrol/logging.md

[Weekly legacy docs review - 2023-06-05 #2639](https://github.com/Particular/GeneralPlatformExperience/issues/2639)

docs review

---

Snippets/Core/Core_7/Pipeline/InjectingDependencies.cs
Snippets/Core/Core_8/Pipeline/InjectingDependencies.cs
nservicebus/pipeline/manipulate-with-behaviors.md

Follow through from https://discuss.particular.net/t/message-lifetime-scoped-behaviors/3606/2

Document DI for behaviors

---

Snippets/Bridge/Bridge_1/Configuration.cs
nservicebus/bridge/configuration.md

Related to:
- https://github.com/Particular/NServiceBus.Transport.Bridge/pull/265

Improved docs for bridge `RegisterPublisher` configuration API

---

samples/logging/log4net-custom/sample.md

Added warning that the sample is incompatible with Core 8 with some migration recommendations

Added warning that the log4net sample is incompatible with Core 8

---

tutorials/quickstart/Solution/ClientUI/Views/Shared/_Layout.cshtml
tutorials/quickstart/Solution/ClientUI/wwwroot/Content/app.js

Pushing events from the "Quick Start" sample to Google Analytics 4

Quick Start solution update to GA4

---

nservicebus/throughput-tool/amazon-sqs.md
nservicebus/throughput-tool/azure-service-bus.md
nservicebus/throughput-tool/faq.md
nservicebus/throughput-tool/index.md
nservicebus/throughput-tool/rabbitmq.md
nservicebus/throughput-tool/service-control.md
nservicebus/throughput-tool/sql-transport.md

More options tweaks

---

servicecontrol/troubleshooting.md

https://docs.particular.net/servicecontrol/troubleshooting#how-to-move-the-database-to-another-location

ServiceControl troubleshooting - How to move the database to another location

---

menu/menu.yaml
servicecontrol/move-database-location.md
servicecontrol/troubleshooting.md

Move the section on "move database location document" to a separate document

move database location document

---

nservicebus/bridge/configuration.md

Documentation improvements related to:
- https://github.com/Particular/NServiceBus.MessagingBridge/issues/175

Messaging bridge mappings are case-sensitive

---

Snippets/Bridge/Bridge_2/Configuration.cs
nservicebus/bridge/configuration.md

- Documentation for https://github.com/Particular/NServiceBus.MessagingBridge/pull/282

MessagingBridge: How to register multiple publishers by invoking `DoNotEnforceBestPractices`

---

servicepulse/host-config.md

Add instructions on how to disable monitoring via  Service Pulse UI

Instructions on  Disable monitoring in servicepulse UI 

---

nservicebus/recoverability/configure-delayed-retries.md
nservicebus/recoverability/configure-error-handling.md
nservicebus/recoverability/configure-immediate-retries.md
nservicebus/recoverability/custom-recoverability-policy.md
samples/custom-recoverability/Core_7/Client/Client.csproj
samples/custom-recoverability/Core_7/Client/Program.cs
samples/custom-recoverability/Core_7/CustomRecoverability.sln
samples/custom-recoverability/Core_7/Server/MyHandler.cs
samples/custom-recoverability/Core_7/Server/Program.cs
samples/custom-recoverability/Core_7/Server/Server.csproj
samples/custom-recoverability/Core_7/Shared/MyMessage.cs
samples/custom-recoverability/Core_7/Shared/Shared.csproj
samples/custom-recoverability/Core_8/Client/Client.csproj
samples/custom-recoverability/Core_8/Client/Program.cs
samples/custom-recoverability/Core_8/CustomRecoverability.sln
samples/custom-recoverability/Core_8/Server/MyHandler.cs
samples/custom-recoverability/Core_8/Server/Program.cs
samples/custom-recoverability/Core_8/Server/Server.csproj
samples/custom-recoverability/Core_8/Shared/MyMessage.cs
samples/custom-recoverability/Core_8/Shared/Shared.csproj
samples/custom-recoverability/sample.md

This PR adds a sample on how to implement custom recoverability policy

adding a sample for custom recoverability

---

servicepulse/health-check-notifications.md

add clarification around health check notifications

add clarification around health check notifications

---

servicecontrol/audit-instances/maintenance-mode.md
servicecontrol/maintenance-mode.md
servicecontrol/troubleshooting.md
servicecontrol/upgrades/index.md

Small improvements to a few servicecontrol docs

Improvements to servicecontrol doc

---

nservicebus/concepts/glossary.md
nservicebus/messaging/forwarding.md
transports/sql/transactions_native_sqltransport_[6,).partial.md
transports/transactions.md

Added Ghost message to the glossary

Added Ghost message to the glossary

---

servicecontrol/servicecontrol-instances/hardware.md

- relates to https://github.com/Particular/docs.particular.net/pull/6079

minor tweaks to servicecontrol/servicecontrol-instances/hardware.md

---

persistence/sql/index_supportedimpls_sqlpersistence_[3,).partial.md

Verified via automated CI tests added in https://github.com/Particular/NServiceBus.Persistence.Sql/pull/1239

Document AWS Aurora support

---

nservicebus/upgrades/release-policy.md

As we have a section immediately under this called "Interpretations/deviations from SemVer".

Clarify wording around the use of SemVer

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

to adjust for the changed ports introduced with

Update docstools ports on devcontainer settings

---

samples/gateway/Gateway_4/Headquarters/Program.cs
samples/gateway/Gateway_4/RemoteSite/Program.cs

Fixes https://github.com/Particular/docs.particular.net/issues/6144

Use XML serializer for gateway sample

---

samples/gateway/Gateway_3/WebClient.Core/wwwroot/Index.html
samples/gateway/Gateway_4/WebClient.Core/wwwroot/Index.html

Remove duplicate gateway code snippet in gateway sample - https://docs.particular.net/samples/gateway/

Remove duplicate gateway code snippet

---

servicecontrol/troubleshooting.md

add some more error logs than can be used in troubleshooting

add some more error logs than can be used in  troubleshooting 

---

nservicebus/messaging/send-a-message.md

Based on https://discuss.particular.net/t/does-sendlocal-make-us-of-the-infrastructure-behind/3650

SendLocal uses queueing infra

---

servicecontrol/audit-instances/creating-config-file.md

Add an image to show how to find the audit config file

Add an image to show how to find the audit config file

---

nservicebus/hosting/nservicebus-host/troubleshooting.md

@soujay @TravisNickels please review the wording changes I've made on top of your #6164 PR.
Also, I wasn't entirely sure what was meant by the "auto" services bit at the end. See if you can improve that further.
Thanks.

Update the wording of troubleshooting.md

---

nservicebus/messaging/message-type-detection.md
transports/sqs/native-integration_messagetypedetection_sqs_[5.7,6.0).partial.md
transports/sqs/native-integration_messagetypedetection_sqs_[6.1,).partial.md

Closes https://github.com/Particular/docs.particular.net/issues/6160
Improves the documentation slightly and catches up with the changes introduced in NServiceBus 7.4 in https://github.com/Particular/NServiceBus/pull/5696

Improve message type detection documentation

---

tutorials/quickstart/tutorial-extending-the-system.md

Pushing tweet completion click event with GA4

Pushing tweet completion click event with GA4

---

nservicebus/lifecycle/endpointstartandstop.md
nservicebus/messaging/timeout-manager.md
nservicebus/messaging/timeout-manager_content_core_[,8).partial.md
persistence/sql/index.md
samples/netcore-reference/sample.md
samples/pipeline/unit-of-work/sample.md
samples/routing/message-forwarding/sample.md

Updates resulting from https://github.com/Particular/GeneralPlatformExperience/issues/2759

Updates to docs from non-critical support

---

menu/menu.yaml
serviceinsight/troubleshooting.md

Add serviceinsight troubleshooting link to the menu

Add serviceinsight troubleshooting link to the menu

---

README.md

Mentioning the described guidance applied in https://github.com/Particular/docs.particular.net/pull/6233 in the readme.

Link to default language version table

---

nservicebus/messaging/databus/index.md

relates to:
- https://github.com/Particular/docs.particular.net/pull/6151

editorial review of recent databus doc changes

---

samples/versioning/sample.md

The versioning sample demonstrates message inheritance via interfaces and polymorphic dispatch which have a relation with articles related to immutable messages and messages as interfaces.

Relate message versioning sample to immutable messages and messages as interfaces docs that mentioned inheritance and polymorphic dispatch

---

samples/hosting/generic-multi-hosting/sample.md
servicepulse/intro-failed-messages.md
transports/types.md

_Solves https://github.com/Particular/GeneralPlatformExperience/issues/2897_

Legacy Docs

---

samples/throttling/Core_7/Limited/GitHubSearchHandler.cs
samples/throttling/Core_7/Limited/Limited.csproj
samples/throttling/Core_7/Limited/Program.cs
samples/throttling/Core_7/Limited/ThrottlingBehavior.cs
samples/throttling/Core_7/Sender/GitHubSearchResponseHandler.cs
samples/throttling/Core_7/Sender/Program.cs
samples/throttling/Core_7/Shared/SearchGitHub.cs
samples/throttling/Core_7/Shared/SearchResponse.cs
samples/throttling/Core_8/Limited/GitHubSearchHandler.cs
samples/throttling/Core_8/Limited/Limited.csproj
samples/throttling/Core_8/Limited/Program.cs
samples/throttling/Core_8/Limited/ThrottlingBehavior.cs
samples/throttling/Core_8/Sender/GitHubSearchResponseHandler.cs
samples/throttling/Core_8/Sender/Program.cs
samples/throttling/Core_8/Shared/SearchGitHub.cs
samples/throttling/Core_8/Shared/SearchResponse.cs
samples/throttling/Core_9/Limited/GitHubSearchHandler.cs
samples/throttling/Core_9/Limited/Limited.csproj
samples/throttling/Core_9/Limited/Program.cs
samples/throttling/Core_9/Limited/ThrottlingBehavior.cs
samples/throttling/Core_9/Sender/GitHubSearchResponseHandler.cs
samples/throttling/Core_9/Sender/Program.cs
samples/throttling/Core_9/Sender/Sender.csproj
samples/throttling/Core_9/Shared/SearchGitHub.cs
samples/throttling/Core_9/Shared/SearchResponse.cs
samples/throttling/Core_9/Shared/Shared.csproj
samples/throttling/Core_9/Throttling.sln

FYI I had to update the GitHub APIs being used in the sample because the previous one now requires you to be authenticated to use.

Add NServiceBus 9 Message Throughput Throttling sample

---

nservicebus/router/direct.md

Part of the recurring documentation review

Note about transactional session

---

servicecontrol/powershell.md

- Resolves https://github.com/Particular/docs.particular.net/issues/6360

Listing requirements for ServiceControl PowerShell module

---

samples/hosting/kubernetes-simple/Core_8/Deployment.yaml
samples/hosting/kubernetes-simple/sample.md

NOTE This will fail to build until the docs engine server updates ([which included the inclusion of yaml files for snippets](https://github.com/Particular/DocsEngine/pull/982)) are published.

Added deployment file to kubernetes sample readme

---

Snippets/Core/Core_7/Sagas/SagaNotFoundHandler.cs
Snippets/Core/Core_8/Sagas/SagaNotFoundHandler.cs
Snippets/Core/Core_9/Sagas/SagaNotFoundHandler.cs
nservicebus/sagas/saga-not-found.md

Got this question on a support case and figured I'll include it in the documentation.

Document how to move saga not found cases into the error queue

---

transports/msmq/index.md

Add instruction on msmq install in windows 11

msmq install in windows11

---

samples/hosting/generic-multi-hosting/Core_8/Sample.MultiHosting/Program.cs

add the missing UseSerialization for instance 2

Add missing UseSerialization 

---

nservicebus/licensing/index_license-management_core_[7,8).partial.md
nservicebus/licensing/index_license-management_core_[8,].partial.md

Fixes https://github.com/Particular/docs.particular.net/issues/6387

Re-wrote the license location text to not mention environment variables

---

nservicebus/licensing/index_license-management_core_[7,8).partial.md
nservicebus/licensing/index_license-management_core_[8,].partial.md

This option is missing.
This came from https://github.com/Particular/docs.particular.net/pull/6388#discussion_r1444903759

Adding environment variable location instructions

---

nservicebus/compliance/business-continuity.md

Related to https://github.com/Particular/CustomerSuccess/issues/3792
I did not add this page to the menu system, I don't think we need it, but happy to change it if needed.

Adding business continuity page to docs

---

nservicebus/upgrades/supported-platforms_content_core_[7,8).partial.md
nservicebus/upgrades/supported-platforms_content_core_[8,9).partial.md
nservicebus/upgrades/supported-platforms_content_core_[9,10).partial.md

Fixes some formatting and adds an entry for .NET 8 to the NServiceBus 8 partial.

Update supported platforms

---

samples/transactional-session/aspnetcore-webapi/SqlPersistenceTS_6/WebApplication/MessageSessionFilter.cs
samples/transactional-session/aspnetcore-webapi/SqlPersistenceTS_6/WebApplication/RequiresTransactionalSessionAttribute.cs
samples/transactional-session/aspnetcore-webapi/SqlPersistenceTS_7/WebApplication/MessageSessionFilter.cs
samples/transactional-session/aspnetcore-webapi/SqlPersistenceTS_7/WebApplication/RequiresTransactionalSessionAttribute.cs

Correcting Transactional Session sample

---

samples/saga/migration/Core_8/Client/Client.csproj
samples/saga/migration/Core_8/Client/Program.cs
samples/saga/migration/Core_8/Server.New/DrainTempQueueSatelliteFeature.cs
samples/saga/migration/Core_8/Server.New/Program.cs
samples/saga/migration/Core_8/Server.New/Server.New.csproj
samples/saga/migration/Core_8/Server/NotFoundHandler.cs
samples/saga/migration/Core_8/Server/Program.cs
samples/saga/migration/Core_8/Server/Server.csproj
samples/saga/migration/Core_8/Shared/Shared.csproj
samples/saga/migration/sample.md

This is just fixing the sample so it works on v8

Update saga migration to work with NServiceBus 8

---

servicecontrol/transports.md

- Related to https://github.com/Particular/ServiceControl/issues/3958

Add support for Azure Service Bus entities partitioning

---

servicecontrol/upgrades/new-persistence.md

Storage engine identification improvement

---

transports/msmq/delayed-delivery_content_msmqtransport_[1.2,2.0).partial.md
transports/msmq/delayed-delivery_content_msmqtransport_[2.0,).partial.md

Add default value to the number of retries when trying to forward due delayed messages

Add default value to number of retries

---

nservicebus/upgrades/supported-platforms_content_core_[7,8).partial.md

We only support, supported version of .Net full

Update supported version

---

nservicebus/index.md
nservicebus/messaging/messages-events-commands.md
nservicebus/sagas/index.md
nservicebus/serialization/index.md

This PR is a first step towards improving the meta descriptions on our site

Update meta descriptions

---

tutorials/nservicebus-step-by-step/3-multiple-endpoints/tutorial.md

Address the feedback received in [issue ](https://github.com/Particular/docs.particular.net/issues/6346)

Add in note about using the  same serializer

---

servicecontrol/audit-instances/creating-config-file.md
servicecontrol/servicecontrol-instances/hardware.md

Feature added here https://github.com/Particular/ServiceControl/pull/4049
And released in 5.0.6

ServiceControl Audit - Document new setting for Bulk Insert Commit Timeout

---

architecture/aws/event-driven-architecture.md
architecture/azure/event-driven-architecture.md

This is the editorial review for event-driven architecture guidance in AWS.

Editorial review - Event driven

---

architecture/aws/compute.md
architecture/aws/data-stores.md
architecture/aws/event-driven-architecture.md
architecture/aws/index.md
architecture/aws/messaging.md
architecture/aws/microservices.md
architecture/aws/multi-tier-architecture.md
architecture/aws/observability.md
architecture/aws/queue-based-architecture.md
architecture/aws/well-architected.md

Summaries of articles in AWS architecture section

AWS summaries

---

nservicebus/sagas/timeouts.md

Fixed a typo and some grammar (using Grammarly)

Update Saga timeouts

---

monitoring/metrics/in-servicepulse.md

allow large images to be viewed in a popup modal

Update images in-servicepulse.md

---

Snippets/ASBFunctionsWorker/ASBFunctionsWorker_5/UpgradeGuides/4to5/Serializer.cs
menu/menu.yaml
nservicebus/hosting/azure-functions-service-bus/index.md
nservicebus/hosting/azure-functions-service-bus/index_package-requirements_ASBFunctionsWorker_[,4].partial.md
nservicebus/upgrades/azure-functions-service-bus-isolated-1to2.md
nservicebus/upgrades/azure-functions-service-bus-isolated-2to3.md
nservicebus/upgrades/azure-functions-service-bus-isolated-3to4.md
nservicebus/upgrades/azure-functions-service-bus-isolated-4to5.md

This adds an upgrade guide for 5.0 of the package and cleans up some of the other documentation.

Update Azure Functions Worker docs

---

servicecontrol/installation.md
servicecontrol/installation_prereqs_servicecontrol_[5,5.2).partial.md
servicecontrol/installation_prereqs_servicecontrol_[5,6).partial.md
servicecontrol/installation_removing_servicecontrol_[,5).partial.md
servicecontrol/installation_removing_servicecontrol_[5,).partial.md

Update ServiceControl installation page

---

nservicebus/sagas/message-correlation.md

_result of https://github.com/Particular/docs.particular.net/issues/6620_

Add a note about possible case sensitivity in the correlation property

---

nservicebus/hosting/cooperative-cancellation.md
nservicebus/hosting/cooperative-cancellation_content_core_[8,].partial.md
transports/azure-storage-queues/troubleshooting.md
transports/sql/entity-framework.md

_part of https://github.com/Particular/GeneralPlatformExperience/issues/3135_

Legacy docs review

---

Snippets/ABSDataBus/ABSDataBus_4/ABSDataBus_4.csproj
Snippets/ABSDataBus/ABSDataBus_4/Usage.cs
Snippets/ABSDataBus/ABSDataBus_5/ABSDataBus_5.csproj
Snippets/ABSDataBus/ABSDataBus_5/Usage.cs
Snippets/ABSDataBus/ABSDataBus_6/ABSDataBus_6.csproj
Snippets/ABSDataBus/ABSDataBus_6/Usage.cs
nservicebus/messaging/databus/azure-blob-storage_config_ABSDataBus_[4.0,5.0).partial.md
nservicebus/messaging/databus/azure-blob-storage_config_ABSDataBus_[5.0,).partial.md

I used the same title for the subsection as the Azure Service Bus documentation does.
https://docs.particular.net/transports/azure-service-bus/configuration#connectivity-token-credentials

Azure Blob Storage Databus Managed Identity documentation

---

nservicebus/release-notifications.md

relates to https://github.com/Particular/docs.particular.net/pull/6629

clarification of release notification instructions

---

architecture/azure/observability.md

To connect the dots better, this PR adds in the links to metrics , logs and tracing and observability samples.

link metrics to observability

---

nservicebus/operations/tuning.md

Added Parellism section to NServiceBus tuning guidance

---

transports/msmq/delayed-delivery_content_msmqtransport_[2.0,).partial.md

Based on previous version found via git blame.
Remaining:
- Merge `[1.2,2.0)` and `[2,)` pages and extract actual differences

Fix MSMQ delayed delivery "How it works" section

---

nservicebus/cancellation-and-catching-exceptions.md
nservicebus/endpoints/index.md
transports/msmq/delayed-delivery.md

Part of https://github.com/Particular/CustomerSuccess/issues/4120:
- https://docs.particular.net/nservicebus/cancellation-and-catching-exceptions
- https://docs.particular.net/nservicebus/endpoints/
- https://docs.particular.net/transports/msmq/delayed-delivery - wording addressed in https://github.com/Particular/docs.particular.net/pull/6679/

Documentation review

---

transports/upgrades/rabbitmq-7to8.md

Part of noncritical support issue.

Added change in behaviour regarding parallelism

---

persistence/cosmosdb/defaultcontainer.include.md

This PR improves the guidance on the Cosmos DB default container creation and customization

CosmosDB: Guidance on container (auto)creation

---

README.md

relates to https://github.com/Particular/docs.particular.net/pull/6594

editorial review of recent Lucid->Miro changes

---

nservicebus/outbox/index.md

Based on https://stackoverflow.com/q/78585080/199551

Recommend to enable outbox on all non-idempotent endpoints

---

nservicebus/recoverability/index.md
nservicebus/upgrades/7to8/index.md

- Resolve: https://github.com/Particular/docs.particular.net/issues/6693

Document logger name(s) used for recoverability log entries

---

samples/azure-service-bus-netstandard/send-receive-with-nservicebus/ASBS_4/Receiver/appsettings.json
samples/azure-service-bus-netstandard/send-receive-with-nservicebus/ASBS_4/Sender/appsettings.json
samples/azure-service-bus-netstandard/send-receive-with-nservicebus/sample.md

and needs to be replaced by the user

make it clear that the connection string is a placeholder

---

menu/menu.yaml

Address the issue: 
- https://github.com/Particular/docs.particular.net/issues/6585

move the platform pages to its own top level menu

---

servicepulse/install-servicepulse-in-iis.md

Work done as part of:
- https://github.com/Particular/ServicePulse/pull/1890

Remove base_url instructions

---

samples/wcf/Wcf_2/Wcf/Program.cs
samples/wcf/Wcf_3/Wcf/Program.cs
samples/wcf/sample.md

I tried to remove the word bridge and bridging too.

Review Wcf sample

---

menu/menu.yaml

Move the sub menu items of service platform to one level higher

move submenu item to top level

---

nservicebus/handlers/accessing-data.md

related to https://github.com/Particular/docs.particular.net/pull/6708

editorial tweaks to recent transaction sharing changes

---

transports/msmq/delayed-delivery_content_msmqtransport_[2.0,).partial.md
transports/upgrades/msmq-2to2.0.4.md

relates to https://github.com/Particular/docs.particular.net/pull/6697

editorial tweaks to recent MSMQ 2.0.4 changes

---

tutorials/quickstart/Solution/ClientUI/Views/Shared/_Layout.cshtml

This PR fixes a broken link in the tutorial

fix broken link

---

nservicebus/upgrades/supported-platforms.md

Part of https://github.com/Particular/GeneralPlatformExperience/issues/3056

Update supported platforms to list .net 9 preview

---

menu/menu.yaml
nservicebus/upgrades/9to9.1/index.md

NServiceBus Upgrade Version 9 to 9.1

---

nservicebus/logging/index.md
samples/azure-functions/service-bus-worker/sample.md

Part of https://github.com/Particular/CustomerSuccess/issues/4201

Docs reviews

---

samples/databus/blob-storage-databus-cleanup-function/ABSDataBus_6/SenderAndReceiver/MessageWithLargePayload.cs
samples/databus/blob-storage-databus-cleanup-function/ABSDataBus_6/SenderAndReceiver/MessageWithLargePayloadHandler.cs
samples/databus/blob-storage-databus-cleanup-function/ABSDataBus_6/SenderAndReceiver/Program.cs
samples/databus/blob-storage-databus/ABSDataBus_6/Receiver/MessageWithLargePayloadHandler.cs
samples/databus/blob-storage-databus/ABSDataBus_6/Receiver/Program.cs
samples/databus/blob-storage-databus/ABSDataBus_6/Sender/Program.cs
samples/databus/blob-storage-databus/ABSDataBus_6/Shared/MessageWithLargePayload.cs
samples/databus/custom-serializer/Core_9/Receiver/MessageWithLargePayloadHandler.cs
samples/databus/custom-serializer/Core_9/Receiver/Program.cs
samples/databus/custom-serializer/Core_9/Sender/Program.cs
samples/databus/custom-serializer/Core_9/Shared/BsonDataBusSerializer.cs
samples/databus/custom-serializer/Core_9/Shared/MessageWithLargePayload.cs
samples/databus/databus-custom-serializer-converter/Core_9/Receiver/MessageWithLargePayloadHandler.cs
samples/databus/databus-custom-serializer-converter/Core_9/Receiver/Program.cs
samples/databus/databus-custom-serializer-converter/Core_9/Sender/Program.cs
samples/databus/databus-custom-serializer-converter/Core_9/Shared/DatabusPropertyConverter.cs
samples/databus/databus-custom-serializer-converter/Core_9/Shared/DatabusPropertyConverterFactory.cs
samples/databus/databus-custom-serializer-converter/Core_9/Shared/MessageWithLargePayload.cs
samples/databus/file-share-databus/Core_9/Receiver/MessageWithLargePayloadHandler.cs
samples/databus/file-share-databus/Core_9/Receiver/Program.cs
samples/databus/file-share-databus/Core_9/Sender/Program.cs
samples/databus/file-share-databus/Core_9/Shared/MessageWithLargePayload.cs
samples/unobtrusive/Core_9/Client/Program.cs
samples/unobtrusive/Core_9/ConventionExtensions.cs
samples/unobtrusive/Core_9/Server/Program.cs

Suppresses the databus obsolete warnings

Suppress databus obsolete warnings

---

nservicebus/operations/transactions-message-processing.md

This documentation improvement was triggered by [this](https://particular-software.lightning.force.com/lightning/r/500P100000EOwFhIAL/view) support case.

Add limitations on Amazon RDS for MSSQL Server when enabling MSDTC

---

nservicebus/usage/index.md

Follow up to https://github.com/Particular/CustomerSuccess/issues/3601

Add note about SP being required in the future

---

samples/databus/blob-storage-databus-cleanup-function/ABSDataBus_6/DataBusBlobCleanupFunctions/DataBusBlobCleanupFunctions.csproj
samples/databus/blob-storage-databus-cleanup-function/ABSDataBus_6/SenderAndReceiver/SenderAndReceiver.csproj
samples/databus/blob-storage-databus/ABSDataBus_6/Receiver/Receiver.csproj
samples/databus/blob-storage-databus/ABSDataBus_6/Sender/Sender.csproj

This fix is temporary while we finish implementing NServiceBus.DataBus.AzureBlobStorage 6.1+.

Fix databus samples

---

nservicebus/handlers/index.md

- This PR attempts to improve the headings in the handler page based on the feedback issue- https://github.com/Particular/docs.particular.net/issues/5687

Handlers header improvement

---

servicecontrol/servicecontrol-instances/remotes.md

This addresses https://github.com/Particular/ServiceControl/issues/4380

Do not use single quotes in json

---

nservicebus/messaging/headers.md

related to https://github.com/Particular/docs.particular.net/pull/6711

editorial tweak to recent OTel edits

---

tests/IntegrityTests/IntegrityTests.csproj

This PR contains all changes related to NUnit4 upgrade including all required dependencies.
The following packages are checked for necessary upgrades but might not necessarily be in the change set if they are not present:
- NServiceBus
- NServiceBus.AcceptanceTesting
- NServiceBus.AcceptanceTests.Sources
- NServiceBus.TransportTests.Sources
- NUnit
In addition, some manual interventions are done when applicable.

Upgrading to NUnit4 including all required dependencies

---

Snippets/Core/Core_7/Core_7.csproj
Snippets/Core/Core_8.1/Core_8.1.csproj
Snippets/Core/Core_8/Core_8.csproj
Snippets/Core/Core_9.1/Core_9.1.csproj
Snippets/Core/Core_9/Core_9.csproj
Snippets/MsmqTransport/MsmqTransport_All/MsmqTransport_All.csproj
Snippets/PostgreSqlTransport/PostgreSqlTransport_8/PostgreSqlTransport_8.csproj
Snippets/Rabbit/Rabbit_All/Rabbit_All.csproj
Snippets/Raven/Raven_All/Raven_All.csproj
Snippets/SqlPersistence/SqlPersistence_4/SqlPersistence_4.csproj
Snippets/SqlPersistence/SqlPersistence_5/SqlPersistence_5.csproj
Snippets/SqlPersistence/SqlPersistence_6/SqlPersistence_6.csproj
Snippets/SqlPersistence/SqlPersistence_7/SqlPersistence_7.csproj
Snippets/SqlPersistence/SqlPersistence_8/SqlPersistence_8.csproj
Snippets/SqlPersistence/SqlPersistence_All/SqlPersistence_All.csproj
Snippets/SqlTransport/SqlTransport_6/SqlTransport_6.csproj
Snippets/SqlTransport/SqlTransport_7/SqlTransport_7.csproj
Snippets/SqlTransport/SqlTransport_8/SqlTransport_8.csproj
Snippets/SqlTransport/SqlTransport_All/SqlTransport_All.csproj
Snippets/Sqs/Sqs_All/Sqs_All.csproj
Snippets/Testing/Testing_7.4/Testing_7.4.csproj
Snippets/Testing/Testing_7/Testing_7.csproj
Snippets/Testing/Testing_8/Testing_8.csproj
Snippets/Testing/Testing_9/Testing_9.csproj

This PR updates all projects where NUnit was referenced using "3.*" to "4.*"

Upgrading to NUnit4 including all required dependencies - manual sweep

---

transports/azure-service-bus/configuration_subscription-rule-customization_asbs_[3.0,].partial.md

remove no longer relevant section

---

tutorials/nservicebus-sagas/1-saga-basics/Solution/Billing/Billing.csproj
tutorials/nservicebus-sagas/1-saga-basics/Solution/Billing/Program.cs
tutorials/nservicebus-sagas/1-saga-basics/Solution/ClientUI/ClientUI.csproj
tutorials/nservicebus-sagas/1-saga-basics/Solution/ClientUI/Program.cs
tutorials/nservicebus-sagas/1-saga-basics/Solution/Messages/Messages.csproj
tutorials/nservicebus-sagas/1-saga-basics/Solution/Sales/Program.cs
tutorials/nservicebus-sagas/1-saga-basics/Solution/Sales/Sales.csproj
tutorials/nservicebus-sagas/1-saga-basics/Solution/Shipping/Program.cs
tutorials/nservicebus-sagas/1-saga-basics/Solution/Shipping/Shipping.csproj
tutorials/nservicebus-sagas/2-timeouts/Solution/Billing/Billing.csproj
tutorials/nservicebus-sagas/2-timeouts/Solution/Billing/Program.cs
tutorials/nservicebus-sagas/2-timeouts/Solution/ClientUI/ClientUI.csproj
tutorials/nservicebus-sagas/2-timeouts/Solution/ClientUI/Program.cs
tutorials/nservicebus-sagas/2-timeouts/Solution/Messages/Messages.csproj
tutorials/nservicebus-sagas/2-timeouts/Solution/Sales/Program.cs
tutorials/nservicebus-sagas/2-timeouts/Solution/Sales/Sales.csproj
tutorials/nservicebus-sagas/2-timeouts/Solution/Shipping/Program.cs
tutorials/nservicebus-sagas/2-timeouts/Solution/Shipping/Shipping.csproj
tutorials/nservicebus-sagas/3-integration/Solution/Billing/Billing.csproj
tutorials/nservicebus-sagas/3-integration/Solution/Billing/Program.cs
tutorials/nservicebus-sagas/3-integration/Solution/ClientUI/ClientUI.csproj
tutorials/nservicebus-sagas/3-integration/Solution/ClientUI/Program.cs
tutorials/nservicebus-sagas/3-integration/Solution/Messages/Messages.csproj
tutorials/nservicebus-sagas/3-integration/Solution/Sales/Program.cs
tutorials/nservicebus-sagas/3-integration/Solution/Sales/Sales.csproj
tutorials/nservicebus-sagas/3-integration/Solution/Shipping/Integration/ShipWithAlpineHandler.cs
tutorials/nservicebus-sagas/3-integration/Solution/Shipping/Integration/ShipWithMapleHandler.cs
tutorials/nservicebus-sagas/3-integration/Solution/Shipping/Program.cs
tutorials/nservicebus-sagas/3-integration/Solution/Shipping/Shipping.csproj

Updated to NServiceBus v9 and dotnet 8. You need to configure a serializer for many of the program files.

Update Saga tutorials to NServiceBus v9 and dotnet 8

---

tutorials/message-replay/Solution/Billing/Billing.csproj
tutorials/message-replay/Solution/Billing/Program.cs
tutorials/message-replay/Solution/ClientUI/ClientUI.csproj
tutorials/message-replay/Solution/ClientUI/Program.cs
tutorials/message-replay/Solution/Messages/Messages.csproj
tutorials/message-replay/Solution/Sales/Program.cs
tutorials/message-replay/Solution/Sales/Sales.csproj
tutorials/message-replay/Solution/Shipping/Program.cs
tutorials/message-replay/Solution/Shipping/Shipping.csproj

Addressing issues in [this issue](https://github.com/Particular/DeveloperEducation/issues/4954)

Update Message Replay tutorial to use NServiceBus v9

---

transports/msmq/delayed-delivery_content_msmqtransport_[2.0,).partial.md

relates to https://github.com/Particular/docs.particular.net/pull/6744

editorial review of addition of SqlServer message store methods

---

menu/menu.yaml
nservicebus/throughput-tool/determine-transport.md
nservicebus/throughput-tool/index.md
nservicebus/throughput-tool/postgresql-transport.md

Part of https://github.com/Particular/Exploration/issues/1323

Add postgresql to throughput tool docs

---

tutorials/nservicebus-sagas/1-saga-basics/tutorial.md
tutorials/nservicebus-sagas/2-timeouts/tutorial.md
tutorials/nservicebus-sagas/3-integration/tutorial.md
tutorials/nservicebus-sagas/index.md

I started this PR as part of my onboarding and I decided that is better late than never to push this changes.

Improvements to the Saga tutorials

---

nservicebus/hosting/assembly-scanning.md
nservicebus/recoverability/subscribing-to-error-notifications.md
servicecontrol/import-failed-messages.md
transports/sql/design.md

_part of https://github.com/Particular/GeneralPlatformExperience/issues/3320_

Legacy Docs Review - 2024-10-21

---

tutorials/nservicebus-step-by-step/1-getting-started/Snippets/Core_9/Lesson1.cs

Updating [NServiceBus Step-by-step: Getting started ](https://docs.particular.net/tutorials/nservicebus-step-by-step/1-getting-started/) so that the line-by-line walkthrough better matches the code block

Make main method code block match the line by line description below

---

tutorials/nservicebus-step-by-step/1-getting-started/Snippets/Core_9/Lesson1.cs
tutorials/nservicebus-step-by-step/1-getting-started/tutorial.md

Updating tutorial: https://docs.particular.net/tutorials/nservicebus-step-by-step/1-getting-started/

Update getting started 1 to show entire main method

---

tutorials/nservicebus-step-by-step/3-multiple-endpoints/tutorial.md

In order to support the application builder methods, additional nuget packages are required.
https://docs.particular.net/tutorials/nservicebus-step-by-step/3-multiple-endpoints/

Update Step by Step NuGet imports

---

tutorials/nservicebus-step-by-step/1-getting-started/Snippets/Core_9/Lesson1.cs

Relates to https://github.com/Particular/docs.particular.net/issues/6889

Updating snippet to new transport API

---

tutorials/nservicebus-sagas/2-timeouts/tutorial.md

Minor grammar tweaks to the tutorial

Grammar fixes for Saga Timeouts tutorial

---

Snippets/Bridge/Bridge_4/API.cs

Add bridgeConfiguration variable to bridgeconfiguration region in snippet

Update Bridge docs snippets

---

transports/azure-service-bus/configuration.md

relates to https://github.com/Particular/docs.particular.net/pull/6918

editorial review of recent ASB prefetch and locking changes

---

README.md

Part of https://github.com/Particular/StrategyCapability/issues/527

Add consideration for the next steps

---

Snippets/Callbacks/Callbacks_3/Callbacks_3.csproj
Snippets/Gateway/Gateway_3.1/Gateway_3.1.csproj
Snippets/Gateway/Gateway_3.2/Gateway_3.2.csproj
Snippets/MsmqTransport/MsmqTransport_1.2/MsmqTransport_1.2.csproj
Snippets/MsmqTransport/MsmqTransport_1/MsmqTransport_1.csproj
Snippets/MsmqTransport/MsmqTransport_2/MsmqTransport_2.csproj
Snippets/Newtonsoft/Newtonsoft_2.4/Newtonsoft_2.4.csproj
Snippets/Newtonsoft/Newtonsoft_2/Newtonsoft_2.csproj
Snippets/NonDurablePersistence/Core_7.2/Core_7.2.csproj
Snippets/PerfCounters/PerfCounters_3/PerfCounters_3.csproj
Snippets/PerfCounters/PerfCounters_4/PerfCounters_4.csproj
Snippets/PlatformConnector/PlatformConnector_1/PlatformConnector_1.csproj
Snippets/Raven/Raven_6.1/Raven_6.1.csproj
Snippets/Raven/Raven_6.3/Raven_6.3.csproj
Snippets/Raven/Raven_6.4/Raven_6.4.csproj
Snippets/Raven/Raven_6.5/Raven_6.5.csproj
Snippets/Raven/Raven_6/Raven_6.csproj
Snippets/TransactionalSession.DynamoDB/DynamoTS_1/DynamoTS_1.csproj
samples/aws/dynamodb-simple/DynamoDB_1/Server/Server.csproj
samples/scheduling/periodictimer/Core_9/Receiver/Receiver.csproj
samples/scheduling/periodictimer/Core_9/Scheduler/Scheduler.csproj
samples/showcase/cinema/Core_8/Cinema.Headquarters/Cinema.Headquarters.csproj
samples/showcase/cinema/Core_8/Cinema.Messages/Cinema.Messages.csproj
samples/showcase/cinema/Core_8/Cinema.TicketSales/Cinema.TicketSales.csproj
tutorials/quickstart/Solution/Billing/Billing.csproj
tutorials/quickstart/Solution/ClientUI/ClientUI.csproj
tutorials/quickstart/Solution/Messages/Messages.csproj
tutorials/quickstart/Solution/Sales/Sales.csproj

Add wildcard to NSB refs in samples, tutorials and snippets

Add wildcard to NSB refs in samples, tutorials and snippets

---

Snippets/TransactionalSession/TransactionalSession.sln
Snippets/TransactionalSession/TransactionalSession_3.1/Api.cs
Snippets/TransactionalSession/TransactionalSession_3.1/MyPersistenceOpenSessionOptions.cs
Snippets/TransactionalSession/TransactionalSession_3.1/TransactionalSession_3.1.csproj
Snippets/TransactionalSession/TransactionalSession_3/Api.cs

The creation of a new partial here https://github.com/Particular/docs.particular.net/pull/6964 led to the website generating an extra version of the page which does not have this snippet.

Fix transactional session snippets

---

nservicebus/licensing/index_license-management_core_[7,8).partial.md
nservicebus/licensing/index_license-management_core_[8,].partial.md
servicecontrol/license.md

Addresses https://github.com/Particular/PlatformBugs/issues/1031

Add a note about required permissions for user specific license location

---

nservicebus/dotnet-templates/index_nsbendpoint_templates_[6,).partial.md

New default for ParticularTemplates (net9)
Part of 
- https://github.com/Particular/ParticularTemplates/pull/545

Updating ParticulartTemplates documentation with new framework default

---

persistence/nhibernate/outbox.md
persistence/nhibernate/outbox_modes_nhibernate_[8.4,).partial.md
samples/index.md
samples/pipeline/index.md
samples/serializers/index.md

Part of https://github.com/Particular/GeneralPlatformExperience/issues/3425

Updates from docs review

---

nservicebus/upgrades/supported-platforms.md

Update the [supported frameworks and platforms](https://docs.particular.net/nservicebus/upgrades/supported-platforms) article in docs for .Net9

 Update the  .Net 9 support period

---

nservicebus/hosting/azure-functions-service-bus/in-process/index.md
nservicebus/hosting/azure-functions-service-bus/index.md
servicecontrol/queues.md
transports/azure-service-bus/operational-scripting.md
transports/azure-service-bus/operational-scripting_endpoint-command_asbs_[5,).partial.md
transports/azure-service-bus/operational-scripting_examples_asbs_[,5).partial.md
transports/azure-service-bus/operational-scripting_examples_asbs_[5,).partial.md
transports/azure-service-bus/operational-scripting_migration-endpoint-command_asbs_[5,).partial.md

By introducing another set of partials

Improve structure of the ASB command-line tool docs

---

tutorials/quickstart/tutorial.md

Leaving in the text on Line 20:
https://github.com/Particular/docs.particular.net/pull/7005/files#diff-f37cf4ecc1ff27521bde4e3de9ed58f55270f5cf4b45706c0453d29bde5eb0f1R20

Remove duplicate text from quickstart opening

---

transports/azure-service-bus/topology_description_asbs_[5,).partial.md

please check that I haven't changed any intended meaning with my changes

editorial review

---

Snippets/ASBS/ASBS_5/ASBS_5.csproj
Snippets/ASBS/ASBS_5/Options.cs
Snippets/ASBS/ASBS_5/Usage.cs
Snippets/ASBS/ASBS_5/migration-options.json
Snippets/ASBS/ASBS_5/topology-options-inheritance.json
Snippets/ASBS/ASBS_5/topology-options.json
samples/azure-service-bus-netstandard/options/ASBS_5/Publisher/Program.cs
samples/azure-service-bus-netstandard/options/ASBS_5/Subscriber/Program.cs
transports/azure-service-bus/configuration_entity-topology_asbs_[5,).partial.md
transports/upgrades/asbs-4to5.md

Adds documentation on advanced configuration options of the topic-per-event topology

Azure Service Bus Configuration Documentation 

---

nservicebus/logging/common-logging.md

Should this be deleted entirely or just left with the notes at the top?

Review common.logging

---

README.md

Removed net6.0 as it is not supported anymore

Removed net6.0 from the target frameworks

---

servicecontrol/servicecontrol-instances/hardware.md

This PR updates the hardware considerations documentation for ServiceControl to include containers as options for hosting in the cloud, with some [caveats](https://github.com/Particular/ServiceControl/issues/3340#issuecomment-2313694640).

Document cloud container compatibility for ServiceControl

---

nservicebus/gateway/troubleshooting.md
security-advisories/index.md
transports/azure-service-bus/configuration.md
transports/sql/sql-statements.md

review legacy docs

---

samples/hosting/aspire/Core_9/AspireDemo.AppHost/AspireDemo.AppHost.csproj
samples/hosting/aspire/Core_9/AspireDemo.AppHost/Program.cs
samples/hosting/aspire/Core_9/Billing/Billing.csproj
samples/hosting/aspire/Core_9/Billing/OrderPlacedHandler.cs
samples/hosting/aspire/Core_9/Billing/Program.cs
samples/hosting/aspire/Core_9/ClientUI/ClientUI.csproj
samples/hosting/aspire/Core_9/ClientUI/MessageSenderService.cs
samples/hosting/aspire/Core_9/ClientUI/Program.cs
samples/hosting/aspire/Core_9/Messages/Messages.csproj
samples/hosting/aspire/Core_9/Messages/OrderBilled.cs
samples/hosting/aspire/Core_9/Messages/OrderPlaced.cs
samples/hosting/aspire/Core_9/Messages/PlaceOrder.cs
samples/hosting/aspire/Core_9/Messages/ShipOrder.cs
samples/hosting/aspire/Core_9/Sales/PlaceOrderHandler.cs
samples/hosting/aspire/Core_9/Sales/Program.cs
samples/hosting/aspire/Core_9/Sales/Sales.csproj
samples/hosting/aspire/Core_9/Shipping/Program.cs
samples/hosting/aspire/Core_9/Shipping/ShipOrderHandler.cs
samples/hosting/aspire/Core_9/Shipping/Shipping.csproj
samples/hosting/aspire/Core_9/Shipping/ShippingPolicy.cs
samples/hosting/aspire/Core_9/Shipping/ShippingPolicyData.cs
samples/hosting/aspire/sample.md

This PR adds ServicePulse and ServiceControl error, audit, and monitoring instances the Aspire AppHost and wires up everything to communicate properly.
It also updates to NServiceBus.RabbitMQ 10.x and aligns the code to more modern language features.

Aspire sample updates

---

Snippets/SqlPersistence/SqlPersistence_4/Usage.cs
Snippets/SqlPersistence/SqlPersistence_5/Usage.cs
Snippets/SqlPersistence/SqlPersistence_6/Usage.cs
Snippets/SqlPersistence/SqlPersistence_7/Usage.cs
Snippets/SqlPersistence/SqlPersistence_8/Usage.cs

Updated the Postgres usage example to use NpgsqlDataSource:
https://www.npgsql.org/doc/basic-usage.html

Updated the Postgres usage example to use NpgsqlDataSource

---

tutorials/quickstart/Snippets/Core_9/OrderPlacedHandler.cs
tutorials/quickstart/Snippets/Core_9/ShippingProgram.cs

The current code makes for unsightly line breaks:
This change mitigates that.

Change the code to prevent unsightly line breaks

---

tutorials/quickstart/Snippets/Core_9/Core_9.csproj
tutorials/quickstart/Snippets/Core_9/OrderPlacedHandler.cs
tutorials/quickstart/Snippets/Core_9/ShippingProgram.cs
tutorials/quickstart/Solution/Billing/OrderPlacedHandler.cs
tutorials/quickstart/Solution/Billing/Program.cs
tutorials/quickstart/Solution/ClientUI/Controllers/HomeController.cs
tutorials/quickstart/Solution/ClientUI/Program.cs
tutorials/quickstart/Solution/Sales/Program.cs

Updated quick start tutorial code to use top-level statements, primary constructors, file-scoped namespaces

Update quick start tutorials to use modern C# features

---

tutorials/nservicebus-step-by-step/1-getting-started/Snippets/Core_9/Lesson1.cs
tutorials/nservicebus-step-by-step/1-getting-started/Solution/ClientUI/Program.cs
tutorials/nservicebus-step-by-step/2-sending-a-command/Snippets/Core_9/Exercise.cs
tutorials/nservicebus-step-by-step/2-sending-a-command/Snippets/Core_9/MultiHandler.cs
tutorials/nservicebus-step-by-step/2-sending-a-command/Snippets/Core_9/PlaceOrderHandler.cs
tutorials/nservicebus-step-by-step/2-sending-a-command/Solution/ClientUI/Program.cs
tutorials/nservicebus-step-by-step/3-multiple-endpoints/Snippets/Core_9/Lesson3.cs
tutorials/nservicebus-step-by-step/3-multiple-endpoints/Solution/ClientUI/Program.cs
tutorials/nservicebus-step-by-step/3-multiple-endpoints/Solution/Sales/Program.cs
tutorials/nservicebus-step-by-step/4-publishing-events/Solution/Billing/Program.cs
tutorials/nservicebus-step-by-step/4-publishing-events/Solution/ClientUI/Program.cs
tutorials/nservicebus-step-by-step/4-publishing-events/Solution/Sales/Program.cs
tutorials/nservicebus-step-by-step/4-publishing-events/Solution/Shipping/Program.cs
tutorials/nservicebus-step-by-step/5-retrying-errors/Solution/Billing/Program.cs
tutorials/nservicebus-step-by-step/5-retrying-errors/Solution/ClientUI/Program.cs
tutorials/nservicebus-step-by-step/5-retrying-errors/Solution/Sales/Program.cs
tutorials/nservicebus-step-by-step/5-retrying-errors/Solution/Shipping/Program.cs

Update step-by-step tutorials to align with modern C# features in quick start tutorial

Update step-by-step tutorials to use modern C# features

---

transports/sqs/configuration-options.md
transports/sqs/configuration-options_visibility-timeout_sqs_[,7.3).partial.md
transports/sqs/configuration-options_visibility-timeout_sqs_[7.3,).partial.md
transports/upgrades/amazonsqs-7.2to7.3.md

Depends on https://github.com/Particular/NServiceBus.AmazonSQS/pull/2773

[SQS] Sqs visibility timeout documentation

---

transports/sqs/configuration-options.md

- depends on https://github.com/Particular/NServiceBus.AmazonSQS/pull/2776

[SQS] S3 Payload signing documentation

---

tutorials/nservicebus-step-by-step/2-sending-a-command/tutorial.md

Updating signature and description of SendLocal function to match the code snippet

Updating signature and description of SendLocal

---

tutorials/nservicebus-step-by-step/3-multiple-endpoints/tutorial.md

Updating description of SendLocal function to match the API

Updating description of SendLocal function

---

transports/rabbitmq/operations-scripting_content_rabbit_[10,).partial.md

New options have been added in 10.1.1 and 10.0.2.

Add new options to RabbitMQ commands

---

servicecontrol/audit-instances/index.md

This was changed in 
- https://github.com/Particular/ServiceControl/issues/2945

Update the default audit retention period to 7d 

---

persistence/upgrades/mongodb-4to5.md

editor review of @danielmarbach's [change](https://github.com/Particular/docs.particular.net/pull/7163/files)

mongodb-4to5 editor review

---

samples/hosting/aspire/sample.md

Append the note about the containers running on predefined ports

Append the note about the containers running on predefined ports

---

nservicebus/transactional-session/index.md
nservicebus/transactional-session/index_remote-processor_transactionalsession_[3.3,).partial.md

Document benefits of using a dedicated transactional session processor endpoint

---

samples/custom-recoverability/sample.md

Reviewed customer recoverability sample

Customer recoverability sample review

---

samples/bridge/azure-service-bus-msmq-bridge/sample.md

Reviewed azure servicebus msmq bridge sample

Azure servicebus msmq bridge sample review

---

servicecontrol/troubleshooting.md

Added a link to maintenance mode

Add link to the maintenance mode in the ServiceControl troubleshooting guidance

---

tutorials/quickstart/tutorial-extending-the-system.md

- Fix for https://github.com/Particular/docs.particular.net/issues/7222
Updated logger.Info(...) to logger.LogInformation(...) to enable structured logging with correct parameter binding.

Quickstart tutorial extending the system

---

nservicebus/bridge/performance.md
nservicebus/security/body-encryption.md
nservicebus/serialization/index.md
nservicebus/serialization/newtonsoft.md

weekly legacy review

---

servicepulse/host-config.md

Add section header for configuring ServicePulse via query string parameters

Add section for ServicePulse query strings

---

modernization/migrate-to-the-cloud/on-premises-to-azure.md

a basic page to migrate  on-premises systems into the cloud

azure migration

---

servicepulse/usage.md

Using same term as in 
- https://github.com/Particular/docs.particular.net/pull/7232

Update reference to control message to the right term "dispatch message"

---

samples/showcase/cinema/Core_8/Cinema.Headquarters/FeaturedFilmSaga.cs
samples/showcase/cinema/Core_8/Cinema.TicketSales/FeaturedFilmChangedHandler.cs
samples/showcase/cinema/Core_9/Cinema.Headquarters/FeaturedFilmSaga.cs
samples/showcase/cinema/Core_9/Cinema.TicketSales/FeaturedFilmChangedHandler.cs
samples/showcase/on-premises/Core_9/Store.ContentManagement/OrderAcceptedHandler.cs
samples/showcase/on-premises/Core_9/Store.ContentManagement/ProvisionDownloadResponseHandler.cs
samples/showcase/on-premises/Core_9/Store.CustomerRelations/OrderAcceptedHandler.cs
samples/showcase/on-premises/Core_9/Store.CustomerRelations/SendLimitedTimeOffer.cs
samples/showcase/on-premises/Core_9/Store.CustomerRelations/SendWelcomePacket.cs
samples/showcase/on-premises/Core_9/Store.Operations/ProvisionDownloadHandler.cs
samples/showcase/on-premises/Core_9/Store.Sales/ProcessOrderSaga.cs
samples/showcase/on-premises/Core_9/Store.Sales/SubmitOrderHandler.cs
samples/sqltransport-nhpersistence/Core_9/Receiver/OrderSubmittedHandler.cs
samples/sqltransport-nhpersistence/Core_9/Sender/OrderAcceptedHandler.cs
samples/sqltransport-sqlpersistence/Core_9/Receiver/Dapper/OrderSubmittedHandler.cs
samples/sqltransport-sqlpersistence/Core_9/Receiver/EntityFramework/OrderSubmittedHandler.cs
samples/sqltransport-sqlpersistence/Core_9/Receiver/OrmLite/OrderSubmittedHandler.cs
samples/sqltransport-sqlpersistence/Core_9/Receiver/Raw/OrderSubmittedHandler.cs
samples/sqltransport-sqlpersistence/Core_9/Sender/OrderAcceptedHandler.cs
samples/sqltransport/native-integration/SqlTransport_8/Receiver/LegacyOrderDetectedHandler.cs
samples/sqltransport/native-integration/SqlTransport_8/Receiver/PlaceOrderHandler.cs

Part of
https://github.com/Particular/GeneralPlatformExperience/issues/3482
Updated all logger.LogInformation and similar calls in the samples to use structured logging message templates and named parameters.
No functional changes

Refactor logger calls in showcase to sqltransport samples to use structured logging

---

samples/faulttolerance/Core_9/Server/MyHandler.cs
samples/fullduplex/Core_9/Client/DataResponseMessageHandler.cs
samples/fullduplex/Core_9/Server/RequestDataMessageHandler.cs
samples/gateway/Gateway_5/Headquarters/AcknowledgedHandler.cs
samples/gateway/Gateway_5/RemoteSite/PriceUpdatedHandler.cs
samples/header-manipulation/Core_9/Sample/MyHandler.cs
samples/immutable-messages/Core_9/Receiver/MyMessageAsClassHandler.cs
samples/immutable-messages/Core_9/Receiver/MyMessageAsInterfaceHandler.cs
samples/messagemutators/Core_9/Sample/Handler.cs
samples/messagemutators/Core_9/Sample/TransportMessageCompressionMutator.cs
samples/messagemutators/Core_9/Sample/ValidationMessageMutator.cs
samples/mongodb/simple/MongoDB_4/Client/OrderCompletedHandler.cs
samples/mongodb/simple/MongoDB_4/Server/OrderSaga.cs
samples/mongodb/simple/MongoDB_5/Client/OrderCompletedHandler.cs
samples/mongodb/simple/MongoDB_5/Server/OrderSaga.cs
samples/performance-counters/PerfCounters_6/Sample/MyHandler.cs
samples/postgresqltransport/simple/PostgreSqlTransport_8/Receiver/MyCommandHandler.cs
samples/postgresqltransport/simple/PostgreSqlTransport_8/Receiver/MyEventHandler.cs
samples/pubsub/native/Core_9/Subscriber/OrderReceivedHandler.cs
samples/ravendb/simple/Raven_9/Client/OrderCompletedHandler.cs
samples/ravendb/simple/Raven_9/Server/OrderSaga.cs
samples/routing/command-routing/Core_9/Receiver/CancelOrderHandler.cs
samples/routing/command-routing/Core_9/Receiver/PlaceOrderHandler.cs
samples/saga/nh-custom-sagafinder/NHibernate_10/Sample/OrderSaga.cs
samples/saga/simple/Core_9/Sample/OrderSaga.cs
samples/saga/sql-sagafinder/SqlPersistence_8/Shared/OrderSaga.cs

Part of
https://github.com/Particular/GeneralPlatformExperience/issues/3482
Updated all logger.LogInformation and similar calls in the samples to use structured logging message templates and named parameters.
No functional changes

Refactor logger calls in feature to saga samples to use structured logging

---

samples/outbox/rabbit/Core_10/RabbitOutbox.sln
samples/outbox/rabbit/Core_10/Sample/Helper.cs
samples/outbox/rabbit/Core_10/Sample/MyHandler.cs
samples/outbox/rabbit/Core_10/Sample/MyMessage.cs
samples/outbox/rabbit/Core_10/Sample/Program.cs
samples/outbox/rabbit/Core_10/Sample/Sample.csproj
samples/outbox/rabbit/Core_10/docker-compose.yml

NServiceBus 10 Outbox/RabbitMQ sample

---

samples/scheduling/periodictimer/Core_10/PeriodicTimerScheduler.sln
samples/scheduling/periodictimer/Core_10/Receiver/MyMessageHandler.cs
samples/scheduling/periodictimer/Core_10/Receiver/Program.cs
samples/scheduling/periodictimer/Core_10/Receiver/Receiver.csproj
samples/scheduling/periodictimer/Core_10/Scheduler/Program.cs
samples/scheduling/periodictimer/Core_10/Scheduler/Scheduler.csproj
samples/scheduling/periodictimer/Core_10/Scheduler/SendMessageJob.cs
samples/scheduling/periodictimer/Core_10/Shared/MyMessage.cs
samples/scheduling/periodictimer/Core_10/Shared/Shared.csproj

Resolves https://github.com/Particular/docs.particular.net/issues/7384

Add v10 version of PeriodicTimer sample

---

samples/scheduling/timer/Core_10/Sample/MyHandler.cs
samples/scheduling/timer/Core_10/Sample/MyMessage.cs
samples/scheduling/timer/Core_10/Sample/MyScheduledTask.cs
samples/scheduling/timer/Core_10/Sample/MyScheduledTaskHandler.cs
samples/scheduling/timer/Core_10/Sample/Program.cs
samples/scheduling/timer/Core_10/Sample/Sample.csproj
samples/scheduling/timer/Core_10/Sample/TimerService.cs
samples/scheduling/timer/Core_10/Timer.sln
samples/scheduling/timer/sample.md

Resolves https://github.com/Particular/docs.particular.net/issues/7386

Samples v10 upgrade timer

---

samples/showcase/cinema/Core_10/Cinema.Headquarters/Cinema.Headquarters.csproj
samples/showcase/cinema/Core_10/Cinema.Headquarters/FeaturedFilmSaga.cs
samples/showcase/cinema/Core_10/Cinema.Headquarters/Program.cs
samples/showcase/cinema/Core_10/Cinema.Headquarters/Properties/launchSettings.json
samples/showcase/cinema/Core_10/Cinema.Messages/Cinema.Messages.csproj
samples/showcase/cinema/Core_10/Cinema.Messages/FeaturedFilmChanged.cs
samples/showcase/cinema/Core_10/Cinema.Messages/RecordTicketSale.cs
samples/showcase/cinema/Core_10/Cinema.TicketSales/Cinema.TicketSales.csproj
samples/showcase/cinema/Core_10/Cinema.TicketSales/FeaturedFilmChangedHandler.cs
samples/showcase/cinema/Core_10/Cinema.TicketSales/Program.cs
samples/showcase/cinema/Core_10/Cinema.TicketSales/Properties/launchSettings.json
samples/showcase/cinema/Core_10/CinemaShowcase.sln
samples/showcase/cinema/sample.md

Resolves https://github.com/Particular/docs.particular.net/issues/7400

Add V10 version of the cinema showcase sample

---

samples/scheduling/quartz/Core_10/QuartzScheduler.sln
samples/scheduling/quartz/Core_10/Receiver/MyHandler.cs
samples/scheduling/quartz/Core_10/Receiver/Program.cs
samples/scheduling/quartz/Core_10/Receiver/Receiver.csproj
samples/scheduling/quartz/Core_10/Scheduler/Program.cs
samples/scheduling/quartz/Core_10/Scheduler/QuartzConsoleLogProvider.cs
samples/scheduling/quartz/Core_10/Scheduler/QuartzContextExtensions.cs
samples/scheduling/quartz/Core_10/Scheduler/Scheduler.csproj
samples/scheduling/quartz/Core_10/Scheduler/SendMessageJob.cs
samples/scheduling/quartz/Core_10/Shared/MyMessage.cs
samples/scheduling/quartz/Core_10/Shared/Shared.csproj
samples/scheduling/quartz/sample.md

Resolves https://github.com/Particular/docs.particular.net/issues/7385

V10 version of Quartz sample

---

samples/servicecontrol/retry-messages/Core_10/PlatformLauncher/PlatformLauncher.csproj
samples/servicecontrol/retry-messages/Core_10/PlatformLauncher/Program.cs
samples/servicecontrol/retry-messages/Core_10/Receiver/Program.cs
samples/servicecontrol/retry-messages/Core_10/Receiver/Receiver.csproj
samples/servicecontrol/retry-messages/Core_10/Receiver/SimpleMessageHandler.cs
samples/servicecontrol/retry-messages/Core_10/Receiver/Toggle.cs
samples/servicecontrol/retry-messages/Core_10/RetryFailedMessages.sln
samples/servicecontrol/retry-messages/Core_10/Sender/Program.cs
samples/servicecontrol/retry-messages/Core_10/Sender/Sender.csproj
samples/servicecontrol/retry-messages/Core_10/Sender/SenderWorker.cs
samples/servicecontrol/retry-messages/Core_10/Shared/ConsoleHelper.cs
samples/servicecontrol/retry-messages/Core_10/Shared/Shared.csproj
samples/servicecontrol/retry-messages/Core_10/Shared/SimpleMessage.cs
samples/servicecontrol/retry-messages/sample.md

fixes: https://github.com/Particular/docs.particular.net/issues/7398

Retry messages sample update

---

samples/servicecontrol/monitoring3rdparty/CustomChecks_5/Sample/Program.cs
samples/servicecontrol/monitoring3rdparty/CustomChecks_6/3rdPartySystem/3rdPartySystem.csproj
samples/servicecontrol/monitoring3rdparty/CustomChecks_6/3rdPartySystem/Program.cs
samples/servicecontrol/monitoring3rdparty/CustomChecks_6/Monitoring3rdParty.sln
samples/servicecontrol/monitoring3rdparty/CustomChecks_6/PlatformLauncher/PlatformLauncher.csproj
samples/servicecontrol/monitoring3rdparty/CustomChecks_6/PlatformLauncher/Program.cs
samples/servicecontrol/monitoring3rdparty/CustomChecks_6/Sample/Monitor.cs
samples/servicecontrol/monitoring3rdparty/CustomChecks_6/Sample/Program.cs
samples/servicecontrol/monitoring3rdparty/CustomChecks_6/Sample/Sample.csproj

fixes: https://github.com/Particular/docs.particular.net/issues/7397

Sample monitoring3rparty update

---

samples/servicecontrol/fix-messages/Core_10/FixMalformedMessages.sln
samples/servicecontrol/fix-messages/Core_10/MessageRepairingEndpoint/MessageRepairingEndpoint.csproj
samples/servicecontrol/fix-messages/Core_10/MessageRepairingEndpoint/Program.cs
samples/servicecontrol/fix-messages/Core_10/MessageRepairingEndpoint/SimpleMessageHandler.cs
samples/servicecontrol/fix-messages/Core_10/PlatformLauncher/PlatformLauncher.csproj
samples/servicecontrol/fix-messages/Core_10/PlatformLauncher/Program.cs
samples/servicecontrol/fix-messages/Core_10/Receiver/Program.cs
samples/servicecontrol/fix-messages/Core_10/Receiver/Receiver.csproj
samples/servicecontrol/fix-messages/Core_10/Receiver/SimpleMessageHandler.cs
samples/servicecontrol/fix-messages/Core_10/Sender/Program.cs
samples/servicecontrol/fix-messages/Core_10/Sender/Sender.csproj
samples/servicecontrol/fix-messages/Core_10/Shared/Shared.csproj
samples/servicecontrol/fix-messages/Core_10/Shared/SimpleMessage.cs
samples/servicecontrol/fix-messages/Core_9/MessageRepairingEndpoint/Program.cs
samples/servicecontrol/fix-messages/Core_9/Receiver/Program.cs

fixes: https://github.com/Particular/docs.particular.net/issues/7396

Fix messages sample update

---

samples/pipeline/masstransit-messages/Core_10/ConsumingMassTransitMessages.sln
samples/pipeline/masstransit-messages/Core_10/MTEndpoint/MTEndpoint.csproj
samples/pipeline/masstransit-messages/Core_10/MTEndpoint/MessageConsumer.cs
samples/pipeline/masstransit-messages/Core_10/MTEndpoint/Program.cs
samples/pipeline/masstransit-messages/Core_10/MTEndpoint/Worker.cs
samples/pipeline/masstransit-messages/Core_10/Messages/Events/MassTransitEvent.cs
samples/pipeline/masstransit-messages/Core_10/Messages/Messages.csproj
samples/pipeline/masstransit-messages/Core_10/NServiceBusSubscriber/MassTransitEventHandler.cs
samples/pipeline/masstransit-messages/Core_10/NServiceBusSubscriber/MassTransitIngestBehavior.cs
samples/pipeline/masstransit-messages/Core_10/NServiceBusSubscriber/NServiceBusSubscriber.csproj
samples/pipeline/masstransit-messages/Core_10/NServiceBusSubscriber/Program.cs
samples/pipeline/masstransit-messages/Core_9/MTEndpoint/MTEndpoint.csproj
samples/pipeline/masstransit-messages/Core_9/MTEndpoint/Program.cs

fixes #7359 
Note that MT has been upgraded to v8, and since it now supports System.Text.Json (which is now the default option), the behaviour JSON parsing has changed significantly.

update sample to NSB 10: masstransit messages

---

samples/pipeline/header-propagation/Core_10/HeaderPropagation.sln
samples/pipeline/header-propagation/Core_10/Messages/Messages.csproj
samples/pipeline/header-propagation/Core_10/Messages/ProcessOrder.cs
samples/pipeline/header-propagation/Core_10/Messages/ShipOrder.cs
samples/pipeline/header-propagation/Core_10/Receiver/MyMessageHandler.cs
samples/pipeline/header-propagation/Core_10/Receiver/Program.cs
samples/pipeline/header-propagation/Core_10/Receiver/PropagateCustomerIdHeaderBehavior.cs
samples/pipeline/header-propagation/Core_10/Receiver/Receiver.csproj
samples/pipeline/header-propagation/Core_10/Sender/Program.cs
samples/pipeline/header-propagation/Core_10/Sender/Sender.csproj

update header propogation sample for NSB 10

---

samples/multi-tenant/propagation/Core_10/Billing/Billing.csproj
samples/multi-tenant/propagation/Core_10/Billing/OrderAcceptedHandler.cs
samples/multi-tenant/propagation/Core_10/Billing/Program.cs
samples/multi-tenant/propagation/Core_10/Client/Client.csproj
samples/multi-tenant/propagation/Core_10/Client/Program.cs
samples/multi-tenant/propagation/Core_10/Sales/PlaceOrderHandler.cs
samples/multi-tenant/propagation/Core_10/Sales/Program.cs
samples/multi-tenant/propagation/Core_10/Sales/Sales.csproj
samples/multi-tenant/propagation/Core_10/Shared/OrderAccepted.cs
samples/multi-tenant/propagation/Core_10/Shared/PlaceOrder.cs
samples/multi-tenant/propagation/Core_10/Shared/PropagateTenantIdBehavior.cs
samples/multi-tenant/propagation/Core_10/Shared/Shared.csproj
samples/multi-tenant/propagation/Core_10/Shared/StoreTenantIdBehavior.cs
samples/multi-tenant/propagation/Core_10/TenantIdPropagation.sln
samples/multi-tenant/propagation/Core_9/Billing/Program.cs
samples/multi-tenant/propagation/Core_9/Client/Program.cs
samples/multi-tenant/propagation/Core_9/Sales/Program.cs

Fixes https://github.com/Particular/docs.particular.net/issues/7337. This pull request includes updates for the [Propagating Tenant Information to Downstream Endpoints](https://docs.particular.net/samples/multi-tenant/propagation/) samples.
- **Core_9 Sample:**: Removed the unnecessary prompt.
- **Core_10 Sample**: Created the new sample for .NET 10.

Updates for Sample: multi-tenant/propagation

---

samples/pipeline/fix-messages-using-behavior/Core_10/FixMalformedMessagesUsingBehavior.sln
samples/pipeline/fix-messages-using-behavior/Core_10/PlatformLauncher/PlatformLauncher.csproj
samples/pipeline/fix-messages-using-behavior/Core_10/PlatformLauncher/Program.cs
samples/pipeline/fix-messages-using-behavior/Core_10/Receiver/FixMessageIdBehavior.cs
samples/pipeline/fix-messages-using-behavior/Core_10/Receiver/Program.cs
samples/pipeline/fix-messages-using-behavior/Core_10/Receiver/Receiver.csproj
samples/pipeline/fix-messages-using-behavior/Core_10/Receiver/SimpleMessageHandler.cs
samples/pipeline/fix-messages-using-behavior/Core_10/Sender/Program.cs
samples/pipeline/fix-messages-using-behavior/Core_10/Sender/Sender.csproj
samples/pipeline/fix-messages-using-behavior/Core_10/Shared/Shared.csproj
samples/pipeline/fix-messages-using-behavior/Core_10/Shared/SimpleMessage.cs

update sample to nsb10: fix malformed messages

---

samples/multi-tenant/nhibernate/NHibernate_11/Sender/Program.cs

Fixes https://github.com/Particular/docs.particular.net/issues/7336. This is for consistency with other multi-tenant samples.

Clean-up NHibernate_11 Sample

---

samples/sql-persistence/saga-rename/SqlPersistence_9/EndpointVersion1/EndpointVersion1.csproj
samples/sql-persistence/saga-rename/SqlPersistence_9/EndpointVersion1/MyReplySagaVersion1.cs
samples/sql-persistence/saga-rename/SqlPersistence_9/EndpointVersion1/MyTimeoutSagaVersion1.cs
samples/sql-persistence/saga-rename/SqlPersistence_9/EndpointVersion1/Program.cs
samples/sql-persistence/saga-rename/SqlPersistence_9/EndpointVersion2/EndpointVersion2.csproj
samples/sql-persistence/saga-rename/SqlPersistence_9/EndpointVersion2/MyReplySagaVersion2.cs
samples/sql-persistence/saga-rename/SqlPersistence_9/EndpointVersion2/MyTimeoutSagaVersion2.cs
samples/sql-persistence/saga-rename/SqlPersistence_9/EndpointVersion2/Program.cs
samples/sql-persistence/saga-rename/SqlPersistence_9/EndpointVersion2/ReplyMutator.cs
samples/sql-persistence/saga-rename/SqlPersistence_9/RenameSaga.StartupProjects.txt
samples/sql-persistence/saga-rename/SqlPersistence_9/RenameSaga.sln
samples/sql-persistence/saga-rename/SqlPersistence_9/Shared/Reply.cs
samples/sql-persistence/saga-rename/SqlPersistence_9/Shared/Request.cs
samples/sql-persistence/saga-rename/SqlPersistence_9/Shared/RequestHandler.cs
samples/sql-persistence/saga-rename/SqlPersistence_9/Shared/SagaTimeout.cs
samples/sql-persistence/saga-rename/SqlPersistence_9/Shared/Shared.csproj
samples/sql-persistence/saga-rename/SqlPersistence_9/Shared/SharedConfiguration.cs
samples/sql-persistence/saga-rename/SqlPersistence_9/Shared/SqlHelper.cs
samples/sql-persistence/saga-rename/SqlPersistence_9/Shared/StartReplySaga.cs
samples/sql-persistence/saga-rename/SqlPersistence_9/Shared/StartTimeoutSaga.cs
samples/sql-persistence/saga-rename/sample.md

Update sample for NSB10: sqlpersistence sage rename

---

samples/sql-persistence/injecting-services/SqlPersistence_9/Endpoint/ConnectionHolder.cs
samples/sql-persistence/injecting-services/SqlPersistence_9/Endpoint/DataService.cs
samples/sql-persistence/injecting-services/SqlPersistence_9/Endpoint/Endpoint.csproj
samples/sql-persistence/injecting-services/SqlPersistence_9/Endpoint/Program.cs
samples/sql-persistence/injecting-services/SqlPersistence_9/Endpoint/SqlConnectionBehavior.cs
samples/sql-persistence/injecting-services/SqlPersistence_9/Endpoint/SqlHelper.cs
samples/sql-persistence/injecting-services/SqlPersistence_9/Endpoint/TestMessageHandler.cs
samples/sql-persistence/injecting-services/SqlPersistence_9/Endpoint/TestMsg.cs
samples/sql-persistence/injecting-services/SqlPersistence_9/InjectingServices.sln

Update sample for NSB10:  sqlpersistence-injecting services

---

samples/azure/native-integration-asq/ASQN_14/NativeIntegrationsASQ.sln
samples/azure/native-integration-asq/ASQN_14/NativeSender/NativeSender.csproj
samples/azure/native-integration-asq/ASQN_14/NativeSender/Program.cs
samples/azure/native-integration-asq/ASQN_14/Receiver/NativeMessageHandler.cs
samples/azure/native-integration-asq/ASQN_14/Receiver/Program.cs
samples/azure/native-integration-asq/ASQN_14/Receiver/Receiver.csproj
samples/azure/native-integration-asq/ASQN_14/Shared/NativeMessage.cs
samples/azure/native-integration-asq/ASQN_14/Shared/Shared.csproj

fixes: https://github.com/Particular/docs.particular.net/issues/7264

ASQ Native Integration sample for core 10

---

samples/web/send-from-aspnetcore-webapi/Core_10/CoreWebAPI.sln
samples/web/send-from-aspnetcore-webapi/Core_10/Endpoint/Endpoint.csproj
samples/web/send-from-aspnetcore-webapi/Core_10/Endpoint/MyHandler.cs
samples/web/send-from-aspnetcore-webapi/Core_10/Endpoint/Program.cs
samples/web/send-from-aspnetcore-webapi/Core_10/Shared/MyMessage.cs
samples/web/send-from-aspnetcore-webapi/Core_10/Shared/Shared.csproj
samples/web/send-from-aspnetcore-webapi/Core_10/WebApp/Program.cs
samples/web/send-from-aspnetcore-webapi/Core_10/WebApp/Properties/launchSettings.json
samples/web/send-from-aspnetcore-webapi/Core_10/WebApp/SendMessageController.cs
samples/web/send-from-aspnetcore-webapi/Core_10/WebApp/WebApp.csproj

For https://github.com/Particular/docs.particular.net/issues/7423

Updated web-api sample fore .NET 10

---

architecture/azure/event-driven-architecture.md

event-driven-architecture - legacy docs review

---

monitoring/metrics/definitions.md

- Improved consistency; changed grammar in a few places.
- Added clarity (time -> amount of time).

metric definitions - legacy docs review

---

samples/messagemutators/Core_10/MessageMutators.sln
samples/messagemutators/Core_10/Sample/CreateProductCommand.cs
samples/messagemutators/Core_10/Sample/Handler.cs
samples/messagemutators/Core_10/Sample/Program.cs
samples/messagemutators/Core_10/Sample/Runner.cs
samples/messagemutators/Core_10/Sample/Sample.csproj
samples/messagemutators/Core_10/Sample/TransportMessageCompressionMutator.cs
samples/messagemutators/Core_10/Sample/ValidationMessageMutator.cs

Fixes for https://github.com/Particular/docs.particular.net/issues/7330

MessageMutators to .NET 10

---

samples/fullduplex/Core_10/Client/Client.csproj
samples/fullduplex/Core_10/Client/DataResponseMessageHandler.cs
samples/fullduplex/Core_10/Client/Program.cs
samples/fullduplex/Core_10/FullDuplex.sln
samples/fullduplex/Core_10/Server/Program.cs
samples/fullduplex/Core_10/Server/RequestDataMessageHandler.cs
samples/fullduplex/Core_10/Server/Server.csproj
samples/fullduplex/Core_10/Shared/DataResponseMessage.cs
samples/fullduplex/Core_10/Shared/RequestDataMessage.cs
samples/fullduplex/Core_10/Shared/Shared.csproj

Update samples with modern C# features – part of
- https://github.com/Particular/docs.particular.net/issues/7311  
- Implement C# 12+ primary constructors for message records and handler classes
- Use modern hosting patterns with Host.CreateApplicationBuilder()
- Apply C# 13+ enhanced using declarations for automatic resource disposal

Add fullduplex Core_10 sample with .NET 10 and modern C# features

---

nservicebus/licensing/index.md

This updates the documentation to more accurately reflect how license validation is carried out.

Update license valid info

---

nservicebus/messaging/timeout-manager.md
nservicebus/messaging/timeout-manager_content_core_[8,).partial.md

Minor updates;
- Add warning block
- Add link to replacement: Delayed Delivery

NCS Documentation Update - Timeout Manager

---

samples/azure-service-bus-netstandard/options/ASBS_6/Options.sln
samples/azure-service-bus-netstandard/options/ASBS_6/Publisher/Program.cs
samples/azure-service-bus-netstandard/options/ASBS_6/Publisher/Publisher.csproj
samples/azure-service-bus-netstandard/options/ASBS_6/Publisher/ServiceCollectionExtensions.cs
samples/azure-service-bus-netstandard/options/ASBS_6/Publisher/Worker.cs
samples/azure-service-bus-netstandard/options/ASBS_6/Publisher/appsettings.json
samples/azure-service-bus-netstandard/options/ASBS_6/Shared/EventOne.cs
samples/azure-service-bus-netstandard/options/ASBS_6/Shared/EventTwo.cs
samples/azure-service-bus-netstandard/options/ASBS_6/Shared/Shared.csproj
samples/azure-service-bus-netstandard/options/ASBS_6/Subscriber/EventOneHandler.cs
samples/azure-service-bus-netstandard/options/ASBS_6/Subscriber/EventTwoHandler.cs
samples/azure-service-bus-netstandard/options/ASBS_6/Subscriber/Program.cs
samples/azure-service-bus-netstandard/options/ASBS_6/Subscriber/Subscriber.csproj
samples/azure-service-bus-netstandard/options/ASBS_6/Subscriber/appsettings.json

Add ASBS_6 to asb-options sample

---

samples/azure-service-bus-netstandard/native-integration/ASBS_6/NativeIntegrationASBS.sln
samples/azure-service-bus-netstandard/native-integration/ASBS_6/NativeSender/NativeSender.csproj
samples/azure-service-bus-netstandard/native-integration/ASBS_6/NativeSender/Program.cs
samples/azure-service-bus-netstandard/native-integration/ASBS_6/Receiver/NativeMessageHandler.cs
samples/azure-service-bus-netstandard/native-integration/ASBS_6/Receiver/Program.cs
samples/azure-service-bus-netstandard/native-integration/ASBS_6/Receiver/Receiver.csproj
samples/azure-service-bus-netstandard/native-integration/ASBS_6/Shared/NativeMessage.cs
samples/azure-service-bus-netstandard/native-integration/ASBS_6/Shared/Shared.csproj

Add ASBS_6 to asb-native-integration sample

---

samples/azure-service-bus-netstandard/native-integration-pub-sub/ASBS_6/NativeIntegrationPubSubASBS.sln
samples/azure-service-bus-netstandard/native-integration-pub-sub/ASBS_6/NativeShared/NativeShared.csproj
samples/azure-service-bus-netstandard/native-integration-pub-sub/ASBS_6/NativeShared/TopologyManager.cs
samples/azure-service-bus-netstandard/native-integration-pub-sub/ASBS_6/NativeSubscriberA/NativeSubscriberA.csproj
samples/azure-service-bus-netstandard/native-integration-pub-sub/ASBS_6/NativeSubscriberA/Program.cs
samples/azure-service-bus-netstandard/native-integration-pub-sub/ASBS_6/NativeSubscriberB/NativeSubscriberB.csproj
samples/azure-service-bus-netstandard/native-integration-pub-sub/ASBS_6/NativeSubscriberB/Program.cs
samples/azure-service-bus-netstandard/native-integration-pub-sub/ASBS_6/Publisher/Program.cs
samples/azure-service-bus-netstandard/native-integration-pub-sub/ASBS_6/Publisher/Publisher.csproj
samples/azure-service-bus-netstandard/native-integration-pub-sub/ASBS_6/Shared/EventOne.cs
samples/azure-service-bus-netstandard/native-integration-pub-sub/ASBS_6/Shared/EventTwo.cs
samples/azure-service-bus-netstandard/native-integration-pub-sub/ASBS_6/Shared/Shared.csproj

Add ASBS_6 to asb-integration-pubsub sample

---

samples/encryption/message-body-encryption/Core_10/Endpoint1/Endpoint1.csproj
samples/encryption/message-body-encryption/Core_10/Endpoint1/Program.cs
samples/encryption/message-body-encryption/Core_10/Endpoint2/CompleteOrderHandler.cs
samples/encryption/message-body-encryption/Core_10/Endpoint2/Endpoint2.csproj
samples/encryption/message-body-encryption/Core_10/Endpoint2/Program.cs
samples/encryption/message-body-encryption/Core_10/MessageBodyEncryption.sln
samples/encryption/message-body-encryption/Core_10/Shared/CompleteOrder.cs
samples/encryption/message-body-encryption/Core_10/Shared/EndpointConfigurationExtensions.cs
samples/encryption/message-body-encryption/Core_10/Shared/MessageEncryptor.cs
samples/encryption/message-body-encryption/Core_10/Shared/Shared.csproj
samples/encryption/message-body-encryption/Core_9/Endpoint2/Program.cs
samples/encryption/message-body-encryption/Core_9/Shared/CompleteOrder.cs

* Fixes https://github.com/Particular/docs.particular.net/issues/7305

Add NSB10 version of message body encryption sample

---

architecture/azure/messaging.md

This is a review of the architecture azure messaging article.
In this review I made some changes regarding the mention of Azure SQL as a messaging option in Azure.

Review architecture azure messaging

---

samples/aws/sqs-simple/Sqs_9/Receiver/MyCommandHandler.cs
samples/aws/sqs-simple/Sqs_9/Receiver/MyEventHandler.cs
samples/aws/sqs-simple/Sqs_9/Receiver/Program.cs
samples/aws/sqs-simple/Sqs_9/Receiver/Receiver.csproj
samples/aws/sqs-simple/Sqs_9/Sender/Program.cs
samples/aws/sqs-simple/Sqs_9/Sender/Sender.csproj
samples/aws/sqs-simple/Sqs_9/Shared/MyCommand.cs
samples/aws/sqs-simple/Sqs_9/Shared/MyEvent.cs
samples/aws/sqs-simple/Sqs_9/Shared/Shared.csproj
samples/aws/sqs-simple/Sqs_9/SimpleSqs.sln
samples/aws/sqs-simple/sample.md

Fixes https://github.com/Particular/docs.particular.net/issues/7254

Add Sqs_9 sample

---

servicecontrol/errorlog-auditlog-behavior.md

editorial review of 7425

---

samples/aws/sqs-native-integration/Sqs_8/Sender/Program.cs
samples/aws/sqs-native-integration/Sqs_9/NativeIntegration.sln
samples/aws/sqs-native-integration/Sqs_9/Receiver/AccessToAmazonSqsNativeMessageBehavior.cs
samples/aws/sqs-native-integration/Sqs_9/Receiver/Program.cs
samples/aws/sqs-native-integration/Sqs_9/Receiver/Receiver.csproj
samples/aws/sqs-native-integration/Sqs_9/Receiver/SomeNativeMessage.cs
samples/aws/sqs-native-integration/Sqs_9/Receiver/SomeNativeMessageHandler.cs
samples/aws/sqs-native-integration/Sqs_9/Receiver/SomeReply.cs
samples/aws/sqs-native-integration/Sqs_9/Sender/Program.cs
samples/aws/sqs-native-integration/Sqs_9/Sender/Sender.csproj
samples/aws/sqs-native-integration/sample.md

Fixes https://github.com/Particular/docs.particular.net/issues/7253

Samples aws sqs native integration updates

---

samples/open-telemetry/prometheus-grafana/Core_10/Endpoint/Endpoint.csproj
samples/open-telemetry/prometheus-grafana/Core_10/Endpoint/LoadSimulator.cs
samples/open-telemetry/prometheus-grafana/Core_10/Endpoint/Program.cs
samples/open-telemetry/prometheus-grafana/Core_10/Endpoint/SomeMessage.cs
samples/open-telemetry/prometheus-grafana/Core_10/Endpoint/SomeMessageHandler.cs
samples/open-telemetry/prometheus-grafana/Core_10/OpenTelemetryDemo.sln
samples/open-telemetry/prometheus-grafana/Core_10/docker-compose.yml
samples/open-telemetry/prometheus-grafana/Core_10/grafana/provisioning/datasources/prometheus_ds.yml
samples/open-telemetry/prometheus-grafana/Core_10/prometheus/prometheus.yml

Fixes https://github.com/Particular/docs.particular.net/issues/7348.

Upgrade Open-Telemetry Prometheus Grafana Sample to .NET 10

---

samples/open-telemetry/metrics-shim/Core_10/Endpoint/Endpoint.csproj
samples/open-telemetry/metrics-shim/Core_10/Endpoint/LoadSimulator.cs
samples/open-telemetry/metrics-shim/Core_10/Endpoint/MetricsShim/EmitNServiceBusMetrics.cs
samples/open-telemetry/metrics-shim/Core_10/Endpoint/MetricsShim/Extensions.cs
samples/open-telemetry/metrics-shim/Core_10/Endpoint/Program.cs
samples/open-telemetry/metrics-shim/Core_10/Endpoint/SomeMessage.cs
samples/open-telemetry/metrics-shim/Core_10/Endpoint/SomeMessageHandler.cs
samples/open-telemetry/metrics-shim/Core_10/ExportNServiceBusMetricsViaOpenTelemetry.sln

Fixes https://github.com/Particular/docs.particular.net/issues/7347.

Update Open-Telemetry Metrics Shim Sample to .NET 10

---

samples/startup-shutdown-sequence/Core_10/Sample/ExtensionPoints/MyFeature.cs
samples/startup-shutdown-sequence/Core_10/Sample/ExtensionPoints/MyFeatureStartupTask.cs
samples/startup-shutdown-sequence/Core_10/Sample/ExtensionPoints/NeedInitialization.cs
samples/startup-shutdown-sequence/Core_10/Sample/ExtensionPoints/NeedToInstallSomething.cs
samples/startup-shutdown-sequence/Core_10/Sample/ExtensionPoints/WantToRunBeforeConfigurationIsFinalized.cs
samples/startup-shutdown-sequence/Core_10/Sample/Logger.cs
samples/startup-shutdown-sequence/Core_10/Sample/Program.cs
samples/startup-shutdown-sequence/Core_10/Sample/Sample.csproj
samples/startup-shutdown-sequence/Core_10/StartupShutdown.sln
samples/startup-shutdown-sequence/Core_10/StartupShutdownSequence.txt

Closes https://github.com/Particular/docs.particular.net/issues/7410

Upgrade startup-shutdown-sequence to v10

---

samples/sqltransport-sqlpersistence/Core_10/Receiver/Dapper/OrderSubmittedHandler.cs
samples/sqltransport-sqlpersistence/Core_10/Receiver/Dapper/SubmittedOrder.cs
samples/sqltransport-sqlpersistence/Core_10/Receiver/EntityFramework/OrderSubmittedHandler.cs
samples/sqltransport-sqlpersistence/Core_10/Receiver/EntityFramework/SubmittedOrder.cs
samples/sqltransport-sqlpersistence/Core_10/Receiver/EntityFramework/SubmittedOrderDbContext.cs
samples/sqltransport-sqlpersistence/Core_10/Receiver/OrderLifecycleSaga.cs
samples/sqltransport-sqlpersistence/Core_10/Receiver/OrderSubmittedHandler.cs
samples/sqltransport-sqlpersistence/Core_10/Receiver/OrderTimeout.cs
samples/sqltransport-sqlpersistence/Core_10/Receiver/OrmLite/OrderSubmittedHandler.cs
samples/sqltransport-sqlpersistence/Core_10/Receiver/OrmLite/SubmittedOrder.cs
samples/sqltransport-sqlpersistence/Core_10/Receiver/Program.cs
samples/sqltransport-sqlpersistence/Core_10/Receiver/Raw/OrderSubmittedHandler.cs
samples/sqltransport-sqlpersistence/Core_10/Receiver/Receiver.csproj
samples/sqltransport-sqlpersistence/Core_10/Receiver/SqlPersistenceSettings.cs
samples/sqltransport-sqlpersistence/Core_10/Receiver/Startup.sql
samples/sqltransport-sqlpersistence/Core_10/Sender/OrderAcceptedHandler.cs
samples/sqltransport-sqlpersistence/Core_10/Sender/Program.cs
samples/sqltransport-sqlpersistence/Core_10/Sender/Sender.csproj
samples/sqltransport-sqlpersistence/Core_10/Shared/OrderAccepted.cs
samples/sqltransport-sqlpersistence/Core_10/Shared/OrderSubmitted.cs
samples/sqltransport-sqlpersistence/Core_10/Shared/Shared.csproj
samples/sqltransport-sqlpersistence/Core_10/Shared/SqlHelper.cs
samples/sqltransport-sqlpersistence/Core_10/SqlTransport-SqlPersistence.sln

Closes https://github.com/Particular/docs.particular.net/issues/7409

Update sqltransport-sqlpersistence sample to v10

---

samples/open-telemetry/logging/Core_10/GenericHost/GenericHost.csproj
samples/open-telemetry/logging/Core_10/GenericHost/MessageGenerator.cs
samples/open-telemetry/logging/Core_10/GenericHost/MyMessage.cs
samples/open-telemetry/logging/Core_10/GenericHost/MyMessageHandler.cs
samples/open-telemetry/logging/Core_10/GenericHost/Program.cs
samples/open-telemetry/logging/Core_10/OpenTelemetryTracesAndLogs.sln

Fixes https://github.com/Particular/docs.particular.net/issues/7346.

Upgrade Open-Telemetry Logging Sample to .NET 10

---

samples/serializers/multiple-deserializers/Core_10/ExternalNewtonsoftBsonEndpoint/ExternalNewtonsoftBsonEndpoint.csproj
samples/serializers/multiple-deserializers/Core_10/ExternalNewtonsoftBsonEndpoint/Program.cs
samples/serializers/multiple-deserializers/Core_10/ExternalNewtonsoftJsonEndpoint/ExternalNewtonsoftJsonEndpoint.csproj
samples/serializers/multiple-deserializers/Core_10/ExternalNewtonsoftJsonEndpoint/Program.cs
samples/serializers/multiple-deserializers/Core_10/MultipleDeserializers.sln
samples/serializers/multiple-deserializers/Core_10/ReceivingEndpoint/CreateOrderHandler.cs
samples/serializers/multiple-deserializers/Core_10/ReceivingEndpoint/IIncomingMessageBodyWriter.cs
samples/serializers/multiple-deserializers/Core_10/ReceivingEndpoint/IncomingMessageBodyWriter.cs
samples/serializers/multiple-deserializers/Core_10/ReceivingEndpoint/Program.cs
samples/serializers/multiple-deserializers/Core_10/ReceivingEndpoint/ReceivingEndpoint.csproj
samples/serializers/multiple-deserializers/Core_10/Shared/CreateOrder.cs
samples/serializers/multiple-deserializers/Core_10/Shared/MessageBuilder.cs
samples/serializers/multiple-deserializers/Core_10/Shared/OrderItem.cs
samples/serializers/multiple-deserializers/Core_10/Shared/OutgoingMessageBodyWriter.cs
samples/serializers/multiple-deserializers/Core_10/Shared/Shared.csproj
samples/serializers/multiple-deserializers/Core_10/SystemJsonEndpoint/Program.cs
samples/serializers/multiple-deserializers/Core_10/SystemJsonEndpoint/SystemJsonEndpoint.csproj
samples/serializers/multiple-deserializers/Core_10/XmlEndpoint/Program.cs
samples/serializers/multiple-deserializers/Core_10/XmlEndpoint/XmlEndpoint.csproj
samples/serializers/multiple-deserializers/Core_9/ExternalNewtonsoftBsonEndpoint/Program.cs
samples/serializers/multiple-deserializers/Core_9/ExternalNewtonsoftJsonEndpoint/Program.cs
samples/serializers/multiple-deserializers/Core_9/ReceivingEndpoint/Program.cs
samples/serializers/multiple-deserializers/Core_9/ReceivingEndpoint/ReceivingEndpoint.csproj
samples/serializers/multiple-deserializers/Core_9/Shared/MessageBuilder.cs
samples/serializers/multiple-deserializers/Core_9/Shared/OutgoingMessageBodyWriter.cs
samples/serializers/multiple-deserializers/Core_9/Shared/Shared.csproj
samples/serializers/multiple-deserializers/Core_9/SystemJsonEndpoint/Program.cs
samples/serializers/multiple-deserializers/Core_9/XmlEndpoint/Program.cs

Multiple deserializers sample for NServiceBus 10

---

nservicebus/hosting/windows-service.md

- Resolve minor lint issues
- Add note about the `sc` tool
- Clarify _Specifying Service dependencies_ command
- Update reviewed date

NCS Documentation Update: Windows Service Hosting

---

nservicebus/hosting/azure-functions-service-bus/analyzers.md

Reviewed and updated reviewed date

NCS Doc Review - Azure Function Analyzers

---

samples/nhibernate/simple/NHibernate_11/Client/Client.csproj
samples/nhibernate/simple/NHibernate_11/Client/OrderCompletedHandler.cs
samples/nhibernate/simple/NHibernate_11/Client/Program.cs
samples/nhibernate/simple/NHibernate_11/Sample.sln
samples/nhibernate/simple/NHibernate_11/Server/CompleteOrder.cs
samples/nhibernate/simple/NHibernate_11/Server/OrderSaga.cs
samples/nhibernate/simple/NHibernate_11/Server/OrderSagaData.cs
samples/nhibernate/simple/NHibernate_11/Server/OrderShipped.cs
samples/nhibernate/simple/NHibernate_11/Server/OrderShippedMap.cs
samples/nhibernate/simple/NHibernate_11/Server/Program.cs
samples/nhibernate/simple/NHibernate_11/Server/Server.csproj
samples/nhibernate/simple/NHibernate_11/Server/ShipOrder.cs
samples/nhibernate/simple/NHibernate_11/Server/ShipOrderHandler.cs
samples/nhibernate/simple/NHibernate_11/Shared/OrderCompleted.cs
samples/nhibernate/simple/NHibernate_11/Shared/Shared.csproj
samples/nhibernate/simple/NHibernate_11/Shared/StartOrder.cs

Add nhibernate/simple NServiceBus 10 version

---

samples/outbox/cosmosdb/Core_10/CosmosDbOutbox.sln
samples/outbox/cosmosdb/Core_10/Sample/Helper.cs
samples/outbox/cosmosdb/Core_10/Sample/MyHandler.cs
samples/outbox/cosmosdb/Core_10/Sample/MyMessage.cs
samples/outbox/cosmosdb/Core_10/Sample/Program.cs
samples/outbox/cosmosdb/Core_10/Sample/Sample.csproj
samples/outbox/cosmosdb/Core_10/docker-compose.yml

Add outbox/cosmosdb NServiceBus 10 sample

---

samples/azure/storage-queues/ASQN_13/StorageReader/AzureHelper.cs
samples/azure/storage-queues/ASQN_14/AzureStorageQueues.sln
samples/azure/storage-queues/ASQN_14/Endpoint1/Endpoint1.csproj
samples/azure/storage-queues/ASQN_14/Endpoint1/Endpoint2ResponseHandler.cs
samples/azure/storage-queues/ASQN_14/Endpoint1/Program.cs
samples/azure/storage-queues/ASQN_14/Endpoint2/Endpoint2.csproj
samples/azure/storage-queues/ASQN_14/Endpoint2/MyRequestResponseHandler.cs
samples/azure/storage-queues/ASQN_14/Endpoint2/Program.cs
samples/azure/storage-queues/ASQN_14/Shared/BackwardsCompatibleQueueNameSanitizer.cs
samples/azure/storage-queues/ASQN_14/Shared/MyRequest.cs
samples/azure/storage-queues/ASQN_14/Shared/MyResponse.cs
samples/azure/storage-queues/ASQN_14/Shared/Shared.csproj
samples/azure/storage-queues/ASQN_14/StorageReader/AzureHelper.cs
samples/azure/storage-queues/ASQN_14/StorageReader/Extensions.cs
samples/azure/storage-queues/ASQN_14/StorageReader/StorageReader.csproj

Fixes https://github.com/Particular/docs.particular.net/issues/7265

Add NServiceBus 10 Azure Storage Queues sample

---

samples/custom-recoverability/Core_10/Client/Client.csproj
samples/custom-recoverability/Core_10/Client/Program.cs
samples/custom-recoverability/Core_10/CustomRecoverability.sln
samples/custom-recoverability/Core_10/Dockerfile
samples/custom-recoverability/Core_10/Server/MyHandler.cs
samples/custom-recoverability/Core_10/Server/Program.cs
samples/custom-recoverability/Core_10/Server/Server.csproj
samples/custom-recoverability/Core_10/Shared/MyMessage.cs
samples/custom-recoverability/Core_10/Shared/Shared.csproj
samples/custom-recoverability/Core_10/run_sample.sh
samples/custom-recoverability/Core_9/Dockerfile
samples/custom-recoverability/Core_9/run_sample.sh

This pull request adds a new sample for custom-recoverability for NServiceBus 10.
Fixes: #7286
- Added comprehensive Dockerfile and test script for containerized validation
- Tests both normal operation and fault scenarios (ArgumentNullException)
- Validates custom recoverability policy behavior with automated testing
- Updated to use .NET 10 and C# preview language version
- Updated to NServiceBus 10.0.0-alpha.1 and related prerelease packages
- Updated Microsoft.Extensions packages to .NET 10 preview versions
- Applied C# 12+ language features improvements
- Added prerelease.txt file as required for prerelease samples
- Comprehensive Docker testing validates both normal and fault scenarios
Both versions include Docker containers that:
- Test normal message processing
- Test fault …

Add NServiceBus 10 custom-recoverability sample

---

transports/msmq/management-using-powershell.md

- Update management-using-powershell.md for accuracy and clarity in prerequisites and usage sections.
- Add warnings about support
- Add additional links.
- Add new Troubleshooting section.
- Updated reviewed date.
- Fix minor lint issues.

NCS Doc Review - MSMQ PowerShell

---

samples/errorhandling/sample.md

- Update review date
- Minor improvements for clarity
- Minor lint issues fixed

NCS Doc Review - Error handling / automatic retry sample

---

samples/azure-functions/service-bus/ASBFunctions_6/AzureFunctions.ASBTrigger.FunctionsHostBuilder/AzureFunctions.ASBTrigger.FunctionsHostBuilder.csproj

Discovered as part of https://github.com/Particular/docs.particular.net/issues/7267

Take the Azure Functions Service Bus NserviceBus 9 sample out of prerelease

---

platform/contributing.md

Remove several links that now redirect to the same location.

Review contributing page

---

samples/platform-connector/code-first/PlatformConnector_4/Endpoint/CustomChecks/SampleCustomCheck.cs
samples/platform-connector/code-first/PlatformConnector_4/Endpoint/Endpoint.csproj
samples/platform-connector/code-first/PlatformConnector_4/Endpoint/Handlers/RequestProcessingHandler.cs
samples/platform-connector/code-first/PlatformConnector_4/Endpoint/Messages/BusinessMessage.cs
samples/platform-connector/code-first/PlatformConnector_4/Endpoint/Messages/RequestProcessing.cs
samples/platform-connector/code-first/PlatformConnector_4/Endpoint/Messages/RequestProcessingResponse.cs
samples/platform-connector/code-first/PlatformConnector_4/Endpoint/Program.cs
samples/platform-connector/code-first/PlatformConnector_4/Endpoint/Sagas/BusinessSaga.cs
samples/platform-connector/code-first/PlatformConnector_4/PlatformLauncher/PlatformLauncher.csproj
samples/platform-connector/code-first/PlatformConnector_4/PlatformLauncher/Program.cs
samples/platform-connector/code-first/PlatformConnector_4/ServicePlatformConnector.CodeFirst.sln

Add NSB10 version of platform-connector code-first

---

samples/pipeline/message-signing/Core_10/ReceivingEndpoint/MyMessageHandler.cs
samples/pipeline/message-signing/Core_10/ReceivingEndpoint/Program.cs
samples/pipeline/message-signing/Core_10/ReceivingEndpoint/ReceivingEndpoint.csproj
samples/pipeline/message-signing/Core_10/Shared/MessageSigningBehavior.cs
samples/pipeline/message-signing/Core_10/Shared/MyMessage.cs
samples/pipeline/message-signing/Core_10/Shared/ReadOnlyStream.cs
samples/pipeline/message-signing/Core_10/Shared/RegisterBehaviors.cs
samples/pipeline/message-signing/Core_10/Shared/Shared.csproj
samples/pipeline/message-signing/Core_10/Shared/SharedKeys.cs
samples/pipeline/message-signing/Core_10/Shared/SignatureVerificationBehavior.cs
samples/pipeline/message-signing/Core_10/SignedSender/Program.cs
samples/pipeline/message-signing/Core_10/SignedSender/SignedSender.csproj
samples/pipeline/message-signing/Core_10/SigningAndEncryption.sln
samples/pipeline/message-signing/Core_10/UnsignedSender/Program.cs
samples/pipeline/message-signing/Core_10/UnsignedSender/UnsignedSender.csproj

Fixes https://github.com/Particular/docs.particular.net/issues/7360

Add NServiceBus 10 pipeline message signing sample

---

samples/azure-functions/service-bus-kafka/sample.md

This pull request updates the documentation for the Azure Functions Service Bus Kafka sample, clarifying requirements for the Service Bus connection string and updating the review date.

Docs review for Azure Functions Service Bus Kafka sample

---

Snippets/NHibernate/NHibernate.sln
Snippets/NHibernate/NHibernate_11/Concurrency/SagaDataWithLockMode.cs
Snippets/NHibernate/NHibernate_11/Concurrency/SagaDataWithRowVersion.cs
Snippets/NHibernate/NHibernate_11/DisableSchemaUpdate.cs
Snippets/NHibernate/NHibernate_11/NHibernate_11.csproj
Snippets/NHibernate/NHibernate_11/Outbox.cs
Snippets/NHibernate/NHibernate_11/OutboxTimeToKeep.xml
Snippets/NHibernate/NHibernate_11/Session/Order.cs
Snippets/NHibernate/NHibernate_11/Session/OrderHandler.cs
Snippets/NHibernate/NHibernate_11/Session/OrderHandlerViaContext.cs
Snippets/NHibernate/NHibernate_11/Session/OrderMessage.cs
Snippets/NHibernate/NHibernate_11/Session/OrderSaga.cs
Snippets/NHibernate/NHibernate_11/Usage.cs
Snippets/NHibernate/NHibernate_11/UsageSqlAzure.cs
Snippets/NHibernate/NHibernate_11/nhibernate.config.xml

Fixes https://github.com/Particular/docs.particular.net/issues/7661

Add NServiceBus 10 version of the NHibernate snippets

---

Snippets/Testing/Testing.sln
Snippets/Testing/Testing_10/Behavior/BehaviorTests.cs
Snippets/Testing/Testing_10/Data/CustomBehavior.cs
Snippets/Testing/Testing_10/Data/DiscountPolicy.cs
Snippets/Testing/Testing_10/Data/DiscountPolicyData.cs
Snippets/Testing/Testing_10/Data/MyHandlerWithLogging.cs
Snippets/Testing/Testing_10/Data/MyReplyingHandler.cs
Snippets/Testing/Testing_10/Data/MyRequest.cs
Snippets/Testing/Testing_10/Data/MyResponse.cs
Snippets/Testing/Testing_10/Data/ProcessOrder.cs
Snippets/Testing/Testing_10/Data/SubmitOrder.cs
Snippets/Testing/Testing_10/Handlers/InterfaceMessageTests.cs
Snippets/Testing/Testing_10/Handlers/MessageHandlerTests.cs
Snippets/Testing/Testing_10/Logging/LoggingTest.cs
Snippets/Testing/Testing_10/Logging/LoggingTestAmbient.cs
Snippets/Testing/Testing_10/MessageSession/MessageSessionTests.cs
Snippets/Testing/Testing_10/Saga/MyCommand.cs
Snippets/Testing/Testing_10/Saga/MyEvent.cs
Snippets/Testing/Testing_10/Saga/MyOtherEvent.cs
Snippets/Testing/Testing_10/Saga/MySaga.cs
Snippets/Testing/Testing_10/Saga/MySagaData.cs
Snippets/Testing/Testing_10/Saga/SagaTests.cs
Snippets/Testing/Testing_10/Saga/StartsSaga.cs
Snippets/Testing/Testing_10/SagaScenarioTesting/BasicScenarioTest.cs
Snippets/Testing/Testing_10/SagaScenarioTesting/Usage.cs
Snippets/Testing/Testing_10/Testing_10.csproj
Snippets/Testing/Testing_7/MessageSession/MessageSessionTests.cs
Snippets/Testing/Testing_8/MessageSession/MessageSessionTests.cs
Snippets/Testing/Testing_9/MessageSession/MessageSessionTests.cs

Fixes https://github.com/Particular/docs.particular.net/issues/7688

Add NServiceBus 10 version of the Testing snippets

---

Snippets/Templates/Templates.sln
Snippets/Templates/Templates_4/usage.txt
Snippets/Templates/Templates_5/usage.txt
Snippets/Templates/Templates_6/usage.txt
Snippets/Templates/Templates_7/Templates_7.csproj
Snippets/Templates/Templates_7/usage.txt
nservicebus/dotnet-templates/index.md

Fixes https://github.com/Particular/docs.particular.net/issues/7687

Add NServiceBus 10 version of the Templates snippets

---

Snippets/Newtonsoft/Newtonsoft.sln
Snippets/Newtonsoft/Newtonsoft_2.4/Newtonsoft_2.4.csproj
Snippets/Newtonsoft/Newtonsoft_2/Newtonsoft_2.csproj
Snippets/Newtonsoft/Newtonsoft_3/Newtonsoft_3.csproj
Snippets/Newtonsoft/Newtonsoft_4/Newtonsoft_4.csproj
Snippets/Newtonsoft/Newtonsoft_5/Newtonsoft_5.csproj
Snippets/Newtonsoft/Newtonsoft_5/Usage.cs
Snippets/Newtonsoft/Newtonsoft_5/Xml/XmlJsonConverter.cs
Snippets/Newtonsoft/Newtonsoft_5/Xml/XmlUsage.cs

Fixes https://github.com/Particular/docs.particular.net/issues/7663

Add NServiceBus 10 version of the Newtonsoft snippets

---

Snippets/Raven/Raven_10/Raven_10.csproj
samples/ravendb/simple/Raven_10/Client/Client.csproj
samples/ravendb/simple/Raven_10/Server/Server.csproj
samples/ravendb/simple/Raven_10/Shared/Shared.csproj

- https://github.com/Particular/NServiceBus.RavenDB/issues/1341
- Upgraded NServiceBus.RavenDB to 10.0.0 and RavenDB.Client to 6.2.9 in raven_10

Update samples for NServiceBus.RavenDB 10.0.0 and RavenDB.Client 6.2.9

---

Snippets/GatewayRavenDB/GatewayRavenDB_5/GatewayRavenDB_5.csproj

- https://github.com/Particular/NServiceBus.Gateway.RavenDB/issues/720
- Upgraded NServiceBus.Gateway.RavenDB references to 5.0.0 in gateway_5

Update Gateway Snippets  to upgrade NServiceBus.Gateway.RavenDB

---

Snippets/TransactionalSession/TransactionalSession.sln
Snippets/TransactionalSession/TransactionalSession_1/TransactionalSession_1.csproj
Snippets/TransactionalSession/TransactionalSession_2/TransactionalSession_2.csproj
Snippets/TransactionalSession/TransactionalSession_3.1/TransactionalSession_3.1.csproj
Snippets/TransactionalSession/TransactionalSession_3.3/TransactionalSession_3.3.csproj
Snippets/TransactionalSession/TransactionalSession_3/TransactionalSession_3.csproj
Snippets/TransactionalSession/TransactionalSession_4/Api.cs
Snippets/TransactionalSession/TransactionalSession_4/MyMessage.cs
Snippets/TransactionalSession/TransactionalSession_4/MyPersistence.cs
Snippets/TransactionalSession/TransactionalSession_4/MyPersistenceConfigExtensions.cs
Snippets/TransactionalSession/TransactionalSession_4/MyPersistenceOpenSessionOptions.cs
Snippets/TransactionalSession/TransactionalSession_4/TransactionalSession_4.csproj

Add NSB 10 TransactionalSession Snippets

---

Snippets/TransactionalSession.NHibernate/NHibernateTS.sln
Snippets/TransactionalSession.NHibernate/NHibernateTS_10/MyMessage.cs
Snippets/TransactionalSession.NHibernate/NHibernateTS_10/NHibernateConfig.cs
Snippets/TransactionalSession.NHibernate/NHibernateTS_10/NHibernateTS_10.csproj
Snippets/TransactionalSession.NHibernate/NHibernateTS_11/MyMessage.cs
Snippets/TransactionalSession.NHibernate/NHibernateTS_11/NHibernateConfig.cs
Snippets/TransactionalSession.NHibernate/NHibernateTS_11/NHibernateTS_11.csproj

Fixes https://github.com/Particular/docs.particular.net/issues/7693
And also adds snippets for previously released versions

Add NServiceBus 10 version of the Transactional session NHibernate snippets

---

Snippets/TransactionalSession.SqlPersistence/SqlPersistenceTS.sln
Snippets/TransactionalSession.SqlPersistence/SqlPersistenceTS_8/MyMessage.cs
Snippets/TransactionalSession.SqlPersistence/SqlPersistenceTS_8/SqlPersistenceConfig.cs
Snippets/TransactionalSession.SqlPersistence/SqlPersistenceTS_8/SqlPersistenceTS_8.csproj
Snippets/TransactionalSession.SqlPersistence/SqlPersistenceTS_9/MyMessage.cs
Snippets/TransactionalSession.SqlPersistence/SqlPersistenceTS_9/SqlPersistenceConfig.cs
Snippets/TransactionalSession.SqlPersistence/SqlPersistenceTS_9/SqlPersistenceTS_9.csproj

Fixes https://github.com/Particular/docs.particular.net/issues/7695
And also adds snippets for previously released versions

Add NServiceBus 10 version of the Transactional session SQL Persistence snippets

---

Snippets/PlatformConnector/PlatformConnector_3/UpgradeGuides/3to4/TimeToBeReceived.cs
Snippets/PlatformConnector/PlatformConnector_4/UpgradeGuides/3to4/TimeToBeReceived.cs
menu/menu.yaml
nservicebus/upgrades/service-platform-connector-3to4.md

Fixes https://github.com/Particular/docs.particular.net/issues/7789

Add the upgrade guide for ServicePlatform Connector Version 3 to 4

---

monitoring/metrics/definitions.md
nservicebus/operations/opentelemetry_metrics_core_[9,).partial.md

Documentation for https://github.com/Particular/NServiceBus.TransactionalSession/pull/463

Transactional session metrics

---

platform/installation.md

SCMU is not an installable application anymore, so this PR attempts to clarify that it just needs to be downloaded.

Clarify how to obtain SCMU
