Particular/docs.particular.net

nservicebus/release-policy.md

@udidahan @SamCamhi here's my attemt to "not bury the lead". Thoughts?

Mention our backporting policy earlier in the doc

---

nservicebus/msmq-information.md

https://github.com/Particular/docs.particular.net/issues/460

added comment for remote queues

---

Snippets/Snippets_3/Callback/Callback.cs
Snippets/Snippets_3/Snippets_3.csproj
Snippets/Snippets_4/Callback/Callback.cs
Snippets/Snippets_4/Snippets_4.csproj
Snippets/Snippets_5/Callback/Callback.cs
Snippets/Snippets_5/Snippets_5.csproj
nservicebus/how-do-i-handle-responses-on-the-client-side.md

Added section on callbacks usage for request/response scenario to address users that need it [usergroup questions](https://groups.google.com/d/msg/particularsoftware/-YmEoyof9U0/GxKdqNdqZ8wJ) mostly in the context of web applications.

callback use for request/response

---

nservicebus/unit-testing.md

Related to #379, @SeanFeldman thoughts?

#379-improve-unit-testing

---

Snippets/Snippets_5/Snippets_5.csproj
Snippets/Snippets_5/Transports/RabbitMQ/App.config
Snippets/Snippets_5/Transports/RabbitMQ/ConfigurationSettings.cs
Snippets/Snippets_5/app.config
Snippets/Snippets_5/packages.config
nservicebus/rabbitmq/configuration-api.md

Updated docs for the Rabbitmq 2.1.0 release

---

nservicebus/individualizing-queues-when-scaling-out.md

@johnsimons please review and pull if good

Reworded the the individualization doco

---

nservicebus/assembly-scanning.md

**types** is the subject, so **is** would be the verb.
http://www.grammarbook.com/grammar/subjectVerbAgree.asp

minor grammatical update

---

nservicebus/deploying-nservicebus-in-a-windows-failover-cluster.md
nservicebus/load-balancing-with-the-distributor.md

@indualagarsamy: Is this a good location to document the duplicate QMIds issue?

Documented the need to have unique QMIds

---

Snippets/Snippets_5/Transports/RabbitMQ/ConfigurationSettings.cs
nservicebus/rabbitmq/configuration-api.md

This is just plugging the hole around routing. We probably need a separate section that diggs deeper into the various topologies

Doco for rabbit mq routing topologies

---

nservicebus/nservicebus-sagas-and-concurrency.md

Saga concurrency under high load

---

platform/extensions.md

Correcting nuget link to NServiceBus.Mandrill

---

samples/sqltransport/native-integration/Version_2/Receiver/ConfigErrorQueue.cs
samples/sqltransport/native-integration/Version_2/Receiver/LegacyOrderDetected.cs
samples/sqltransport/native-integration/Version_2/Receiver/LegacyOrderDetectedHandler.cs
samples/sqltransport/native-integration/Version_2/Receiver/PlaceOrder.cs
samples/sqltransport/native-integration/Version_2/Receiver/PlaceOrderHandler.cs
samples/sqltransport/native-integration/Version_2/Receiver/Program.cs
samples/sqltransport/native-integration/Version_2/Receiver/Receiver.csproj
samples/sqltransport/native-integration/Version_2/Receiver/Scripts.sql
samples/sqltransport/native-integration/Version_2/Receiver/packages.config
samples/sqltransport/native-integration/Version_2/SQLNativeIntegration.sln
samples/sqltransport/native-integration/Version_2/SQLNativeIntegration.sln.DotSettings
samples/sqltransport/native-integration/sample.md

Sample showing integration using the SQL transport

---

servicepulse/introduction-and-installing-servicepulse.md

Prerequisites added for the browser

---

Snippets/Snippets_4/CriticalError.cs
Snippets/Snippets_5/CriticalError.cs
nservicebus/azure/hosting-in-azure-cloud-services.md

Based on https://github.com/Particular/Requirements/issues/241
**Attention**: should be merged when Azure Host **6.2.2** is released

Handling Critical failures when using Azure host

---

servicecontrol/troubleshooting.md

Related to #553, @SimonCropp @ramonsmits please review

Document that SC database folder(s) needs to be excluded by AV scan

---

nservicebus/licensing/license-management.md
nservicebus/operations/management-using-powershell.md
nservicebus/operations/running-on-windows.md

Doco Changes for NSB Powershell V5

PowerShell v5  changes

---

Snippets/Snippets_4/Containers.cs
Snippets/Snippets_4/Snippets_4.csproj
Snippets/Snippets_4/app.config
Snippets/Snippets_4/packages.config
Snippets/Snippets_5/Containers.cs
Snippets/Snippets_5/Snippets_5.csproj
nservicebus/containers/index.md
samples/web/asp-mvc-injecting-bus/Version_5/WebApplication/Global.asax.cs

Also added missing Castle example to V4.

Clarify container usage with existing containers. 

---

nservicebus/rabbitmq/configuration-api.md

Explicit port configuration when running with multiple brokers

Explicit port configuration when running with multiple brokers

---

samples/web/asp-mvc-application/sample.md

typo; plages

---

menu/menu.yaml
nservicebus/rabbitmq/index.md
nservicebus/rabbitmq/rabbitmqclient-nuget.md

for the release of 2.1.3 of NSB.RabbitMQ https://github.com/Particular/NServiceBus.RabbitMQ/milestones/2.1.3

add doco about rabbitmq client dependency

---

Snippets/Snippets_5/Persistence/NHibernate/AccessingData.cs

@SzymonPobiega can you review?

Fixing OrderHandler sample for NH direct access

---

nservicebus/azure/azure-servicebus-transport.md

ASB scenarios for BatchSize

---

Snippets/Snippets_6/Headers/MutateOutgoingPhysicalMessages.cs
Snippets/Snippets_6/Headers/MutateOutgoingTransportMessages.cs
Snippets/Snippets_6/Snippets_6.csproj
Snippets/Snippets_6/packages.config
nservicebus/upgrades/5to6.md

Updated doco and upgrade guide on mutators in v6

---

home.md

Relates to https://github.com/Particular/FeatureDevelopment/issues/276
Changed the description for SM and the links displayed under for SM and SI.

Changes in doc home page

---

nservicebus/operations/monitoring-endpoints.md

PR to address performance counters doco issue https://github.com/Particular/docs.particular.net/issues/171

Document all performance counters

---

nservicebus/licensing/license-management.md
servicepulse/introduction-and-installing-servicepulse.md

Note that I'm making the recommendation that using the registry is the preferred method of installing the license. That could be controversial I guess.
Related to Desk case 11165.

Clarify how ServicePulse looks for its license in a couple places.

---

servicecontrol/creating-config-file.md

Explain the relationship between the input queues name and forwarding queues names.

Sc explain audit and error queue naming

---

Snippets/Snippets_5/Snippets_5.csproj
Snippets/Snippets_5/packages.config
nservicebus/containers/child-containers.md
samples/containers/spring/Version_5/Sample/Program.cs
samples/containers/spring/Version_5/Sample/Sample.csproj
samples/containers/spring/Version_5/Sample/packages.config

I'm working on the release. I'll update on this PR as soon as it is released

Child containers are now supported by spring

---

nservicebus/messaging/publish-subscribe/index.md
nservicebus/scalability-and-ha/distributor/index.md

Plus consistently use 'Distributor' rather than 'distributor'.

Rephrase a few things to make it easier to understand. 

---

nservicebus/operations/dotnet-framework-version-requirements.md
nservicebus/upgrades/5to6.md
platform/installer/offline.md

Related to https://github.com/Particular/NServiceBus/pull/2770 and https://github.com/Particular/FeatureDevelopment/issues/233

Mentioning V6 requires .NET 4.5.1

---

Snippets/Snippets_3/Snippets_3.csproj
Snippets/Snippets_3/UnitTesting/Unobtrusive.cs
Snippets/Snippets_4/Snippets_4.csproj
Snippets/Snippets_4/UnitTesting/Unobtrusive.cs
Snippets/Snippets_5/Snippets_5.csproj
Snippets/Snippets_5/UnitTesting/Unobtrusive.cs
nservicebus/testing/index.md

Clarify how unobtrusive conventions are configured for unit testing

---

Snippets/Snippets_4/RavenDB/ConfiguringTransactionRecoveryStorage.cs
Snippets/Snippets_5/RavenDB/ConfiguringTransactionRecoveryStorage.cs

clarify that transaction recovery storage is unique per endpoint

---

Snippets/Snippets_4/SCCluterAppSettings.xml
servicecontrol/deploying-servicecontrol-in-a-cluster.md

based on Calum's comments
fixes #442

Clustering ServiceControl

---

nservicebus/messaging/messages-events-commands.md

Removed some bloat and improved spelling. Tried my hand at clarifying command characteristics

Bloat & spelling

---

nservicebus/msmq/transportconfig.md

@Particular/nservicebus @SimonCropp please review

Adding a section about default queue permissions

---

nservicebus/ravendb/connecting.md
nservicebus/ravendb/installation.md
nservicebus/ravendb/uninstalling-v4.md
nservicebus/sagas/concurrency.md
samples/saga/ravendb-custom-sagafinder/sample.md

closes change raven links to use search #713

---

nservicebus/upgrades/5to6.md

Relates to https://github.com/Particular/NServiceBus/pull/2784

Accessing the builder outside the NServiceBus infrastructure

---

servicecontrol/creating-config-file.md

I added a snippet about how to configure Service Control for #296

ServiceControl MaxBodySizeToStore configuration instructions

---

samples/show-case/on-premise/Version_5/Store.CustomerRelations/App.config

Fix pub sub on showcase sample

---

servicepulse/troubleshooting.md

Slightly more descriptoin based on https://github.com/Particular/ServiceControl.Plugin.Nsb5.Heartbeat/issues/7 and a related desk case.

Described how to setup IIS in AlwaysRunning, Preload and Application Initialization

---

nservicebus/upgrades/4to5diff.md

Incorrect info placed in Obsolete attribute.

Clean up NSB upgrade doc

---

nservicebus/messaging/third-party-integration.md

@weralabaj did some tweaks, what do you think?

Clarify how to embed type info

---

nservicebus/upgrades/5to6.md

Relates to https://github.com/Particular/NServiceBus/pull/2794

Upgrade guide for saga persisters and saga finders

---

nservicebus/operations/auditing.md

FYI @SeanFeldman @indualagarsamy 
Please review

Clarify that v6 won't set TTBR on audit messages

---

nservicebus/messaging/handling-responses-on-the-client-side.md

Clarified that callbacks in a handler is a no no.

Added warning regarding where not to use callbacks

---

menu/menu.yaml
nservicebus/messaging/message-headers-for-third-party-integrations.md
nservicebus/messaging/third-party-integration.md

Relates to https://github.com/Particular/FeatureDevelopment/issues/194
@andreasohlund @gbiellem @SimonCropp @danielmarbach Could you please review and see if we missed anyting?

Headers for integration

---

nservicebus/upgrades/5to6.md

Belongs to https://github.com/Particular/NServiceBus/pull/2802

Doco for timeout storage split and timeout persistence options

---

nservicebus/upgrades/5to6.md

Belongs to https://github.com/Particular/NServiceBus/pull/2800

OutboxStorageOptions upgrade guide

---

nservicebus/serialization/index.md

Clarify serializers configuration.

---

README.md

to allow quick lookup w/o searching repo for example

Elaborate on snippets in various file types

---

menu/menu.yaml
servicepulse/install-servicepulse-in-iis.md
servicepulse/servicepulse-host-config.md

Rework SP docs to:
-  Separate IIS config from SP confg
-  Detail how to host SP in IIS and reverse proxy SC

Sp updates

---

Snippets/Operations/Msmq/QueueCreation.cs
Snippets/Operations/Msmq/QueueCreationTests.cs
Snippets/Operations/Operations.csproj
Snippets/Operations/SqlServer/NativeSend.cs
Snippets/Operations/SqlServer/NativeSendTests.cs
Snippets/Operations/SqlServer/QueueCreation.cs
Snippets/Operations/SqlServer/QueueCreationTests.cs
Snippets/Operations/SqlServer/QueueDeletion.cs
Snippets/Operations/SqlServer/QueueDeletionTests.cs
Snippets/Operations/packages.config
Snippets/Snippets_6/Snippets_6.csproj
Snippets/Snippets_6/app.config
nservicebus/sqlserver/operations-scripting.md

Provides a snippet to demonstrate native sends on SqlServer Transport for doco http://docs.particular.net/samples/sqltransport/native-integration/#code-walk-through-sending-the-message
https://github.com/Particular/docs.particular.net/issues/663

Operations SqlServer Native Send Example NSBv5

---

nservicebus/messaging/messages-events-commands.md
nservicebus/messaging/unobtrusive-mode.md

Mention that unobtrusive is suited for cross platform environments when using for example PCL's

Remark about PCL and small improvements

---

nservicebus/upgrades/3to4.md

@SimonCropp should we just pull this in and add content as we go?

First draft of v3 to v4 upgrade guide

---

nservicebus/outbox/index.md

Related to https://github.com/Particular/PlatformDevelopment/issues/277

Updated paragraph on outbox support in transports to reflect the code reality

---

nservicebus/hosting/assembly-scanning.md
nservicebus/upgrades/5to6.md

@andreasohlund IIRC you've mentioned that there's a way for existing customers that rely on nested folders asm scanning to have those scanned using profiles. Could you please add that info to the this PR?

WIP: Section on asm scanning changed

---

nservicebus/upgrades/release-policy.md

Clarify version support policy #806

---

nservicebus/upgrades/5to6.md

`UnicastBus` has been made internal. This PR documents a few exotic scenarios and workarounds

Documented a few more scenarios for UnicastBus

---

servicecontrol/creating-config-file.md

Doco for `ServiceControl/HttpDefaultConnectionLimit` to document PR https://github.com/Particular/ServiceControl/pull/527

HttpDefaultConnectionLimit setting

---

Snippets/Snippets_3/Scanning/ScanningPublicApi.cs
Snippets/Snippets_4/Scanning/ScanningPublicApi.cs
Snippets/Snippets_5/Scanning/ScanningPublicApi.cs
Snippets/Snippets_6/Scanning/ScanningPublicApi.cs
nservicebus/hosting/assembly-scanning.md
nservicebus/upgrades/5to6.md

Upgrade guide to demonstrate the change in API usage

Add example of assembly scanning include vs exclude lists in upgrade from v5 to v6

---

Snippets/Snippets_3/Snippets_3.csproj
Snippets/Snippets_3/Transactions.cs
Snippets/Snippets_4/Transactions.cs
Snippets/Snippets_6/Snippets_6.csproj
Snippets/Snippets_6/Transactions.cs
nservicebus/messaging/transactions.md
nservicebus/upgrades/3to4.md

Added doco for isolation level and transaction timeout

---

servicecontrol/plugins/heartbeat.md

added note to plugin documentation page.

heartbeat plugin does not support send-only endpoints

---

samples/startup-shutdown-sequence/Version_6/Sample/ExtensionPoints/WantToRunWhenBusStartsAndStops.cs
samples/startup-shutdown-sequence/Version_6/Sample/Program.cs
samples/startup-shutdown-sequence/Version_6/Sample/Sample.csproj
samples/startup-shutdown-sequence/Version_6/Sample/packages.config
samples/startup-shutdown-sequence/Version_6/StartupShutdownSequence.txt

@Particular/documentation See the thread changes introduced. Would this require to remove the info box 
> In some versions of NServiceBus certain extension points are executed on separate threads.
Thoughts?

Startup and Shutdown sequence sample upgraded to 6.0.0-unstable0878

---

nservicebus/lifecycle/iwanttorunwhenthebusstartsandstops.md
nservicebus/upgrades/5to6.md

I tried to be as close to the original article as possible. Divided into V6 and previous versions sections.

Interface lifecycle update for `IWantToRunWhenTheBusStartsAndStops`

---

nservicebus/upgrades/5to6.md

Related to https://github.com/Particular/NServiceBus/pull/2916

Removed `IQuerySubscriptions`

---

nservicebus/upgrades/5to6.md

@andreasohlund do we need more?

MarkAsComplete no longer virtual

---

Snippets/Snippets_3/BasicUsageOfIBus.cs
Snippets/Snippets_3/ImmediateDispatch/Usage.cs
Snippets/Snippets_3/Snippets_3.csproj
Snippets/Snippets_4/BasicUsageOfIBus.cs
Snippets/Snippets_4/ImmediateDispatch/Usage.cs
Snippets/Snippets_4/Snippets_4.csproj
Snippets/Snippets_5/BasicUsageOfIBus.cs
Snippets/Snippets_5/ImmediateDispatch/Usage.cs
Snippets/Snippets_5/Snippets_5.csproj
Snippets/Snippets_6/BasicUsageOfIBus.cs
Snippets/Snippets_6/Headers/IncomingBehavior.cs
Snippets/Snippets_6/ImmediateDispatch/Usage.cs
Snippets/Snippets_6/PubSub/Publishing/PublishAtStartup.cs
Snippets/Snippets_6/Snippets_6.csproj
Snippets/Snippets_6/packages.config
menu/menu.yaml
nservicebus/messaging/batched-dispatch.md
nservicebus/messaging/send-a-message.md
nservicebus/upgrades/5to6.md

Immediate dispatch

---

nservicebus/messaging/publish-subscribe/index.md

Clarification on IAuthorizeSubscriptions

---

README.md

@SimonCropp please review if this works for explanation

instructions-on-sequence-diagram-images

---

nservicebus/sagas/index.md
nservicebus/upgrades/5to6.md

Doco for https://github.com/Particular/NServiceBus/pull/2995

Correlated props are read only in v6

---

samples/azure/storage-persistence/Version_5/Client/Client.csproj
samples/azure/storage-persistence/Version_5/Client/packages.config
samples/azure/storage-persistence/Version_5/Server/OrderSaga.cs
samples/azure/storage-persistence/Version_5/Server/Server.csproj
samples/azure/storage-persistence/Version_5/Server/packages.config
samples/azure/storage-persistence/Version_5/Shared/Shared.csproj
samples/azure/storage-persistence/Version_5/Shared/packages.config
samples/azure/storage-persistence/Version_5/StorageReader/AzureHelper.cs

Original code set timeout to 50,000 seconds :)

Sample fix for timeout to execute after 5 seconds and dependencies update

---

samples/azure/azure-service-bus/Version_5/Endpoint1/Endpoint1.csproj
samples/azure/azure-service-bus/Version_5/Endpoint1/packages.config
samples/azure/azure-service-bus/Version_5/Endpoint2/Endpoint2.csproj
samples/azure/azure-service-bus/Version_5/Endpoint2/packages.config
samples/azure/azure-service-bus/Version_5/Shared/Shared.csproj
samples/azure/azure-service-bus/Version_5/Shared/packages.config
samples/azure/blob-storage-databus/Version_5/Receiver/Receiver.csproj
samples/azure/blob-storage-databus/Version_5/Receiver/packages.config
samples/azure/blob-storage-databus/Version_5/Sender/Sender.csproj
samples/azure/blob-storage-databus/Version_5/Sender/packages.config
samples/azure/shared-host/Version_5/HostWorker/HostWorker.csproj
samples/azure/shared-host/Version_5/HostWorker/packages.config
samples/azure/shared-host/Version_5/PackageAndDeploy.ps1
samples/azure/shared-host/Version_5/Receiver/Receiver.csproj
samples/azure/shared-host/Version_5/Receiver/packages.config
samples/azure/shared-host/Version_5/Sender/Sender.csproj
samples/azure/shared-host/Version_5/Sender/packages.config
samples/azure/shared-host/Version_5/Shared/Shared.csproj
samples/azure/shared-host/Version_5/Shared/packages.config
samples/azure/storage-queues/Version_5/Endpoint1/Endpoint1.csproj
samples/azure/storage-queues/Version_5/Endpoint1/packages.config
samples/azure/storage-queues/Version_5/Endpoint2/Endpoint2.csproj
samples/azure/storage-queues/Version_5/Endpoint2/packages.config
samples/azure/storage-queues/Version_5/Shared/Shared.csproj
samples/azure/storage-queues/Version_5/Shared/packages.config

Also fixes a PS script - creates a container if such is missing for uploaded endpoints. If container is missing (new machine) and PS script fails and sample is becoming useless.

Dependency updates for azure projects

---

Snippets/Snippets_6/Persistence/Custom/Usage.cs
nservicebus/persistence/authoring-custom.md

@timbussmann have a look.
I was thinking about adding comment that v6 is still under active development, but snippet will be shown as pre-release, so that should be good enough.

Add info and snippet for v6

---

nservicebus/sagas/index.md
nservicebus/upgrades/5to6.md

Doco for https://github.com/Particular/NServiceBus/pull/3007

Saga corr props must have a value

---

Snippets/Snippets_3/Encryption/Configuration/encryption.config.xml
Snippets/Snippets_4/Encryption/Configuration/encryption.config.xml
Snippets/Snippets_5/Encryption/Configuration/encryption.config.xml
nservicebus/messaging/headers.md
nservicebus/security/encryption.md
nservicebus/security/generating-encryption-keys.md
nservicebus/upgrades/encryption-key-identifiers.md
samples/encryption/basic-encryption/Version_3/Endpoint1/Endpoint1.csproj
samples/encryption/basic-encryption/Version_3/Endpoint1/packages.config
samples/encryption/basic-encryption/Version_3/Endpoint2/Endpoint2.csproj
samples/encryption/basic-encryption/Version_3/Endpoint2/packages.config
samples/encryption/basic-encryption/Version_3/Shared/ConfigureEncryption.cs
samples/encryption/basic-encryption/Version_3/Shared/Shared.csproj
samples/encryption/basic-encryption/Version_3/Shared/packages.config
samples/encryption/basic-encryption/Version_4/Endpoint1/Endpoint1.csproj
samples/encryption/basic-encryption/Version_4/Endpoint1/packages.config
samples/encryption/basic-encryption/Version_4/Endpoint2/Endpoint2.csproj
samples/encryption/basic-encryption/Version_4/Endpoint2/packages.config
samples/encryption/basic-encryption/Version_4/Shared/ConfigureEncryption.cs
samples/encryption/basic-encryption/Version_4/Shared/Shared.csproj
samples/encryption/basic-encryption/Version_4/Shared/packages.config
samples/encryption/basic-encryption/Version_5/Endpoint1/Endpoint1.csproj
samples/encryption/basic-encryption/Version_5/Endpoint1/packages.config
samples/encryption/basic-encryption/Version_5/Endpoint2/Endpoint2.csproj
samples/encryption/basic-encryption/Version_5/Endpoint2/packages.config
samples/encryption/basic-encryption/Version_5/Shared/ConfigureEncryption.cs
samples/encryption/basic-encryption/Version_5/Shared/Shared.csproj
samples/encryption/basic-encryption/Version_5/Shared/packages.config

- key identifier header
- key identifier configuration
- key format in ascii and base64 encoding
Connects to Particular/PlatformDevelopment#423

Added encryption service key identifier documentation.

---

Snippets/Snippets_5/Azure/CloudServices/HostingAndConfiguration.cs
Snippets/Snippets_5/Snippets_5.csproj
Snippets/Snippets_5/app.config
Snippets/Snippets_5/packages.config
nservicebus/azure/hosting-in-azure-cloud-services.md

@SimonCropp 3 snippets converted from hard-coded to c# snippets
Please review.

hard-coded code to snippets

---

nservicebus/upgrades/5to6.md

Mention the startup and shutdown sample

---

Snippets/Snippets_5/Azure/CloudServices/HostingAndConfiguration.cs
Snippets/Snippets_5/Snippets_5.csproj
Snippets/Snippets_5/packages.config

Removing NServiceBus.Hosting.Azure to avoid collision

---

Snippets/AzureSnippets/AzureSnippets.csproj
Snippets/AzureSnippets/CloudServices/HostingAndConfiguration.cs
Snippets/AzureSnippets/app.config
Snippets/AzureSnippets/packages.config
Snippets/NSBDoco.sln
Snippets/Snippets_5/Snippets_5.csproj

No more cheating.
@SimonCropp I've gone with the simple approach right now (marking version on the snippets). Once we have the next major, I'll keep an eye on this if it's worth doing something additional or not.
Thanks for suggestion.
PS: please review and merge if ok :stuck_out_tongue:

Moving azure hosting related snippets into its own project

---

nservicebus/messaging/transactions.md

Connects to https://github.com/Particular/NServiceBus/issues/2752
How is the wording here? I assumed we'd go with documenting current behavior and reference that previous versions behave differently in a note.
@indu @ramon

Update transactions document for NServiceBus/issues/2752

---

Snippets/Snippets_6/Snippets_6.csproj
Snippets/Snippets_6/UpgradeGuides/5to6/RawSend.cs
Snippets/Snippets_6/UpgradeGuides/5to6/Recoverable.cs
Snippets/Snippets_6/UpgradeGuides/5to6/TimeToBeReceived.cs
nservicebus/upgrades/5to6.md

Connects to https://github.com/Particular/NServiceBus/pull/2946
@andreasohlund can you start reviewing?
I hardcoded the snippets for `Recoverable` and `TimeToBeReceived` for right now. Going to change that as soon as #905 is solved.

Obsolete transport message

---

nservicebus/messaging/batched-dispatch.md
nservicebus/upgrades/5to6.md

Clariy batched dispatch

---

nservicebus/errors/automatic-retries.md

Doco on the max 24 h retry limit

---

samples/index.md

@SimonCropp does this sound good?

clarification on samples usage with Platform tools

---

Snippets/Snippets_6/Routing/NewOutingAPIs.cs
Snippets/Snippets_6/Snippets_6.csproj
nservicebus/messaging/message-owner.md
nservicebus/messaging/routing.md

Related to https://github.com/Particular/PlatformDevelopment/issues/133

Doco on new routing APIs

---

nservicebus/licensing/index.md

cc / @SimonCropp @indualagarsamy

Contact us link for expired support.

---

samples/web/owin-pass-through/Version_6/Endpoint/Endpoint.csproj
samples/web/owin-pass-through/Version_6/Endpoint/Program.cs
samples/web/owin-pass-through/Version_6/Endpoint/packages.config
samples/web/owin-pass-through/Version_6/Messages/Messages.csproj
samples/web/owin-pass-through/Version_6/Messages/packages.config
samples/web/owin-pass-through/Version_6/OwinPassThrough/OwinPassThrough.csproj
samples/web/owin-pass-through/Version_6/OwinPassThrough/OwinToBus.cs
samples/web/owin-pass-through/Version_6/OwinPassThrough/packages.config

Using BusContext for OwinPassThrough and `ConfigureAwait(false)` since this is middleware

---

nservicebus/upgrades/5to6.md

Relates to https://github.com/Particular/NServiceBus/pull/3080

Queue creation

---

Snippets/Snippets_6/Headers/OutgoingBehavior.cs
Snippets/Snippets_6/UpgradeGuides/5to6/OutgoingBehavior.cs
nservicebus/upgrades/5to6.md
samples/header-manipulation/Version_6/Sample/Pipeline/OutgoingHeaderBehavior.cs

needs to update nsb core reference to latest unstable as soon the header changes are merged.

[WIP] Set headers in v6

---

nservicebus/lifecycle/iwanttorunwhenbusstartsandstops.md

Lifecycle still contains suffix `Async`

---

nservicebus/sqlserver/operations-scripting.md

Instructs users on how to shift SqlTransport audit logs data into long term storage 
/cc @SimonCropp

How to shift SqlTransport audit log to long term storage

---

servicepulse/install-servicepulse-in-iis.md

fixes: https://github.com/Particular/ServicePulse/issues/230

Added woff2 config instructions

---

Snippets/Snippets_3/BasicUsageOfIBus.cs
Snippets/Snippets_4/BasicUsageOfIBus.cs
Snippets/Snippets_5/BasicUsageOfIBus.cs
Snippets/Snippets_6/BasicUsageOfIBus.cs
nservicebus/messaging/send-a-message.md

@Particular/tf-asyncawait plase review

Updated send-a-message page to V6

---

Snippets/Snippets_6/Extending/Features.cs
Snippets/Snippets_6/Features/FeatureConfiguration.cs
Snippets/Snippets_6/Features/MyFeature.cs
Snippets/Snippets_6/Snippets_6.csproj
nservicebus/pipeline/features.md

Relates to https://github.com/Particular/NServiceBus/pull/3137
@SzymonPobiega please update when you pulled the PR

Feature startup task

---

Snippets/Snippets_3/Handlers/ReplyingHandler.cs
Snippets/Snippets_3/Snippets_3.csproj
Snippets/Snippets_4/Handlers/ReplyingHandler.cs
Snippets/Snippets_4/Snippets_4.csproj
Snippets/Snippets_5/Handlers/ReplyingHandler.cs
Snippets/Snippets_5/Snippets_5.csproj
Snippets/Snippets_6/Handlers/ReplyingHandler.cs
Snippets/Snippets_6/Snippets_6.csproj
nservicebus/messaging/reply-to-a-message.md

updating snippets on this page: http://docs.particular.net/nservicebus/messaging/reply-to-a-message

Update Reply doco page

---

Snippets/Snippets_5/Snippets_5.csproj
Snippets/Snippets_5/UpgradeGuides/5to6/UpgradeMessageHandler.cs
Snippets/Snippets_6/Handlers/MyEvent.cs
Snippets/Snippets_6/Handlers/MyOtherMessage.cs
Snippets/Snippets_6/Snippets_6.csproj
Snippets/Snippets_6/UpgradeGuides/5to6/UpgradeMessageHandler.cs
nservicebus/upgrades/5to6.md

Added the upgrade guide section for Message Handlers.
I noticed that the signature also changed for Tim's implementation of the context.
Could I have some review on my text and snippets?
cc / @SeanFeldman @timbussmann @danielmarbach

[WIP] Message Handler upgrade section

---

samples/pipeline/multi-serializer/Version_6/Shared/DeserializeConnector.cs
samples/pipeline/multi-serializer/Version_6/Shared/SerializeConnector.cs

Relates to https://github.com/Particular/NServiceBus/pull/3222

Multi deserializer sample works again

---

nservicebus/azure/azure-servicebus-transport.md

Note what features are implemented natively

---

menu/menu.yaml
nservicebus/licensing/license-management.md
platform/installer/index.md
platform/installer/offline.md
platform/release-notes.md
serviceinsight/index.md

Cleaning up doc articles and removing SM references.

Removing ServiceMatrix references.

---

platform/getting-started-with-particular-service-platform.md
servicematrix/customizing-extending.md
servicematrix/getting-started-sagasfullduplex-2.0.md
servicematrix/getting-started-signalr-2.2.md
servicematrix/getting-started-with-nservicebus-using-servicematrix-2.0-fault-tolerance.md
servicematrix/getting-started-with-nservicebus-using-servicematrix-2.0-publish-subscribe.md
servicematrix/getting-started-with-servicematrix-2.0.md
servicematrix/getting-started.md
servicematrix/installing-servicematrix-2.0.md
servicematrix/licensing-servicematrix-v2.0.md
servicematrix/servicematrix-persistence.md
servicematrix/servicematrix-serviceinsight.md
servicematrix/sm-discontinued.include.md
servicematrix/troubleshooting-servicematrix-2.0.md

Relates to https://github.com/Particular/PlatformDevelopment/issues/454

WIP - Adding an include file and header for SM discontinued message

---

Snippets/Snippets_3/Profiles/behavior.cs
Snippets/Snippets_3/Profiles/configure_logging.cs
Snippets/Snippets_3/Profiles/defining_profile.cs
Snippets/Snippets_3/Profiles/dependent_profile.cs
Snippets/Snippets_3/Snippets_3.csproj
Snippets/Snippets_4/Profiles/configure_logging.cs
Snippets/Snippets_4/Profiles/dependent_profile.cs
Snippets/Snippets_4/Snippets_4.csproj
Snippets/Snippets_5/Profiles/behavior.cs
Snippets/Snippets_5/Profiles/configure_logging.cs
Snippets/Snippets_5/Profiles/dependent_profile.cs
Snippets/Snippets_5/Snippets_5.csproj
nservicebus/hosting/nservicebus-host/profiles.md

Also removed `Behavior requiring initialization to be complete` section, can't figure out the value in it

Updating host profiles doco to include snippets for different versions

---

Snippets/Snippets_5/Azure/Transports/AzureServiceBus/BrokeredMessageBodyConventionUsage.cs
Snippets/Snippets_5/Snippets_5.csproj
nservicebus/azure/azure-servicebus-transport.md

@Particular/azure please review

Adding doco/snippets for BrokeredMessageBodyConventionUsage

---

nservicebus/pipeline/customizing-v6.md

Adding description about audit and fault pipeline. 
Related to this pull request:
https://github.com/Particular/NServiceBus/pull/3240

Adding description about Audit and Fault Pipeline into v6 documentation

---

samples/saga/ravendb-custom-sagafinder/sample.md

@Particular/documentation @SimonCropp 
First change so went conservative and created a PR. There appeared to be a duplicate section at the end of this document so I just deleted it.

removed duplicate text

---

Snippets/Snippets_6/Routing/AutomaticSubscriptions/AutoSubscribeSettings.cs
nservicebus/messaging/publish-subscribe/controlling-what-is-subscribed.md
nservicebus/upgrades/5to6.md

Updates related to https://github.com/Particular/NServiceBus/pull/3284

Removed AutoSubscribePlainMessages as settings option

---

Snippets/Snippets_6/Snippets_6.csproj
Snippets/Snippets_6/UpgradeGuides/5to6/StartupInterface.cs
nservicebus/upgrades/5to6.md

- Added that IBus has been deprecated
- Moved MessageHandlers and IWantToRunWhenBusStartsAndStops to the top.
- Clarified the interface changes for  IWantToRunWhenBusStartsAndStops

UpgradeGuide v5-v6 Improvements

---

nservicebus/licensing/index.md
nservicebus/upgrades/release-policy.md
nservicebus/upgrades/support-policy.md

@SimonCropp I put the file in /upgrades , better ideas?
@udidahan FYI

Separated support policy from licensing

---

nservicebus/upgrades/support-policy.md

Better wording

---

Snippets/Snippets_6/Pipeline/CustomForkConnector.cs
Snippets/Snippets_6/Snippets_6.csproj
Snippets/Snippets_6/app.config
Snippets/Snippets_6/packages.config

fixes #1034 
@SimonCropp please review

fix broken custom ForkConnector sample

---

nservicebus/sagas/index.md

Connects to https://github.com/Particular/NServiceBus/issues/3291

Explain saga property types must match

---

Snippets/Snippets_3/UpgradeGuides/3to4/Upgrade.cs
Snippets/Snippets_4/UpgradeGuides/3to4/Upgrade.cs
Snippets/Snippets_4/UpgradeGuides/4to5/Upgrade.cs
Snippets/Snippets_5/UpgradeGuides/4to5/Upgrade.cs
Snippets/Snippets_6/UpgradeGuides/5to6/Upgrade.cs
nservicebus/upgrades/3to4.md
nservicebus/upgrades/4to5.md
nservicebus/upgrades/5to6.md
samples/azure/storage-queues/sample.md

@Particular/documentation review please

"impersonation" and WinIdName

---

nservicebus/messaging/messages-events-commands.md

Adding information about exceptions being thrown while violating the best practices
Relates to https://github.com/Particular/NServiceBus/issues/3267

Improving MessagingBestPractices/Validations exception messages

---

samples/azure/azure-service-bus/Version_6/AzureServiceBus.sln
samples/azure/azure-service-bus/Version_6/AzureServiceBus.sln.DotSettings
samples/azure/azure-service-bus/Version_6/Endpoint1/Endpoint1.csproj
samples/azure/azure-service-bus/Version_6/Endpoint1/Endpoint1.csproj.DotSettings
samples/azure/azure-service-bus/Version_6/Endpoint1/Message2Handler.cs
samples/azure/azure-service-bus/Version_6/Endpoint1/Program.cs
samples/azure/azure-service-bus/Version_6/Endpoint1/app.config
samples/azure/azure-service-bus/Version_6/Endpoint1/packages.config
samples/azure/azure-service-bus/Version_6/Endpoint2/Endpoint2.csproj
samples/azure/azure-service-bus/Version_6/Endpoint2/Endpoint2.csproj.DotSettings
samples/azure/azure-service-bus/Version_6/Endpoint2/Message1Handler.cs
samples/azure/azure-service-bus/Version_6/Endpoint2/Program.cs
samples/azure/azure-service-bus/Version_6/Endpoint2/app.config
samples/azure/azure-service-bus/Version_6/Endpoint2/packages.config
samples/azure/azure-service-bus/Version_6/Shared/Message1.cs
samples/azure/azure-service-bus/Version_6/Shared/Message2.cs
samples/azure/azure-service-bus/Version_6/Shared/Shared.csproj
samples/azure/azure-service-bus/Version_6/Shared/app.config
samples/azure/azure-service-bus/Version_6/Shared/packages.config

First ASB sample converted to use core v6 and transport v7 (`StandardTopology`)

Core v6 version of the sample

---

Snippets/Snippets_6/Routing/RoutingAPIs.cs
Snippets/Snippets_6/Routing/RoutingFile.xml
Snippets/Snippets_6/Routing/RoutingFile.xsd
Snippets/Snippets_6/Snippets_6.csproj
nservicebus/messaging/file-based-routing.md
nservicebus/messaging/routing.md

Adds doco on file-based routing and adds a missing section on static routes to the main routing doco.

File routing table

---

samples/azure/native-integration-asb/Version_6/MessageGenerator/MessageGenerator.csproj
samples/azure/native-integration-asb/Version_6/MessageGenerator/SerializedMessageGenerator.cs
samples/azure/native-integration-asb/Version_6/MessageGenerator/packages.config
samples/azure/native-integration-asb/Version_6/NativeIntegrationASB.sln
samples/azure/native-integration-asb/Version_6/NativeIntegrationASB.sln.DotSettings
samples/azure/native-integration-asb/Version_6/NativeSender/App.config
samples/azure/native-integration-asb/Version_6/NativeSender/NativeSender.csproj
samples/azure/native-integration-asb/Version_6/NativeSender/Program.cs
samples/azure/native-integration-asb/Version_6/NativeSender/packages.config
samples/azure/native-integration-asb/Version_6/Receiver/App.config
samples/azure/native-integration-asb/Version_6/Receiver/NativeMessageHandler.cs
samples/azure/native-integration-asb/Version_6/Receiver/Program.cs
samples/azure/native-integration-asb/Version_6/Receiver/Receiver.csproj
samples/azure/native-integration-asb/Version_6/Receiver/Receiver.csproj.DotSettings
samples/azure/native-integration-asb/Version_6/Receiver/packages.config
samples/azure/native-integration-asb/Version_6/Shared/NativeMessage.cs
samples/azure/native-integration-asb/Version_6/Shared/Shared.csproj
samples/azure/native-integration-asb/Version_6/Shared/packages.config

Second ASB sample converted to use core v6 and transport v7 (`StandardTopology`)

Core v6 version of the ASB native integration sample

---

nservicebus/scalability-and-ha/deploying-to-a-windows-failover-cluster.md
nservicebus/scalability-and-ha/distributor/index.md

Cleaned up some outdated and irrelevant configuration for the distributor.

Cleaned up distributor documentation.

---

nservicebus/upgrades/5to6.md

Connects to https://github.com/Particular/NServiceBus/pull/3335

Removed FeaturesReport

---

Snippets/Snippets_5/Snippets_5.csproj
Snippets/Snippets_5/UpgradeGuides/5to6/null.xml
Snippets/Snippets_6/Snippets_6.csproj
Snippets/Snippets_6/UpgradeGuides/5to6/null.xml
nservicebus/upgrades/5to6.md

I'm not 100% happy with the wording around the backwards compat

Add notes about XML Serialization changes

---

Snippets/Snippets_3/CustomChecks.cs
Snippets/Snippets_3/Snippets_3.csproj
Snippets/Snippets_3/packages.config
Snippets/Snippets_4/CustomChecks.cs
Snippets/Snippets_4/Snippets_4.csproj
Snippets/Snippets_4/packages.config
Snippets/Snippets_5/CustomChecks.cs
Snippets/Snippets_5/Snippets_5.csproj
Snippets/Snippets_5/packages.config
servicecontrol/plugins/custom-checks.md

Clarifies the CC documentation by adding API snippets.

Custom check API clarifications

---

nservicebus/upgrades/5to6.md

Connects to https://github.com/Particular/NServiceBus/pull/3339

RegisterEncryptionService builder access upgrade guide

---

nservicebus/msmq/connection-strings.md
nservicebus/operations/auditing.md

Connects to https://github.com/Particular/docs.particular.net/issues/1088

Add info about deadletter

---

Snippets/Snippets_6/UpgradeGuides/5to6/RawSend.cs

Connects to https://github.com/Particular/NServiceBus/pull/3357

Update raw sending

---

nservicebus/operations/performance-counters.md

WIP: Wording, possibly explain _why_ this is necessary

Explain Performance Counter User Group Installer

---

Snippets/Snippets_6/NonDurable/DefineExpress.cs
Snippets/Snippets_6/NonDurable/DisableDurable.cs
Snippets/Snippets_6/NonDurable/MessageWithExpress.cs
Snippets/Snippets_6/Snippets_6.csproj

Add Non Durable snippets for v6

---

Snippets/Snippets_6/Serialization/JsonSerialization.cs
Snippets/Snippets_6/Serialization/XmlSerialization.cs
Snippets/Snippets_6/Snippets_6.csproj

Added Serialization snippets for v6 core

---

Snippets/Snippets_3/InstallSomething.cs
Snippets/Snippets_3/Installers.cs
Snippets/Snippets_3/Snippets_3.csproj
Snippets/Snippets_4/InstallSomething.cs
Snippets/Snippets_4/Snippets_4.csproj
Snippets/Snippets_5/InstallSomething.cs
Snippets/Snippets_5/Snippets_5.csproj
Snippets/Snippets_6/InstallSomething.cs
Snippets/Snippets_6/Snippets_6.csproj
nservicebus/operations/installers.md

Installers page clean-up and update to v6

---

Snippets/Snippets_6/CustomChecks.cs
Snippets/Snippets_6/Snippets_6.csproj
Snippets/Snippets_6/packages.config
samples/custom-checks/monitoring3rdparty/Version_6/Sample/Monitor.cs
samples/custom-checks/monitoring3rdparty/Version_6/Sample/Sample.csproj
samples/custom-checks/monitoring3rdparty/Version_6/Sample/packages.config
servicecontrol/plugins/custom-checks.md

@SimonCropp Should I do a note in the upgrade guide as well? Does CustomCheck plugin upgrades also belong into the V5 to V6 upgrade guide?

Using new CustomChecks API

---

nservicebus/sqlserver/concurrency.md

Connects to: Particular/NServiceBus.SqlServer#100

Concurrency model in SqlServer v3

---

nservicebus/msmq/index.md

Relates to https://github.com/Particular/docs.particular.net/issues/917

MSMQ configuration

---

samples/sqltransport-nhpersistence/Version_2.2/Receiver/Program.cs
samples/sqltransport-nhpersistence/Version_2.2/Sender/Program.cs
samples/sqltransport-nhpersistence/Version_3.0/Messages/Messages.csproj.DotSettings
samples/sqltransport-nhpersistence/Version_3.0/Messages/OrderAccepted.cs
samples/sqltransport-nhpersistence/Version_3.0/Messages/OrderSubmitted.cs
samples/sqltransport-nhpersistence/Version_3.0/Messages/Shared.csproj
samples/sqltransport-nhpersistence/Version_3.0/Messages/packages.config
samples/sqltransport-nhpersistence/Version_3.0/Receiver/App.config
samples/sqltransport-nhpersistence/Version_3.0/Receiver/Order.cs
samples/sqltransport-nhpersistence/Version_3.0/Receiver/OrderLifecycleSaga.cs
samples/sqltransport-nhpersistence/Version_3.0/Receiver/OrderLifecycleSagaData.cs
samples/sqltransport-nhpersistence/Version_3.0/Receiver/OrderMap.cs
samples/sqltransport-nhpersistence/Version_3.0/Receiver/OrderSubmittedHandler.cs
samples/sqltransport-nhpersistence/Version_3.0/Receiver/OrderTimeout.cs
samples/sqltransport-nhpersistence/Version_3.0/Receiver/Program.cs
samples/sqltransport-nhpersistence/Version_3.0/Receiver/Receiver.csproj
samples/sqltransport-nhpersistence/Version_3.0/Receiver/Receiver.csproj.DotSettings
samples/sqltransport-nhpersistence/Version_3.0/Receiver/packages.config
samples/sqltransport-nhpersistence/Version_3.0/SQLNHibernate.sln
samples/sqltransport-nhpersistence/Version_3.0/SQLNHibernate.sln.DotSettings
samples/sqltransport-nhpersistence/Version_3.0/Sender/App.config
samples/sqltransport-nhpersistence/Version_3.0/Sender/OrderAcceptedHandler.cs
samples/sqltransport-nhpersistence/Version_3.0/Sender/Program.cs
samples/sqltransport-nhpersistence/Version_3.0/Sender/Sender.csproj
samples/sqltransport-nhpersistence/Version_3.0/Sender/Sender.csproj.DotSettings
samples/sqltransport-nhpersistence/Version_3.0/Sender/packages.config

Not ready to merge
Connects to https://github.com/Particular/NServiceBus.NHibernate/issues/138

WIP: SQLtransport Nhibernate Sample

---

nservicebus/serialization/binary.md
nservicebus/serialization/index.md
nservicebus/serialization/json.md
samples/serializers/binary/sample.md

+ add some deprecation notices

Adding deprecation notice of binary/bson serializers in v6

---

nservicebus/upgrades/5to6.md

related to https://github.com/Particular/NServiceBus/issues/2859

adjust upgrade guide about obsoleted throttling API

---

Snippets/Snippets_5/UpgradeGuides/5to6/Upgrade.config
Snippets/Snippets_6/UpgradeGuides/5to6/Upgrade.config
nservicebus/upgrades/5to6.md

Connects to https://github.com/Particular/NServiceBus.Gateway/pull/26

Gateway: replaced NumberOfWorkerThreads with MaxConcurrency

---

Snippets/Snippets_4/WCF/Expose_wcf.cs
Snippets/Snippets_5/WCF/Expose_wcf.cs

Handler exposed as WCF needs to do a Bus.Return()

---

Snippets/Snippets_6/RavenDB/ChangeResourceManagerID.cs
Snippets/Snippets_6/RavenDB/ConfiguringTransactionRecoveryStorage.cs
nservicebus/ravendb/index.md
nservicebus/ravendb/resourcemanagerid.md

Related to Particular/NServiceBus.RavenDB#136 and held in WIP until 3.1 is released.

[WIP] Change TransactionRecoveryStorage info based on tx settings fix

---

nservicebus/messaging/publish-subscribe/publish-handle-event.md

Related to Particular/NServiceBus#3399

IBusSession renamed to IMessageSession

---

Snippets/Snippets_6/Routing/RoutingFile.xml
menu/menu.yaml
nservicebus/scalability-and-ha/scale-out.md

This doco should link to lower-level scale out documents (e.g. distributor)

Top-level scale out doco

---

servicecontrol/creating-config-file.md
servicecontrol/logging.md

ServiceControl 1.9 changes

---

Snippets/Snippets_4/Forwarding/ConfigurationSource.cs
Snippets/Snippets_4/Forwarding/ConfigurationSourceUsage.cs
Snippets/Snippets_4/Forwarding/ForwardingConfig.xml
Snippets/Snippets_4/Forwarding/ProvideConfiguration.cs
Snippets/Snippets_4/Snippets_4.csproj
Snippets/Snippets_5/Forwarding/ConfigurationSource.cs
Snippets/Snippets_5/Forwarding/ConfigurationSourceUsage.cs
Snippets/Snippets_5/Forwarding/ForwardingConfig.xml
Snippets/Snippets_5/Forwarding/ProvideConfiguration.cs
Snippets/Snippets_5/Snippets_5.csproj
Snippets/Snippets_6/Forwarding/Usage.cs
Snippets/Snippets_6/Snippets_6.csproj
menu/menu.yaml
nservicebus/messaging/forwarding.md

Added code level API for configuring message forwarding in v6.
Added the xml and IProvideConfiguration options for message forwarding for v4 & v5.

Added doco for MessageForwarding feature.

---

samples/azure/polymorphic-events-asb/Version_6/PolyorphicEventsASB.sln
samples/azure/polymorphic-events-asb/Version_6/PolyorphicEventsASB.sln.DotSettings
samples/azure/polymorphic-events-asb/Version_6/Publisher/Program.cs
samples/azure/polymorphic-events-asb/Version_6/Publisher/Publisher.csproj
samples/azure/polymorphic-events-asb/Version_6/Publisher/Publisher.csproj.DotSettings
samples/azure/polymorphic-events-asb/Version_6/Publisher/app.config
samples/azure/polymorphic-events-asb/Version_6/Publisher/packages.config
samples/azure/polymorphic-events-asb/Version_6/Shared/Events/BaseEvent.cs
samples/azure/polymorphic-events-asb/Version_6/Shared/Events/DerivedEvent.cs
samples/azure/polymorphic-events-asb/Version_6/Shared/Shared.csproj
samples/azure/polymorphic-events-asb/Version_6/Shared/app.config
samples/azure/polymorphic-events-asb/Version_6/Shared/packages.config
samples/azure/polymorphic-events-asb/Version_6/Subscriber/BaseEventHandler.cs
samples/azure/polymorphic-events-asb/Version_6/Subscriber/DerivedEventHandler.cs
samples/azure/polymorphic-events-asb/Version_6/Subscriber/Program.cs
samples/azure/polymorphic-events-asb/Version_6/Subscriber/Subscriber.csproj
samples/azure/polymorphic-events-asb/Version_6/Subscriber/Subscriber.csproj.DotSettings
samples/azure/polymorphic-events-asb/Version_6/Subscriber/app.config
samples/azure/polymorphic-events-asb/Version_6/Subscriber/packages.config
samples/azure/polymorphic-events-asb/Version_6/publisher-from-sample.txt
samples/azure/polymorphic-events-asb/Version_6/publisher.txt
samples/azure/polymorphic-events-asb/Version_6/subscriber-from-sample.txt
samples/azure/polymorphic-events-asb/Version_6/subscriber.txt
samples/azure/polymorphic-events-asb/sample.md

* Sample converted to v6
* .md update to let users know that this workaround is not needed for the new topology
Note: I'm using lower core version since transport is not up-to-date with the latest core unstable

v6 version of Polyorphic Events sample with note for topology difference

---

servicecontrol/plugins/index.md

For a long time the examples and guidance was MSMQ specific.
Changed it to be MSMQ agnostic and in examples state that it's for MSMQ.

updated connecting to SC section

---

servicecontrol/creating-config-file.md

@SimonCropp is this what you wanted?

standardising version above & below

---

Snippets/Snippets_5/Snippets_5.csproj
Snippets/Snippets_5/UpgradeGuides/5to6/Callbacks.cs
Snippets/Snippets_6/Snippets_6.csproj
Snippets/Snippets_6/UpgradeGuides/5to6/Callbacks.cs
nservicebus/messaging/handling-responses-on-the-client-side.md
nservicebus/upgrades/5to6.md

* Added callbacks to the upgrade guide
* Documented callback routing in 6 and in previous version

Callback doco impromevents

---

Snippets/Snippets_3/Encryption/Configuration/ProvideConfiguration.cs
Snippets/Snippets_4/Encryption/Configuration/ProvideConfiguration.cs
Snippets/Snippets_5/Encryption/Configuration/FromCode.cs
Snippets/Snippets_5/Encryption/Configuration/ProvideConfiguration.cs
Snippets/Snippets_6/Encryption/Configuration/FromCode.cs
Snippets/Snippets_6/Encryption/Configuration/ProvideConfiguration.cs
samples/encryption/basic-encryption/Version_6/Shared/ConfigureEncryption.cs

Fixing samples and snippets to use features implemented in https://github.com/Particular/NServiceBus/pull/3063
This PR should not be merged before the actual change to the Core, as samples for v6 need to have updated NSB package to build

[WIP] Fixing samples and snippets for Encoding changes

---

samples/ravendb/evolving-sagadata/Version_6/EndpointV1/EndpointV1.csproj
samples/ravendb/evolving-sagadata/Version_6/EndpointV1/packages.config
samples/ravendb/evolving-sagadata/Version_6/EndpointV2/EndpointV2.csproj
samples/ravendb/evolving-sagadata/Version_6/EndpointV2/packages.config
samples/ravendb/evolving-sagadata/Version_6/EndpointV3/EndpointV3.csproj
samples/ravendb/evolving-sagadata/Version_6/EndpointV3/packages.config
samples/ravendb/simple/Version_6/Server/Server.csproj
samples/ravendb/simple/Version_6/Server/packages.config
samples/saga/ravendb-custom-sagafinder/Version_6/Sample/Sample.csproj
samples/saga/ravendb-custom-sagafinder/Version_6/Sample/packages.config

Raven works now so I figured I'd update the samples.

Update raven samples

---

Snippets/Snippets_6/Snippets_6.csproj
Snippets/Snippets_6/UpgradeGuides/5to6/MessageContext.cs
nservicebus/upgrades/5to6.md

Connects to #1227 
Closes #1227

Snippet for accessing message context information

---

servicecontrol/servicecontrol-in-practice.md

This is a modified version of https://github.com/Particular/docs.particular.net/pull/1098#event-564935177
Created a new branch to allow side-by-side comparison and discussion.
I moved from "Features" to "Capabilities and Plugins". I also modified the tone to try and remove opinion-sounding things. Structurally I tried to present the problem, propose an approach and finish with specific tips.
@Particular/docs-maintainers @petersgiles - take a look and see if you agree with this approach?

[WIP] Mike's take on ServiceControl in Practice

---

menu/menu.yaml
servicecontrol/servicecontrol-in-practice.md

Mike's guidance content. On the new branch for less messy git history.

Service control in practice

---

nservicebus/messaging/discard-old-messages.md
nservicebus/sqlserver/design.md

This is doco for Particular/NServiceBus.SqlServer#165.

SQL transport purges expired messages

---

Snippets/Snippets_6/Azure/Persistence/AzureStorage/AzurePersistence.config.xml
Snippets/Snippets_6/Azure/Persistence/AzureStorage/Usage.cs
Snippets/Snippets_6/Snippets_6.csproj
Snippets/Snippets_6/packages.config
nservicebus/azure/azure-storage-persistence.md

Connects to https://github.com/Particular/NServiceBus.AzureStoragePersistence/pull/34
Connects to https://github.com/Particular/NServiceBus.AzureStoragePersistence/pull/33
Updates the docs and the snippets to highlight the changes made in those PRs.

Updated docs to cater for Azure Storage Persistences v7 connection string changes

---

nservicebus/upgrades/sqlserver-2to3.md

Doco PR for Particular/NServiceBus.SqlServer#158.

Manually create index on SQL transport upgrade

---

Snippets/Snippets_5/UpgradeGuides/5to6/Upgrade.cs
Snippets/Snippets_6/UpgradeGuides/5to6/Upgrade.cs
nservicebus/upgrades/5to6.md

Add snippets for transactions configuration API

---

nservicebus/operations/auditing.md

Thanks to @agross for mentioning this!

Fixing registry hives for auditing

---

nservicebus/azure/azure-servicebus-transport.md
nservicebus/azure/azure-storage-queues-transport.md
nservicebus/azure/transactions.md
nservicebus/messaging/transactions.md
nservicebus/sqlserver/design.md

Connects to https://github.com/Particular/docs.particular.net/issues/1176.

Transport transactions matrix and description

---

Snippets/Snippets_6/Persistence/NHibernate/UpgradeGuides/6to7/AccessingSession.cs
Snippets/Snippets_6/Snippets_6.csproj
nservicebus/upgrades/nhibernate-6to7.md

Related to the changes in https://github.com/Particular/NServiceBus.NHibernate/pull/175 and more generally new version of NServiceBus.NHibernate.
@Particular/persistence-maintainers please review and check if we need to cover anything else.

Upgrade guide document for NHibernate 6 to 7

---

nservicebus/containers/index.md
nservicebus/containers/injecting-ibus.md
nservicebus/gateway/index.md
nservicebus/hosting/publishing-from-web-applications.md
nservicebus/messaging/reply-to-a-message.md
nservicebus/sagas/reply-replaytooriginator-differences.md

Connects to #1237
Blocked by definitions of Endpoint and Endpoint Instance requested in: #1278

Do a search and QA on usages of `IBus` in Doco

---

samples/hosting/multi-hosting/sample.md
samples/hosting/windows-service/sample.md
samples/web/asp-mvc-application/sample.md
samples/web/asp-mvc-injecting-bus/sample.md
samples/web/asp-web-application/sample.md
samples/web/owin-pass-through/sample.md

Do a search and QA on usages of `IBus` in Samples

---

nservicebus/concept-overview.md
nservicebus/endpoint/index.md
nservicebus/endpoint/specify-input-queue-name.md
nservicebus/ravendb/index.md

PR created so that @mikeminutillo can help :stuck_out_tongue: . I made you an contributor.
Connects to #1237
Initiated by comment in to following PR: #1278

Adding concept description of Endpoint and Endpoint Instance

---

nservicebus/sqlserver/configuration.md

Connects to: https://github.com/Particular/NServiceBus.SqlServer/issues/136

Added note about sql connection pooling

---

nservicebus/errors/automatic-retries.md

FLR does not work without transport transactions

---

Snippets/Snippets_6/Hosting.cs

Connects to https://github.com/Particular/NServiceBus/pull/3623

Removed Endpoint.Prepare

---

samples/sqltransport/native-integration/Version_2/Receiver/Program.cs
samples/sqltransport/native-integration/Version_3/Receiver/PlaceOrderHandler.cs
samples/sqltransport/native-integration/Version_3/Receiver/Program.cs

@Particular/docs-maintainers please review & merge

Enabling installers in sql transport sample - native integration

---

nservicebus/scalability-and-ha/deploying-to-a-windows-failover-cluster.md
nservicebus/scalability-and-ha/distributor/index.md
samples/scaleout/distributor/sample.md

Resolve: https://github.com/Particular/NServiceBus/issues/3429 

Adding information about `MasterNodeConfig` being obsoleted.

---

Snippets/Snippets_5/Snippets_5.csproj
Snippets/Snippets_5/Transports/SqlServer_2/ConnectionStrings.cs
Snippets/Snippets_5/Transports/SqlServer_2/MultiDb.cs
Snippets/Snippets_5/Transports/SqlServer_2/UpgradeGuides/MultiInstance.cs
Snippets/Snippets_6/Snippets_6.csproj
Snippets/Snippets_6/Transports/SqlServer_3/ConnectionStrings.cs
Snippets/Snippets_6/Transports/SqlServer_3/MultiDb.cs
Snippets/Snippets_6/Transports/SqlServer_3/UpgradeGuides/MultiInstance.cs
nservicebus/sqlserver/configuration.md
nservicebus/sqlserver/deployment-options.md
nservicebus/upgrades/sqlserver-2to3.md

Connects to https://github.com/Particular/NServiceBus.SqlServer/issues/139

SQL Server multi-instance upgrade guide

---

servicecontrol/creating-config-file.md
servicecontrol/installation-powershell.md
servicecontrol/installation-silent.md
servicecontrol/installation.md

Documents the changes in https://github.com/Particular/ServiceControl/pull/693
This should be merged when SC 1.12 ships

ServiceControl - Changes for SC issue 693

---

nservicebus/upgrades/5to6.md

Related to https://github.com/Particular/NServiceBus/issues/3256

Adding PipelineExecutor paragraph to the upgrade guide

---

nservicebus/upgrades/5to6.md

Updated notifications section

---

servicecontrol/installation.md

It is difficult to see the warning the way it was originally set up. Needs to be more outstanding.
@Particular/servicecontrol-maintainers please review

Marking warning as such

---

Snippets/Snippets_5/EndpointName/EndpointMapping.config.xml
Snippets/Snippets_5/EndpointName/Usage.cs
Snippets/Snippets_5/Snippets_5.csproj
Snippets/Snippets_6/EndpointName/Usage.cs
nservicebus/endpoints/specify-endpoint-name.md

Related to GG question: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/particularsoftware/FLMs0sOGPtU/0b94MZS9AQAJ

Extended the specify endpoint name/input queue page

---

nservicebus/errors/automatic-retries.md
nservicebus/errors/index.md

Connects to: https://github.com/Particular/NServiceBus/issues/3032

Explaining SLR and Error behaviros with transport transactions disabled

---

nservicebus/hosting/critical-errors.md

Connects to https://github.com/Particular/NServiceBus/issues/3342
Updating Critical Errors doc to resolve moving interface from core to host and renaming.

IWantToRunWhenEndpointStartsAndStops - Critical Errors

---

nservicebus/messaging/transactions.md
nservicebus/msmq/transportconfig.md
nservicebus/sqlserver/design.md

Resolves https://github.com/Particular/docs.particular.net/issues/1184.

Clarify MSMQ transport transaction options

---

nservicebus/hosting/nservicebus-host/index.md
nservicebus/hosting/windows-service.md

Connects to https://github.com/Particular/NServiceBus/issues/3342
This PR handles changes to lifecycle and hosting documents only. See #1373 for changes to snippets and upgrade guide.

Update references to IWantToRunWhenBusStartsAndStops in hosting docs

---

Snippets/Rabbit_3/UpgradeGuides/3to4/Upgrade.cs
Snippets/Rabbit_4/UpgradeGuides/3to4/Upgrade.cs
nservicebus/upgrades/rabbitmq-3to4.md

[WIP] Working on upgrade guide for Rabbit

---

Snippets/Snippets_6/Snippets_6.csproj
Snippets/Snippets_6/packages.config
nservicebus/upgrades/5to6.md
nservicebus/upgrades/5to6removePShelpers.include.md
nservicebus/upgrades/host-6to7.md
samples/hosting/nservicebus-host/Version_6/Sample/Sample.csproj
samples/hosting/nservicebus-host/Version_6/Sample/packages.config
samples/logging/hostcustom/Version_6/Sample/Sample.csproj
samples/logging/hostcustom/Version_6/Sample/packages.config
samples/logging/hostdefault/Version_6/Sample/Sample.csproj
samples/logging/hostdefault/Version_6/Sample/packages.config
samples/logging/hostprofiles/Version_6/Sample/Sample.csproj
samples/logging/hostprofiles/Version_6/Sample/packages.config

Connects to https://github.com/Particular/NServiceBus.Host/issues/68

Update host doco

---

Snippets/Snippets_6/Snippets_6.csproj
Snippets/Snippets_6/UpgradeGuides/5to6/Callbacks.cs
Snippets/Snippets_6/UpgradeGuides/5to6/IConfigureComponentsNotInjected.cs
nservicebus/upgrades/5to6.md

Connects to https://github.com/Particular/PlatformDevelopment/issues/706

Upgrade guide for iconfigurecomponents no longer registered in DI

---

servicecontrol/creating-config-file.md
servicecontrol/errorlog-auditlog-behavior.md
servicecontrol/how-purge-expired-data.md
servicecontrol/installation-powershell.md
servicecontrol/installation-silent.md

Connects to https://github.com/Particular/PlatformDevelopment/issues/667.
This PR has the reuired updates to the ServiceControl doco as part of the changes in v1.13.0.
The changes are documented in:
- https://github.com/Particular/ServiceControl/pull/694

Updates to ServiceControl for v1.13.0

---

Snippets/Snippets_6/Snippets_6.csproj
Snippets/Snippets_6/packages.config

Connects to https://github.com/Particular/PlatformDevelopment/issues/706
@Particular/docs-maintainers Please verify and merge

Using alpha package of gateway and callbacks

---

nservicebus/messaging/transactions.md
nservicebus/rabbitmq/configuration-api.md

Connects to #1185 
Once this is merged, it will also wrap up #1176.

Add RabbitMQ transaction mode details

---

samples/nhibernate/custom-mappings/Version_6/Sample.Attributes/Sample.Attributes.csproj
samples/nhibernate/custom-mappings/Version_6/Sample.Attributes/packages.config
samples/nhibernate/custom-mappings/Version_6/Sample.Default/Sample.Default.csproj
samples/nhibernate/custom-mappings/Version_6/Sample.Default/packages.config
samples/nhibernate/custom-mappings/Version_6/Sample.Fluent/Sample.Fluent.csproj
samples/nhibernate/custom-mappings/Version_6/Sample.Fluent/packages.config
samples/nhibernate/custom-mappings/Version_6/Sample.Loquacious/Sample.Loquacious.csproj
samples/nhibernate/custom-mappings/Version_6/Sample.Loquacious/packages.config
samples/nhibernate/custom-mappings/Version_6/Sample.XmlMapping/Sample.XmlMapping.csproj
samples/nhibernate/custom-mappings/Version_6/Sample.XmlMapping/packages.config
samples/outbox/sqltransport-nhpersistence-ef/Version_3/Receiver/Receiver.csproj
samples/outbox/sqltransport-nhpersistence-ef/Version_3/Receiver/packages.config
samples/outbox/sqltransport-nhpersistence-ef/Version_3/Sender/Sender.csproj
samples/outbox/sqltransport-nhpersistence-ef/Version_3/Sender/packages.config
samples/outbox/sqltransport-nhpersistence/Version_3/Receiver/Receiver.csproj
samples/outbox/sqltransport-nhpersistence/Version_3/Receiver/packages.config
samples/outbox/sqltransport-nhpersistence/Version_3/Sender/Sender.csproj
samples/outbox/sqltransport-nhpersistence/Version_3/Sender/packages.config
samples/sqltransport-nhpersistence/Version_3/Receiver/Program.cs
samples/sqltransport-nhpersistence/Version_3/Receiver/Receiver.csproj
samples/sqltransport-nhpersistence/Version_3/Receiver/packages.config
samples/sqltransport-nhpersistence/Version_3/Sender/Sender.csproj
samples/sqltransport-nhpersistence/Version_3/Sender/packages.config
samples/sqltransport/store-and-forward/Version_3/Receiver/Program.cs
samples/sqltransport/store-and-forward/Version_3/Receiver/Receiver.csproj
samples/sqltransport/store-and-forward/Version_3/Receiver/packages.config
samples/sqltransport/store-and-forward/Version_3/Sender/Program.cs
samples/sqltransport/store-and-forward/Version_3/Sender/Sender.csproj
samples/sqltransport/store-and-forward/Version_3/Sender/packages.config

Connects to https://github.com/Particular/PlatformDevelopment/issues/706

Update NH samples to beta

---

Snippets/Snippets_6/Snippets_6.csproj
Snippets/Snippets_6/packages.config
samples/hosting/nservicebus-host/Version_6/Sample/Sample.csproj
samples/hosting/nservicebus-host/Version_6/Sample/packages.config
samples/logging/hostcustom/Version_6/Sample/Sample.csproj
samples/logging/hostcustom/Version_6/Sample/packages.config
samples/logging/hostdefault/Version_6/Sample/Sample.csproj
samples/logging/hostdefault/Version_6/Sample/packages.config
samples/logging/hostprofiles/Version_6/Sample/Sample.csproj
samples/logging/hostprofiles/Version_6/Sample/packages.config

https://github.com/Particular/PlatformDevelopment/issues/706
I did a manual compare against develop and found out that two crucial PRs haven't been included on the release branch. Therefore this update
@Particular/docs-maintainers please review and merge

Update to host beta 2

---

Snippets/Castle/Castle_6/Castle_6.csproj
Snippets/Castle/Castle_6/packages.config
samples/containers/castle/Version_6/Sample/Sample.csproj
samples/containers/castle/Version_6/Sample/packages.config

Connects to https://github.com/Particular/PlatformDevelopment/issues/706

Update to NServiceBus.CastleWindsor beta 2

---

Snippets/StructureMap/StructureMap_6/StructureMap_6.csproj
Snippets/StructureMap/StructureMap_6/packages.config
samples/containers/structuremap/Version_6/Sample/Sample.csproj
samples/containers/structuremap/Version_6/Sample/packages.config

@Particular/docs-maintainers please review and merge

Structure map beta 1

---

Snippets/Unity/Unity_7/Unity_7.csproj
Snippets/Unity/Unity_7/packages.config
samples/containers/unity/Version_6/Sample/Sample.csproj
samples/containers/unity/Version_6/Sample/packages.config

@Particular/docs-maintainers you know the drill ;)

Unity beta 1

---

Snippets/ASQ/ASQ_7/Usage.cs
nservicebus/azure-storage-queues/configuration.md
nservicebus/azure-storage-queues/index.md

Connects to https://github.com/Particular/docs.particular.net/issues/1277

Securing the connection string

---

menu/menu.yaml

Forgot to add the satellites doco as an item in the menu as part of the PR: https://github.com/Particular/docs.particular.net/pull/1396
@Particular/docs-maintainers - please review and merge.

Added the satellite doco to the menu.

---

nservicebus/messaging/file-based-routing.md

removing the word 'introduced' in the opening statement, it does not read well.

removing the word 'introduced'

---

menu/menu.yaml

Azure upgrade guides menu update

---

menu/menu.yaml
nservicebus/azure-service-bus/transaction-support.md
nservicebus/azure-storage-queues/transaction-support.md
nservicebus/azure/transactions.md
nservicebus/messaging/transactions.md
nservicebus/msmq/transportconfig.md
nservicebus/rabbitmq/configuration-api.md
nservicebus/sqlserver/design.md

* Aligning the names used for describing Transport Transaction modes
* Ensuring that relevant pages has Tag: transactions
* Adding header reviewed
@Particular/docs-maintainers please review and merge

Small adjustments in Transport Transaction Modes

---

nservicebus/upgrades/5to6.md

Upgrade guide for the obsoleted configure class

---

menu/menu.yaml
nservicebus/errors/automatic-retries.md
nservicebus/errors/index.md
nservicebus/msmq/transportconfig.md
nservicebus/rabbitmq/configuration-api.md
nservicebus/sqlserver/configuration.md
nservicebus/sqlserver/design.md
nservicebus/transports/transactions.md
nservicebus/upgrades/3to4.md
nservicebus/upgrades/5to6.md
nservicebus/upgrades/sqlserver-2to3.md

Is the redirect configured correctly?

Moving transport transactions page and adding it to menu

---

nservicebus/upgrades/asq-6to7.md

Connects to: https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/87

Making a note about API cleanup in the ASQ Upgrade Guide

---

nservicebus/azure-storage-queues/index.md

* Removed pricing details which seem to be out of date
* The intro started with some text about distributed transactions, seems weird to have DTC as a starting point to introduce ASQ.
* Moved Advantages/Disadvantages up and removed the bullet-point formating

Restructure ASQ overview

---

Snippets/ASB/ASB_7/Usage.cs
menu/menu.yaml
nservicebus/azure-service-bus/message-lock-renewal.md

Connect to https://github.com/Particular/PlatformDevelopment/issues/718
Describe what message lock renewal feature is and how to use it. (issue #1263)

[WIP] ASB message lock renewal

---

Snippets/ASQ/ASQ_7/Usage.cs
nservicebus/azure-storage-queues/configuration.md

Connects to https://github.com/Particular/PlatformDevelopment/issues/723
Addresses SHA1 MD5 configuration.

ASQ SHA1-MD5

---

menu/menu.yaml
nservicebus/azure-storage-persistence/azure-storage-performance-tuning.include.md
nservicebus/azure-storage-persistence/performance-tuning.md
nservicebus/azure-storage-queues/configuration.md
nservicebus/azure-storage-queues/performance-tuning.md
nservicebus/azure/azure-storage-performance-tuning.include.md

Connects to Particular/PlatformDevelopment#723
adds a performance tuning page for ASQ transport.
Since ASQ transport and persistence share a lot of tuning settings I created an include file for the shared settings.
todo: verify impact of ServicePointManager.CheckCertificateRevocationList

Performance tuning page for ASQ transport

---

README.md

Capture how generated images could be maintained.

lucidchart update

---

nservicebus/azure-storage-queues/configuration.md

ASQ configuration changes including:
* styles
* change default values for `ConnectionString`
* add version for `DegreeOfReceiveParallelism`
cc: @Particular/docs-maintainers

ASQ configuration changes

---

Snippets/ASQ/ASQ_7/ASQ_7.csproj
Snippets/ASQ/ASQ_7/UpgradeGuides/6to7/Upgrade.cs
Snippets/ASQ/ASQ_7/Usage.cs
nservicebus/azure-storage-queues/configuration.md
nservicebus/upgrades/asq-6to7.md

Connects to https://github.com/Particular/PlatformDevelopment/issues/723

ASQ upgrade guide extension

---

Snippets/ASB/ASB_7/Usage.cs
menu/menu.yaml
nservicebus/azure-service-bus/retries.md
nservicebus/errors/automatic-retries.md

Describes the ASB retry behavior

ASB retry behaviour

---

Snippets/ASQ/ASQ_7/ASQ_7.csproj
Snippets/ASQ/ASQ_7/packages.config
samples/azure/shared-host/CloudServicesHost_7/Receiver/Receiver.csproj
samples/azure/shared-host/CloudServicesHost_7/Receiver/packages.config
samples/azure/shared-host/CloudServicesHost_7/Sender/Sender.csproj
samples/azure/shared-host/CloudServicesHost_7/Sender/packages.config
samples/azure/storage-queues/ASQ_7/Endpoint1/Endpoint1.csproj
samples/azure/storage-queues/ASQ_7/Endpoint1/packages.config
samples/azure/storage-queues/ASQ_7/Endpoint2/Endpoint2.csproj
samples/azure/storage-queues/ASQ_7/Endpoint2/packages.config

@Particular/docs-maintainers please review and merge

Updating ASQ package to 7.0.0-alpha0162

---

nservicebus/azure-service-bus/batching.md

Connect to https://github.com/Particular/PlatformDevelopment/issues/718
(implements https://github.com/Particular/docs.particular.net/issues/1264)

ASB Batching

---

Snippets/Rabbit/Rabbit_4/Rabbit_4.csproj
Snippets/Rabbit/Rabbit_4/Usage.cs
Snippets/Rabbit/Rabbit_4/packages.config
samples/rabbitmq/native-integration/Rabbit_4/Receiver/Receiver.csproj
samples/rabbitmq/native-integration/Rabbit_4/Receiver/packages.config
samples/rabbitmq/simple/Rabbit_4/Sample/Sample.csproj
samples/rabbitmq/simple/Rabbit_4/Sample/packages.config

This should make sure everything builds correctly after the changes made in https://github.com/Particular/NServiceBus.RabbitMQ/pull/143.
Connects to https://github.com/Particular/PlatformDevelopment/issues/719

Update Rabbit samples and snippets to react to namespace changes

---

Snippets/Core/Core_5/Core_5.csproj
Snippets/Core/Core_5/packages.config
Snippets/Raven/Raven_2/Raven_2.csproj
Snippets/Raven/Raven_2/packages.config
Snippets/Raven/Raven_3/Raven_3.csproj
Snippets/Raven/Raven_3/packages.config
samples/ravendb/evolving-sagadata/Raven_3/EndpointV1/EndpointV1.csproj
samples/ravendb/evolving-sagadata/Raven_3/EndpointV1/packages.config
samples/ravendb/evolving-sagadata/Raven_3/EndpointV2/EndpointV2.csproj
samples/ravendb/evolving-sagadata/Raven_3/EndpointV2/packages.config
samples/ravendb/evolving-sagadata/Raven_3/EndpointV3/EndpointV3.csproj
samples/ravendb/evolving-sagadata/Raven_3/EndpointV3/packages.config
samples/ravendb/simple/Raven_3/Server/Server.csproj
samples/ravendb/simple/Raven_3/Server/packages.config
samples/saga/ravendb-custom-sagafinder/Raven_3/Sample/Sample.csproj
samples/saga/ravendb-custom-sagafinder/Raven_3/Sample/packages.config

Related to Particular/PlatformDevelopment#789

Update Raven refs from 3.0.8 to 3.0.9

---

Snippets/ASP/ASP_1/ASP_1.csproj
Snippets/ASP/ASP_1/Usage.cs
Snippets/ASP/ASP_1/packages.config
components/components.yaml
components/nugetAlias.txt
nservicebus/upgrades/asp-saga-deduplication.md
samples/azure/shared-host/CloudServicesHost_6/AzureSharedHosting.sln
samples/azure/shared-host/CloudServicesHost_6/HostCloudService/HostCloudService.ccproj
samples/azure/shared-host/CloudServicesHost_6/HostWorker/HostWorker.csproj
samples/azure/shared-host/CloudServicesHost_6/HostWorker/app.config
samples/azure/shared-host/CloudServicesHost_7/AzureSharedHosting.sln
samples/azure/shared-host/CloudServicesHost_7/HostCloudService/HostCloudService.ccproj
samples/azure/shared-host/CloudServicesHost_7/HostWorker/HostWorker.csproj
samples/azure/shared-host/CloudServicesHost_7/HostWorker/app.config
samples/azure/shared-host/CloudServicesHost_7/Receiver/Receiver.csproj
samples/azure/shared-host/CloudServicesHost_7/Receiver/packages.config
samples/azure/shared-host/CloudServicesHost_7/Sender/Sender.csproj
samples/azure/shared-host/CloudServicesHost_7/Sender/packages.config
samples/azure/storage-persistence/ASP_1/Server/Server.csproj
samples/azure/storage-persistence/ASP_1/Server/app.config
samples/azure/storage-persistence/ASP_1/Server/packages.config

Also updated the Azure shared host sample to use Azure SDK 2.9

Update snippets and samples to use Azure Storage Persistence v1 beta

---

Snippets/Gateway/Gateway_2/Gateway_2.csproj
Snippets/Gateway/Gateway_2/packages.config
samples/gateway/Gateway_2/Headquarters/Headquarters.csproj
samples/gateway/Gateway_2/Headquarters/packages.config
samples/gateway/Gateway_2/RemoteSite/RemoteSite.csproj
samples/gateway/Gateway_2/RemoteSite/packages.config

Connects to https://github.com/particular/platformdevelopment/issues/757

Update Gateway Package to Beta1

---

Snippets/Core/Core_6/Core_6.csproj
Snippets/Core/Core_6/packages.config
Snippets/Raven/Raven_4/Raven_4.csproj
Snippets/Raven/Raven_4/packages.config
samples/ravendb/evolving-sagadata/Raven_4/EndpointV1/EndpointV1.csproj
samples/ravendb/evolving-sagadata/Raven_4/EndpointV1/packages.config
samples/ravendb/evolving-sagadata/Raven_4/EndpointV2/EndpointV2.csproj
samples/ravendb/evolving-sagadata/Raven_4/EndpointV2/packages.config
samples/ravendb/evolving-sagadata/Raven_4/EndpointV3/EndpointV3.csproj
samples/ravendb/evolving-sagadata/Raven_4/EndpointV3/packages.config
samples/ravendb/simple/Raven_4/Server/Server.csproj
samples/ravendb/simple/Raven_4/Server/packages.config
samples/saga/ravendb-custom-sagafinder/Raven_4/Sample/Sample.csproj
samples/saga/ravendb-custom-sagafinder/Raven_4/Sample/packages.config

Connects to Particular/PlatformDevelopment#733

Update refs to NServiceBus.RavenDB nuget

---

nservicebus/azure-service-bus/asb-credential-warning.include.md

Do we really need to have a warning in the upgrade guide @SimonCropp ? 
I can see a warning in the general doco, but the upgrade guide.

Original message was not clear

---

nservicebus/azure-storage-queues/faq.md
nservicebus/azure-storage-queues/index.md
nservicebus/azure-storage-queues/performance-tuning.md
nservicebus/azure-storage-queues/transaction-support.md

Adding 2 tags to each relevant documentation page: 
* ASQ
* Azure Storage Queues

Adding ASQ tags to related doco

---

Snippets/Rabbit/Rabbit_4/UpgradeGuides/3to4/Upgrade.cs
Snippets/Rabbit/Rabbit_4/Usage.cs
Snippets/Rabbit/Rabbit_4/rabbitmqconnection.config.xml
nservicebus/rabbitmq/configuration-api.md
nservicebus/rabbitmq/connection-strings.md
nservicebus/upgrades/rabbitmq-3to4.md

@bording @johnsimons feel free to contribute on configuration api and upgrade guide
Connects to https://github.com/Particular/PlatformDevelopment/issues/719

Making overall change to Rabbit configuration-api and upgrade guide

---

nservicebus/ravendb/installation.md
nservicebus/upgrades/ravendb-3to4.md

Fixes #1474 
Will remove WIP once final namespace move is complete and either 1) I'm sure that namespaces in samples don't need to be updated, or 2) I have appended a commit to update the samples to match.

RavenDB namespace changes in V4

---

Snippets/Rabbit/Rabbit_3/Usage.cs
Snippets/Rabbit/Rabbit_3/rabbitmqconnection.config.xml
nservicebus/rabbitmq/configuration-api.md

This links to https://github.com/Particular/NServiceBus.RabbitMQ/pull/147

[WIP] Documenting support for TLS in Rabbit v3.2

---

servicecontrol/contracts.md

Replacement for https://github.com/Particular/docs.particular.net/pull/1475

Add warning about duplicated SC notification events

---

Snippets/ASB/ASB_7/ASB_7.csproj
Snippets/ASB/ASB_7/packages.config
samples/azure/azure-service-bus/ASB_7/Endpoint1/Endpoint1.csproj
samples/azure/azure-service-bus/ASB_7/Endpoint1/packages.config
samples/azure/azure-service-bus/ASB_7/Endpoint2/Endpoint2.csproj
samples/azure/azure-service-bus/ASB_7/Endpoint2/packages.config
samples/azure/azure-service-bus/ASB_7/Shared/Shared.csproj
samples/azure/azure-service-bus/ASB_7/Shared/packages.config
samples/azure/custom-sanitization/ASB_7/Publisher/Publisher.csproj
samples/azure/custom-sanitization/ASB_7/Publisher/packages.config
samples/azure/custom-sanitization/ASB_7/Subscriber/Sha1Sanitization.cs
samples/azure/custom-sanitization/ASB_7/Subscriber/Subscriber.csproj
samples/azure/custom-sanitization/ASB_7/Subscriber/packages.config
samples/azure/native-integration-asb/ASB_7/Receiver/Receiver.csproj
samples/azure/native-integration-asb/ASB_7/Receiver/packages.config
samples/azure/polymorphic-events-asb/ASB_7/Publisher/Publisher.csproj
samples/azure/polymorphic-events-asb/ASB_7/Publisher/packages.config
samples/azure/polymorphic-events-asb/ASB_7/Subscriber/Subscriber.csproj
samples/azure/polymorphic-events-asb/ASB_7/Subscriber/packages.config

* nuget package update
* code update (removing `EntityType.EventHub`)

Update code to asb 7 beta3

---

Snippets/Rabbit/Rabbit_3/UpgradeGuides/3to4/Upgrade.cs
Snippets/Rabbit/Rabbit_3/UpgradeGuides/3to4/rabbitmqconnection.config.xml
Snippets/Rabbit/Rabbit_4/UpgradeGuides/3to4/Upgrade.cs
nservicebus/upgrades/rabbitmq-3to4.md

Went ahead and pushed up the work I've got so far, though it's not finished yet.

Rabbit4 upgrade guide changes

---

menu/menu.yaml

restructured menu.yaml for asb

---

nservicebus/azure-service-bus/topologies/index.md

changing comparison table

---

samples/azure/storage-persistence/ASP_1/Server/Program.cs
samples/azure/storage-persistence/ASP_1/Server/app.config

Connects to https://github.com/Particular/PlatformDevelopment/issues/729

ASP: bumping up samples to the code first configuration

---

nservicebus/azure-service-bus/addressing-logic.md
nservicebus/azure-service-bus/configuration/full.md
nservicebus/azure-service-bus/configuration/index.md
nservicebus/azure-service-bus/native-integration.md
nservicebus/azure-service-bus/publisher-names-configuration.md
nservicebus/azure-service-bus/transaction-support.md
nservicebus/azure/azure-compared-to-msmq.include.md

Connects to https://github.com/Particular/PlatformDevelopment/issues/718
* missing space
* code wrap for special characters (consistency with other docs)
* changes to the sanitization that are not reflected here

[WIP] A pass of cleanups for ASB

---

menu/menu.yaml

Remove Transports section from menu

---

Snippets/ASB/ASB_7/ASB_7.csproj
Snippets/ASB/ASB_7/packages.config
samples/azure/azure-service-bus/ASB_7/Endpoint1/Endpoint1.csproj
samples/azure/azure-service-bus/ASB_7/Endpoint1/packages.config
samples/azure/azure-service-bus/ASB_7/Endpoint2/Endpoint2.csproj
samples/azure/azure-service-bus/ASB_7/Endpoint2/packages.config
samples/azure/azure-service-bus/ASB_7/Shared/Shared.csproj
samples/azure/azure-service-bus/ASB_7/Shared/packages.config
samples/azure/custom-sanitization/ASB_7/Publisher/Publisher.csproj
samples/azure/custom-sanitization/ASB_7/Publisher/packages.config
samples/azure/custom-sanitization/ASB_7/Subscriber/Subscriber.csproj
samples/azure/custom-sanitization/ASB_7/Subscriber/packages.config
samples/azure/native-integration-asb/ASB_7/Receiver/Receiver.csproj
samples/azure/native-integration-asb/ASB_7/Receiver/packages.config
samples/azure/polymorphic-events-asb/ASB_7/Publisher/Publisher.csproj
samples/azure/polymorphic-events-asb/ASB_7/Publisher/packages.config
samples/azure/polymorphic-events-asb/ASB_7/Subscriber/Subscriber.csproj
samples/azure/polymorphic-events-asb/ASB_7/Subscriber/packages.config

ASB beta4 upgrade

---

samples/azure/shared-host/CloudServicesHost_6/HostCloudService/HostCloudService.ccproj
samples/azure/shared-host/CloudServicesHost_7/HostCloudService/HostCloudService.ccproj
samples/azure/shared-host/CloudServicesHost_7/Receiver/app.config
samples/azure/shared-host/CloudServicesHost_7/Sender/app.config

Connects to Particular/PlatformDevelopment#730

Fix Azure Cloud Services host

---

nservicebus/upgrades/5to6.md

Fixes https://github.com/Particular/docs.particular.net/issues/1544

Document additional context parameter for saga operations

---

Snippets/Testing/Testing_4/Saga/Tests.cs
Snippets/Testing/Testing_4/Testing_4.csproj
Snippets/Testing/Testing_4/packages.config
Snippets/Testing/Testing_5/Saga/Tests.cs
Snippets/Testing/Testing_5/Testing_5.csproj
Snippets/Testing/Testing_5/UpgradeGuides/5to6/UsingWhen.cs
Snippets/Testing/Testing_5/packages.config
Snippets/Testing/Testing_6/Handlers/GatewayTest.cs
Snippets/Testing/Testing_6/Saga/ConfigureSagaMessageId.cs
Snippets/Testing/Testing_6/Saga/Tests.cs
Snippets/Testing/Testing_6/Testing_6.csproj
Snippets/Testing/Testing_6/UpgradeGuides/5to6/UsingWhen.cs
Snippets/Testing/Testing_6/packages.config
menu/menu.yaml
nservicebus/upgrades/5to6-testing.md
nservicebus/upgrades/testing-5to6.md

Based on the feedback of the v6 beta programm I tried to summarize breaking changes of the Testing Framework in a dedicated upgrade guide.
@Particular/docs-maintainers @indualagarsamy please review

NserviceBus.Testing 5to6 upgrade guide

---

samples/azure/shared-host/CloudServicesHost_7/AzureSharedHosting.sln
samples/azure/shared-host/CloudServicesHost_7/HostCloudService/ServiceConfiguration.Cloud.cscfg
samples/azure/shared-host/CloudServicesHost_7/HostCloudService/ServiceConfiguration.Local.cscfg
samples/azure/shared-host/CloudServicesHost_7/HostCloudService/ServiceDefinition.csdef
samples/azure/shared-host/CloudServicesHost_7/HostWorker/EndpointConfig.cs
samples/azure/shared-host/CloudServicesHost_7/HostWorker/HostWorker.csproj
samples/azure/shared-host/CloudServicesHost_7/HostWorker/WorkerRole.cs
samples/azure/shared-host/CloudServicesHost_7/HostWorker/app.config
samples/azure/shared-host/CloudServicesHost_7/HostWorker/packages.config
samples/azure/shared-host/CloudServicesHost_7/Receiver/Receiver.csproj
samples/azure/shared-host/CloudServicesHost_7/Receiver/packages.config
samples/azure/shared-host/CloudServicesHost_7/Sender/Sender.csproj
samples/azure/shared-host/CloudServicesHost_7/Sender/packages.config

Relates to Particular/PlatformDevelopment#730

Update the Azure shared host sample to changes in the host API

---

Snippets/Core/Core_5/Core_5.csproj
Snippets/Core/Core_5/UpgradeGuides/5to6/Saga.cs
Snippets/Core/Core_6/Core_6.csproj
Snippets/Core/Core_6/Sagas/Reply/MySaga.cs
Snippets/Core/Core_6/Sagas/SimpleSaga/OrderSaga.cs
Snippets/Core/Core_6/Sagas/Timeouts/MySaga.cs
Snippets/Core/Core_6/UpgradeGuides/5to6/Saga.cs
nservicebus/upgrades/5to6.md

If I understood @DavidBoike correctly, this line is invalid and users shouldn't set the correlation property manually?

Saga correlation

---

tools/coreDependencies.linq

LINQPad Script to detect the core dependency of each NuGet package

[WIP] Detect Core Dependencies

---

samples/azure/shared-host/CloudServicesHost_6/HostWorker/HostWorker.csproj
samples/azure/shared-host/CloudServicesHost_6/HostWorker/packages.config
samples/azure/shared-host/CloudServicesHost_6/Receiver/Receiver.csproj
samples/azure/shared-host/CloudServicesHost_6/Receiver/packages.config
samples/azure/shared-host/CloudServicesHost_6/Sender/Sender.csproj
samples/azure/shared-host/CloudServicesHost_6/Sender/packages.config

Azure host upgrade to 6.2.5

---

Snippets/Core/Core_6/UpgradeGuides/5to6/EndpointStartStop.cs
Snippets/Core/Core_6/UpgradeGuides/5to6/SpecifyingHostId.cs
nservicebus/upgrades/5to6-endpoint-name-helper.md
nservicebus/upgrades/5to6-moving-away-from-ibus.md
nservicebus/upgrades/5to6.md
nservicebus/upgrades/host-6to7.md

Relates to: 
https://github.com/Particular/docs.particular.net/issues/1497
https://github.com/Particular/docs.particular.net/issues/1327

Moving away from IBus

---

nservicebus/sagas/index.md
nservicebus/sagas/saga-finding.md
nservicebus/sagas/saga-not-found.md

A few points of clarification, based on conversation with customers and Andreas.

Clarify sagas

---

nservicebus/upgrades/nhibernate-6to7.md

Raised in https://github.com/Particular/PlatformDevelopment/issues/737

Add info about unique attribute in NHibernate upgrade guide

---

nservicebus/upgrades/sqlserver-2to3.md

Connects to: https://github.com/Particular/NServiceBus.SqlServer/issues/253

Removed promise of supporting multi-catalog from upgrade guide

---

nservicebus/sqlserver/deployment-options.md

Connects to: https://github.com/Particular/NServiceBus.SqlServer/issues/253

Add note about not supporting multi-instance mode with Outbox in Version 3

---

Snippets/ASB/ASB_7/ASB_7.csproj
samples/azure/azure-service-bus/ASB_6/Endpoint1/Program.cs
samples/azure/azure-service-bus/ASB_6/Endpoint2/Program.cs
samples/azure/azure-service-bus/ASB_7/Endpoint1/Endpoint1.csproj
samples/azure/azure-service-bus/ASB_7/Endpoint1/packages.config
samples/azure/azure-service-bus/ASB_7/Endpoint2/Endpoint2.csproj
samples/azure/azure-service-bus/ASB_7/Endpoint2/packages.config
samples/azure/azure-service-bus/ASB_7/Shared/Shared.csproj
samples/azure/azure-service-bus/ASB_7/Shared/packages.config
samples/azure/custom-sanitization-asb/ASB_7/Publisher/Publisher.csproj
samples/azure/custom-sanitization-asb/ASB_7/Publisher/packages.config
samples/azure/custom-sanitization-asb/ASB_7/Shared/Shared.csproj
samples/azure/custom-sanitization-asb/ASB_7/Shared/packages.config
samples/azure/custom-sanitization-asb/ASB_7/Subscriber/Subscriber.csproj
samples/azure/custom-sanitization-asb/ASB_7/Subscriber/packages.config
samples/azure/native-integration-asb/ASB_7/MessageGenerator/MessageGenerator.csproj
samples/azure/native-integration-asb/ASB_7/MessageGenerator/packages.config
samples/azure/native-integration-asb/ASB_7/Receiver/Receiver.csproj
samples/azure/native-integration-asb/ASB_7/Receiver/packages.config
samples/azure/native-integration-asb/ASB_7/Shared/Shared.csproj
samples/azure/native-integration-asb/ASB_7/Shared/packages.config
samples/azure/polymorphic-events-asb/ASB_7/Publisher/Publisher.csproj
samples/azure/polymorphic-events-asb/ASB_7/Publisher/packages.config
samples/azure/polymorphic-events-asb/ASB_7/Shared/Shared.csproj
samples/azure/polymorphic-events-asb/ASB_7/Shared/packages.config
samples/azure/polymorphic-events-asb/ASB_7/Subscriber/Subscriber.csproj
samples/azure/polymorphic-events-asb/ASB_7/Subscriber/packages.config

Upgrade to ASB beta6 / Core beta4

---

samples/azure/storage-queues/ASQ_7/Endpoint1/Endpoint1.csproj
samples/azure/storage-queues/ASQ_7/Endpoint1/packages.config
samples/azure/storage-queues/ASQ_7/Endpoint2/Endpoint2.csproj
samples/azure/storage-queues/ASQ_7/Endpoint2/packages.config
samples/azure/storage-queues/ASQ_7/Shared/Shared.csproj
samples/azure/storage-queues/ASQ_7/Shared/packages.config
samples/outbox/sqltransport-nhpersistence/SqlServer_3/Receiver/OrderLifecycleSaga.cs
samples/outbox/sqltransport-nhpersistence/SqlServer_3/Receiver/Receiver.csproj
samples/outbox/sqltransport-nhpersistence/SqlServer_3/Receiver/packages.config
samples/outbox/sqltransport-nhpersistence/SqlServer_3/Sender/Sender.csproj
samples/outbox/sqltransport-nhpersistence/SqlServer_3/Sender/packages.config
samples/outbox/sqltransport-nhpersistence/SqlServer_3/Shared/Shared.csproj
samples/outbox/sqltransport-nhpersistence/SqlServer_3/Shared/packages.config

Updating samples to beta4

---

Snippets/Core/Core_5/Persistence/Msmq/Usage.cs
Snippets/Core/Core_6/Persistence/Msmq/Usage.cs
nservicebus/msmq/subscription-persistence.md

Based on the feedback received here: https://github.com/Particular/docs.particular.net/issues/1604
we should give some better guidance on how to use the MSMQ subscription storage.

Improve MSMQ subscription storage doco

---

nservicebus/upgrades/sqlserver-2to3.md

Connects to https://github.com/Particular/docs.particular.net/issues/1609

Mention push mode for sql transport upgrade guide

---

Snippets/SqlServer/SqlServer_3/UpgradeGuides/Transactions.cs
nservicebus/upgrades/sqlserver-2to3.md

Blocked by https://github.com/Particular/NServiceBus.SqlServer/pull/252

Added info to upgrade guide for using transport connection in the handler

---

nservicebus/messaging/messages-events-commands.md

Connects to https://github.com/Particular/docs.particular.net/issues/517

Guidance for messages design

---

Snippets/NHibernate/NHibernate_6/Usage.cs
Snippets/NHibernate/NHibernate_7/Usage.cs
nservicebus/nhibernate/index.md

Connects to https://github.com/Particular/docs.particular.net/issues/928.

NHibernate persistence - add info about passing connection string via code

---

nservicebus/messaging/publish-subscribe/controlling-what-is-subscribed.md

http://public.wsu.edu/~brians/errors/lose.html

lose an event

---

platform/release-notes.md

Connects to https://github.com/Particular/docs.particular.net/issues/1487

Extend release notes page

---

nservicebus/testing/index.md

Connects to https://github.com/Particular/docs.particular.net/issues/1145

Add info about tests structure

---

Snippets/Core/Core_6/Core_6.csproj
Snippets/Core/Core_6/Errors/FirstLevel/FlrCodeFirstConfiguration.cs
Snippets/Core/Core_6/Errors/SecondLevel/SlrCodeFirstConfiguration.cs
Snippets/Core/Core_6/UpgradeGuides/5to6/Recoverability.cs
nservicebus/errors/automatic-retries.md
nservicebus/upgrades/5to6.md

relates to https://github.com/Particular/NServiceBus/pull/3814
replaces https://github.com/Particular/docs.particular.net/pull/1591
does not yet compile, will require the next core beta package

[WIP] Recoverability API

---

nservicebus/msmq/subscription-authorisation.md
nservicebus/pipeline/aborting.md
nservicebus/security/encryption.md
nservicebus/security/generating-encryption-keys.md

Tagged some pages with security tag.
Haven't decided if other pages that have a section/paragraph should also be tagged or not. Related to #1613

[WIP] Tagging security related pages

---

nservicebus/sqlserver/index.md

We don't really have firm data to back this sentence. Performance of the SQL Server transport depends on so many factors and can be subject to various database tuning techniques.
/cc @SimonCropp @weralabaj @Particular/sqlserver-transport-maintainers

Remove vague sentence

---

samples/routing/data-distribution/Core_6/Client/CacheInvalidationHandler.cs
samples/routing/data-distribution/Core_6/Client/Client.csproj
samples/routing/data-distribution/Core_6/Client/OrderAcceptedHandler.cs
samples/routing/data-distribution/Core_6/Client/Program.cs
samples/routing/data-distribution/Core_6/Client/packages.config
samples/routing/data-distribution/Core_6/Client2/CacheInvalidationHandler.cs
samples/routing/data-distribution/Core_6/Client2/Client2.csproj
samples/routing/data-distribution/Core_6/Client2/OrderAcceptedHandler.cs
samples/routing/data-distribution/Core_6/Client2/Program.cs
samples/routing/data-distribution/Core_6/Client2/packages.config
samples/routing/data-distribution/Core_6/DataDistribution.sln
samples/routing/data-distribution/Core_6/DataDistribution.sln.DotSettings
samples/routing/data-distribution/Core_6/Server/PlaceOrderHandler.cs
samples/routing/data-distribution/Core_6/Server/Program.cs
samples/routing/data-distribution/Core_6/Server/Server.csproj
samples/routing/data-distribution/Core_6/Server/packages.config
samples/routing/data-distribution/Core_6/Shared/OrderAccepted.cs
samples/routing/data-distribution/Core_6/Shared/PlaceOrder.cs
samples/routing/data-distribution/Core_6/Shared/Shared.csproj
samples/routing/data-distribution/Core_6/Shared/packages.config
samples/routing/data-distribution/sample.md

Another day, another routing sample

Data distribution sample

---

nservicebus/messaging/forwarding.md
nservicebus/operations/auditing.md
nservicebus/upgrades/5to6.md

Resolves https://github.com/Particular/docs.particular.net/issues/366.

Clarify the difference between auditing and forwarding

---

nservicebus/rabbitmq/index.md

Resolves https://github.com/Particular/docs.particular.net/issues/1244.

RabbitMQ transport - advantages and disadvantages

---

Snippets/ASB/ASB_7/ASB_7.csproj
Snippets/ASB/ASB_7/AddressingStrategies.cs
Snippets/ASB/ASB_7/Sanitization.cs
Snippets/ASB/ASB_7/Usage.cs
Snippets/ASB/ASB_7/packages.config
menu/menu.yaml
nservicebus/azure-service-bus/addressing-logic.md
nservicebus/azure-service-bus/configuration/full.md
nservicebus/azure-service-bus/configuration/index.md
nservicebus/azure-service-bus/sanitization.md
nservicebus/upgrades/asb-6to7.md
samples/azure/azure-service-bus/ASB_7/Endpoint1/Endpoint1.csproj
samples/azure/azure-service-bus/ASB_7/Endpoint1/packages.config
samples/azure/azure-service-bus/ASB_7/Endpoint2/Endpoint2.csproj
samples/azure/azure-service-bus/ASB_7/Endpoint2/packages.config
samples/azure/azure-service-bus/ASB_7/Shared/Shared.csproj
samples/azure/azure-service-bus/ASB_7/Shared/packages.config
samples/azure/custom-sanitization-asb/ASB_7/Publisher/Publisher.csproj
samples/azure/custom-sanitization-asb/ASB_7/Publisher/packages.config
samples/azure/custom-sanitization-asb/ASB_7/Subscriber/Subscriber.csproj
samples/azure/custom-sanitization-asb/ASB_7/Subscriber/packages.config
samples/azure/custom-sanitization-asb/sample.md
samples/azure/native-integration-asb/ASB_7/Receiver/Receiver.csproj
samples/azure/native-integration-asb/ASB_7/Receiver/packages.config
samples/azure/polymorphic-events-asb/ASB_7/Publisher/Program.cs
samples/azure/polymorphic-events-asb/ASB_7/Publisher/Publisher.csproj
samples/azure/polymorphic-events-asb/ASB_7/Publisher/packages.config
samples/azure/polymorphic-events-asb/ASB_7/Subscriber/Program.cs
samples/azure/polymorphic-events-asb/ASB_7/Subscriber/Subscriber.csproj
samples/azure/polymorphic-events-asb/ASB_7/Subscriber/packages.config

Connect to https://github.com/Particular/NServiceBus.AzureServiceBus/issues/252
Validation and Sanitization got merged.

ASB Beta7 changes - Sanitization

---

nservicebus/upgrades/5to6.md

Related to https://github.com/Particular/NServiceBus/pull/3864

Update 5to6 ConfigureHowToFindSaga wording to be more exact

---

nservicebus/sqlserver/index.md

@Particular/sqlserver-transport-maintainers /cc: @SimonCropp

Update disadvantages section with low latency processing note

---

Snippets/Core/Core_All/Core_All.csproj
Snippets/Core/Core_All/Msmq/NativeSend.ps1
Snippets/Core/Core_All/Msmq/NativeSendUsage.ps1
nservicebus/msmq/operations-scripting.md

[WIP] Add NativeSend PS Snippets

---

samples/azure/blob-storage-databus/Azure_6/Receiver/Receiver.csproj
samples/azure/blob-storage-databus/Azure_6/Receiver/packages.config
samples/azure/blob-storage-databus/Azure_6/Sender/Sender.csproj
samples/azure/blob-storage-databus/Azure_6/Sender/packages.config
samples/azure/shared-host/CloudServicesHost_6/Receiver/Receiver.csproj
samples/azure/shared-host/CloudServicesHost_6/Receiver/packages.config
samples/azure/shared-host/CloudServicesHost_6/Sender/Sender.csproj
samples/azure/shared-host/CloudServicesHost_6/Sender/packages.config
samples/azure/shared-host/CloudServicesHost_7/Receiver/Receiver.csproj
samples/azure/shared-host/CloudServicesHost_7/Receiver/packages.config
samples/azure/shared-host/CloudServicesHost_7/Sender/Sender.csproj
samples/azure/shared-host/CloudServicesHost_7/Sender/packages.config
samples/azure/storage-persistence/ASP_1/Server/Server.csproj
samples/azure/storage-persistence/ASP_1/Server/packages.config
samples/azure/storage-persistence/Azure_6/Server/Server.csproj
samples/azure/storage-persistence/Azure_6/Server/packages.config
samples/azure/storage-queues/ASQ_6/Endpoint1/Endpoint1.csproj
samples/azure/storage-queues/ASQ_6/Endpoint1/packages.config

Connects to https://github.com/Particular/PlatformDevelopment/issues/836
Includes:
- Bump up of NServiceBus.Azure from "6.2.4" to "6.2.5"
- Bump up of NServiceBus.Persistence.AzureStorage from "1.0.0-beta0003" to "1.0.0-beta0004"

Azure Storage Persistence bump up

---

Snippets/ServiceControl/ServiceControl_All/MultiDb.config.xml
Snippets/SqlServer/SqlServer_2/MultiDb.config.xml

Connects to Particular/PlatformDevelopment#555

Move ServiceControl multiple connection string config to SC snippets

---

Snippets/ASB/ASB_6/Usage.cs
Snippets/ASB/ASB_7/ASB_7.csproj
Snippets/ASB/ASB_7/MultipleNamespaces.cs
Snippets/ASB/ASB_7/SecureCredentials.cs
nservicebus/azure-service-bus/asb-credential-warning.include.md
nservicebus/azure-service-bus/multiple-namespaces-support.md
nservicebus/azure-service-bus/securing-connection-strings.md

This PR shows how cross namespace routing can be done (now and in the past), and also explains the interactions with multinamespace partitioning

Asb namespace naming

---

menu/menu.yaml
nservicebus/upgrades/sqlserver-1.x-1.2.5.md
nservicebus/upgrades/sqlserver-2.x-2.2.4.md
nservicebus/upgrades/sqlserver-2to3.md
security-advisories/index.md
security-advisories/sqlserver-sqlinjection.md

Related to Particular/PlatformDevelopment#831

SQL Server transport injection security advisory

---

servicecontrol/plugins/index.md

Connects to: #1624 
I was planning creating sample to show how to configure SC but I decided to put it into existing doco pages. 
Please have a look and let me know what you think: @Particular/servicecontrol-maintainers @Particular/docs-maintainers @WilliamBZA

Configuring SC to monitor endpoints

---

security-advisories/sqlserver-sqlinjection.md

A little bit more v6-proof.
/cc @SimonCropp @weralabaj @udidahan

Add IMessageHandlerContext info for v6

---

Snippets/ASB/ASB_7/ASB_7.csproj
Snippets/ASB/ASB_7/TokenProvider.cs
Snippets/ASB/ASB_7/packages.config
menu/menu.yaml
nservicebus/azure-service-bus/token-provider.md

Shows how to register a custom token provider (f.e. ADFS integration)

ASB  custom token provider

---

nservicebus/handlers/async-handlers.md

Another option would be "for integration".
I think the first one sounds better

Fixed grammar

---

Snippets/ASQ/ASQ_7/ASQ_7.csproj
Snippets/ASQ/ASQ_7/Usage.cs
Snippets/ASQ/ASQ_7/packages.config
menu/menu.yaml
nservicebus/azure-storage-queues/configuration.md
nservicebus/azure-storage-queues/multi-storageaccount-support.md
samples/azure/shared-host/CloudServicesHost_7/Receiver/Receiver.csproj
samples/azure/shared-host/CloudServicesHost_7/Receiver/packages.config
samples/azure/shared-host/CloudServicesHost_7/Sender/Sender.csproj
samples/azure/shared-host/CloudServicesHost_7/Sender/packages.config
samples/azure/storage-queues/ASQ_7/Endpoint1/Endpoint1.csproj
samples/azure/storage-queues/ASQ_7/Endpoint1/packages.config
samples/azure/storage-queues/ASQ_7/Endpoint2/Endpoint2.csproj
samples/azure/storage-queues/ASQ_7/Endpoint2/packages.config

Connects to https://github.com/Particular/PlatformDevelopment/issues/871
Addresses https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/119

ASQ: Scale Out scenario with secure connection strings

---

Snippets/Gateway/Gateway_2/Usage.cs
nservicebus/gateway/index.md

Resolves https://github.com/Particular/docs.particular.net/issues/1442

Gateway article review

---

components/components.yaml
nservicebus/azure-service-bus/multiple-namespaces-support.md
nservicebus/hosting/cloud-services-host/configuration.md
nservicebus/messaging/handling-responses-on-the-client-side.md
nservicebus/messaging/handling-responses-on-the-client-side_cancellation_callbacks_1.partial.md
nservicebus/messaging/handling-responses-on-the-client-side_fakeHandler_callbacks_3.partial.md
nservicebus/messaging/handling-responses-on-the-client-side_rout_callbacks_1.partial.md
nservicebus/messaging/handling-responses-on-the-client-side_rout_callbacks_[3.0,6.0).partial.md
nservicebus/testing/index.md

Required for https://github.com/Particular/DocsEngine/pull/219

Version switching and partials

---

Snippets/Core/Core_6/Handlers/AsyncHandler.cs
nservicebus/handlers/async-handlers.md

Should NOTE become WARN?
Or should we just drop the `Task.Run` samples because there are potentially too many variables at play? 
In my personal opinion we should show it for completeness reasons.
@Particular/docs-maintainers thoughts?

Some clarification and caveats for Task.Run / Factory.StartNew in handlers

---

nservicebus/azure-storage-persistence/index.md

Connects to https://github.com/Particular/NServiceBus.Persistence.AzureStorage/issues/92

ASP supported saga properties' types

---

nservicebus/upgrades/5to6-moving-away-from-ibus.md

Fixes: https://github.com/Particular/docs.particular.net/issues/1327

Added reasons as to why the bus was deprecated.

---

samples/scaleout/distributor/sample.md

Resolves https://github.com/Particular/docs.particular.net/issues/1582.

Clarify distributor sample

---

Snippets/Core/Core_6/AsyncSuffix/MissingAwait.cs
Snippets/Core/Core_6/AsyncSuffix/ServiceWithAsync.cs
Snippets/Core/Core_6/Core_6.csproj
menu/menu.yaml
nservicebus/upgrades/5to6-async-suffix.md
nservicebus/upgrades/5to6-moving-away-from-ibus.md

Fixes:
- https://github.com/Particular/docs.particular.net/issues/1523
- https://github.com/Particular/docs.particular.net/issues/1537
@SimonCropp @danielmarbach - please review
cc / @Particular/docs-maintainers

Explanation for no async suffix

---

serviceinsight/license.md

updating the ServiceInsight licensing page, added related to links

---

nservicebus/messaging/publish-subscribe/controlling-what-is-subscribed.md
nservicebus/messaging/publish-subscribe/index.md

Resolves https://github.com/Particular/docs.particular.net/issues/860

clarify what's required for transport without native pub-sub

---

servicecontrol/deploying-servicecontrol-in-a-cluster.md

Changes based on https://nservicebus.desk.com/agent/case/18615

RavenDB shared storage explanation

---

samples/index.md

@SimonCropp  something like this?

Add link to step by step at top of samples page

---

samples/show-case/on-premise/Core_5/Store.ECommerce/Content/js/product.js
samples/show-case/on-premise/Core_5/Store.ECommerce/Global.asax.cs
samples/show-case/on-premise/Core_5/Store.ECommerce/Views/Home/Index.cshtml
samples/show-case/on-premise/Core_5/Store.ECommerce/Views/Shared/_Layout.cshtml
samples/show-case/on-premise/Core_6/Store.ECommerce/Content/js/product.js
samples/show-case/on-premise/Core_6/Store.ECommerce/Views/Home/Index.cshtml
samples/show-case/on-premise/Core_6/Store.ECommerce/Views/Shared/_Layout.cshtml

Connects to #1717 
Fix #1717 
Do you prefer to have a single squashed commit?

Update showcase sample

---

Snippets/Core/Core_6/AdditionalDeserializers.cs
Snippets/Core/Core_6/Core_6.csproj
Snippets/Core/Core_6/Serialization/AdditionalDeserializers.cs
Snippets/Core/Core_6/Serialization/RegisterCustomSerializer.cs
nservicebus/serialization/custom-serializer.md
nservicebus/serialization/index.md

Connects to #1694 
Requires at least `NServiceBus  6.0.0-Beta6`.

[WIP] Additional settings for serializers.

---

Snippets/Callbacks/Callbacks_1/Callbacks_1.csproj
Snippets/Callbacks/Callbacks_1/UpgradeGuides/5to6/Callbacks.cs
nservicebus/upgrades/5to6.md

@weralabaj can you take a look?

Changed callbacks upgrade guide to be more helpful

---

Snippets/Testing/Testing_6/Testing_6.csproj
Snippets/Testing/Testing_6/packages.config
samples/unit-testing/Testing_6/Sample/Sample.csproj
samples/unit-testing/Testing_6/Sample/packages.config

Connects to Particular/V6Launch#65

Update NServiceBus.Testing snippets and samples to Beta2

---

Snippets/NHibernate/NHibernate_7/NHibernate_7.csproj
Snippets/NHibernate/NHibernate_7/packages.config
samples/nhibernate/custom-mappings/NHibernate_7/Sample.Attributes/Sample.Attributes.csproj
samples/nhibernate/custom-mappings/NHibernate_7/Sample.Attributes/packages.config
samples/nhibernate/custom-mappings/NHibernate_7/Sample.Default/Sample.Default.csproj
samples/nhibernate/custom-mappings/NHibernate_7/Sample.Default/packages.config
samples/nhibernate/custom-mappings/NHibernate_7/Sample.Fluent/Sample.Fluent.csproj
samples/nhibernate/custom-mappings/NHibernate_7/Sample.Fluent/packages.config
samples/nhibernate/custom-mappings/NHibernate_7/Sample.Loquacious/Sample.Loquacious.csproj
samples/nhibernate/custom-mappings/NHibernate_7/Sample.Loquacious/packages.config
samples/nhibernate/custom-mappings/NHibernate_7/Sample.XmlMapping/Sample.XmlMapping.csproj
samples/nhibernate/custom-mappings/NHibernate_7/Sample.XmlMapping/packages.config
samples/nhibernate/custom-mappings/NHibernate_7/Shared/Shared.csproj
samples/nhibernate/custom-mappings/NHibernate_7/Shared/packages.config

Connects to Particular/V6Launch#65

Update NServiceBus.NHibernate to 7.0.0-Beta5

---

nservicebus/security/encryption.md

Connects to https://github.com/Particular/NServiceBus/pull/3991

Small note about how encryption is enabled and disabled

---

nservicebus/nhibernate/outbox.md
nservicebus/outbox/index.md
nservicebus/ravendb/outbox.md
nservicebus/sqlserver/configuration.md

Resolves https://github.com/Particular/docs.particular.net/issues/1334

Outbox review

---

servicecontrol/backup-sc-database.md

@johnsimons can you double check this change to ensure it is correct as per our conversation about ServiceControl yesterday?

Update ServiceControl backup limitations

---

menu/menu.yaml
nservicebus/operations/transactions-message-processing.md
nservicebus/operations/warning-for-cid-values.md

Resolves https://github.com/Particular/docs.particular.net/issues/1713.

Review "Transactions and message processing"

---

Snippets/Host/Host_7/Host_7.csproj
Snippets/Host/Host_7/packages.config
samples/hosting/nservicebus-host/Host_7/Sample/Sample.csproj
samples/hosting/nservicebus-host/Host_7/Sample/packages.config
samples/hosting/windows-service/Core_6/Sample/Sample.csproj
samples/hosting/windows-service/Core_6/Sample/packages.config

Update samples and snippets for the windows host to core beta6

---

samples/rabbitmq/native-integration/Rabbit_4/NativeSender/NativeSender.csproj
samples/rabbitmq/native-integration/Rabbit_4/NativeSender/packages.config
samples/rabbitmq/native-integration/Rabbit_4/Receiver/Receiver.csproj
samples/rabbitmq/native-integration/Rabbit_4/Receiver/app.config
samples/rabbitmq/native-integration/Rabbit_4/Receiver/packages.config
samples/rabbitmq/simple/Rabbit_4/Sample/Sample.csproj
samples/rabbitmq/simple/Rabbit_4/Sample/app.config
samples/rabbitmq/simple/Rabbit_4/Sample/packages.config

@Particular/docs-maintainers please merge after build is green

Updating Rabbit client to 3.6.5

---

nservicebus/messaging/routing.md

some adjustments to the description of the instance distribution behavior.
/cc @SzymonPobiega

Update description of distribution behavior on routing

---

Snippets/Rabbit/Rabbit_4/Rabbit_4.csproj
Snippets/Rabbit/Rabbit_4/Usage.cs
Snippets/Rabbit/Rabbit_4/packages.config
Snippets/Rabbit/Rabbit_All/NativeSendTests.cs
Snippets/Rabbit/Rabbit_All/Rabbit_All.csproj
Snippets/Rabbit/Rabbit_All/packages.config
samples/rabbitmq/native-integration/Rabbit_4/Receiver/Receiver.csproj
samples/rabbitmq/native-integration/Rabbit_4/Receiver/packages.config
samples/rabbitmq/simple/Rabbit_4/Sample/Sample.csproj
samples/rabbitmq/simple/Rabbit_4/Sample/packages.config

cc: @Particular/docs-maintainers when green please merge

Updating snippets and samples to use latest version of Rabbit beta5

---

Snippets/Gateway/Gateway_2/Gateway_2.csproj
Snippets/Gateway/Gateway_2/packages.config
Snippets/Testing/Testing_6/Testing_6.csproj
Snippets/Testing/Testing_6/packages.config
samples/gateway/Gateway_2/Headquarters/Headquarters.csproj
samples/gateway/Gateway_2/Headquarters/packages.config
samples/gateway/Gateway_2/RemoteSite/RemoteSite.csproj
samples/gateway/Gateway_2/RemoteSite/packages.config
samples/gateway/Gateway_2/Shared/Shared.csproj
samples/gateway/Gateway_2/Shared/packages.config

Connects to Particular/V6Launch#65

Update snippets and samples to Gateway 2.0.0-Beta3

---

Snippets/Core/Core_5/ScaleOut/IndividualizeQueues.cs

To be merged after https://github.com/Particular/DocsEngine/pull/231

[WIP] Fixing snippet versions

---

Snippets/SqlServer/SqlServer_2/ExpiredIndex.sql
Snippets/SqlServer/SqlServer_2/UpgradeGuides/ExpiredIndex.sql
Snippets/SqlServer/SqlServer_3/ExpiredIndex.sql
nservicebus/sqlserver/design.md
nservicebus/sqlserver/operations-scripting.md
samples/msmqtosqlrelay/Core_5/MsmqPublisher/AddSubscriber.sql
samples/msmqtosqlrelay/Core_5/MsmqPublisher/CreateDatabase.sql
samples/msmqtosqlrelay/Core_6/MsmqPublisher/AddSubscriber.sql
samples/msmqtosqlrelay/Core_6/MsmqPublisher/CreateDatabase.sql
samples/routing/custom/Core_6/Shared/AutomaticRouting/Installer.cs
samples/sqltransport/native-integration/SqlServer_3/Receiver/Scripts.sql

@Particular/sqlserver-transport-maintainers @Particular/nhibernate-persistence-maintainers please review

remove redundant sql

---

nservicebus/messaging/handling-responses-on-the-client-side_rout_callbacks_1.partial.md
nservicebus/upgrades/5to6.md

relates to https://github.com/Particular/docs.particular.net/issues/1649

Update some docs around MakeInstanceUniquelyAddressable

---

menu/menu.yaml
nservicebus/azure-storage-queues/multi-storageaccount-support.md
nservicebus/hosting/nservicebus-host/no-endpoint-configuration-found-in-scanned-assemblies-exception.md
nservicebus/ravendb/installation.md
nservicebus/upgrades/asp-6to1.md
platform/installer/offline.md
samples/scaleout/distributor-upgrade/sample.md
samples/scaleout/senderside/sample.md
servicecontrol/securing-servicecontrol.md

Related to https://github.com/Particular/DocsEngine/issues/228.
Those documents will be broken after the changes in the engine get merged.

SEO - best practices

---

nservicebus/messaging/best-practice-enforcement.md

i think the
‘To enable this feature at the endpoint level using:’ 
should be 
‘To disable this feature at the endpoint level using:’

Repair representation error

---

Snippets/NHibernate/NHibernate_7/NHibernate_7.csproj
Snippets/NHibernate/NHibernate_7/packages.config
samples/nhibernate/custom-mappings/NHibernate_7/Sample.Attributes/Sample.Attributes.csproj
samples/nhibernate/custom-mappings/NHibernate_7/Sample.Attributes/packages.config
samples/nhibernate/custom-mappings/NHibernate_7/Sample.Default/Sample.Default.csproj
samples/nhibernate/custom-mappings/NHibernate_7/Sample.Default/packages.config
samples/nhibernate/custom-mappings/NHibernate_7/Sample.Fluent/Sample.Fluent.csproj
samples/nhibernate/custom-mappings/NHibernate_7/Sample.Fluent/packages.config
samples/nhibernate/custom-mappings/NHibernate_7/Sample.Loquacious/Sample.Loquacious.csproj
samples/nhibernate/custom-mappings/NHibernate_7/Sample.Loquacious/packages.config
samples/nhibernate/custom-mappings/NHibernate_7/Sample.XmlMapping/Sample.XmlMapping.csproj
samples/nhibernate/custom-mappings/NHibernate_7/Sample.XmlMapping/packages.config
samples/nhibernate/custom-mappings/NHibernate_7/Shared/Shared.csproj
samples/nhibernate/custom-mappings/NHibernate_7/Shared/packages.config
samples/outbox/multi-tenant/Core_6/Receiver/Receiver.csproj
samples/outbox/multi-tenant/Core_6/Receiver/packages.config
samples/outbox/multi-tenant/Core_6/Sender/Sender.csproj
samples/outbox/multi-tenant/Core_6/Sender/packages.config
samples/outbox/multi-tenant/Core_6/Shared/Shared.csproj
samples/outbox/multi-tenant/Core_6/Shared/packages.config
samples/saga/nh-custom-sagafinder/NHibernate_7/Sample/Sample.csproj
samples/saga/nh-custom-sagafinder/NHibernate_7/Sample/packages.config

Updating nhibernate samples and snippets

---

samples/delayed-delivery/Core_5/Server/Server.csproj
samples/delayed-delivery/Core_6/Client/Client.csproj
samples/delayed-delivery/Core_6/Client/packages.config
samples/delayed-delivery/Core_6/Server/Server.csproj
samples/delayed-delivery/Core_6/Server/packages.config
samples/delayed-delivery/Core_6/Shared/Shared.csproj
samples/delayed-delivery/Core_6/Shared/packages.config
samples/unobtrusive/Core_5/Client/CommandSender.cs
samples/unobtrusive/Core_5/Shared/Shared.csproj
samples/unobtrusive/Core_6/Client/Client.csproj
samples/unobtrusive/Core_6/Client/CommandSender.cs
samples/unobtrusive/Core_6/Client/packages.config
samples/unobtrusive/Core_6/Server/Server.csproj
samples/unobtrusive/Core_6/Server/packages.config
samples/unobtrusive/Core_6/Shared/Shared.csproj
samples/unobtrusive/Core_6/Shared/packages.config

Updated some samples to latest v6 beta and v5 versions and smoke tested them.

Samples updates

---

nservicebus/outbox/index.md

Resolves https://github.com/Particular/docs.particular.net/issues/1023.

Outbox - note about transactions

---

Snippets/Rabbit/Rabbit_4/Rabbit_4.csproj
Snippets/Rabbit/Rabbit_4/packages.config
Snippets/Rabbit/Rabbit_All/NativeSendTests.cs
Snippets/Rabbit/Rabbit_All/Rabbit_All.csproj
Snippets/Rabbit/Rabbit_All/packages.config
samples/rabbitmq/native-integration/Rabbit_4/Receiver/Receiver.csproj
samples/rabbitmq/native-integration/Rabbit_4/Receiver/packages.config
samples/rabbitmq/simple/Rabbit_4/Sample/Sample.csproj
samples/rabbitmq/simple/Rabbit_4/Sample/packages.config

cc: @Particular/docs-maintainers please review and merge

Updating Samples and Snippets to latest Rabbit v4 beta6 and NSB v6 beta7

---

Snippets/ASP/ASP_1/ASP_1.csproj
Snippets/ASP/ASP_1/packages.config
samples/azure/storage-persistence/ASP_1/Client/Client.csproj
samples/azure/storage-persistence/ASP_1/Client/app.config
samples/azure/storage-persistence/ASP_1/Client/packages.config
samples/azure/storage-persistence/ASP_1/Server/Server.csproj
samples/azure/storage-persistence/ASP_1/Server/packages.config
samples/azure/storage-persistence/ASP_1/Shared/Shared.csproj
samples/azure/storage-persistence/ASP_1/Shared/packages.config
samples/azure/storage-persistence/ASP_1/StorageReader/AzureHelper.cs

Components that are bumped up:
- Core6 beta7
- ASP1 beta6

ASP samples & snippets bumped up

---

nservicebus/serialization/custom-serializer.md
nservicebus/serialization/index.md

Since the interface is so simple and this is an advance feature, not sure it is worth saying more about it ?

WIP: Implement a custom serializer

---

samples/custom-transport/Core_6/Endpoint1/Endpoint1.csproj
samples/custom-transport/Core_6/Endpoint1/packages.config
samples/custom-transport/Core_6/Endpoint2/Endpoint2.csproj
samples/custom-transport/Core_6/Endpoint2/packages.config
samples/custom-transport/Core_6/Shared/DirectoryBasedTransaction.cs
samples/custom-transport/Core_6/Shared/Dispatcher.cs
samples/custom-transport/Core_6/Shared/FileTransport.cs
samples/custom-transport/Core_6/Shared/FileTransportMessagePump.cs
samples/custom-transport/Core_6/Shared/FileTransportQueueCreator.cs
samples/custom-transport/Core_6/Shared/Shared.csproj
samples/custom-transport/Core_6/Shared/packages.config

basic sample works, but error handling is not working properly. Need to figure out how to work with these transactions.

Update custom transport sample to core beta6

---

samples/scaleout/distribution-strategy/Core_6/Client/Client.csproj
samples/scaleout/distribution-strategy/Core_6/Client/WeightedDistributionStrategy.cs
samples/scaleout/distribution-strategy/Core_6/Client/packages.config
samples/scaleout/distribution-strategy/Core_6/Messages/Messages.csproj
samples/scaleout/distribution-strategy/Core_6/Messages/packages.config
samples/scaleout/distribution-strategy/Core_6/Server1/Server1.csproj
samples/scaleout/distribution-strategy/Core_6/Server1/packages.config
samples/scaleout/distribution-strategy/Core_6/Server2/Server2.csproj
samples/scaleout/distribution-strategy/Core_6/Server2/packages.config

ping @Particular/docs-maintainers 
/cc @MarcinHoppe

Update custom distribution strategy sample to v6 beta7

---

Snippets/CustomChecks/CustomChecks6_1/CustomChecks6_1.csproj
samples/custom-checks/monitoring3rdparty/CustomChecks6_1/3rdPartySystem/Program.cs
samples/custom-checks/monitoring3rdparty/CustomChecks6_1/Sample/Sample.csproj
samples/custom-checks/monitoring3rdparty/CustomChecks6_1/Sample/packages.config

Connects to https://github.com/Particular/V6Launch/issues/65
To be merged when the Custom Checks plugin is pushed to NuGet.

Update Custom Checks sample and snippets to beta 6 (Core beta 7)

---

nservicebus/hosting/nservicebus-host/index.md

Related to https://github.com/Particular/NServiceBus.Host/issues/93 and https://github.com/Particular/NServiceBus.Host/pull/98

Add GMSA note for Host v7

---

samples/mongodb/Mongo_7/Client/Client.csproj
samples/mongodb/Mongo_7/Client/packages.config
samples/mongodb/Mongo_7/Server/Server.csproj
samples/mongodb/Mongo_7/Server/packages.config
samples/mongodb/Mongo_7/Shared/Shared.csproj
samples/mongodb/Mongo_7/Shared/packages.config

Resolves https://github.com/Particular/V6Launch/issues/106.
Smoke tested locally.

Upgrade mongodb sample to beta7

---

Snippets/ASQ/ASQ_7/ASQ_7.csproj
Snippets/ASQ/ASQ_7/Usage.cs
Snippets/ASQ/ASQ_7/packages.config
nservicebus/azure-storage-queues/configuration.md
nservicebus/azure-storage-queues/multi-storageaccount-support.md
samples/azure/storage-queues/ASQ_7/Endpoint1/Endpoint1.csproj
samples/azure/storage-queues/ASQ_7/Endpoint1/packages.config
samples/azure/storage-queues/ASQ_7/Endpoint2/Endpoint2.csproj
samples/azure/storage-queues/ASQ_7/Endpoint2/packages.config
samples/azure/storage-queues/ASQ_7/Shared/Shared.csproj
samples/azure/storage-queues/ASQ_7/Shared/packages.config

Related to https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/144

Repharsing `name` as `alias` for Azure Storage Queues

---

components/components.yaml
components/nugetAlias.txt

Required for https://github.com/Particular/docs.particular.net/issues/1699.

Add SC contracts component

---

Snippets/ASB/ASB_7/ASB_7.csproj
Snippets/ASB/ASB_7/MultipleNamespaces.cs
Snippets/ASB/ASB_7/SecureCredentials.cs
Snippets/ASB/ASB_7/packages.config
nservicebus/azure-service-bus/multiple-namespaces-support.md
nservicebus/azure-service-bus/securing-connection-strings.md
samples/azure/azure-service-bus/ASB_7/Endpoint1/Endpoint1.csproj
samples/azure/azure-service-bus/ASB_7/Endpoint1/Program.cs
samples/azure/azure-service-bus/ASB_7/Endpoint1/packages.config
samples/azure/azure-service-bus/ASB_7/Endpoint2/Endpoint2.csproj
samples/azure/azure-service-bus/ASB_7/Endpoint2/Program.cs
samples/azure/azure-service-bus/ASB_7/Endpoint2/packages.config
samples/azure/azure-service-bus/ASB_7/Shared/Shared.csproj
samples/azure/azure-service-bus/ASB_7/Shared/packages.config
samples/azure/custom-sanitization-asb/ASB_7/Publisher/Publisher.csproj
samples/azure/custom-sanitization-asb/ASB_7/Publisher/packages.config
samples/azure/custom-sanitization-asb/ASB_7/Subscriber/Subscriber.csproj
samples/azure/custom-sanitization-asb/ASB_7/Subscriber/packages.config
samples/azure/native-integration-asb/ASB_7/Receiver/Receiver.csproj
samples/azure/native-integration-asb/ASB_7/Receiver/packages.config
samples/azure/polymorphic-events-asb/ASB_7/Publisher/Publisher.csproj
samples/azure/polymorphic-events-asb/ASB_7/Publisher/packages.config
samples/azure/polymorphic-events-asb/ASB_7/Subscriber/Subscriber.csproj
samples/azure/polymorphic-events-asb/ASB_7/Subscriber/packages.config

Connects to https://github.com/Particular/NServiceBus.AzureServiceBus/issues/304
@Particular/azure-service-bus-maintainers @Particular/docs-maintainers  please review
NOTE: references the next beta of the NSB.ASB so compilation will fail. DO NOT merge until NSB.ASB beta 0013 is on myget

Replace NS name with alias

---

nservicebus/azure-service-bus/configuration/full.md
nservicebus/azure-service-bus/send-atomic-with-receive-note.include.md

Connects to https://github.com/Particular/NServiceBus.AzureServiceBus/issues/306

TransportType addition to configuration API

---

nservicebus/messaging/routing.md
nservicebus/messaging/routing_commands_core_[6,).partial.md

Added some missing content (from the previous `message-oweneship` page)

Added missing routing content

---

nservicebus/persistence/in-memory.md

Clearly indicate it's NOT for production
@Particular/docs-maintainers

Make InMemoryPersistence summary clear

---

Snippets/Core/Core_6/BestPracticesConfiguration.cs
Snippets/Core/Core_6/Core_6.csproj
Snippets/Core/Core_6/packages.config

Connects to https://github.com/Particular/NServiceBus/pull/4090
TODO:

Update disabling best practices

---

Snippets/Gateway/Gateway_2/Gateway_2.csproj
Snippets/Gateway/Gateway_2/packages.config
samples/gateway/Gateway_2/Headquarters/Headquarters.csproj
samples/gateway/Gateway_2/Headquarters/packages.config
samples/gateway/Gateway_2/RemoteSite/RemoteSite.csproj
samples/gateway/Gateway_2/RemoteSite/packages.config

Update gateway to RC1

---

Snippets/Testing/Testing_6/Testing_6.csproj

Update Gateway RC 1

---

samples/servicecontrol/events-subscription/ServiceControlContracts_1/NServiceBusEndpoint/NServiceBusEndpoint.csproj
samples/servicecontrol/events-subscription/ServiceControlContracts_1/NServiceBusEndpoint/packages.config

Update heartbeat RC 1

---

Snippets/Autofac/Autofac_6/Autofac_6.csproj
Snippets/Autofac/Autofac_6/packages.config
Snippets/Core/Core_6/Core_6.csproj
Snippets/Core/Core_6/packages.config
samples/containers/autofac/Autofac_6/Sample/Sample.csproj
samples/containers/autofac/Autofac_6/Sample/packages.config
samples/endpoint-configuration/Core_6/Sample/Sample.csproj
samples/endpoint-configuration/Core_6/Sample/packages.config
samples/web/asp-mvc-application/Core_6/AsyncPagesMVC/AsyncPagesMVC.csproj
samples/web/asp-mvc-application/Core_6/AsyncPagesMVC/Web.config
samples/web/asp-mvc-application/Core_6/AsyncPagesMVC/packages.config
samples/web/send-from-mvc-controller/Core_6/WebApplication/Web.config
samples/web/send-from-mvc-controller/Core_6/WebApplication/WebApplication.csproj
samples/web/send-from-mvc-controller/Core_6/WebApplication/packages.config

Update Autofac RC 1

---

Snippets/CustomChecks/CustomChecks6_1/CustomChecks6_1.csproj
Snippets/CustomChecks/CustomChecks6_1/packages.config
samples/custom-checks/monitoring3rdparty/CustomChecks6_1/Sample/Sample.csproj
samples/custom-checks/monitoring3rdparty/CustomChecks6_1/Sample/packages.config

Update custom check to RC 1

---

Snippets/CommonLogging/CommonLogging_3/CommonLogging_3.csproj
Snippets/CommonLogging/CommonLogging_3/packages.config
samples/logging/commonlogging/CommonLogging_3/Sample/Sample.csproj
samples/logging/commonlogging/CommonLogging_3/Sample/packages.config

Update common logging RC1

---

Snippets/NLog/NLog_2/NLog_2.csproj
Snippets/NLog/NLog_2/packages.config
samples/logging/nlog-custom/NLog_2/Sample/Sample.csproj
samples/logging/nlog-custom/NLog_2/Sample/packages.config
samples/logging/stack-trace-cleaning/Core_6/SampleWithClean/SampleWithClean.csproj
samples/logging/stack-trace-cleaning/Core_6/SampleWithClean/packages.config
samples/logging/stack-trace-cleaning/Core_6/SampleWithoutClean/SampleWithoutClean.csproj
samples/logging/stack-trace-cleaning/Core_6/SampleWithoutClean/packages.config

Update nlog RC1

---

Snippets/Log4Net/Log4Net_2/Log4Net_2.csproj
Snippets/Log4Net/Log4Net_2/packages.config
samples/endpoint-configuration/Core_6/Sample/Sample.csproj
samples/endpoint-configuration/Core_6/Sample/packages.config
samples/logging/hostcustom/Host_7/Sample/Sample.csproj
samples/logging/hostcustom/Host_7/Sample/packages.config
samples/logging/hostprofiles/Host_7/Sample/Sample.csproj
samples/logging/hostprofiles/Host_7/Sample/packages.config
samples/logging/log4net-custom/Log4Net_2/Sample/Sample.csproj
samples/logging/log4net-custom/Log4Net_2/Sample/packages.config

Update log4net RC1

---

Snippets/Testing/Testing_6/Testing_6.csproj
Snippets/Testing/Testing_6/packages.config
samples/unit-testing/Testing_6/Sample/Sample.csproj
samples/unit-testing/Testing_6/Sample/packages.config

Testing update RC1

---

Snippets/ASB/ASB_7/ASB_7.csproj
Snippets/ASB/ASB_7/packages.config
samples/azure/azure-service-bus/ASB_7/Endpoint1/Endpoint1.csproj
samples/azure/azure-service-bus/ASB_7/Endpoint1/packages.config
samples/azure/azure-service-bus/ASB_7/Endpoint2/Endpoint2.csproj
samples/azure/azure-service-bus/ASB_7/Endpoint2/packages.config
samples/azure/azure-service-bus/ASB_7/Shared/Shared.csproj
samples/azure/azure-service-bus/ASB_7/Shared/packages.config
samples/azure/custom-sanitization-asb/ASB_7/Publisher/Publisher.csproj
samples/azure/custom-sanitization-asb/ASB_7/Publisher/packages.config
samples/azure/custom-sanitization-asb/ASB_7/Subscriber/Subscriber.csproj
samples/azure/custom-sanitization-asb/ASB_7/Subscriber/app.config
samples/azure/custom-sanitization-asb/ASB_7/Subscriber/packages.config
samples/azure/native-integration-asb/ASB_7/Receiver/Receiver.csproj
samples/azure/native-integration-asb/ASB_7/Receiver/packages.config
samples/azure/polymorphic-events-asb/ASB_7/Publisher/Publisher.csproj
samples/azure/polymorphic-events-asb/ASB_7/Publisher/packages.config
samples/azure/polymorphic-events-asb/ASB_7/Subscriber/Subscriber.csproj
samples/azure/polymorphic-events-asb/ASB_7/Subscriber/app.config
samples/azure/polymorphic-events-asb/ASB_7/Subscriber/packages.config

Samples updated to Core RC1

---

Snippets/ABSDataBus/ABSDataBus_1/ABSDataBus_1.csproj
Snippets/ABSDataBus/ABSDataBus_1/packages.config
samples/azure/blob-storage-databus/ABSDataBus_1/Receiver/Receiver.csproj
samples/azure/blob-storage-databus/ABSDataBus_1/Receiver/packages.config
samples/azure/blob-storage-databus/ABSDataBus_1/Sender/Sender.csproj
samples/azure/blob-storage-databus/ABSDataBus_1/Sender/packages.config
samples/azure/blob-storage-databus/sample.md

Azure databus rc update

---

Snippets/SqlServer/SqlServer_3/DelayConfig.cs
Snippets/SqlServer/SqlServer_3/SqlServer_3.csproj
Snippets/SqlServer/SqlServer_3/packages.config
nservicebus/sqlserver/queuepeek-settings.md

Waiting for the api to get updated and published to myget before I can make this build green. Resolves #1835

Sqlserver delay config

---

servicepulse/how-to-configure-endpoints-for-monitoring.md
servicepulse/install-servicepulse-in-iis.md
servicepulse/installation.md
servicepulse/servicepulse-host-config.md
servicepulse/troubleshooting.md

cc: @Particular/docs-maintainers

Updating reviewed date for some ServicePulse pages

---

Snippets/StructureMap/StructureMap_6/StructureMap_6.csproj
Snippets/StructureMap/StructureMap_6/packages.config
samples/containers/structuremap/StructureMap_6/Sample/Sample.csproj
samples/containers/structuremap/StructureMap_6/Sample/packages.config

Updating structuremap to rc1

---

Snippets/ASP/ASP_1/ASP_1.csproj
Snippets/ASP/ASP_1/packages.config
samples/azure/storage-persistence/ASP_1/Server/Server.csproj
samples/azure/storage-persistence/ASP_1/Server/packages.config

Connects to Particular/V6Launch#3

ASP bumped up to v6 RC dependencies

---

samples/serializers/newtonsoft/Newtonsoft_1/Sample/Sample.csproj
samples/serializers/newtonsoft/Newtonsoft_1/Sample/packages.config

Update newtonsoft json sample

---

Snippets/ASQ/ASQ_7/ASQ_7.csproj
Snippets/ASQ/ASQ_7/packages.config
samples/azure/storage-queues/ASQ_7/Endpoint1/Endpoint1.csproj
samples/azure/storage-queues/ASQ_7/Endpoint1/packages.config
samples/azure/storage-queues/ASQ_7/Endpoint2/Endpoint2.csproj
samples/azure/storage-queues/ASQ_7/Endpoint2/packages.config

Connects to Particular/V6Launch#3

ASQ bumped up to v6 RC dependencies

---

samples/azure/shared-host/CloudServicesHost_7/HostWorker/HostWorker.csproj
samples/azure/shared-host/CloudServicesHost_7/HostWorker/packages.config
samples/azure/shared-host/CloudServicesHost_7/Receiver/NServiceBus.Hosting.Azure.HostProcess.exe.config
samples/azure/shared-host/CloudServicesHost_7/Receiver/Receiver.csproj
samples/azure/shared-host/CloudServicesHost_7/Receiver/packages.config
samples/azure/shared-host/CloudServicesHost_7/Sender/Sender.csproj
samples/azure/shared-host/CloudServicesHost_7/Sender/packages.config

Azure shared host RC update

---

Snippets/Core/Core_3/Scanning/ScanningPublicApi.cs
Snippets/Core/Core_4/Scanning/ScanningPublicApi.cs
Snippets/Core/Core_5/Scanning/ScanningPublicApi.cs

Based on desk case: https://nservicebus.desk.com/agent/case/18852

ScanningExcludeTypes snippet for V3, V4 and V5.

---

nservicebus/sqlserver/connection-settings.md

Related to Particular/NServiceBus.SqlServer#204 changes.

Clarifying connection pool and concurrency implication in v6

---

samples/scaleout/senderside/sample.md

Some minor adjustments which came up when reviewing the the samples description.
@Particular/docs-maintainers @SzymonPobiega please review

Adjustments to scale out sample description

---

nservicebus/outbox/index.md

Add information about duplicate outgoing messages when using Outbox

---

servicepulse/intro-pending-retries.md

> Person should ensure that this message was not processed or was processed incorrectly before using retry feature.
This sounds weird.

Improved wording

---

nservicebus/sqlserver/index.md

Clarify that legacy multi-instance topology is for backwards compat only

---

nservicebus/imanageunitsofwork-outbox.include.md
nservicebus/pipeline/unit-of-work.md
nservicebus/pipeline/unit-of-work_imanageunitsofwork-outbox_core_[6.0,).partial.md

Note on unit of work and outbox

---

Snippets/Rabbit/Rabbit_4/Rabbit_4.csproj
Snippets/Rabbit/Rabbit_4/packages.config
Snippets/Rabbit/Rabbit_All/Rabbit_All.csproj
Snippets/Rabbit/Rabbit_All/packages.config
samples/rabbitmq/native-integration/Rabbit_4/NativeSender/NativeSender.csproj
samples/rabbitmq/native-integration/Rabbit_4/NativeSender/packages.config
samples/rabbitmq/native-integration/Rabbit_4/Receiver/Receiver.csproj
samples/rabbitmq/native-integration/Rabbit_4/Receiver/packages.config
samples/rabbitmq/simple/Rabbit_4/Sample/Sample.csproj
samples/rabbitmq/simple/Rabbit_4/Sample/packages.config

cc: @Particular/docs-maintainers please merge when green

Update Rabbit samples and snippets to RC1

---

nservicebus/azure-storage-queues/configuration.md
nservicebus/azure-storage-queues/configuration_aliasesAndHashing_asq_[7,].partial.md
nservicebus/azure-storage-queues/configuration_config_asq_[,6].partial.md
nservicebus/azure-storage-queues/configuration_config_asq_[7,].partial.md
nservicebus/azure-storage-queues/configuration_serialization_asq_[7,].partial.md

Connects to https://github.com/Particular/docs.particular.net/issues/1865

ASQ - Partials for aliases and hashing

---

Snippets/Core/Core_6/UpgradeGuides/5to6/EndpointStartStop.cs
nservicebus/upgrades/5to6/index.md

Creating a lighter-weight homepage for the upgrade guide to guide readers through the process at a high level and link off to additional detail where necessary.

[WIP] Upgrade Guide Homepage

---

Snippets/Rabbit/Rabbit_4/UpgradeGuides/3to4/Upgrade.cs
nservicebus/upgrades/rabbitmq-3to4.md

Connects to: https://github.com/Particular/NServiceBus.RabbitMQ/issues/185#issuecomment-245631265
Need to wait for release of newest package to myget so that snippets would build

[WIP] Updating UsePublisherConfirms API

---

nservicebus/msmq/troubleshooting.md

Add links to MSMQ events on TechNet

---

README.md

as per discussion in https://github.com/Particular/docs.particular.net/issues/1725, resolves https://github.com/Particular/docs.particular.net/issues/1725

List EIP patterns for reference

---

samples/containers/autofac/Autofac_5/Sample/Sample.csproj
samples/containers/autofac/Autofac_5/Sample/packages.config

Relates to https://github.com/Particular/NServiceBus.Autofac/issues/22

Update NServiceBus.Autofac 5.1.0

---

nservicebus/azure-service-bus/configuration/full.md

1. mentioning HTTPS
2. link to connectivity mode on msdn

Connectivity mode update

---

Snippets/ASB/ASB_7/Usage.cs
nservicebus/upgrades/asb-6to7.md

1. Reordered items.
2. BrokerMessage conventions addition
@Particular/azure-service-bus-maintainers @Particular/docs-maintainers please review

Updates to the ASB upgrade guide

---

README.md

Do not merge until after https://github.com/Particular/DocsEngine/pull/251 is deployed.

README info about suppressRelated

---

Snippets/CloudServicesHost/CloudServicesHost_7/CloudServicesHost_7.csproj
Snippets/CloudServicesHost/CloudServicesHost_7/packages.config
samples/azure/shared-host/CloudServicesHost_7/HostWorker/HostWorker.csproj
samples/azure/shared-host/CloudServicesHost_7/HostWorker/packages.config
samples/azure/shared-host/CloudServicesHost_7/Receiver/NServiceBus.Hosting.Azure.HostProcess.exe.config
samples/azure/shared-host/CloudServicesHost_7/Receiver/Receiver.csproj
samples/azure/shared-host/CloudServicesHost_7/Receiver/app.config
samples/azure/shared-host/CloudServicesHost_7/Receiver/packages.config
samples/azure/shared-host/CloudServicesHost_7/Sender/Sender.csproj
samples/azure/shared-host/CloudServicesHost_7/Sender/app.config
samples/azure/shared-host/CloudServicesHost_7/Sender/packages.config

Primed, smoked, and ready to be eaten.
@Particular/docs-maintainers please review. Bon Appétit!

Azure host rc2 update

---

nservicebus/msmq/subscription-persistence.md
nservicebus/msmq/subscription-persistence_config_core_[,4].partial.md
nservicebus/msmq/subscription-persistence_config_core_[5.0,].partial.md

relates to https://github.com/Particular/NServiceBus/issues/4147
/cc @andreasohlund

Adjust MSMQ subscription storage doco to actual behavior

---

menu/menu.yaml

resolves https://github.com/Particular/docs.particular.net/issues/1744

reorganize "messaging section"

---

nservicebus/upgrades/release-policy.md

Clarify how we backport

---

nservicebus/azure-storage-queues/multi-storageaccount-support.md
nservicebus/azure-storage-queues/multi-storageaccount-support_aliases_asq_[7,].partial.md

Connects to #1865
Multi storage accounts gets partialized in regards to aliases. Based on the following https://github.com/Particular/docs.particular.net/issues/1865#issuecomment-248010424

ASQ Multi Storage Accounts partialized

---

nservicebus/azure-service-bus/sanitization.md

@Particular/docs-maintainers we've missed a sample :)

added sample link

---

samples/nhibernate/simple/NHibernate_5/Client/App.config
samples/nhibernate/simple/NHibernate_5/Client/Client.csproj
samples/nhibernate/simple/NHibernate_5/Client/OrderCompletedHandler.cs
samples/nhibernate/simple/NHibernate_5/Client/Program.cs
samples/nhibernate/simple/NHibernate_5/Client/packages.config
samples/nhibernate/simple/NHibernate_5/Sample.sln
samples/nhibernate/simple/NHibernate_5/Sample.sln.DotSettings
samples/nhibernate/simple/NHibernate_5/Server/App.config
samples/nhibernate/simple/NHibernate_5/Server/CompleteOrder.cs
samples/nhibernate/simple/NHibernate_5/Server/OrderSaga.cs
samples/nhibernate/simple/NHibernate_5/Server/OrderSagaData.cs
samples/nhibernate/simple/NHibernate_5/Server/OrderShipped.cs
samples/nhibernate/simple/NHibernate_5/Server/OrderShippedMap.cs
samples/nhibernate/simple/NHibernate_5/Server/Program.cs
samples/nhibernate/simple/NHibernate_5/Server/Server.csproj
samples/nhibernate/simple/NHibernate_5/Server/ShipOrder.cs
samples/nhibernate/simple/NHibernate_5/Server/ShipOrderHandler.cs
samples/nhibernate/simple/NHibernate_5/Server/packages.config
samples/nhibernate/simple/NHibernate_5/Shared/ConfigErrorQueue.cs
samples/nhibernate/simple/NHibernate_5/Shared/OrderCompleted.cs
samples/nhibernate/simple/NHibernate_5/Shared/Shared.csproj
samples/nhibernate/simple/NHibernate_5/Shared/StartOrder.cs
samples/nhibernate/simple/NHibernate_5/Shared/packages.config

Adding a sample for version 5 of NServiceBus.NHibernate.
Not sure if there is value in this, but I needed to do it for a support case so perhaps it can just be included anyway.

Add a sample for version 5

---

nservicebus/upgrades/support-policy.md

Resolves https://github.com/Particular/PlatformDevelopment/issues/917.
Connects to https://github.com/Particular/V6Launch/issues/99

Clarify upgrade policy

---

nservicebus/operations/performance-counters.md
samples/performance-counters/sample.md

- Clarified that endpoints must be restarted before data will be collected
- Added instructions to install counters

Clarify startup behaviour for performance counters

---

Snippets/Autofac/Autofac_6/Autofac_6.csproj
Snippets/Autofac/Autofac_6/packages.config
Snippets/Castle/Castle_6/Castle_6.csproj
Snippets/Castle/Castle_6/packages.config
Snippets/Core/Core_6/Core_6.csproj
Snippets/Core/Core_6/packages.config
Snippets/Ninject/Ninject_6/Ninject_6.csproj
Snippets/Ninject/Ninject_6/packages.config
Snippets/Spring/Spring_7/Spring_7.csproj
Snippets/Spring/Spring_7/packages.config
Snippets/Unity/Unity_7/Unity_7.csproj
Snippets/Unity/Unity_7/packages.config
samples/containers/autofac/Autofac_6/Sample/Sample.csproj
samples/containers/autofac/Autofac_6/Sample/packages.config
samples/containers/ninject/Ninject_6/Sample/Sample.csproj
samples/containers/ninject/Ninject_6/Sample/packages.config
samples/containers/spring/Spring_7/Sample/Sample.csproj
samples/containers/spring/Spring_7/Sample/packages.config
samples/containers/unity/Unity_7/Sample/Sample.csproj
samples/containers/unity/Unity_7/Sample/packages.config
samples/endpoint-configuration/Core_6/Sample/Sample.csproj
samples/endpoint-configuration/Core_6/Sample/packages.config
samples/web/asp-mvc-application/Core_6/AsyncPagesMVC/AsyncPagesMVC.csproj
samples/web/asp-mvc-application/Core_6/AsyncPagesMVC/packages.config
samples/web/send-from-mvc-controller/Core_6/WebApplication/WebApplication.csproj
samples/web/send-from-mvc-controller/Core_6/WebApplication/packages.config

cc @Particular/container-maintainers

Update containers to RC2

---

Snippets/Autofac/Autofac_6/Autofac_6.csproj
Snippets/Autofac/Autofac_6/Upgrade.cs
nservicebus/upgrades/5to6/container.md

Relates to https://github.com/Particular/NServiceBus/issues/4144
and corresponding PRs on containers

Mentioning breaking change for containers in upgrade guide

---

nservicebus/messaging/publish-subscribe/index.md

@Particular/docs-maintainers is this the way to go or do we add partials? (we'll backport the removal to 5.2.X as well)
* Upgrade guide

[WIP]Remove versioning section

---

nservicebus/ravendb/outbox.md

@Particular/ravendb-persistence-maintainers @Particular/docs-maintainers please review

table has no meaning in RavenDB context

---

nservicebus/sagas/concurrency.md

@Particular/ravendb-persistence-maintainers @Particular/docs-maintainers please review

expand to scaled out scenarios

---

nservicebus/ravendb/manual-dtc-settings.md

@Particular/ravendb-persistence-maintainers @Particular/docs-maintainers please review

small update and doco review

---

nservicebus/ravendb/version-compatibility.md

@Particular/ravendb-persistence-maintainers please review

adding details about v6

---

Snippets/Core/Core_6/Core_6.csproj
Snippets/Core/Core_6/packages.config
Snippets/Raven/Raven_4/Raven_4.csproj
Snippets/Raven/Raven_4/packages.config
samples/ravendb/simple/Raven_4/Server/Server.csproj
samples/ravendb/simple/Raven_4/Server/packages.config
samples/saga/ravendb-custom-sagafinder/Raven_4/Sample/Sample.csproj
samples/saga/ravendb-custom-sagafinder/Raven_4/Sample/packages.config

Upgrade raven to rc2

---

nservicebus/sqlserver/deployment-options_multi-instance_sqlserver_[,3].partial.md
nservicebus/sqlserver/index.md
nservicebus/upgrades/sqlserver-2to3.md

/cc: @Particular/sqlserver-transport-maintainers

Sql multi-instance mode depricated but for now will not be removed.

---

nservicebus/nhibernate/accessing-data_direct-access_nhibernate_[6,7).partial.md

@SimonCropp This addresses your comments on #1973 (already merged).

Improve wording in NHibernate data access doco

---

nservicebus/rabbitmq/routing-topology.md

Connects to #1952
/cc @Particular/rabbitmq-transport-maintainers

routing-topology - wording and grammar improvements

---

nservicebus/sqlserver/index.md

shouldn't we include this on the advantages?

List DTC support as advantage

---

menu/menu.yaml
nservicebus/endpoints/decommissioning-endpoints.md
nservicebus/ravendb/reroute-existing-timeouts-fields-raven-[3].partial.md
nservicebus/ravendb/reroute-existing-timeouts-fields-raven-[4].partial.md
nservicebus/ravendb/reroute-existing-timeouts.md

@Particular/docs-maintainers please have a look as I am not entirely sure if I used partials correcly and if it is the place that this content should reside in.

Adding documentation for rerouting timeouts

---

nservicebus/rabbitmq/routing-topology.md

Fixes https://github.com/Particular/NServiceBus.RabbitMQ/issues/183
@Particular/docs-maintainers @Particular/rabbitmq-transport-maintainers please have a look if this approach make sense? this PR still need more work but I want to show which direction I am heading to minimize the chances that I am doing something in a sub-optimal manner

Expanding on how routing topologies work

---

menu/menu.yaml
nservicebus/licensing/index.md
nservicebus/ravendb/licensing.md

Added ravendb license page

---

servicecontrol/db-compaction.md

@Particular/servicecontrol-maintainers please review
@Particular/ravendb-persistence-maintainers can you confirm the outlined steps?

updates the compaction steps based on the new Management utility

---

samples/azure/storage-persistence/ASP_1/Server/app.config

Fixes ASP sample that wasn't working.

ASP sample fix

---

servicepulse/event-types.md
servicepulse/intro-endpoints-custom-checks.md
servicepulse/intro-endpoints-heartbeats.md

cc: @Particular/docs-maintainers please merge in

The last 3 pages of SP now has reviewed by date. Doco looks good

---

Snippets/Core/Core_6/Core_6.csproj
Snippets/Core/Core_6/packages.config
Snippets/Raven/Raven_4/Raven_4.csproj
Snippets/Raven/Raven_4/packages.config
samples/ravendb/simple/Raven_4/Server/Server.csproj
samples/ravendb/simple/Raven_4/Server/packages.config
samples/saga/ravendb-custom-sagafinder/Raven_4/Sample/Sample.csproj
samples/saga/ravendb-custom-sagafinder/Raven_4/Sample/packages.config

Raven RTM upgrade

---

Snippets/ASQ/ASQ_7/ASQ_7.csproj
Snippets/ASQ/ASQ_7/packages.config
samples/azure/shared-host/CloudServicesHost_7/Receiver/Receiver.csproj
samples/azure/shared-host/CloudServicesHost_7/Receiver/packages.config
samples/azure/shared-host/CloudServicesHost_7/Sender/Sender.csproj
samples/azure/shared-host/CloudServicesHost_7/Sender/packages.config
samples/azure/storage-queues/ASQ_7/Endpoint1/Endpoint1.csproj
samples/azure/storage-queues/ASQ_7/Endpoint1/app.config
samples/azure/storage-queues/ASQ_7/Endpoint1/packages.config
samples/azure/storage-queues/ASQ_7/Endpoint2/Endpoint2.csproj
samples/azure/storage-queues/ASQ_7/Endpoint2/app.config
samples/azure/storage-queues/ASQ_7/Endpoint2/packages.config

Connects to https://github.com/Particular/V6Launch/issues/4

Bump to NServiceBus.Azure.Transports.WindowsAzureStorageQueues 7.0.0

---

nservicebus/upgrades/5to6/index.md

Fixes https://github.com/Particular/docs.particular.net/issues/1902
@SimonCropp @mikeminutillo - any more references?

Removed the note to include the -pre release option.

---

nservicebus/containers/index_content_core_[,5].partial.md

Closes https://github.com/Particular/docs.particular.net/issues/2002
@Particular/docs-maintainers thoughts?

Clarify v5 dispose sequence

---

nservicebus/upgrades/release-policy.md

Is this the right home for this?
If yes we'll update platdev to link here and only have specific instructions related to our internal process in platdev

Add release quality details

---

Snippets/Core/Core_6/Routing/MSMQ/InstanceMappingFileScaleOut.xml

see https://github.com/Particular/NServiceBus/issues/4154

Machine attribute is case sensitive

---

nservicebus/messaging/discard-old-messages.md

Based on issue https://github.com/Particular/PlatformDevelopment/issues/978 and the [comment from @tmasternak](https://github.com/Particular/PlatformDevelopment/issues/978#issuecomment-253770944)

Clock synchronization issues

---

samples/sqltransport/simple/sample.md

SQL sample typo

---

samples/rabbitmq/simple/sample.md

/cc @Particular/rabbitmq-transport-maintainers

review simple rabbit sample

---

serviceinsight/sequence-diagram/index.md

Fixes #2055
@Particular/docs-maintainers @Particular/serviceinsight-maintainers please review.

[WIP] Reviewed SI sequence diagram page

---

nservicebus/hosting/nservicebus-host/nservicebus-32-bit-x86-host-process.md

https://github.com/Particular/docs.particular.net/issues/2082

Review of nservicebus-32-bit-x86-host-process.md

---

nservicebus/azure-storage-queues/index.md

Connects to #2062 
The dangling link fixed.

ASQ index review

---

serviceinsight/sequence-diagram/index.md

This time largely focused on tweaking the language used.
@Particular/docs-maintainers @Particular/serviceinsight-maintainers please review.

second review of SI sequence diagram page

---

samples/azure/performance-tuning-asb/ASB_7/FastNonAtomicReceiver/SomeMessageHandler.cs

@yvesgoeleven handler should not send anything since it's receive sample. Could you please confirm?

FastNonAtomicReceiver handler should not send

---

nservicebus/azure-storage-queues/configuration.md
nservicebus/azure-storage-queues/faq.md

ASQ Adding missing `reviewed` headers added to the pages that were recently reviewed

---

nservicebus/messaging/delayed-delivery.md

Adding the doco for HandleCurrentMessageLater

---

nservicebus/recoverability/configure-immediate-retries.md
nservicebus/recoverability/configure-immediate-retries_config_core_[6.0,).partial.md

review for immediate retries doco

---

nservicebus/recoverability/configure-error-handling.md

closes  #2074
ping @danielmarbach

Error configuration review

---

Snippets/CloudServicesHost/CloudServicesHost_7/logging.xml
nservicebus/hosting/cloud-services-host/faq.md
nservicebus/hosting/cloud-services-host/index.md
nservicebus/hosting/cloud-services-host/index_web_cloudserviceshost_[,7).partial.md
nservicebus/hosting/cloud-services-host/index_web_cloudserviceshost_[7,).partial.md
nservicebus/hosting/cloud-services-host/index_worker_cloudserviceshost_[,7).partial.md
nservicebus/hosting/cloud-services-host/index_worker_cloudserviceshost_[7,).partial.md
nservicebus/hosting/cloud-services-host/logging.md

Review as requested for
https://github.com/Particular/docs.particular.net/issues/2069
https://github.com/Particular/docs.particular.net/issues/2067
https://github.com/Particular/docs.particular.net/issues/2066

review of azure hosting content

---

nservicebus/msmq/scalability-and-ha/sender-side-distribution.md
nservicebus/upgrades/5to6/distributor.md

Clarifies that SSD model has no flow control, sugested by Steve https://groups.google.com/forum/#!msg/particularsoftware/cjjulDns9Hc/bX_KuqDpAwAJ

Clarify no flow control in SSD

---

nservicebus/recoverability/configure-delayed-retries.md
nservicebus/recoverability/configure-delayed-retries_config_core_[6.0,).partial.md
nservicebus/recoverability/configure-delayed-retries_legacy_core_[6,7].partial.md

delayed retries review

---

samples/step-by-step/sample.md

Updated the framework version information in the guide

---

menu/menu.yaml
nservicebus/hosting/override-hostid.md

Relates to https://github.com/Particular/docs.particular.net/issues/2076
Should this be on the ServiceControl configuration instead on the NServiceBus hosting section?

Review override-hostid.md

---

Snippets/Host/Host_4/Host_4.csproj
Snippets/Host/Host_4/Profiles/CustomProfiles.cs
nservicebus/hosting/nservicebus-host/profiles.md

relates to https://github.com/Particular/docs.particular.net/issues/2083

Review hosting profiles page

---

samples/azure/performance-tuning-asb/ASB_7/Shared/ReceiveCounter.cs

Fix concurrency issue with ASB performance samples

---

servicepulse/troubleshooting.md

Troubleshooting based on https://github.com/Particular/ServiceControl/issues/828

ServicePulse reports empty failed message groups

---

Snippets/SimpleInjector/SimpleInjector_1/SimpleInjector_1.csproj
Snippets/SimpleInjector/SimpleInjector_1/Usage.cs
Snippets/SimpleInjector/SimpleInjector_1/packages.config
nservicebus/containers/simpleinjector.md

* Update to version 1.0.1 of NServiceBus.SimpleInjector
* Add a sample showing how to use an existing container with Simple Injector.
Ping @Particular/docs-maintainers

Add snippet for using an existing container

---

samples/scaleout/distributor-upgrade/sample.md

Fixes capacity explanation

---

servicecontrol/creating-config-file.md

Update for https://github.com/Particular/ServiceControl/pull/827

Added EventRetentionPeriod setting

---

nservicebus/hosting/cloud-services-host/startup.md

reviewed azure host startup

---

nservicebus/nhibernate/sql-azure.md

Review Sql azure docs

---

nservicebus/hosting/nservicebus-host/logging.md
nservicebus/hosting/nservicebus-host/logging_customize_host_[,4].partial.md
nservicebus/hosting/nservicebus-host/logging_customize_host_[5,].partial.md

Review host logging page

---

nservicebus/lifecycle/index.md

Review Lifecycle homepage

---

platform/release-notes.md

Removed the old Azure transport link
Closes #2202

Review platform releases page

---

nservicebus/wcf/index.md

Reviewed WCF page

---

nservicebus/messaging/non-durable-messaging.md

Clarify limitations of msmq express messages

---

README.md

Ping @SimonCropp 
Is it ok or repetitive to much?

Explicit reminder to use nuget aliases instead of components in partials

---

nservicebus/pipeline/context-map-generator.linq
nservicebus/pipeline/context-map.svg
nservicebus/pipeline/steps-stages-connectors_extra_core_[6.0,).partial.md

There is no `IFaultContext` any more.
Also there are some other contexts that are not mentioned here. Should some/all of these be added? Were they left out intentionally?
- **Transport Receive** comes before Incoming Physical Message. It is executed even before the outbox and the batch sending catcher. I don't think anyone would ever need to drop a behavior in here so leaving it out is probably fine.
- **Routing** comes after Outgoing Physical. Is currently used to force immediate dispatch, attach sender info, and route deferred messages to the timeout manager. Also catches messages in the batch dispatch bucket.
- **Dispatch** comes after routing. It currently just contains a terminator for handing off to the transport
- **Batch Dispatch** is invoked for outgoing messages that are sent …

[WIP] Update Pipeline Stages

---

nservicebus/persistence/index.md

Very minor - will self merge assuming it passes valdiation.
Received from SF case 22393

Subscriptions link was pointing to sagas

---

nservicebus/nhibernate/index.md

Very small, same issue as #2226, but @Particular/nhibernate-persistence-maintainers could I get a quick review to make sure this is good with you?

Fixing, adding links for NH supported persistence features

---

servicecontrol/troubleshooting.md

The MaxVerPages is now handled automatically as part of the installation.
Exposing ravendb database is now handled via "maintenance mode"

Remove deprecated sections

---

nservicebus/hosting/publishing-from-web-applications.md

Review publishing from webapps

---

nservicebus/messaging/reply-to-a-message.md
nservicebus/messaging/reply-to-a-message_influence_core_[5.0,).partial.md
nservicebus/messaging/send-a-message_influence-reply_core_[5.0,].partial.md

Review reply-to-a-message.md

---

nservicebus/azure-storage-persistence/configuration.md
nservicebus/azure-storage-persistence/configuration_sections_asp_[1,].partial.md
nservicebus/azure-storage-persistence/configuration_sections_azure_[,6.2].partial.md

This removes a few versioned related notes and makes the configuration.md less version dependent (there's one note at the end, but I'm not going to push a partial for one config value).

[WIP] ASP configuration clarified

---

nservicebus/operations/tuning.md
nservicebus/operations/tuning_configuration_core_[,5].partial.md
nservicebus/operations/tuning_configuration_core_[6,).partial.md
nservicebus/operations/tuning_defaults_core_[,5].partial.md
nservicebus/operations/tuning_defaults_core_[6,).partial.md
nservicebus/operations/tuning_runtime_core_[4,5].partial.md
nservicebus/operations/tuning_throttling_core_[,5].partial.md
nservicebus/operations/tuning_throttling_core_[6,).partial.md

relates to https://github.com/Particular/docs.particular.net/issues/2181

review tuning.md

---

nservicebus/security/index.md

Update security index

---

nservicebus/rabbitmq/routing-topology.md

Fixes https://github.com/Particular/NServiceBus.RabbitMQ/issues/268

warn about interfaces with direct routing topology

---

nservicebus/security/encryption.md
nservicebus/security/encryption_keyformat_core_[5.0,).partial.md
samples/encryption/basic-encryption/Core_4/Endpoint2/Handler.cs
samples/encryption/basic-encryption/Core_5/Endpoint2/Handler.cs
samples/encryption/basic-encryption/Core_6/Endpoint2/Handler.cs

Update encryption page

---

nservicebus/rabbitmq/routing-topology.md

fix for changes in #2252 
fixes Particular/NServiceBus.RabbitMQ#268

fix link in direct routing topology warning

---

nservicebus/messaging/discard-old-messages.md
nservicebus/messaging/discard-old-messages_msmq_core_[6.0,).partial.md

Related to https://github.com/Particular/docs.particular.net/issues/2168

Clarify msmq TTBR

---

nservicebus/pipeline/manipulate-with-behaviors_registernew_core_[6.0,).partial.md

@andreasohlund @Particular/docs-maintainers thoughts? Should the snippet maybe have a sample of to use the "DI registration" to have more context on that warning?

Mention behavior lifetime

---

nservicebus/rabbitmq/routing-topology.md
nservicebus/rabbitmq/routing-topology_delegate-argument_rabbit_[4,].partial.md
nservicebus/rabbitmq/routing-topology_queue-declaration_rabbit_[4,].partial.md

connects to https://github.com/Particular/NServiceBus.RabbitMQ/issues/248

add queue-declaration to custom routing topology

---

Snippets/Core/Core_6/Core_6.csproj
Snippets/Core/Core_6/Transports/Throughput/ConcurrencyConfiguration.cs
nservicebus/operations/tuning_configuration_core_[6,).partial.md

documents https://github.com/Particular/NServiceBus/issues/4264
based on top of https://github.com/Particular/docs.particular.net/pull/2245
requires a 6.1 unstable package available on myget.

TimeoutManager concurrency setting

---

samples/pipeline/unit-of-work/Core_6/Endpoint/Endpoint.csproj
samples/pipeline/unit-of-work/Core_6/Endpoint/IMySession.cs
samples/pipeline/unit-of-work/Core_6/Endpoint/MyEntity.cs
samples/pipeline/unit-of-work/Core_6/Endpoint/MyMessage.cs
samples/pipeline/unit-of-work/Core_6/Endpoint/MyMessageHandler1.cs
samples/pipeline/unit-of-work/Core_6/Endpoint/MyMessageHandler2.cs
samples/pipeline/unit-of-work/Core_6/Endpoint/MyOtherEntity.cs
samples/pipeline/unit-of-work/Core_6/Endpoint/MySession.cs
samples/pipeline/unit-of-work/Core_6/Endpoint/MySessionContextExtensions.cs
samples/pipeline/unit-of-work/Core_6/Endpoint/MySessionProvider.cs
samples/pipeline/unit-of-work/Core_6/Endpoint/MyUowBehavior.cs
samples/pipeline/unit-of-work/Core_6/Endpoint/Program.cs
samples/pipeline/unit-of-work/Core_6/Endpoint/packages.config
samples/pipeline/unit-of-work/Core_6/UnitOfWork.sln
samples/pipeline/unit-of-work/Core_6/UnitOfWork.sln.DotSettings
samples/pipeline/unit-of-work/sample.md

Needs a review and also a discussion about how to dispose the session (now leaning on the container)
Related to https://github.com/Particular/NServiceBus/issues/4281

UOW sample using the pipeline

---

samples/pipeline/unit-of-work/Core_6/Endpoint/Program.cs
samples/pipeline/unit-of-work/sample.md

cc @timbussmann @danielmarbach

Stop using DI for the session factory

---

nservicebus/upgrades/5to6/index.md
nservicebus/upgrades/index.md

Moved the generic points of upgrade to the landing page

---

menu/menu.yaml
nservicebus/ravendb/index.md
nservicebus/ravendb/subscription-versioning.md

@Particular/ravendb-persistence-maintainers this is a very first draft to document the issue and workaround outlined in https://github.com/Particular/PlatformDevelopment/issues/960
Connects to https://github.com/Particular/PlatformDevelopment/issues/960
To do:

RavenDB subscription-versioning

---

home.md

Linked Getting Started to tutorial

Linked Getting Started to tutorial

---

nservicebus/operations/performance-counters.md

reinstall-perfcounters

---

nservicebus/messaging/best-practice-enforcement.md

https://twitter.com/johncmolyneux/status/803580079850790913

small typo

---

Snippets/MsmqTransport/MsmqTransport_All/QueueCreation/QueueCreation.ps1
Snippets/MsmqTransport/MsmqTransport_All/QueueCreation/QueueCreationUtils.cs

Connects to Particular/PlatformDevelopment#1039

Do not modify permissions for existing queues

---

tutorials/nservicebus-101/lesson-5/tutorial.md

Resolves comments from https://github.com/Particular/Academy/issues/15

Nsb101 reviews

---

servicecontrol/creating-config-file.md

Related to https://github.com/Particular/ServiceControl/pull/852
Merge when ServiceControl v1.29 ships

Forwarding Queues only created as needed

---

nservicebus/pipeline/steps-stages-connectors_extra_core_[6.0,).partial.md

This is to resolve concerns raised in Particular/NServiceBus#4354

Move pipeline customization warning to top of page

---

nservicebus/operations/tuning.md

Minor change on the tuning docs (https://docs.particular.net/nservicebus/operations/tuning) changing the usage of "to" to "too".

Changing "to" to "too"

---

samples/routing-slips/sample.md

Typo "away"

---

tutorials/nservicebus-101/lesson-1/tutorial.md
tutorials/nservicebus-101/lesson-2/tutorial.md
tutorials/nservicebus-101/lesson-5/tutorial.md

Fixes https://github.com/Particular/Academy/issues/13

NSB101 review notes

---

samples/pipeline/unit-of-work/Core_6/Endpoint/MySession.cs
samples/pipeline/unit-of-work/Core_6/Endpoint/MySessionProvider.cs
samples/pipeline/unit-of-work/Core_6/Endpoint/MyUowBehavior.cs
samples/pipeline/unit-of-work/Core_6/Endpoint/Program.cs

Fix typo in sample

---

servicecontrol/plugins/heartbeat.md

Acted on feedback in  #2329 
@SimonCropp  review please

Added Heartbeat Nuget Table

---

nservicebus/rabbitmq/index.md

To avoid confusion, as the connection settings page is a little buried currently, and the existing text makes it sound like UseTransport is all that's required.

Link to Rabbit connection settings article

---

samples/show-case/on-premise/sample.md

@Particular/docs-maintainers thoughts?

Add showcase walkthrough diagrams

---

components/components.yaml

To be merged together with the parent docs engine pull: https://github.com/Particular/DocsEngine/pull/287

[WIP] Changed the structure of components.yaml to allow for different support levels

---

samples/unit-testing/Testing_6/Sample/BehaviorTests.cs
samples/unit-testing/Testing_6/Sample/Data/CustomBehavior.cs
samples/unit-testing/Testing_6/Sample/Sample.csproj
samples/unit-testing/sample.md

addresses https://github.com/Particular/docs.particular.net/issues/2345
Adds an example on how to test a custom behavior to the unit testing page.

Add a sample of a behavior unit test

---

platform/installer/index.md

No substantial content changes; only minor spelling and grammar changes.

Update index.md to fix typos and grammar

---

nservicebus/upgrades/5to6/extension-seams.md

Documenting the right interface that got obsoleted.
Resolves #2356

Update the transport seam document

---

servicepulse/intro-archived-messages.md

Explain usefulness of archiving and unarchiving

---

tutorials/nservicebus-101/lesson-1/tutorial.md
tutorials/nservicebus-101/lesson-2/tutorial.md
tutorials/nservicebus-101/lesson-3/tutorial.md
tutorials/nservicebus-101/lesson-4/tutorial.md
tutorials/nservicebus-101/lesson-5/tutorial.md

Related to call between Udi/Britt/Kyle/myself.
@kbaley please review

NSB101 replace objectives with paragraphs and time estimates

---

menu/menu.yaml
security-advisories/msmq-permissions.md

Connects to Particular/PlatformDevelopment#1059

MSMQ permissions security advisory

---

Snippets/Core/Core_3/Installers.cs
Snippets/Core/Core_4/Installers.cs
Snippets/Core/Core_5/Installers.cs
Snippets/Core/Core_6/Installers.cs
nservicebus/operations/installers.md

@SimonCropp Some spike code which shows the v6 part of the sample for https://github.com/Particular/docs.particular.net/issues/1889 
I'm very unsure about the AD part because I've never written AD queries before.

Installers

---

Snippets/ABSDataBus/ABSDataBus_1/Usage.cs
Snippets/ABSDataBus/Azure_6/Usage.cs
nservicebus/messaging/databus/azure-blob-storage.md
samples/azure/blob-storage-databus/ABSDataBus_1/Receiver/Receiver.csproj
samples/azure/blob-storage-databus/ABSDataBus_1/Receiver/packages.config
samples/azure/blob-storage-databus/ABSDataBus_1/Sender/Sender.csproj
samples/azure/blob-storage-databus/ABSDataBus_1/Sender/packages.config
samples/azure/blob-storage-databus/Azure_6/Receiver/Receiver.csproj
samples/azure/blob-storage-databus/Azure_6/Receiver/packages.config
samples/azure/blob-storage-databus/Azure_6/Sender/Sender.csproj
samples/azure/blob-storage-databus/Azure_6/Sender/packages.config

[WIP] Azure databus hotfix 1.0.1 and 6.2.7

---

samples/azure/index.md

Link to the cloud show case

---

Snippets/FileBasedRouting/FileBasedRouting_1/Snippets.cs
nservicebus/messaging/file-based-routing.md

documents new API in NServiceBus.FileBasedRouting 1.1.0
ping @Particular/docs-maintainers

Add new uri based configuration API to docs

---

samples/azure/shared-host/CloudServicesHost_7/Receiver/Receiver.csproj
samples/azure/shared-host/CloudServicesHost_7/Receiver/packages.config
samples/azure/shared-host/CloudServicesHost_7/Sender/Sender.csproj
samples/azure/shared-host/CloudServicesHost_7/Sender/packages.config
samples/azure/storage-persistence/ASP_1/Server/Server.csproj
samples/azure/storage-persistence/ASP_1/Server/packages.config
samples/show-case/cloud-azure/Core_6/Store.Shared/Store.Shared.csproj
samples/show-case/cloud-azure/Core_6/Store.Shared/packages.config

ASP 1.0.1 update

---

nservicebus/recoverability/index.md

@Particular/nservicebus-maintainers @SimonCropp @ramonsmits thoughts?

Document that immediate retries may happen even if turned off

---

nservicebus/messaging/third-party-integration.md

relates to https://github.com/Particular/docs.particular.net/issues/2174

Review third party integration

---

samples/rabbitmq/native-integration/Rabbit_4/Receiver/Receiver.csproj
samples/rabbitmq/native-integration/Rabbit_4/Receiver/packages.config
samples/rabbitmq/simple/Rabbit_4/Sample/Sample.csproj
samples/rabbitmq/simple/Rabbit_4/Sample/packages.config

connects to https://github.com/Particular/NServiceBus.RabbitMQ/issues/340

update to NSB.RabbitMQ 4.2.1

---

nservicebus/azure/data-distribution.md
samples/routing/data-distribution/sample.md

Fixes #2375 
Just warnings
@indualagarsamy

Data distribution warning

---

Snippets/ASB/ASB_7/MultipleNamespaces.cs

snippet missing strategy selection

---

nservicebus/upgrades/support-dates.include.md
nservicebus/upgrades/support-policy.md
tools/supportedVersions.linq

- Extracts the supported versions into an include
- Automates the generation of the include using data from NuGet

Automate support dates

---

nservicebus/sqlserver/connection-settings.md

Minimum pool size is also required to prevent warning

WIP: Update connection-settings.md

---

samples/azure/storage-queues/ASQ_7/Endpoint1/Endpoint1.csproj
samples/azure/storage-queues/ASQ_7/Endpoint1/packages.config
samples/azure/storage-queues/ASQ_7/Endpoint2/Endpoint2.csproj
samples/azure/storage-queues/ASQ_7/Endpoint2/packages.config

ASQ bump up

---

nservicebus/scheduling/index.md

warning how scheduler can be interrupted

---

samples/azure/azure-service-fabric-routing/Core_6/CandidateVoteCount/CandidateVotes.cs
samples/azure/azure-service-fabric-routing/Core_6/CandidateVoteCount/EndpointCommunicationListener.cs
samples/azure/azure-service-fabric-routing/Core_6/Contracts/CloseElection.cs
samples/azure/azure-service-fabric-routing/Core_6/Contracts/Contracts.csproj
samples/azure/azure-service-fabric-routing/Core_6/Contracts/DistributeMessagesBasedOnPayload.cs
samples/azure/azure-service-fabric-routing/Core_6/Contracts/TrackZipCodeReply.cs
samples/azure/azure-service-fabric-routing/Core_6/Contracts/VotePlaced.cs
samples/azure/azure-service-fabric-routing/Core_6/Voter/Program.cs
samples/azure/azure-service-fabric-routing/Core_6/ZipCodeVoteCount/ZipCodeVotes.cs

@danielmarbach @tmasternak @SzymonPobiega we've changed the scenario a little to demonstrate 
- pub/sub (Voter publishes `VotePlaced` and CandidateVoteCount subscribes to it) commit: 4d190f9b3c63615a751caaa63e2967339dee4597
- request/reply ( between CandidateVoteCount  and ZipCodeVoteCount) commit: e91d5efd1fc9f9df44447b71d2aba4eea94b13de

[WIP] Automated voting with VotePlaced as an event and explicit end of election with a command CloseElection

---

nservicebus/pipeline/steps-stages-connectors_extra_core_[6.0,).partial.md

@Particular/nservicebus-maintainers Please review if my description for `ITransportReceiveContext` is correct.

Added info about `ITransportReceiveContext`

---

Snippets/Core/Core_6/CustomConfigSource.cs
Snippets/Core/Core_6/Headers/Writers/HeaderWriterEncryption.cs
Snippets/Core/Core_6/Routing/Extensibility.cs
Snippets/Core/Core_6/project.json
nservicebus/messaging/routing-extensibility_content_core_[6,).partial.md

Relates to https://github.com/Particular/NServiceBus/pull/4461
@Particular/docs-maintainers wasn't exactly sure if we need more explanation. I went with the approach to have the same snippet versioned.
Since the old way still works and is supported would be still need an upgrade guide?
// cc @Particular/nservicebus-maintainers

WIP Routing strategy snippet 6.2

---

Snippets/Core/Core_6/Core_6.csproj
Snippets/Core/Core_6/CustomConfigSource.cs
Snippets/Core/Core_6/Headers/Writers/HeaderWriterEncryption.cs
Snippets/Core/Core_6/Recoverability/Delayed/CustomPolicies/CustomExceptionPolicy.cs
Snippets/Core/Core_6/Recoverability/Delayed/CustomPolicies/FullyCustomizedPolicy.cs
Snippets/Core/Core_6/Recoverability/Delayed/CustomPolicies/PartiallyCustomizedPolicy.cs
Snippets/Core/Core_6/Recoverability/UnrecoverableExceptions.cs
Snippets/Core/Core_6/project.json
nservicebus/recoverability/custom-recoverability-policy.md
nservicebus/recoverability/index.md
nservicebus/recoverability/index_unrecoverableexceptions_core_[6.0,).partial.md

Documentation for https://github.com/Particular/NServiceBus/pull/4479
@Particular/nservicebus-maintainers @Particular/docs-maintainers please review

WIP Unrecoverable exceptions

---

samples/pipeline/audit-filtering/Core_6/AuditFilter/AuditThisMessageHandler.cs
samples/pipeline/audit-filtering/Core_6/AuditFilter/Program.cs

- fixing minor log error and sending audit to centralized audit queue.
@timbussmann - have a quick look.

Audit pipeline sample V6

---

nservicebus/endpoints/specify-endpoint-name.md
nservicebus/hosting/nservicebus-host/index.md

Connects to https://github.com/Particular/docs.particular.net/issues/2487

NSB host review - part 1

---

nservicebus/rabbitmq/connection-settings_tls-details_rabbit_[3].partial.md
nservicebus/rabbitmq/connection-settings_tls-details_rabbit_[4,].partial.md

Went ahead and made the suggested changes from #2366.
Closes #2493.

Address remaining feedback on TLS settings

---

nservicebus/messaging/databus/index.md

based on https://github.com/Particular/docs.particular.net/issues/2475

DataBus feedback

---

samples/show-case/cloud-azure/Core_6/Store.ECommerce/Store.ECommerce.csproj
samples/show-case/cloud-azure/Core_6/Store.ECommerce/packages.config
samples/show-case/cloud-azure/Core_6/Store.Sales/App.config
samples/show-case/cloud-azure/Core_6/Store.Sales/Store.Sales.csproj
samples/show-case/cloud-azure/Core_6/Store.Sales/packages.config
samples/show-case/cloud-azure/Core_6/Store.Shared/CommonConfiguration.cs

The original PR was for Storage library update, but the sample was broken with 2 issues:
1. Connection string for persistence was not provided (fixed)
1. Microsoft.AspNet.Razor was targeting net45 rather than net461 (fixed)
Smoked tested locally and it's working now.

Azure show case storage library update

---

samples/azure/shared-host/CloudServicesHost_7/HostWorker/HostWorker.csproj
samples/azure/shared-host/CloudServicesHost_7/HostWorker/app.config
samples/azure/shared-host/CloudServicesHost_7/HostWorker/packages.config
samples/azure/shared-host/CloudServicesHost_7/Receiver/Receiver.csproj
samples/azure/shared-host/CloudServicesHost_7/Receiver/app.config
samples/azure/shared-host/CloudServicesHost_7/Receiver/packages.config
samples/azure/shared-host/CloudServicesHost_7/Sender/Sender.csproj
samples/azure/shared-host/CloudServicesHost_7/Sender/app.config
samples/azure/shared-host/CloudServicesHost_7/Sender/packages.config
samples/azure/shared-host/CloudServicesHost_7/Shared/Shared.csproj
samples/azure/shared-host/CloudServicesHost_7/Shared/app.config
samples/azure/shared-host/CloudServicesHost_7/Shared/packages.config

The plan is to release it tomorrow with the rest of azure storage related packages, so OK to merge.

Azure host - dependencies update

---

samples/servicecontrol/events-subscription/sample.md
servicecontrol/license.md
servicepulse/installation.md

Linked /servicecontro/license in SP license to give more clues about
licensing SP.

Linked /servicecontro/license in SP license

---

Snippets/ASQ/ASQ_7/ASQ_7.csproj
Snippets/ASQ/ASQ_7/CustomEnvelopeUnwrapper.cs
Snippets/ASQ/ASQ_7/MessageWrapperSerializer.cs
Snippets/ASQ/ASQ_7/project.json
nservicebus/azure-storage-queues/configuration.md

First part of https://github.com/Particular/docs.particular.net/issues/2389
@Particular/azure-maintainers please review

Doco for ASQ custom envelope unwrapper

---

nservicebus/msmq/index.md

Adding the machine name limitation and also documenting that [we don't support public queues]( https://github.com/Particular/docs.particular.net/issues/2470).
cc / @andreasohlund @dbelcham
@gbiellem - should we add or link to anything here where we talk about MSMQ install properties?
@Particular/docs-maintainers - please review.

Documenting MSMQ transport limitations

---

nservicebus/imanageunitsofwork-outbox.include.md
nservicebus/pipeline/unit-of-work_imanageunitsofwork-outbox_core_[6.0,).partial.md

addresses https://github.com/Particular/docs.particular.net/issues/2483
Is there the need to have the partial using an include? @Particular/docs-maintainers

Clarify transaction wrapping note

---

Snippets/Core/Core_6/Pipeline/CustomForkConnector.cs
Snippets/Core/Core_6/Pipeline/CustomStageConnector.cs
Snippets/Core/Core_6/Pipeline/CustomStageForkConnector.cs
nservicebus/pipeline/steps-stages-connectors_extra_core_[6.0,).partial.md

Closes https://github.com/Particular/docs.particular.net/issues/2508

Showing replacing existing connectors and forks

---

menu/menu.yaml
nservicebus/messaging/publish-subscribe/publish-handle-event.md

fixes https://github.com/Particular/docs.particular.net/issues/2177

Review publish events

---

Snippets/Core/Core_5/Features/Features.cs
Snippets/Core/Core_6/Features/Features.cs
nservicebus/pipeline/features.md

tries to address a feedback received here: https://github.com/Particular/NServiceBus/issues/4500#issuecomment-284465740

Show how to configure feature settings from EndpointConfiguration

---

Snippets/MsmqTransport/MsmqTransport_All/QueueCreation/QueueCreation.ps1

Updated the CreateQueue powershell sample to validate the account name,  previously it would create the queue regardless and them throw a non terminating error  when setting permissions if an invalid account was passed to it

Added account name validation

---

nservicebus/pipeline/steps-stages-connectors_extra_core_[6.0,).partial.md

addresses https://github.com/Particular/docs.particular.net/issues/2480

Remove other pipeline stages section

---

nservicebus/hosting/nservicebus-host/logging-configuration.md
nservicebus/hosting/nservicebus-host/profiles.md
nservicebus/hosting/nservicebus-host/profiles_logging_host_(,4].partial.md
nservicebus/hosting/nservicebus-host/profiles_logging_host_[5,).partial.md

Fixes https://github.com/Particular/PlatformDevelopment/issues/1170

Fix logging profiles

---

nservicebus/hosting/web-application.md

Document web application container integration recommendations

---

samples/azure/shared-host/CloudServicesHost_7/HostWorker/HostWorker.csproj
samples/azure/shared-host/CloudServicesHost_7/HostWorker/packages.config
samples/azure/shared-host/CloudServicesHost_7/Receiver/Receiver.csproj
samples/azure/shared-host/CloudServicesHost_7/Receiver/packages.config
samples/azure/shared-host/CloudServicesHost_7/Sender/Sender.csproj
samples/azure/shared-host/CloudServicesHost_7/Sender/packages.config
samples/sql-persistence/saga-rename/SqlPersistence_2/Shared/Shared.csproj
samples/sql-persistence/simple/SqlPersistence_2/EndpointMySql/EndpointMySql.csproj
samples/sql-persistence/simple/SqlPersistence_2/EndpointSqlServer/EndpointSqlServer.csproj
samples/sql-persistence/transitioning-correlation-ids/SqlPersistence_2/Phase1/EndpointMySql/EndpointMySqlPhase1.csproj
samples/sql-persistence/transitioning-correlation-ids/SqlPersistence_2/Phase1/EndpointSqlServer/EndpointSqlServerPhase1.csproj
samples/sql-persistence/transitioning-correlation-ids/SqlPersistence_2/Phase2/EndpointMySql/EndpointMySqlPhase2.csproj
samples/sql-persistence/transitioning-correlation-ids/SqlPersistence_2/Phase2/EndpointSqlServer/EndpointSqlServerPhase2.csproj
samples/sql-persistence/transitioning-correlation-ids/SqlPersistence_2/Phase3/EndpointMySql/EndpointMySqlPhase3.csproj
samples/sql-persistence/transitioning-correlation-ids/SqlPersistence_2/Phase3/EndpointSqlServer/EndpointSqlServerPhase3.csproj

Triggered by azure storage related releases
/cc @Scooletz

Updating dependencies

---

nservicebus/upgrades/5to6/callbacks.md

For callbacks endpoints need to be uniquely addressable

---

samples/azure/blob-storage-databus/ABSDataBus_1/Receiver/Receiver.csproj
samples/azure/blob-storage-databus/ABSDataBus_1/Receiver/app.config
samples/azure/blob-storage-databus/ABSDataBus_1/Receiver/packages.config
samples/azure/blob-storage-databus/ABSDataBus_1/Sender/Sender.csproj
samples/azure/blob-storage-databus/ABSDataBus_1/Sender/app.config
samples/azure/blob-storage-databus/ABSDataBus_1/Sender/packages.config
samples/azure/shared-host/CloudServicesHost_7/Receiver/Receiver.csproj
samples/azure/shared-host/CloudServicesHost_7/Receiver/app.config
samples/azure/shared-host/CloudServicesHost_7/Receiver/packages.config
samples/azure/shared-host/CloudServicesHost_7/Sender/Sender.csproj
samples/azure/shared-host/CloudServicesHost_7/Sender/app.config
samples/azure/shared-host/CloudServicesHost_7/Sender/packages.config
samples/azure/storage-persistence/ASP_1/Server/Server.csproj
samples/azure/storage-persistence/ASP_1/Server/app.config
samples/azure/storage-persistence/ASP_1/Server/packages.config
samples/azure/storage-queues/ASQ_7/Endpoint1/Endpoint1.csproj
samples/azure/storage-queues/ASQ_7/Endpoint1/app.config
samples/azure/storage-queues/ASQ_7/Endpoint1/packages.config
samples/azure/storage-queues/ASQ_7/Endpoint2/Endpoint2.csproj
samples/azure/storage-queues/ASQ_7/Endpoint2/app.config
samples/azure/storage-queues/ASQ_7/Endpoint2/packages.config
samples/show-case/cloud-azure/Core_6/Store.ECommerce/Web.config
samples/show-case/cloud-azure/Core_6/Store.Shared/Store.Shared.csproj
samples/show-case/cloud-azure/Core_6/Store.Shared/app.config
samples/show-case/cloud-azure/Core_6/Store.Shared/packages.config

This PR bumps up ASQ, ASP, Azure Blob Storage DataBus.
The related issues:
https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/187
https://github.com/Particular/NServiceBus.Persistence.AzureStorage/issues/135
https://github.com/Particular/NServiceBus.DataBus.AzureBlobStorage/issues/19

ASQ, ASP, Azure Blob Storage DataBus bumped up & smoke tested

---

Snippets/SqlServer/SqlServer_3/MultiSchema.cs
nservicebus/sqlserver/addressing_content_sqlserver_[3,3.1).partial.md

@MarcinHoppe does it read better then the current version?

Clarified usages of UseSchemaForQueue and UseSchemaForEndpoint

---

samples/azure/azure-service-fabric-routing/Core_6/CandidateVoteCount/CandidateVoteCount.csproj
samples/azure/azure-service-fabric-routing/Core_6/CandidateVoteCount/CandidateVoteCountService.cs
samples/azure/azure-service-fabric-routing/Core_6/CandidateVoteCount/CandidateVotesSaga.cs
samples/azure/azure-service-fabric-routing/Core_6/CandidateVoteCount/EndpointCommunicationListener.cs
samples/azure/azure-service-fabric-routing/Core_6/CandidateVoteCount/app.config
samples/azure/azure-service-fabric-routing/Core_6/CandidateVoteCount/packages.config
samples/azure/azure-service-fabric-routing/Core_6/Contracts/Contracts.csproj
samples/azure/azure-service-fabric-routing/Core_6/Contracts/packages.config
samples/azure/azure-service-fabric-routing/Core_6/ServiceFabricRouting/ApplicationPackageRoot/ApplicationManifest.xml
samples/azure/azure-service-fabric-routing/Core_6/ServiceFabricRouting/ApplicationParameters/Local.5Node.xml
samples/azure/azure-service-fabric-routing/Core_6/ServiceFabricRouting/Scripts/Deploy-FabricApplication.ps1
samples/azure/azure-service-fabric-routing/Core_6/ServiceFabricRouting/ServiceFabricRouting.sfproj
samples/azure/azure-service-fabric-routing/Core_6/ServiceFabricRouting/packages.config
samples/azure/azure-service-fabric-routing/Core_6/Shared/EndpointConfigurationExtensions.cs
samples/azure/azure-service-fabric-routing/Core_6/Shared/SagaEntry.cs
samples/azure/azure-service-fabric-routing/Core_6/Shared/Shared.csproj
samples/azure/azure-service-fabric-routing/Core_6/Shared/app.config
samples/azure/azure-service-fabric-routing/Core_6/Shared/packages.config
samples/azure/azure-service-fabric-routing/Core_6/Voter/Program.cs
samples/azure/azure-service-fabric-routing/Core_6/Voter/Voter.csproj
samples/azure/azure-service-fabric-routing/Core_6/Voter/app.config
samples/azure/azure-service-fabric-routing/Core_6/Voter/packages.config
samples/azure/azure-service-fabric-routing/Core_6/ZipCodeVoteCount/EndpointCommunicationListener.cs
samples/azure/azure-service-fabric-routing/Core_6/ZipCodeVoteCount/ZipCodeVoteCount.csproj
samples/azure/azure-service-fabric-routing/Core_6/ZipCodeVoteCount/ZipCodeVoteCountService.cs
samples/azure/azure-service-fabric-routing/Core_6/ZipCodeVoteCount/ZipCodeVotesSaga.cs
samples/azure/azure-service-fabric-routing/Core_6/ZipCodeVoteCount/app.config
samples/azure/azure-service-fabric-routing/Core_6/ZipCodeVoteCount/packages.config

Service fabric sample with SF persistence

---

Snippets/PerfCounters/PerfCounters_1/project.json
samples/performance-counters/PerfCounters_1/Sample/Sample.csproj
samples/performance-counters/PerfCounters_1/Sample/packages.config

Update to NServiceBus.Metrics.PerformanceCounters 1.0 stable
Remove prerelease markers

Perf counters stable

---

nservicebus/pipeline/customizing-error-handling.md
nservicebus/pipeline/customizing-error-handling_content_core_(,6.0).partial.md
nservicebus/pipeline/customizing-error-handling_content_core_[6.0,).partial.md

Should we mention in this page the new recoverability policy or at least link to it?

Review custom error handling

---

nservicebus/pipeline/events.md

/cc: @timbussmann @andreasohlund

Receive pipeline completed not called when pipeline processing fails

---

Snippets/SimpleInjector/SimpleInjector_1/Usage.cs
Snippets/SimpleInjector/SimpleInjector_1/project.json
samples/containers/simpleinjector/SimpleInjector_1/Sample/Sample.csproj
samples/containers/simpleinjector/SimpleInjector_1/Sample/packages.config

Updates the Simple Injector samples and snippets to V2 of NServiceBus.SimpleInjector

Update SimpleInjector samples and snippets to v2

---

nservicebus/upgrades/nhibernate-timeouts-index.md

Guidance for https://github.com/Particular/PlatformDevelopment/issues/1145

NHibernate timeout index guidance

---

nservicebus/messaging/callbacks_route_callbacks_[1,).partial.md

Fixes #2563 
User mentioned that difference between shared queue and callback queue wasn't clear.

Clarifying additional callback queue

---

samples/containers/autofac/Autofac_6/Sample/Program.cs

Changes the sample to show how to use an existing container and inject the IEndpointInstance into the container as well.
Ping @Particular/container-maintainers

Update autofac sample to show existing container usage

---

nservicebus/sagas/index.md

Describing the design approach of "never-ending" sagas to avoid having sagas request/response data from other endpoints.

Sagas that live forever

---

nservicebus/messaging/callbacks.md

If there is no callback waiting when they arrive

Clarify that int callbacks won't cause messages to go to the error queue

---

nservicebus/messaging/databus/index.md

Fixed questionable bullet from databus doco

---

nservicebus/azure-storage-persistence/index.md
nservicebus/azure-storage-persistence/index_config_asp_[1,].partial.md
nservicebus/azure-storage-persistence/index_config_azure_[,6].partial.md
nservicebus/azure-storage-persistence/index_correlation_asp_[1,].partial.md
nservicebus/azure-storage-persistence/index_correlation_azure_[,6].partial.md

Azure Storage Persistence index review

---

nservicebus/sqlserver/connection-settings_circuit-breaker_sqlserver_[3,).partial.md

Resolves #2657
@Particular/docs-maintainers This is a minor one. Please review at your convenience.

Removed the redundant partial from sql v3

---

nservicebus/azure/azure-compared-to-msmq.include.md

The unfriendly "The short answer is no." has been reworded.

[WIP] azure-compared-to-msmq slightly reworded

---

nservicebus/azure-storage-queues/configuration.md
nservicebus/azure-storage-queues/configuration_connectionstring_asq_[,6].partial.md
nservicebus/azure-storage-queues/configuration_connectionstring_asq_[7,].partial.md
nservicebus/azure-storage-queues/configuration_parallelismdegree_asq_[7,].partial.md

This PR extracts connection string default values and DegreeOfReceiveParallelism into properly versioned partials.

[WIP] ASQ configuration extracted to versioned partials

---

nservicebus/azure-storage-queues/index.md

Mention ASQ instead of ASB, slight rewording.

ASQ index minors

---

Snippets/Metrics/Metrics_1/project.json
menu/menu.yaml
samples/metrics/tracing/Metrics_1/Endpoint/Endpoint.csproj
samples/metrics/tracing/Metrics_1/Endpoint/packages.config

Metrics update

---

platform/installer/index.md

Connects to: https://github.com/Particular/PlatformInstaller/issues/207

Platform installer performance counters

---

nservicebus/messaging/routing.md

Fixes #2658
@timbussmann could you verify this note makes sense from the core's perspective?
Thanks.

Pub/sub note for ASB's old topology

---

servicepulse/intro-failed-messages.md

Addresses #2673
@WilliamBZA please review

added endpoint address grouping option

---

Snippets/Rabbit/Rabbit_All/project.json
samples/rabbitmq/native-integration/Rabbit_4/Receiver/Receiver.csproj
samples/rabbitmq/simple/Rabbit_4/Sample/Sample.csproj

Updating samples and snippets to NSB.Rabbit 4.3.1

---

nservicebus/msmq/index.md
nservicebus/msmq/uninstalling-msmq.md

remove Windows 7 and 2008. support ended January 2015

Obsolete os

---

nservicebus/handlers/async-handlers.md

Async handler improvements

---

nservicebus/sql-persistence/index.md

fixes https://github.com/Particular/NServiceBus.Persistence.Sql/issues/89

add warning about project json and sql scripts

---

samples/entity-framework/sample.md

@ramonsmits please take a look.

Clarified what to do when table update is needed.

---

Snippets/NHibernate/NHibernate_7/NHibernate_7.csproj
Snippets/NHibernate/NHibernate_7/UpgradeGuides/MissingUniqueConstraintOnSagaDataTables/unique_constraints.sql
menu/menu.yaml
nservicebus/upgrades/nhibernate-saga-index-fix.md

Connects to https://github.com/Particular/NServiceBus.NHibernate/issues/280.
ping @MarcinHoppe @SzymonPobiega

NHibernate unique constraints migration guide 

---

samples/saga/simple/Core_6/Sample/Program.cs

Remove unneeded config from Simple saga sample

---

tutorials/intro-to-nservicebus/1-getting-started/tutorial.md
tutorials/intro-to-nservicebus/2-sending-a-command/tutorial.md
tutorials/intro-to-nservicebus/3-multiple-endpoints/tutorial.md
tutorials/intro-to-nservicebus/4-publishing-events/tutorial.md

Requires redeploy of DocsEngine after merge of https://github.com/Particular/DocsEngine/pull/303

[WIP] Intro tutorial metadata

---

nservicebus/transports/transactions.md

@SzymonPobiega @tmasternak Please review.
/cc @Particular/docs-maintainers

Example of eventual consistency with a distributed tx

---

get-started.md

Added link to the plural sight course under Tutorials section.

Update the get started page to include the Pluralsight tutorials

---

home.md

Point to the new link for the MicroServices course based on NServiceBus Version 6.

Updated to the Pluralsight course based on v6

---

tutorials/intro-to-nservicebus/2-sending-a-command/tutorial.md

Fixes #2729 
The code snippet shows an auto-property rather than a parameterless constructor. Rather than update the method I tried to reword it so that the method is no longer referenced directly at all.

Apply customer feedback

---

Snippets/Core/Core_3/PurgingMessagesAtStartup.cs
Snippets/Core/Core_4/PurgingMessagesAtStartup.cs
Snippets/Core/Core_5/PurgingMessagesAtStartup.cs
Snippets/Core/Core_6/PurgingMessagesAtStartup.cs
nservicebus/messaging/discard-old-messages.md

fixes https://github.com/Particular/docs.particular.net/issues/2722

document purging messages at startup

---

samples/outbox/sqltransport-nhpersistence/SqlServer_3/Receiver/Program.cs
samples/outbox/sqltransport-nhpersistence/SqlServer_3/Receiver/app.config
samples/outbox/sqltransport-nhpersistence/SqlServer_3/Sender/Program.cs
samples/outbox/sqltransport-nhpersistence/SqlServer_3/Sender/app.config

Sql hb outbox sample switching from obsolete api

---

nservicebus/msmq/dead-letter-queues.md

@Particular/msmq-transport-maintainers @Particular/docs-maintainers Please take a look. The info is taken from [reputable source](http://andreasohlund.net/2012/10/25/monitoring-your-dead-letter-queues/).

MSMQ DLQ monitoring

---

samples/sqltransport/native-integration/sample.md

Introductory paragraph added

---

nservicebus/msmq/index.md

Corrected some typos, made it more readable and added error message for SEO purposes.
Based on https://github.com/Particular/NServiceBus/issues/4735

Improvements  on MSMQ permission doco

---

nservicebus/operations/metrics.md

Connects to https://github.com/Particular/LaunchWave.DevOpsAdvancedMonitoring/issues/66
@SzymonPobiega @Scooletz I leave this in your capable hands.

Describe queue length metric

---

samples/containers/autofac/Autofac_5/Sample/Program.cs
samples/containers/autofac/Autofac_6/Sample/Program.cs

Customer feedback from regarding single instance. Updated V5 sample to be similar to V6 one.

Autofac singleton bug

---

nservicebus/architecture/principles.md

fixes https://github.com/Particular/docs.particular.net/issues/2775

update Architectural principles page

---

samples/azure/custom-sanitization-asb/ASB_7/Publisher/Program.cs
samples/azure/custom-sanitization-asb/ASB_7/Subscriber/Program.cs
samples/azure/custom-sanitization-asb/ASB_7/Subscriber/app.config
samples/azure/polymorphic-events-asb/ASB_7/Publisher/Program.cs
samples/azure/polymorphic-events-asb/ASB_7/Subscriber/Program.cs
samples/azure/polymorphic-events-asb/ASB_7/Subscriber/app.config

Removing message endpoint mappings from azure samples

Azure samples without message endpoint mappings

---

nservicebus/msmq/routing_content_core_[6,).partial.md

note on cases sensitivity of endpoint names

---

nservicebus/service-fabric/transaction-sharing.md

[WIP] Why one needs a custom service fabric transaction

---

servicepulse/installation.md

Related to https://github.com/Particular/ServicePulse/issues/443

Update to ServicePulse installation parameters & defaults

---

nservicebus/upgrades/6to7/index.md

Closes https://github.com/Particular/docs.particular.net/issues/2795

Document namespace move GetSettings

---

nservicebus/sql-persistence/index.md

Fixes https://github.com/Particular/NServiceBus.Persistence.Sql/issues/100

document sql persistence unicode support 

---

samples/azure/shared-host/CloudServicesHost_7/HostWorker/HostWorker.csproj
samples/azure/shared-host/CloudServicesHost_7/HostWorker/app.config
samples/azure/shared-host/CloudServicesHost_7/HostWorker/packages.config
samples/azure/shared-host/CloudServicesHost_7/Receiver/Receiver.csproj
samples/azure/shared-host/CloudServicesHost_7/Receiver/app.config
samples/azure/shared-host/CloudServicesHost_7/Receiver/packages.config
samples/azure/shared-host/CloudServicesHost_7/Sender/Sender.csproj
samples/azure/shared-host/CloudServicesHost_7/Sender/app.config
samples/azure/shared-host/CloudServicesHost_7/Sender/packages.config
samples/azure/shared-host/CloudServicesHost_7/Shared/Shared.csproj
samples/azure/shared-host/CloudServicesHost_7/Shared/app.config
samples/azure/shared-host/CloudServicesHost_7/Shared/packages.config
samples/azure/storage-persistence/ASP_1/Client/Client.csproj
samples/azure/storage-persistence/ASP_1/Client/app.config
samples/azure/storage-persistence/ASP_1/Client/packages.config
samples/azure/storage-persistence/ASP_1/Server/Server.csproj
samples/azure/storage-persistence/ASP_1/Server/packages.config
samples/azure/storage-persistence/ASP_1/StorageReader/StorageReader.csproj
samples/azure/storage-persistence/ASP_1/StorageReader/app.config
samples/azure/storage-persistence/ASP_1/StorageReader/packages.config
samples/azure/storage-queues/ASQ_7/Endpoint1/Endpoint1.csproj
samples/azure/storage-queues/ASQ_7/Endpoint1/app.config
samples/azure/storage-queues/ASQ_7/Endpoint1/packages.config
samples/azure/storage-queues/ASQ_7/Endpoint2/Endpoint2.csproj
samples/azure/storage-queues/ASQ_7/Endpoint2/app.config
samples/azure/storage-queues/ASQ_7/Endpoint2/packages.config
samples/azure/storage-queues/ASQ_7/StorageReader/StorageReader.csproj
samples/azure/storage-queues/ASQ_7/StorageReader/app.config
samples/azure/storage-queues/ASQ_7/StorageReader/packages.config

Samples smoke tested + build for snippets.

[WIP] ASQ/ASP bump up

---

Snippets/SimpleInjector/SimpleInjector_2/SimpleInjector_2.csproj
nservicebus/containers/simpleinjector.md
samples/containers/simpleinjector/SimpleInjector_2/Sample/Sample.csproj
samples/containers/simpleinjector/SimpleInjector_2/Sample/app.config
samples/containers/simpleinjector/SimpleInjector_2/Sample/packages.config

Updates to the latest package versions

Update simpleinjector versions

---

nservicebus/upgrades/all-versions.include.md
nservicebus/upgrades/supported-versions-downstreams.include.md

cc @Particular/azure-maintainers

update supported versions

---

nservicebus/upgrades/6to7/index.md

relates to https://github.com/Particular/NServiceBus/issues/4454

Add message property encryption to upgrade guide

---

nservicebus/upgrades/6to7/index.md

relates to https://github.com/Particular/NServiceBus/issues/4225

Document removal of SetCorrelationId in upgrade guide

---

nservicebus/containers/structuremap.md
samples/containers/structuremap/StructureMap_6/Sample/Sample.csproj
samples/containers/structuremap/StructureMap_6/Sample/packages.config

Smoketested structuremap against docs samples and reviewed md file.

Update 3rd party dependency

---

samples/azure/shared-host/CloudServicesHost_7/HostWorker/EndpointConfig.cs
samples/azure/shared-host/CloudServicesHost_7/HostWorker/HostWorker.csproj
samples/azure/shared-host/CloudServicesHost_7/HostWorker/app.config
samples/azure/shared-host/CloudServicesHost_7/HostWorker/packages.config
samples/azure/shared-host/CloudServicesHost_7/Receiver/Receiver.csproj
samples/azure/shared-host/CloudServicesHost_7/Receiver/app.config
samples/azure/shared-host/CloudServicesHost_7/Receiver/packages.config
samples/azure/shared-host/CloudServicesHost_7/Sender/Sender.csproj
samples/azure/shared-host/CloudServicesHost_7/Sender/app.config
samples/azure/shared-host/CloudServicesHost_7/Sender/packages.config
samples/azure/shared-host/sample.md

Connects to https://github.com/Particular/NServiceBus.Host.AzureCloudService/pull/95
Removes implementation of `IConfigureThisEndpoint` in the sample, matching documentation instructions.
Updates references.

Updates sample for release 7.1.3 of Azure host

---

get-started.md
menu/menu.yaml
tutorials/index.md
tutorials/quickstart/quickstart-tutorial-intro-paragraph.include.md
tutorials/quickstart/tutorial.md

Related to https://github.com/Particular/DeveloperEducation/issues/910

Link in the Quick Start tutorial

---

nservicebus/azure-service-bus/brokered-message-creation.md
nservicebus/azure-service-bus/topologies/index.md

@Particular/azure-maintainers Please review

Added note regarding Stream incompatibility with ServiceControl

---

samples/web/asp-mvc-application/Core_6/AsyncPagesMVC/Global.asax.cs
samples/web/asp-mvc-application/Core_7/AsyncPagesMVC/Global.asax.cs

fixes https://github.com/Particular/docs.particular.net/issues/2830
@ramonsmits can you have a look at this approach? I think this should solve the issues you mentioned (e.g. allows to share a singleton between message handler and MVC controllers)
(if we want to apply this change, we should probably also adjust the v7 sample)

Change autofac configuration

---

servicecontrol/plugins/heartbeat.md

Fixes https://github.com/Particular/docs.particular.net/issues/2723
@Particular/msmq-transport-maintainers - can you please review and merge?

Added the changed TTBR behavior based on recent version.

---

nservicebus/nhibernate/index.md

@DavidBoike I added a link to ODP.NET managed driver NuGet package.

Indicate ODP.NET NuGet package

---

samples/azure/shared-host/CloudServicesHost_7/Receiver/NServiceBus.Hosting.Azure.HostProcess.exe.config
samples/azure/shared-host/CloudServicesHost_7/Receiver/Receiver.csproj
samples/azure/shared-host/CloudServicesHost_7/Sender/NServiceBus.Hosting.Azure.HostProcess.exe.config
samples/azure/shared-host/CloudServicesHost_7/Sender/Sender.csproj

Fixes https://github.com/Particular/docs.particular.net/issues/2840

Fixes binding redirects azure shared host sample

---

nservicebus/upgrades/sqlpersistence-oracle-null-endpoint.md

@weralabaj @SzymonPobiega @DavidBoike Please take a look at the upgrade guide for the SQL persistence patch.

NServiceBus.Persistence.Sql 2.1.2, 2.0.1 and 1.0.5 - upgrade guide draft

---

nservicebus/azure-service-bus/autorenewtimeout-warning.include.md
nservicebus/azure-service-bus/message-lock-renewal.md
samples/azure/azure-service-bus-long-running/sample.md

Connects to https://github.com/Particular/NServiceBus.AzureServiceBus/issues/576
@yvesgoeleven this warning should suffice.

clarification about autorenewtimeout

---

nservicebus/azure-service-bus/brokered-message-creation.md
nservicebus/azure-service-bus/multiple-namespaces-support.md
nservicebus/azure-service-bus/securing-connection-strings.md
nservicebus/azure-service-bus/topologies/index.md
nservicebus/azure-storage-queues/configuration_envelope_asq_[7,].partial.md
nservicebus/azure-storage-queues/multi-storageaccount-support.md
nservicebus/azure-storage-queues/multi-storageaccount-support_aliases_asq_[7,].partial.md
servicecontrol/transport-adapter/incompatible-features.md

Fixes #2851 
Fixes #2850 
Connects to https://github.com/Particular/NServiceBus.AzureServiceBus/issues/572
Listed the features
In the description of each feature, explain that it is incompatible & refer to the transport adapter as solution

List asb & asq transport features that are not compatible with SC

---

menu/menu.yaml

Add Oracle Caveats to menu

---

Snippets/NHibernate/NHibernate_7/Outbox.cs
nservicebus/nhibernate/outbox_customizing_nhibernate_[7,).partial.md

fixes https://github.com/Particular/DocsEngine/issues/317

fix outbox snippets

---

Snippets/SqlServer/SqlServer_3/ConnectionStrings.xml
Snippets/SqlServer/SqlServer_3/ConnectionStringsNamed.xml
Snippets/SqlServer/SqlServer_3/NamedConnectionString.cs
samples/outbox/sqltransport-nhpersistence/SqlServer_3/Receiver/Program.cs
samples/outbox/sqltransport-nhpersistence/SqlServer_3/Sender/Program.cs
samples/servicecontrol/adapter-mixed-transports/SCTransportAdapter_1/Adapter/Program.cs
samples/servicecontrol/adapter-mixed-transports/SCTransportAdapter_1/Shipping/Program.cs
samples/servicecontrol/adapter-sqlserver-multi-instance/SCTransportAdapter_1/Adapter/Program.cs
samples/servicecontrol/adapter-sqlserver-multi-instance/SCTransportAdapter_1/Shared/Connections.cs
samples/servicecontrol/adapter-sqlserver-multi-instance/sample.md
samples/servicecontrol/adapter-sqlserver-multi-schema/SCTransportAdapter_1/Adapter/Program.cs
samples/servicecontrol/adapter-sqlserver-multi-schema/SCTransportAdapter_1/Sales/Program.cs
samples/servicecontrol/adapter-sqlserver-multi-schema/SCTransportAdapter_1/Shipping/Program.cs
samples/servicecontrol/adapter-sqlserver-multi-schema/sample.md
samples/sqltransport-nhpersistence/SqlServer_3/Receiver/App.config
samples/sqltransport-nhpersistence/SqlServer_3/Sender/App.config
samples/sqltransport-sqlpersistence/Core_6/Receiver/Program.cs
samples/sqltransport-sqlpersistence/Core_6/Sender/Program.cs
samples/sqltransport/store-and-forward/SqlServer_3/Receiver/Program.cs
samples/sqltransport/store-and-forward/SqlServer_3/Sender/ConnectionProvider.cs
tutorials/intro-to-nservicebus/using-sql-transport.md

remove redundant pool size

---

nservicebus/security/index.md

Add a section on security links for SQS

---

nservicebus/messaging/callbacks-testing.md

Reviewed callback testing

---

transports/eventstore/index.md

Reviewed event store

---

transports/msmq/troubleshooting.md

Reviewed msmq trouble shooting

---

nservicebus/outbox/index.md

Trying to explain the Outbox better and provide a path for how to move a system from DTC to Outbox.
Please review @Particular/nservicebus-maintainers @Particular/docs-maintainers

More Outbox details, DTC to Outbox conversion

---

samples/outbox/sqltransport-nhpersistence-ef/SqlServer_2.2/Receiver/OrderSubmittedHandler.cs
samples/outbox/sqltransport-nhpersistence-ef/SqlServer_2.2/Receiver/Program.cs
samples/outbox/sqltransport-nhpersistence-ef/SqlServer_2.2/Receiver/Receiver.csproj
samples/outbox/sqltransport-nhpersistence-ef/SqlServer_2.2/Receiver/ReceiverDataContext.cs
samples/outbox/sqltransport-nhpersistence-ef/SqlServer_2.2/Receiver/Startup.sql
samples/outbox/sqltransport-nhpersistence-ef/SqlServer_2.2/Receiver/packages.config
samples/outbox/sqltransport-nhpersistence-ef/SqlServer_2.2/Sender/Sender.csproj
samples/outbox/sqltransport-nhpersistence-ef/SqlServer_2.2/Sender/packages.config
samples/outbox/sqltransport-nhpersistence-ef/SqlServer_2.2/Shared/Shared.csproj
samples/outbox/sqltransport-nhpersistence-ef/SqlServer_2.2/Shared/SqlHelper.cs
samples/outbox/sqltransport-nhpersistence-ef/SqlServer_2.2/Shared/packages.config
samples/outbox/sqltransport-nhpersistence-ef/SqlServer_3/Receiver/OrderSubmittedHandler.cs
samples/outbox/sqltransport-nhpersistence-ef/SqlServer_3/Receiver/Program.cs
samples/outbox/sqltransport-nhpersistence-ef/SqlServer_3/Receiver/Receiver.csproj
samples/outbox/sqltransport-nhpersistence-ef/SqlServer_3/Receiver/ReceiverDataContext.cs
samples/outbox/sqltransport-nhpersistence-ef/SqlServer_3/Receiver/Startup.sql
samples/outbox/sqltransport-nhpersistence-ef/SqlServer_3/Receiver/packages.config
samples/outbox/sqltransport-nhpersistence-ef/SqlServer_3/Sender/Sender.csproj
samples/outbox/sqltransport-nhpersistence-ef/SqlServer_3/Sender/packages.config
samples/outbox/sqltransport-nhpersistence-ef/SqlServer_3/Shared/Shared.csproj
samples/outbox/sqltransport-nhpersistence-ef/SqlServer_3/Shared/SqlHelper.cs
samples/outbox/sqltransport-nhpersistence-ef/SqlServer_3/Shared/packages.config
samples/outbox/sqltransport-nhpersistence-ef/sample.md

Move Outbox/SQL transport/NH persistence/EF sample to EF Core

---

nservicebus/upgrades/encryption-key-identifiers.md
nservicebus/upgrades/externalize-encryption.md

Reviewed encryption key identifiers and externalize-encryption

---

transports/msmq/distributor/configuration.md
transports/msmq/distributor/disconnect-workers.md
transports/msmq/distributor/error-handling.md
transports/msmq/distributor/index.md
transports/msmq/distributor/publish-subscribe.md
transports/msmq/distributor/when-worker-goes-down.md

Reviewed distributor index and configuration

---

platform/servicecontrol.include.md

@Particular/docs-maintainers @Particular/servicecontrol-maintainers thoughts?

better language for SC HTTP API note

---

transports/msmq/index.md

@ramonsmits @mikeminutillo @SimonCropp - I have made some changes, making it more clearer, fixing the version language, etc. Please review. I started this as a PR to the one that @ramonsmits started.

clean up targeting the MSMQ Permissions PR

---

persistence/in-memory.md

fixes https://github.com/Particular/docs.particular.net/issues/2940

Simplify InMemory persistence warning

---

menu/menu.yaml
servicecontrol/integration/index.md
servicecontrol/servicecontrol-instances/index.md

Implements the structure defined in https://github.com/Particular/docs.particular.net/issues/2935#issuecomment-313579404

Propose new SC menu structure

---

menu/menu.yaml
persistence/in-memory.md
samples/endpoint-configuration/sample.md
samples/endpoint-configuration/sample_persistence_core_[,5.0].partial.md
samples/endpoint-configuration/sample_persistence_core_[6.0,].partial.md
samples/endpoint-configuration/sample_transport_core_[,5.0].partial.md
samples/endpoint-configuration/sample_transport_core_[6.0,].partial.md

Fixes #2952 
Also includes a revision to the in-memory persistence page.

Fix endpoint configuration sample

---

tutorials/intro-to-nservicebus/2-sending-a-command/tutorial.md

changed 'logger' to 'log' to match tutorial and code snippets

Updated logger in tutorial for consistency

---

Snippets/ASB/ASB_7/Performance.cs
Snippets/ASB/ASB_8/Performance.cs
transports/azure-service-bus/performance-tuning.md
transports/azure-service-bus/performance-tuning_body_asb_[,7).partial.md
transports/azure-service-bus/performance-tuning_body_asb_[7,).partial.md

Closes https://github.com/Particular/docs.particular.net/issues/2939
@Particular/azure-maintainers thoughts?

Asb performance

---

samples/azure/native-integration-asb/ASB_7/NativeSender/Program.cs

https://github.com/Particular/NServiceBus.AzureServiceBus/commit/b5713e224b5c15f853722731ae1d628545d79321

Update transport encoding header key to match new value

---

nservicebus/upgrades/6to7/index.md

relates to https://github.com/Particular/NServiceBus/pull/4859

Document stage change of AttachCausationHeadersBehavior

---

nservicebus/messaging/timeout-manager_circuit-breaker_core_[5,).partial.md

Based on https://github.com/Particular/NServiceBus/issues/4833
@timbussmann documentation of current behavior.

Timeout manager circuit breaker behavior

---

servicecontrol/capacity-and-planning.md
servicecontrol/installation.md

@Particular/servicecontrol-maintainers @Particular/docs-maintainers Please review

Added a note to install SC in isolation and to reserve enough resources

---

persistence/sql/saga_finder_sqlpersistence_[2,).partial.md
persistence/sql/sql-saga-finder-warning.include.md
samples/saga/sql-sagafinder/sample.md

Related to https://github.com/Particular/NServiceBus.Persistence.Sql/issues/131
@Particular/sqlpersistence-maintainers please review

Saga finder SQL 2016 warning

---

samples/servicecontrol/adapter-asb-multi-namespace/sample.md

Trying to give a more complete description of the sample (to make the reader *want* to continue reading). Hope I didn't make anything wrong in the process.

Moved diagram up

---

samples/web/owin-pass-through/Core_5/OwinPassThrough/OwinToBus.cs
samples/web/owin-pass-through/Core_5/OwinPassThrough/OwinToMsmq.cs
samples/web/owin-pass-through/Core_6/OwinPassThrough/OwinToBus.cs
samples/web/owin-pass-through/Core_6/OwinPassThrough/OwinToMsmq.cs
samples/web/owin-pass-through/Core_7/OwinPassThrough/OwinToBus.cs
samples/web/owin-pass-through/Core_7/OwinPassThrough/OwinToMsmq.cs

Shows how to set a response code on the OWIN passthrough sample. I used 202 Accepted as I believe that's the correct response code for this. 
Addresses https://github.com/Particular/docs.particular.net/issues/3003

OWIN Pass-through response code

---

nservicebus/operations/metrics.md

Each of these is a separate statistic so they deserve their own header.

Clarify Receive Stats

---

samples/application-insights/sample.md

In order to make the opening paragraph more appealing, I've moved the chart earlier. Leaning against removing it from the end (where I took it from), but would be open to another opinion as well.

Moved the chart earlier

---

samples/azure/storage-queues/ASQ_7/Endpoint1/app.config
samples/azure/storage-queues/ASQ_7/Endpoint2/app.config

fix asq sample

---

samples/azure/blob-storage-databus/ABSDataBus_1/Receiver/app.config
samples/azure/blob-storage-databus/ABSDataBus_1/Sender/app.config
samples/azure/shared-host/CloudServicesHost_7/HostWorker/app.config
samples/azure/shared-host/CloudServicesHost_7/Receiver/NServiceBus.Hosting.Azure.HostProcess.exe.config
samples/azure/shared-host/CloudServicesHost_7/Receiver/app.config
samples/azure/shared-host/CloudServicesHost_7/Sender/NServiceBus.Hosting.Azure.HostProcess.exe.config
samples/azure/shared-host/CloudServicesHost_7/Sender/app.config
samples/azure/storage-persistence/ASP_1/Server/app.config
samples/show-case/cloud-azure/Core_6/Store.ContentManagement/App.config
samples/show-case/cloud-azure/Core_6/Store.CustomerRelations/App.config
samples/show-case/cloud-azure/Core_6/Store.ECommerce/Web.config
samples/show-case/cloud-azure/Core_6/Store.Operations/App.config
samples/show-case/cloud-azure/Core_6/Store.Sales/App.config
samples/show-case/cloud-azure/Core_6/Store.Shared/app.config

more storage binding redirect fixes

fixed binding redirects

---

samples/servicecontrol/monitoring3rdparty/CustomChecks5_2/Sample/Monitor.cs
samples/servicecontrol/monitoring3rdparty/CustomChecks6_3/Sample/Monitor.cs

Connects to https://github.com/Particular/docs.particular.net/issues/3031
Ping @Particular/servicecontrol-maintainers for review (can't select them as a group in docs)

Share a static HttpClient

---

transports/sqs/index.md
transports/upgrades/amazonsqs-2to3.md

Closes https://github.com/Particular/docs.particular.net/issues/3024

Adding SQS permission which will potentially be used in minor

---

nservicebus/upgrades/6to7/index.md

Adds entry for https://github.com/Particular/NServiceBus/pull/4889

Add removal of ConfigurationErrorsException to upgrade guide

---

transports/azure-service-bus/configuration/full.md

See https://github.com/Particular/NServiceBus.AzureServiceBus/blob/09c16d9f3fd2f7e9131e5b4862a81bd9d3bda682/src/Transport/Config/DefaultConfigurationValues.cs#L51

Number of clients per entity

---

.gitattributes

@bording @Scooletz I need your gitfoo skills to verify this

Treat powershell as text

---

persistence/ravendb/index.md
persistence/ravendb/raven-dispose-warning.include.md
samples/ravendb/simple/Raven_3/Server/Program.cs
samples/ravendb/simple/Raven_4/Server/Program.cs
samples/ravendb/simple/sample.md
samples/saga/ravendb-custom-sagafinder/Raven_3/Sample/Program.cs
samples/saga/ravendb-custom-sagafinder/Raven_4/Sample/Program.cs
samples/saga/ravendb-custom-sagafinder/sample.md

RavenDB Persistence:  note reminding to do dispose the user created document store

---

transports/rabbitmq/index.md

Closes https://github.com/Particular/NServiceBus.RabbitMQ/issues/365

Add warning about minimum version of RabbitMQ required

---

nservicebus/serialization/index.md

Based on my comment in https://github.com/Particular/PlatformDevelopment/issues/1378#issuecomment-321644975 and the immediately following response from @SimonCropp.
Basically says use Newtonsoft unless you have specific performance or integration requirements.

Note on Newtonsoft serializer

---

samples/servicecontrol/adapter-mixed-transports/SCTransportAdapter_1/Shipping/Program.cs
samples/servicecontrol/adapter-mixed-transports/SCTransportAdapter_1/Shipping/SqlHelper.cs
samples/servicecontrol/adapter-mixed-transports/sample.md
samples/servicecontrol/adapter-sqlserver-multi-instance/SCTransportAdapter_1/Adapter/Program.cs
samples/servicecontrol/adapter-sqlserver-multi-instance/SCTransportAdapter_1/Sales/Program.cs
samples/servicecontrol/adapter-sqlserver-multi-instance/SCTransportAdapter_1/Shared/Connections.cs
samples/servicecontrol/adapter-sqlserver-multi-instance/SCTransportAdapter_1/Shared/SqlHelper.cs
samples/servicecontrol/adapter-sqlserver-multi-instance/SCTransportAdapter_1/Shipping/Program.cs
samples/servicecontrol/adapter-sqlserver-multi-instance/sample.md
samples/servicecontrol/adapter-sqlserver-multi-schema/SCTransportAdapter_1/Adapter/Program.cs
samples/servicecontrol/adapter-sqlserver-multi-schema/SCTransportAdapter_1/Sales/Program.cs
samples/servicecontrol/adapter-sqlserver-multi-schema/SCTransportAdapter_1/Shared/SqlHelper.cs
samples/servicecontrol/adapter-sqlserver-multi-schema/SCTransportAdapter_1/Shipping/App.config
samples/servicecontrol/adapter-sqlserver-multi-schema/SCTransportAdapter_1/Shipping/Program.cs
samples/servicecontrol/adapter-sqlserver-multi-schema/sample.md

Added automatic DB+schema creation
Fixes #3064 #3065 #3066

Feedback for SC samples

---

nservicebus/upgrades/6to7/index.md

related to https://github.com/Particular/PlatformDevelopment/issues/1386
This is just the upgrade guide part. Will raise a dedicated PR to update the licensing page.

Add licensing section to upgrade guide

---

components/components.yaml

Switch owner of SQS

---

Snippets/Core/Core_6/Installers.cs
Snippets/Core/Core_7/Installers.cs
nservicebus/operations/installers.md
nservicebus/operations/installers_disable_core_[6,].partial.md

relates to https://github.com/Particular/NServiceBus/issues/4893

Document disable installers config option

---

menu/menu.yaml

@Particular/azure-maintainers @Particular/docs-maintainers please review

identation issue in the menu

---

nservicebus/operations/auditing.md

fixes #3101 
@Particular/nservicebus-maintainers please review

clarification-on-enabling-auditing

---

tools/supportedVersions.linq

fix supportedVersions.linq to work with NuGet.PackageManagement 4.3.0

---

samples/mailer/Mailer_3/Endpoint/Program.cs

Added missing serializer to mailer sample

---

transports/learning/index.md
transports/transactions_matrix_core_[6,).partial.md

Closes https://github.com/Particular/docs.particular.net/issues/3044

Add learning transport transaction modes

---

samples/containers/unity/Unity_8/Sample/MyHandler.cs
samples/containers/unity/Unity_8/Sample/MyMessage.cs
samples/containers/unity/Unity_8/Sample/MyService.cs
samples/containers/unity/Unity_8/Sample/Program.cs
samples/containers/unity/Unity_8/Sample/Sample.csproj
samples/containers/unity/Unity_8/UnitySample.sln
samples/containers/unity/Unity_8/UnitySample.sln.DotSettings

Relates to https://github.com/Particular/NServiceBus.Unity/pull/44
Create a sample for v8 of the unity container. Currently references a PR build of the NuGet package. Only full framework sample as core is not supported by Unity

[WIP] NServiceBus.ObjectBuilder.Unity v8 Sample

---

samples/containers/structuremap/StructureMap_7/Sample/MyHandler.cs
samples/containers/structuremap/StructureMap_7/Sample/MyMessage.cs
samples/containers/structuremap/StructureMap_7/Sample/MyService.cs
samples/containers/structuremap/StructureMap_7/Sample/Program.cs
samples/containers/structuremap/StructureMap_7/Sample/Sample.Core.csproj
samples/containers/structuremap/StructureMap_7/Sample/Sample.csproj
samples/containers/structuremap/StructureMap_7/StructureMapSample.Core.sln
samples/containers/structuremap/StructureMap_7/StructureMapSample.Core.sln.DotSettings
samples/containers/structuremap/StructureMap_7/StructureMapSample.sln
samples/containers/structuremap/StructureMap_7/StructureMapSample.sln.DotSettings

Relates to https://github.com/Particular/NServiceBus.StructureMap/pull/45
Create a sample for v7 of the structuremap container. Currently references a PR build of the NuGet package.

[WIP] NServiceBus.ObjectBuilder.Structuremap v7 Sample

---

Snippets/Core/Core_5/Headers/Writers/HeaderWriterEncryption.cs
Snippets/Core/Core_6/Headers/Writers/HeaderWriterEncryption.cs
Snippets/Core/Core_7/Headers/Writers/HeaderWriterEncryption.cs
Snippets/PropertyEncryption/Core_5/Usage.cs
Snippets/PropertyEncryption/Core_6/UpgradeGuides/Split/Usage.cs
Snippets/PropertyEncryption/Core_6/Usage.cs
Snippets/PropertyEncryption/PropertyEncryption_1/Conventions/Usage.cs
Snippets/PropertyEncryption/PropertyEncryption_1/UpgradeGuides/Split/Conventions/Usage.cs
Snippets/PropertyEncryption/PropertyEncryption_1/UpgradeGuides/Split/Usage.cs
Snippets/PropertyEncryption/PropertyEncryption_1/Usage.cs
Snippets/PropertyEncryption/PropertyEncryption_2/Conventions/Usage.cs
Snippets/PropertyEncryption/PropertyEncryption_2/Usage.cs
nservicebus/upgrades/encryption-key-identifiers.md
samples/encryption/basic-encryption/PropertyEncryption_1/Shared/EncryptionExtensions.cs
samples/encryption/basic-encryption/PropertyEncryption_2/Shared/EncryptionExtensions.cs
samples/encryption/encryption-conventions/Core_6/Shared/EncryptionExtensions.cs
samples/encryption/encryption-conventions/PropertyEncryption_1/Shared/EncryptionExtensions.cs
samples/encryption/encryption-conventions/PropertyEncryption_2/Shared/EncryptionExtensions.cs

Resolve Particular/NServiceBus.Encryption.MessageProperty#11

Use Base64 encryption keys instead of ASCII

---

Snippets/Wcf/Wcf.sln
Snippets/Wcf/Wcf_2/Binding/Message.cs
Snippets/Wcf/Wcf_2/Binding/Usage.cs
Snippets/Wcf/Wcf_2/Cancellation/Message.cs
Snippets/Wcf/Wcf_2/Cancellation/Usage.cs
Snippets/Wcf/Wcf_2/Enum/Handler.cs
Snippets/Wcf/Wcf_2/Enum/Message.cs
Snippets/Wcf/Wcf_2/Enum/Status.cs
Snippets/Wcf/Wcf_2/Enum/Usage.cs
Snippets/Wcf/Wcf_2/ExposeWcf.cs
Snippets/Wcf/Wcf_2/Int/Handler.cs
Snippets/Wcf/Wcf_2/Int/Message.cs
Snippets/Wcf/Wcf_2/Int/Usage.cs
Snippets/Wcf/Wcf_2/Object/Handler.cs
Snippets/Wcf/Wcf_2/Object/Message.cs
Snippets/Wcf/Wcf_2/Object/ResponseMessage.cs
Snippets/Wcf/Wcf_2/Object/Usage.cs
Snippets/Wcf/Wcf_2/Routing/Handler.cs
Snippets/Wcf/Wcf_2/Routing/Message.cs
Snippets/Wcf/Wcf_2/Routing/Usage.cs
Snippets/Wcf/Wcf_2/Wcf_2.csproj

pending a package being on myget

WIP: wcf to nsb v7

---

Snippets/ASQ/ASQ.sln
Snippets/ASQ/ASQ_7/ASQ_7.csproj
Snippets/ASQ/ASQ_7/MessageWrapperSerializer.cs
Snippets/ASQ/ASQ_7/Usage.cs
Snippets/ASQ/ASQ_8/ASQ_8.csproj
Snippets/ASQ/ASQ_8/CustomEnvelopeUnwrapper.cs
Snippets/ASQ/ASQ_8/DelayedDelivery.cs
Snippets/ASQ/ASQ_8/MessageWrapperSerializer.cs
Snippets/ASQ/ASQ_8/Usage.cs
samples/azure/storage-queues/ASQ_8/AzureStorageQueues.Core.sln
samples/azure/storage-queues/ASQ_8/AzureStorageQueues.Core.sln.DotSettings
samples/azure/storage-queues/ASQ_8/AzureStorageQueues.sln
samples/azure/storage-queues/ASQ_8/AzureStorageQueues.sln.DotSettings
samples/azure/storage-queues/ASQ_8/Endpoint1/Endpoint1.Core.csproj
samples/azure/storage-queues/ASQ_8/Endpoint1/Endpoint1.csproj
samples/azure/storage-queues/ASQ_8/Endpoint1/Message2Handler.cs
samples/azure/storage-queues/ASQ_8/Endpoint1/Program.cs
samples/azure/storage-queues/ASQ_8/Endpoint2/Endpoint2.Core.csproj
samples/azure/storage-queues/ASQ_8/Endpoint2/Endpoint2.csproj
samples/azure/storage-queues/ASQ_8/Endpoint2/Message1Handler.cs
samples/azure/storage-queues/ASQ_8/Endpoint2/Program.cs
samples/azure/storage-queues/ASQ_8/Shared/Message1.cs
samples/azure/storage-queues/ASQ_8/Shared/Message2.cs
samples/azure/storage-queues/ASQ_8/Shared/Shared.Core.csproj
samples/azure/storage-queues/ASQ_8/Shared/Shared.csproj
samples/azure/storage-queues/ASQ_8/StorageReader/AzureHelper.cs
samples/azure/storage-queues/ASQ_8/StorageReader/Extensions.cs
samples/azure/storage-queues/ASQ_8/StorageReader/StorageReader.Core.csproj
samples/azure/storage-queues/ASQ_8/StorageReader/StorageReader.csproj

pending a package being on myget

WIP: Asq to nsb v7

---

Snippets/ASP/ASP.sln
Snippets/ASP/ASP_2/ASP_2.csproj
Snippets/ASP/ASP_2/Usage.cs
menu/menu.yaml
persistence/upgrades/asp-1to2.md
samples/azure/storage-persistence/ASP_2/AzureStoragePersistence.Core.sln
samples/azure/storage-persistence/ASP_2/AzureStoragePersistence.Core.sln.DotSettings
samples/azure/storage-persistence/ASP_2/AzureStoragePersistence.sln
samples/azure/storage-persistence/ASP_2/AzureStoragePersistence.sln.DotSettings
samples/azure/storage-persistence/ASP_2/Client/Client.Core.csproj
samples/azure/storage-persistence/ASP_2/Client/Client.csproj
samples/azure/storage-persistence/ASP_2/Client/OrderCompletedHandler.cs
samples/azure/storage-persistence/ASP_2/Client/Program.cs
samples/azure/storage-persistence/ASP_2/Server/CompleteOrder.cs
samples/azure/storage-persistence/ASP_2/Server/OrderSaga.cs
samples/azure/storage-persistence/ASP_2/Server/OrderSagaData.cs
samples/azure/storage-persistence/ASP_2/Server/Program.cs
samples/azure/storage-persistence/ASP_2/Server/Server.Core.csproj
samples/azure/storage-persistence/ASP_2/Server/Server.csproj
samples/azure/storage-persistence/ASP_2/Shared/OrderCompleted.cs
samples/azure/storage-persistence/ASP_2/Shared/Shared.Core.csproj
samples/azure/storage-persistence/ASP_2/Shared/Shared.csproj
samples/azure/storage-persistence/ASP_2/Shared/StartOrder.cs
samples/azure/storage-persistence/ASP_2/StorageReader/AzureHelper.cs
samples/azure/storage-persistence/ASP_2/StorageReader/Extensions.cs
samples/azure/storage-persistence/ASP_2/StorageReader/StorageReader.Core.csproj
samples/azure/storage-persistence/ASP_2/StorageReader/StorageReader.csproj

pending a package being on myget

WIP: Asp to nsb v7

---

samples/msmq/dlq-customcheck/Core_5/DeadLetterQueueCustomCheck.sln
samples/msmq/dlq-customcheck/Core_5/DeadLetterQueueCustomCheck.sln.DotSettings
samples/msmq/dlq-customcheck/Core_5/SampleEndpoint/App.config
samples/msmq/dlq-customcheck/Core_5/SampleEndpoint/CheckDeadLetterQueue.cs
samples/msmq/dlq-customcheck/Core_5/SampleEndpoint/ConfigErrorQueue.cs
samples/msmq/dlq-customcheck/Core_5/SampleEndpoint/Program.cs
samples/msmq/dlq-customcheck/Core_5/SampleEndpoint/SampleEndpoint.csproj
samples/msmq/dlq-customcheck/Core_6/DeadLetterQueueCustomCheck.sln
samples/msmq/dlq-customcheck/Core_6/DeadLetterQueueCustomCheck.sln.DotSettings
samples/msmq/dlq-customcheck/Core_6/SampleEndpoint/CheckDeadLetterQueue.cs
samples/msmq/dlq-customcheck/Core_6/SampleEndpoint/Program.cs
samples/msmq/dlq-customcheck/Core_6/SampleEndpoint/SampleEndpoint.csproj
samples/msmq/dlq-customcheck/sample.md

Sample that watches the MSMQ DLQ using a ServiceControl Custom Check

MSMQ DLQ Custom Check

---

Snippets/ServiceFabricPersistence/ServiceFabricPersistence_1/ServiceFabricPersistence_1.csproj
samples/azure/azure-service-fabric-routing/Core_6/CandidateVoteCount/CandidateVoteCount.csproj
samples/azure/azure-service-fabric-routing/Core_6/Shared/Shared.csproj
samples/azure/azure-service-fabric-routing/Core_6/ZipCodeVoteCount/ZipCodeVoteCount.csproj

Smoke tested latest Service Fabric Persistence

Sf persistence stable

---

samples/azure/storage-persistence/ASP_2/StorageReader/AzureHelper.cs

Fixes the asp sample, so that api works for netcore

fix blob api usage

---

samples/msmq/dlq-customcheck/Core_5/SampleEndpoint/MsmqUtils.cs
samples/msmq/dlq-customcheck/Core_5/SampleEndpoint/Program.cs
samples/msmq/dlq-customcheck/Core_5/SampleEndpoint/SampleEndpoint.csproj
samples/msmq/dlq-customcheck/Core_6/SampleEndpoint/MsmqUtils.cs
samples/msmq/dlq-customcheck/Core_6/SampleEndpoint/Program.cs
samples/msmq/dlq-customcheck/Core_6/SampleEndpoint/SampleEndpoint.csproj

Enable the DLQ Custom Checks sample to populate the local DLQ

Enable writing messages to DLQ

---

Snippets/Metrics/Metrics.sln
Snippets/Metrics/Metrics_2/Configuration.cs
Snippets/Metrics/Metrics_2/Metrics_2.csproj
nservicebus/operations/metrics_reporting_metrics_[1.0,1.1).partial.md
nservicebus/operations/metrics_reporting_metrics_[1.1,2).partial.md
nservicebus/operations/metrics_reporting_metrics_[2,).partial.md
samples/logging/metrics/Metrics_2/Endpoint/Endpoint.Core.csproj
samples/logging/metrics/Metrics_2/Endpoint/Endpoint.csproj
samples/logging/metrics/Metrics_2/Endpoint/Program.cs
samples/logging/metrics/Metrics_2/Endpoint/SomeCommand.cs
samples/logging/metrics/Metrics_2/Endpoint/SomeCommandHandler.cs
samples/logging/metrics/Metrics_2/MetricsTracing.Core.sln
samples/logging/metrics/Metrics_2/MetricsTracing.Core.sln.DotSettings
samples/logging/metrics/Metrics_2/MetricsTracing.sln
samples/logging/metrics/Metrics_2/MetricsTracing.sln.DotSettings

until there is a package on myget

WIP: metrics to nsb v7

---

menu/menu.yaml

Adding mailer to the menu structure

---

Snippets/Bridge/Bridge.sln
Snippets/Bridge/Bridge_2/API.cs
Snippets/Bridge/Bridge_2/Bridge_2.csproj

WIP: transport bridge to NSB v7

---

samples/rabbitmq/native-integration/Rabbit_5/Receiver/Program.cs
samples/rabbitmq/simple/Rabbit_5/Sample/Program.cs

Since v5 makes it mandatory
Connect to https://github.com/Particular/NServiceBus.RabbitMQ/issues/427

Configure routing topology

---

Snippets/Rabbit/Rabbit_5/Usage.cs
transports/rabbitmq/index.md
transports/rabbitmq/index_topology_rabbit_[,5).partial.md
transports/rabbitmq/index_topology_rabbit_[5,).partial.md
transports/rabbitmq/routing-topology.md
transports/rabbitmq/routing-topology_mandatory_rabbit_[,5).partial.md
transports/rabbitmq/routing-topology_mandatory_rabbit_[5,).partial.md
transports/upgrades/rabbitmq-4to5.md

Connects to https://github.com/Particular/NServiceBus.RabbitMQ/issues/427

Rabbit topology selection is mandatory

---

nservicebus/sagas/index.md

@SeanFeldman rearranged the text slightly, what do you think?

Clarify saga completion caveats

---

Snippets/ASP/ASP_2/ASP_2.csproj
Snippets/ASP/ASP_2/Usage.cs
samples/azure/storage-persistence/ASP_2/Client/Program.cs
samples/azure/storage-persistence/ASP_2/Server/Program.cs

ASP 2.0 beta update

---

Snippets/ASB/ASB_7/AddressingStrategies/Composition.cs
Snippets/ASB/ASB_7/AddressingStrategies/Individualization.cs
Snippets/ASB/ASB_7/Composition.cs
Snippets/ASB/ASB_7/DeadLetterQueueForwarding.cs
Snippets/ASB/ASB_7/SecureCredentials.cs
Snippets/ASB/ASB_7/Usage.cs
Snippets/ASB/ASB_8/AddressingStrategies/Composition.cs
Snippets/ASB/ASB_8/AddressingStrategies/Individualization.cs
Snippets/ASB/ASB_8/Composition.cs
Snippets/ASB/ASB_8/DeadLetterQueueForwarding.cs
Snippets/ASB/ASB_8/SecureCredentials.cs
Snippets/ASB/ASB_8/Usage.cs
transports/azure-service-bus/configuration/full.md
transports/upgrades/asb-7to8.md

- DescriptionFactory was replaced by DescriptionCustomizer on the Queues, Topics & Subscriptions extension points
- fixed the snippet for converters

Asb api obsoletes review

---

nservicebus/hosting/servicehelper.include.md
nservicebus/hosting/windows-service.md
samples/hosting/windows-service/sample.md

Clarify why ServiceHelper is used

---

nservicebus/upgrades/6to7/index.md

@Particular/nservicebus-maintainers Made some tweaks and added a note about System.ValueTuple.

Upgrade guide updates

---

nservicebus/operations/performance-counters_note_perfcounters_[1,).partial.md

PerfCounters enabled-by-default note added to 1.x packages

---

samples/servicecontrol/monitoring3rdparty/sample.md

Fix bad grammar

---

Snippets/Rabbit/Rabbit_4/Usage.cs
Snippets/Rabbit/Rabbit_4/rabbitmq-connection-client-auth.txt
Snippets/Rabbit/Rabbit_4/rabbitmq-connection-tls.txt
Snippets/Rabbit/Rabbit_5/Usage.cs
Snippets/Rabbit/Rabbit_5/rabbitmq-connection-client-auth.txt
Snippets/Rabbit/Rabbit_5/rabbitmq-connection-tls.txt
transports/rabbitmq/connection-settings_tls-details_rabbit_[4,].partial.md

Adds documentation for https://github.com/Particular/NServiceBus.RabbitMQ/issues/380 and https://github.com/Particular/NServiceBus.RabbitMQ/issues/407

Add new TLS-related settings

---

samples/show-case/cloud-azure/Core_6/Store.ContentManagement/Store.ContentManagement.csproj
samples/show-case/cloud-azure/Core_6/Store.CustomerRelations/Store.CustomerRelations.csproj
samples/show-case/cloud-azure/Core_6/Store.ECommerce/Store.ECommerce.csproj
samples/show-case/cloud-azure/Core_6/Store.ECommerce/Web.config
samples/show-case/cloud-azure/Core_6/Store.Operations/Store.Operations.csproj
samples/show-case/cloud-azure/Core_6/Store.Sales/Store.Sales.csproj
samples/show-case/cloud-azure/Core_6/Store.Shared/Store.Shared.csproj

fixed binding redirects as nuget no longer updates them (it does but puts them in the wrong place :s)

fixed cloud showcase

---

persistence/ravendb/manual-dtc-settings.md

Connects to https://github.com/Particular/docs.particular.net/issues/3055
@DavidBoike just to remind you that we need this done 😄

[WIP] note about disposing the DocStore

---

tutorials/intro-to-nservicebus/1-getting-started/Snippets/Core_6/AsyncBoilerplate.cs
tutorials/intro-to-nservicebus/1-getting-started/Snippets/Core_6/Lesson1.cs
tutorials/intro-to-nservicebus/1-getting-started/Solution/ClientUI/Program.cs
tutorials/intro-to-nservicebus/1-getting-started/tutorial.md
tutorials/intro-to-nservicebus/2-sending-a-command/Solution/ClientUI/Program.cs
tutorials/intro-to-nservicebus/3-multiple-endpoints/Solution/ClientUI/Program.cs
tutorials/intro-to-nservicebus/3-multiple-endpoints/Solution/Sales/Program.cs
tutorials/intro-to-nservicebus/4-publishing-events/Solution/Billing/Program.cs
tutorials/intro-to-nservicebus/4-publishing-events/Solution/ClientUI/Program.cs
tutorials/intro-to-nservicebus/4-publishing-events/Solution/Sales/Program.cs
tutorials/intro-to-nservicebus/4-publishing-events/Solution/Shipping/Program.cs
tutorials/intro-to-nservicebus/5-retrying-errors/Solution/Billing/Program.cs
tutorials/intro-to-nservicebus/5-retrying-errors/Solution/ClientUI/Program.cs
tutorials/intro-to-nservicebus/5-retrying-errors/Solution/Sales/Program.cs
tutorials/intro-to-nservicebus/5-retrying-errors/Solution/Shipping/Program.cs
tutorials/message-replay/Solution/Billing/Program.cs
tutorials/message-replay/Solution/ClientUI/Program.cs
tutorials/message-replay/Solution/Sales/Program.cs
tutorials/message-replay/Solution/Shipping/Program.cs
tutorials/quickstart/Snippets/Core_6/ShippingProgram.cs
tutorials/quickstart/Solution/Billing/Program.cs
tutorials/quickstart/Solution/ClientUI/Program.cs
tutorials/quickstart/Solution/Sales/Program.cs

to bring it inline with https://groups.google.com/forum/#!topic/particularsoftware/wfJZjI062Kw

async main tutorials

---

samples/msmq/persistence/MsmqTransport_1/Sample/MyEvent.cs
samples/msmq/persistence/MsmqTransport_1/Sample/MyEventHandler.cs
samples/msmq/persistence/MsmqTransport_1/Sample/Program.cs
samples/msmq/persistence/MsmqTransport_1/Sample/Sample.csproj
samples/msmq/persistence/MsmqTransport_1/SimpleMsmqPersistence.sln
samples/msmq/persistence/MsmqTransport_1/SimpleMsmqPersistence.sln.DotSettings
samples/msmq/persistence/sample.md

Do we need a v6 sample as well?
Fixes #3110

Adding a v1 MSMQ Persistence sample

---

nservicebus/wcf/index.md
samples/wcf/Wcf_1/Wcf.sln
samples/wcf/Wcf_1/Wcf.sln.DotSettings
samples/wcf/Wcf_1/Wcf/MyRequestMessage.cs
samples/wcf/Wcf_1/Wcf/MyRequestMessageHandler.cs
samples/wcf/Wcf_1/Wcf/MyResponseMessage.cs
samples/wcf/Wcf_1/Wcf/MyService.cs
samples/wcf/Wcf_1/Wcf/Program.cs
samples/wcf/Wcf_1/Wcf/Wcf.csproj
samples/wcf/Wcf_2/Wcf.sln
samples/wcf/Wcf_2/Wcf.sln.DotSettings
samples/wcf/Wcf_2/Wcf/MyRequestMessage.cs
samples/wcf/Wcf_2/Wcf/MyRequestMessageHandler.cs
samples/wcf/Wcf_2/Wcf/MyResponseMessage.cs
samples/wcf/Wcf_2/Wcf/MyService.cs
samples/wcf/Wcf_2/Wcf/Program.cs
samples/wcf/Wcf_2/Wcf/Wcf.csproj
samples/wcf/sample.md

Closes #3162 and addresses #931

Wcf sample
