Particular/docs.particular.net

- Snippets/Snippets_3/Injection/Injection.cs
- Snippets/Snippets_3/Snippets_3.csproj
- Snippets/Snippets_5/CustomConfigOverrides.cs
- Snippets/Snippets_5/Injection/Injection.cs
- Snippets/Snippets_5/Persistence.cs
- Snippets/Snippets_5/Persistence/NHibernate/ConfiguringNHibernate.cs
- Snippets/Snippets_5/Persistence/PersistenceOrder.cs
- Snippets/Snippets_5/ScaleOut/individualize_queues.cs
- Snippets/Snippets_5/Snippets_5.csproj
- Snippets/Snippets_5/packages.config
- menu/menu.yaml
- nservicebus/index.md
- nservicebus/individualizing-queues-when-scaling-out.md
- nservicebus/property-injection-in-handlers.md
**Warning**: Merge this documentation once NServiceBus V5.2 is released.
Updated code snippets to reflect changes in Persistence extensibility per storage API (deprecation of `Storage` and introduction of `StorageType`) introduced with the [following PR](https://github.com/Particular/NServiceBus/pull/2587).
/cc @johnsimons
> New Persistence extensibility per storage API

- nservicebus/testing/unit-testing.md
* Removed is
* Than instead of Then (typical mistake originated with the Israeli accent in English)
* Removed double use of 'this'
* Clarified some of the text
> corrected some of the English

- nservicebus/handlers/index.md
are (not: is) for plural. 
hyphenated: publish-and-subscribe
> small grammar corrections

- nservicebus/azure/azure-servicebus-transport.md
- nservicebus/azure/azure-storage-queues-transport.md
Based on https://github.com/Particular/Requirements/issues/245 
**Attention**: should be merged when PR for ASB https://github.com/Particular/NServiceBus.AzureServiceBus/pull/27 and PR for ASQ https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/9 are accepted and released.
> Obsoletng QueueName and QueuePerInstance from Azure transports in favour on core settings

- Snippets/Snippets_5/Outbox/RavenDB/TimeToKeep.cs
- Snippets/Snippets_5/Snippets_5.csproj
- Snippets/Snippets_5/packages.config
- nservicebus/outbox/index.md
I'm not yet sure whether we should really document the access to the `Outbox.*` settings. Really on the fence here. But I added time for completeness reasons.
Additionally I have a few questions about the current structure:
We have the outbox doco page which is describing outbox in general and then primarily NH persistence and Sql transport related things (before). Now I just added as an extension the ravendb outbox settings as well. My question is:
Should we move all persistence specific doco into a page in the corresponding persister? And if we do so also align the navigation there? For example currently the persister in the NH case is called `NHibernate persister` but in the RavenDB case simple `RavenDB`.
> Describing outbox ravendb and including how to configure timetokeep

- nservicebus/upgrades/release-policy.md
Better information about which versions are supported to decide when backporting is required and for customers to understand if their current version is still supported to receive bug fixes.
@andreasohlund Please review, this should reflect the discussion we had on Slacks #release-policy channel.
> Release policy restructured with samples

- nservicebus/licensing/license-management.md
Culled from [the code that is responsible](https://github.com/Particular/NServiceBus/blob/a151f2341d61a57ade9b9be29e7a9c08fbe4002f/src/NServiceBus.Core/Licensing/LicenseLocationConventions.cs) so should be accurate.
The one **DEPRECATED** I'm assuming because in the code it's referred to as `oldLocalLicenseFile`. Assume it's still being checked for backward compatibility.
> Document where NServiceBus will look for license information, and in what order

- nservicebus/operations/auditing.md
The documentation states that a warning recommends to use the `AuditConfig` section when using `ForwardReceivedMessagesTo`. Verified that this warning does not appear when using `ForwardReceivedMessagesTo` in NSB 5.2.3, therefore removed the note.
> remove backwards compatibility note in auditing doc

- Snippets/Snippets_5/Transports/SqlServer/MultiDb.config
- nservicebus/sqlserver/multiple-databases.md
- servicecontrol/multi-transport-support.md
**DO-NOT-MERGE** until v.1.2.3 is released.
update SQL Server transport documents to reflect changes introduced in the Queue Schema feature back-ported to v1.2.3.
@SimonCropp can you please review? Can you also suggest if other documents need to be updated?
/cc @danielmarbach @adamralph 
related to https://github.com/Particular/FeatureDevelopment/issues/320
> SQL Server transport queue schema support updates

- nservicebus/errors/automatic-retries.md
add a note about the configured FLR value beeing a "minimum number of retries" value. There is a chance of more retries than configured which increases with competing consumers.
> add note about FLR best effort behavior

- nservicebus/messaging/transactions.md
We've had some desk cases where users have missed this
> Clarify behavior when transactions are off

- nservicebus/sqlserver/index.md
This is to ensure users that copy-paste the sql script do not forget to create the index.
> Included the index in the SQL DDL snippet

- nservicebus/upgrades/5to6.md
adding a short chapter to note users implementing their own timeout persistence that interfaces have changed and to consult the corresponding docs page which is already updated.
> add changed timeout persistence interface in upgrade guide

- servicecontrol/creating-config-file.md
- servicecontrol/plugins/heartbeat.md
There are 2 settings that can affect each other if not configured appropriately. Since settings are not in the same doco/configuration file, adding that information in doco.
1. SC `ServiceControl/HeartbeatGracePeriod`
1. Heartbeat plugin `heartbeat/interval`
@Particular/servicecontrol please review
> Clarification about heartbeat interval and grace period settings

- nservicebus/outbox/index.md
This caveat never made sense. You have to have your Outbox data in the same database as your business data, but if you have multiple endpoints, you have to have it in a *separate* data store?
More to the point, this refers to the bug in NHibernate that I fixed, and to NHibernate in general, which at the time was the only Outbox storage in town. Now it makes no sense.
Related to Particular/NServiceBus.NHibernate#117
/cc @indualagarsamy @SzymonPobiega @andreasohlund @SeanFeldman @johnsimons (Participants on bug issue)
> Outbox caveat no longer applicable

- Snippets/Snippets_6/BusNotifications/EventsToObservables.cs
- Snippets/Snippets_6/Snippets_6.csproj
- Snippets/Snippets_6/packages.config
- nservicebus/upgrades/5to6.md
sadly, the example code requires all the rx packages, should we just omit it?
> notifications section in v6 upgrade guide

- Snippets/Snippets_6/Transactions.cs
- nservicebus/concept-overview.md
- nservicebus/messaging/transactions.md
- nservicebus/upgrades/5to6.md
Documents the obsoletion of DoNotWrapHandlersInTransactionScope and also restructures the transaction doco
> Remove `.DoNotWrapHandlersInTransactionScope`

- Snippets/Snippets_4/Pipeline/SampleBehavior.cs
- Snippets/Snippets_5/Pipeline/SampleBehavior.cs
- Snippets/Snippets_6/Headers/IncomingBehavior.cs
- Snippets/Snippets_6/Headers/OutgoingBehavior.cs
- Snippets/Snippets_6/Pipeline/AbortingPipeline.cs
- Snippets/Snippets_6/Pipeline/SampleBehavior.cs
- Snippets/Snippets_6/Pipeline/SharingBehaviorData.cs
- Snippets/Snippets_6/UpgradeGuides/5to6/OutgoingBehavior.cs
- samples/pipeline/handler-timer/Version_6/Sample/HandlerTimerBehavior.cs
- samples/pipeline/stream-properties/Version_6/Shared/StreamReceiveBehavior.cs
- samples/pipeline/stream-properties/Version_6/Shared/StreamSendBehavior.cs
@Particular/documentation This PR adds `ConfigureAwait(false)` to the behaviors. Inside the pipeline it matters.
I know this is a slight contradiction to http://docs.particular.net/samples/#technology-choices-async-await
I also aligned Snippet 4 and Snippet 4 behavior comment to Snippets 6 behavior
> ConfigureAwait in behaviors

- nservicebus/upgrades/5to6.md
As the documentation for transports describe use cases of existing transports, I haven't put that low level implementation detail in there. 
The upgrade notes 5to6 have notes for transport implementors. I've added a paragraph about handling the receive cancellation gracefully.
Related to Particular/NServiceBus#3254
> [WIP] upgrade 5to6 now mentions the cancellation of a pipeline in Transport seam

- samples/sqltransport-nhpersistence/sample.md
Coming from https://groups.google.com/forum/#!msg/particularsoftware/R9ZYJwRX6XI/6XJAjfPBCAAJ:
I wasn't sure about the truth of that statement so I spent some time investigating. It appears that the
statement isn't valid. I verified by creating multiple endpoints where the only naming difference was
in the assembly name. Configuration was specified to only use dbo schema, using Outbox, Sagas and Timeouts.
All communication appeared to work as expected.
I'm happy to have missed some detail, but as of now it appears that this sentence is not exactly true.
> Remove section on schema name https://github.com/Particular/docs.particular.net/pull/1037requirement

- nservicebus/upgrades/5to6.md
Connects to #1083
@Particular/documentation I contemplated about mentioning the usage of callbacks inside handlers and sagas but then back tracked because I didn't want to encourage bad design choices by mentioning it. If you feel otherwise I'm happy to add it to the "Handling responses on the client side" documentation page.
> Mentioning that callbacks can no longer be used in handlers or sagas.

- Snippets/Snippets_5/UpgradeGuides/5to6/Upgrade.cs
- Snippets/Snippets_6/MsmqTransactionScope.cs
- Snippets/Snippets_6/Snippets_6.csproj
- Snippets/Snippets_6/TransactionScopeUnitOfWork.cs
- Snippets/Snippets_6/TransportTransactions.cs
- Snippets/Snippets_6/Transports/SqlServer/ConfigurationSettings.cs
- Snippets/Snippets_6/UpgradeGuides/5to6/Upgrade.cs
- Snippets/Snippets_6/app.config
- Snippets/Snippets_6/packages.config
- nservicebus/messaging/transactions.md
- nservicebus/msmq/transportconfig.md
- nservicebus/pipeline/unit-of-work.md
- nservicebus/sqlserver/index.md
- nservicebus/upgrades/5to6.md
First stab at documenting the transaction API cleanup.
> Document transaction scope wrapper UoW and MSMQ & SQL transaction scope opts

- nservicebus/handlers/index.md
I added a single paragraph. But although it might be clear or correct what it states (I have you to verify that ;-) ) I'm not sure of readers of the document will understand.
I've thought about a code snippet of a single line, which seems ridiculous. Also because it's not NSB version related, it's .NET related.
I've also thought about putting a triple ` addition, like in the step-by-step page (http://docs.particular.net/samples/step-by-step/)
But I'm not sure if I'm allowed to use that.
So I'd like some feedback
> Add info for message type fallback

- Snippets/Snippets_6/Transports/Throughput/InitialThroughput.config.xml
- nservicebus/operations/tuning.md
* Remove obsolete throughput throttling configuration options for v6 snippets
* Add a note to the tuning page that this has been removed with v6
See Particular/NServiceBus#3306
Note that I created a new issue about providing some samples on how to implement custom throughput throttling here: #1086
> Throughput throttling

- nservicebus/errors/automatic-retries.md
- nservicebus/upgrades/5to6.md
As of v6, the TimeoutManager has its own fixed FLR policy.
This is doco PR for Particular/NServiceBus#3337.
> Describe that FLR settings do not apply to TimeoutManager in v6

- servicecontrol/troubleshooting.md
- servicecontrol/use-ravendb-studio.md
If the service account is not a local administrator or localsystem enabling the ExposeRavenDB setting can cause the server to fail on startup. This is because A URLACL is required to allow the Raven Management Studio to be exposed on the /storage virtual directory. Raven will create this automatically if the service account has the privileges.
This PR details the worlkaround
> Add Troubleshooting info on required URLACL

- nservicebus/licensing/license-management.md
We had feedback via a desk case that the licensing doc should be more explicit about importing the license into the WOW3264Node of the registry
> WIP - Licensing - Make 32bit and 64 bit more explicit

- Snippets/Snippets_4/UnitTesting/AdditionalServices/Tests.cs
- Snippets/Snippets_5/UnitTesting/AdditionalServices/Tests.cs
- nservicebus/testing/index.md
There was no reference how to obtain a copy of bus to use with a handler that is using constructor injected `IBus` which led to confusion ([GG post](https://groups.google.com/forum/#!topic/particularsoftware/s4tMzGZ4Liw)).
> added sample code + section

- nservicebus/upgrades/5to6.md
Connects to https://github.com/Particular/NServiceBus.Gateway/pull/25
Gateway changes for V6. Obsoletes several public interfaces and introduces an explicit configurable extension point.
> Version 6 gateway changes

- nservicebus/messaging/transactions.md
- nservicebus/upgrades/5to6.md
Relates to https://github.com/particular/nservicebus/issues/2752
- Clarified the behavior differences of disabling transactions in Version 5 and Version 6
- Updated the upgrade guide for this behavior change.
> Changes related to disabling transactions in v6

- Snippets/Snippets_5/RavenDB/SpecificDocumentStoreViaConnectionString.config.xml
- Snippets/Snippets_6/RavenDB/SpecificDocumentStoreViaConnectionString.config.xml
- nservicebus/ravendb/index.md
Starting with the most esoteric option (because it's what the code looks for first) is just wrong. It's like giving your down-the-street neighbor directions to your house via the North Pole.
> Flipping the Raven configuration options order

- menu/menu.yaml
- nservicebus/handlers/index.md
- nservicebus/messaging/conventions.md
- nservicebus/messaging/headers.md
- nservicebus/messaging/memory-transport.md
- nservicebus/messaging/message-owner.md
- nservicebus/messaging/messages-events-commands.md
- nservicebus/messaging/unobtrusive-mode.md
- nservicebus/upgrades/5to6.md
Connects to https://github.com/Particular/NServiceBus/pull/3461
With the above PR it is no longer possible to inject `Conventions`. This adds that fact to the upgrade 
guide.
> Mentioning Conventions can no longer be injected

- samples/throttling/Version_6/Sample/GitHubSearchHandler.cs
- samples/throttling/Version_6/Sample/ThrottlingBehavior.cs
fixes the bug in the throttling sample where the replyto address was overridden when doing a local send. We can now maintain the original reply to address using the new `RouteReplyTo` send option.
related to https://github.com/Particular/docs.particular.net/issues/1086
@hmemcpy @SimonCropp @johnsimons
> maintain original ReplyTo address

- nservicebus/outbox/index.md
As discussed [here](https://github.com/Particular/docs.particular.net/pull/1174#discussion-diff-52883776R55) that is to include info removed from SQL Server transport doco.
Plus clean up and clarify a few points.
> Update outbox doco

- samples/custom-transport/Version_6/Shared/Dispatcher.cs
Sample fails if directory does not yet exist
> fix to create directory if not exists

- nservicebus/upgrades/5to6.md
The statement with `await Task.FromResult` was weird. Removed it for better clarity. It was also not clear to what "this" was referring to.
> Removed statement about `await Task.FromResult` from upgrade guide

- nservicebus/upgrades/5to6.md
Added this in the upgrade guide. Please see #1177 if anything else should be added.
> Adding note about deprecating ConfigureTransport

- nservicebus/messaging/send-a-message.md
differentiate between sending from within or outside the pipeline which allows a better documentation of the v6 api. Something like this would allow the `IBus` deprecation notes to link to this page.
I didn't rename the file to keep a readable diff.
> enhance send-a-message.md

- Snippets/Snippets_5/Persistence/NHibernate/AccessingData.cs
- Snippets/Snippets_6/Persistence/NHibernate/AccessingData.cs
- Snippets/Snippets_6/Sagas/FindSagas/NHibernateSagaFinder.cs
- nservicebus/nhibernate/accessing-data.md
- samples/outbox/sqltransport-nhpersistence-ef/Version_3/Receiver/Program.cs
This would update the documents and samples on how to access ISession in v6 (while keeping the other available approaches in v5).
> Updating the sample and documents for ISession access in v6

- samples/outbox/sqltransport-nhpersistence-ef/Version_3/Receiver/Receiver.csproj
- samples/outbox/sqltransport-nhpersistence-ef/Version_3/Receiver/packages.config
- samples/outbox/sqltransport-nhpersistence-ef/Version_3/Sender/Sender.csproj
- samples/outbox/sqltransport-nhpersistence-ef/Version_3/Sender/packages.config
- samples/outbox/sqltransport-nhpersistence-ef/Version_3/Shared/Shared.csproj
- samples/outbox/sqltransport-nhpersistence-ef/Version_3/Shared/packages.config
- samples/outbox/sqltransport-nhpersistence/Version_3/Receiver/Receiver.csproj
- samples/outbox/sqltransport-nhpersistence/Version_3/Receiver/packages.config
- samples/outbox/sqltransport-nhpersistence/Version_3/Sender/Sender.csproj
- samples/outbox/sqltransport-nhpersistence/Version_3/Sender/packages.config
- samples/outbox/sqltransport-nhpersistence/Version_3/Shared/Shared.csproj
- samples/outbox/sqltransport-nhpersistence/Version_3/Shared/packages.config
Related to the timeouts bug raised here https://github.com/Particular/NServiceBus/issues/3499.
After upgrade the bug is fixed.
> Upgrade dependencies in outbox nhibernate samples

- nservicebus/hosting/assembly-scanning.md
- nservicebus/hosting/nservicebus-host/index.md
When answering a [StackOverflow question](http://stackoverflow.com/questions/35871942/nservicebus-scanning-all-assemblies) it turned out that the `/scannedAssemblies` switch of `NServiceBus.Host.exe` is undocumented.
@Particular/nservicebus-maintainers @Particular/docs-maintainers Please review this for correctness. Knowledge I describe here was gathered by code spelunking and experimentation.
> Describe /scannedAssemblies switch of NServiceBus.Host

- Snippets/Snippets_4/Snippets_4.csproj
- Snippets/Snippets_4/UnitTesting/AdditionalServices/MyMessage.cs
- Snippets/Snippets_4/UnitTesting/AdditionalServices/MyService.cs
- Snippets/Snippets_4/UnitTesting/AdditionalServices/Tests.cs
- Snippets/Snippets_5/Snippets_5.csproj
- Snippets/Snippets_5/UnitTesting/AdditionalServices/MyMessage.cs
- Snippets/Snippets_5/UnitTesting/AdditionalServices/MyService.cs
- Snippets/Snippets_5/UnitTesting/AdditionalServices/Tests.cs
- Snippets/Snippets_6/Snippets_6.csproj
- Snippets/Snippets_6/Transports/SqlServer_3/MultiSchema.config
- Snippets/Snippets_6/UnitTesting/AdditionalServices/MyMessage.cs
- Snippets/Snippets_6/UnitTesting/AdditionalServices/MyService.cs
- Snippets/Snippets_6/UnitTesting/AdditionalServices/Tests.cs
- Snippets/Snippets_6/UnitTesting/HeaderManipulation/RequestMessage.cs
- Snippets/Snippets_6/UnitTesting/HeaderManipulation/ResponseMessage.cs
- Snippets/Snippets_6/UnitTesting/HeaderManipulation/Tests.cs
- Snippets/Snippets_6/UnitTesting/Saga/MyCommand.cs
- Snippets/Snippets_6/UnitTesting/Saga/MyEvent.cs
- Snippets/Snippets_6/UnitTesting/Saga/MyResponse.cs
- Snippets/Snippets_6/UnitTesting/Saga/MySaga.cs
- Snippets/Snippets_6/UnitTesting/Saga/MySagaData.cs
- Snippets/Snippets_6/UnitTesting/Saga/StartsSaga.cs
- Snippets/Snippets_6/UnitTesting/Saga/Tests.cs
- Snippets/Snippets_6/UnitTesting/ServiceLayer/RequestMessage.cs
- Snippets/Snippets_6/UnitTesting/ServiceLayer/ResponseMessage.cs
- Snippets/Snippets_6/UnitTesting/ServiceLayer/Tests.cs
- Snippets/Snippets_6/packages.config
- nservicebus/testing/index.md
Connects to https://github.com/Particular/NServiceBus.Testing/issues/29
This adds testing snippets, converted to v6.
Also adding a few tweaks in the testing docs (mainly, removing the word "unit" whenever possible)
> Updating unit testing snippets to v6

- nservicebus/upgrades/5to6.md
Renamed the upgrade guide file but missed reference from 5to6.md.
@Particular/docs-maintainers Please merge to make the build green again.
> Fix reference to gateway upgrade guide

- nservicebus/ravendb/index.md
@SimonCropp I committed a little fix to master because you had put NServiceBus.RavenDB 5 at the top of the RavenDB article which doesn't make any sense - it actually referred to Core. There is no NSB.Raven V4 yet let alone V5. But I agree that it's confusing to have NServiceBus 5 right at the top of the Raven article. What do you think of this attempt to get rid of that confusion?
> Alternative to "NServiceBus 5" at the top of the RavenDB article

- nservicebus/testing/index.md
The assemblies to scan must include the testing assembly or an exception will be thrown. http://stackoverflow.com/questions/28722542/nservicebus-test-initialize-given-key-was-not-present
> Add example of initializing test with lambda

- nservicebus/upgrades/5to6.md
This started with me fixing a typo in the original:
> In the interest of "smaller changes are easier to verify" it is recommended to update to .NET 4.5.2, and full migration to production, before updating to NServiceBus Version 6.
But I also felt the text in the rest of the section could be tightened up a bit.
> Some tweaks to the Move to 4.5.2 section

- nservicebus/ravendb/index.md
- nservicebus/ravendb/resourcemanagerid.md
Connects to Particular/PlatformDevelopment#697
NSB.Raven 3.1.0 was pulled, this brings docs back in line with what is currently released and for the upcoming 3.0.7 hotfix.
Snippets still do not reflect V6. That is out of scope for this PR and will come later, especially considering Particular/PlatformDevelopment#686 which may change things a bit.
> Do not mention pulled 3.1.0 version any longer.

- nservicebus/host-startup.include.md
Connects to https://github.com/Particular/NServiceBus.Host/issues/68
[Startup behaviour](http://docs.particular.net/nservicebus/hosting/nservicebus-host/#startup-behavior) described in http://docs.particular.net/nservicebus/hosting/nservicebus-host/ - descriptions for `Start` and `Stop` go into implementation details:
>  Each call to Start is called in the OnStart method of a FeatureStartupTask.
and 
> Each call to Stop is called in the OnStop method of a FeatureStartupTask.
From a user perspective, this could be confusing internal implementation details .
/cc @weralabaj @bording @colin-higgins
> Removing internal details about Start and Stop of IWantToRunWhenEndpointStartsAndStops

- samples/azure/shared-host/Version_7/HostCloudService/HostCloudService.ccproj
- samples/azure/shared-host/Version_7/HostWorker/HostWorker.csproj
- samples/azure/shared-host/Version_7/HostWorker/packages.config
- samples/azure/shared-host/Version_7/Receiver/Receiver.csproj
- samples/azure/shared-host/Version_7/Receiver/packages.config
- samples/azure/shared-host/Version_7/Sender/Sender.csproj
- samples/azure/shared-host/Version_7/Sender/packages.config
Package: Unofficial.Microsoft.WindosAzure.Diagnostics
Note: ASQ transport is currently breaking due to unimplemented interface
```
System.TypeLoadException: Method 'Initialize' in type 'NServiceBus.AzureStorageQueueTransport' from assembly 'NServiceBus.Azure.Transports.WindowsAzureStorageQueues, Version=7.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c' does not have an implementation.
```
/cc @SimonCropp
> Replacing SDK reference with nuget package

- Snippets/Snippets_5/Features/AdvancedSatellite.cs
- Snippets/Snippets_5/Features/SimpleSatellite.cs
- Snippets/Snippets_5/Snippets_5.csproj
- Snippets/Snippets_6/Features/AdvancedSatelliteFeature.cs
- Snippets/Snippets_6/Features/SatelliteFeature.cs
- Snippets/Snippets_6/Snippets_6.csproj
- nservicebus/pipeline/satellites.md
- nservicebus/upgrades/5to6.md
Fixes https://github.com/Particular/docs.particular.net/issues/532
Satellites are obsolete from V6.
Satellites are implemented using the pipeline Feature.
> Satellite migration doco

- nservicebus/ravendb/index.md
@SimonCropp this minor tweak doesn't go too far in documenting ReadOnlySettings itself, does it?
> Slight tweak to the Raven "External shared store at initialization" description

- Snippets/Rabbit/Rabbit_4/Rabbit_4.csproj
- Snippets/Rabbit/Rabbit_4/packages.config
- samples/rabbitmq/native-integration/Rabbit_4/Receiver/Receiver.csproj
- samples/rabbitmq/native-integration/Rabbit_4/Receiver/packages.config
- samples/rabbitmq/simple/Rabbit_4/Sample/Sample.csproj
- samples/rabbitmq/simple/Rabbit_4/Sample/packages.config
Because there is an old unlisted 4.0.0 beta1 and beta2 on nuget.org already, we had to bump up to beta 3.
> Update Rabbit V4 snippets and samples to beta3

- nservicebus/messaging/publish-subscribe/index.md
NHibernate link was pointing to "ravendb", changed it to "nhibernate"
> corrected NHibernate link on pub/sub

- nservicebus/azure-service-bus/secure-credentials.md
1. sensitive information => connection string
1. `UseNamespaceNamesInsteadOfConnectionStrings()` is not a feature => configuration API
1. secrets => key
1. error queue doesn't leak connections strings => removed
@SimonCropp please review
> minor tweaks

- nservicebus/azure-storage-queues/configuration.md
make it more clear what the connectionstring is for, to be consistent (and differentiating from) the same text in asb doco
> make it more clear what the connectionstring is for

- nservicebus/upgrades/absdatabus-6to1.md
- nservicebus/upgrades/azure-deprecation.md
Went with a short section in the main upgrade guide and then a new page for the data bus specific details.
Depends on https://github.com/Particular/docs.particular.net/pull/1502 since I'm linking to the upgrade guide for ASP
> Upgrade guide for the azure databus split

- nservicebus/testing/index.md
based on the feedback gathered by @indualagarsamy:
> Regular doco for Testing wasn't clear for the Message conventions (unobtrusive) on what to do and if it has changes in v6.
Added a note stating that v6 does no longer require unobtrusive message conventions configuration for tests.
> Add note about v6 not requiring unobtrusive config

- servicepulse/install-servicepulse-in-iis.md
This change in doco involves writing down a IIS Reverse Proxy rule that was created by @rlaveycal in the following [Service Pulse bug](https://github.com/Particular/ServicePulse/issues/343#issuecomment-219088021). This section will disappear when the SignalR will be fixed to properly work with reverse proxy hosting configuration.
@Particular/docs-maintainers please review. 
I have questions/doubts regarding:
* if we should state that this configuration is due to a bug in another library. 
* if we should describe a bit more what was the problem and what this solution actually does (however for customers that didn't encounter this error it is just not important)
* I struggle here how to name this situation, currently I use 2 terms:
* non-root directory
* sub directory
To refer to the same …
> [WIP] Adding IIS reverse proxy rule 

- nservicebus/sagas/saga-finding.md
Inspired by a customer that used both mechanisms at the same time, and used custom finder even though they needed only simple property mapping. The doco could be more explicit and mention the main article (so if somebody lands on the custom finder page only, they can go to the main page for full context).
@Particular/docs-maintainers please, see if that's clear enough?
> Clarify when to use custom saga finder

- Snippets/Core/Core_6/Routing/RoutingFile.xsd
Testing the xml schema showed that theres a missing maxOccurs schema constraint which is required if you want to declare multiple endpoints, otherwise schema validation fails.
/cc @SzymonPobiega
> Allow multiple endpoints in the schema

- samples/scaleout/senderside/Core_6/AwareClient/Program.cs
- samples/scaleout/senderside/Core_6/AwareClient/routes.xml
- samples/scaleout/senderside/Core_6/Messages/DoSomething.cs
- samples/scaleout/senderside/Core_6/Server1/DoSomethingHandler.cs
- samples/scaleout/senderside/Core_6/Server2/DoSomethingHandler.cs
- samples/scaleout/senderside/Core_6/UnawareClient/Program.cs
Fix bug in sender-side distribution sample, add SequenceId to the message for clarity, so you can see the even and odd ones segregated when using the round-robin routing in the AwareClient.
> Sender side distribution sample bug

- serviceinsight/index.md
- serviceinsight/managing-errors-and-retries.md
- servicepulse/intro-failed-messages.md
Relates to #1238 
Takes the Error Handling part of the ServiceInsight doco and puts in a different page in the doco so that it can be referred by the ServicePulse doco.
@Particular/serviceinsight-maintainers can you please review this and see if you're happy with the change.
> Remove manual "Related Articles" in SP doco

- Snippets/Core/Core_5/Features/Features.cs
- Snippets/Core/Core_6/Features/Features.cs
- nservicebus/pipeline/features.md
- nservicebus/upgrades/5to6.md
relates to https://github.com/Particular/NServiceBus/pull/3774
there was no statement about not removing the feature suffix in v6
@SimonCropp ping
> Update dependsOn documentation

- Snippets/Core/Core_6/Pipeline/NewPipelineStep.cs
- nservicebus/pipeline/manipulate-with-behaviors.md
- nservicebus/upgrades/5to6.md
- samples/feature/Core_6/Sample/Handler/HandlerTimerFeature.cs
- samples/feature/Core_6/Sample/Saga/SagaStateAuditFeature.cs
- samples/pipeline/stream-properties/Core_6/Shared/StreamConfig.cs
Decision was made to obsolete WellKnownStep for v6 and essentially make InsertBefore/After more difficult and treat it as a "hidden api" (since we want to remove it in the future)
> Obsolete wellknownstep

- samples/sqltransport/multi-instance/SqlServer_2/EndpointConnectionLookup/ConnectionProvider.cs
- samples/sqltransport/multi-instance/SqlServer_3/EndpointConnectionLookup/ConnectionProvider.cs
* Both V2 and V3 sample now use a *StartsWith*
* Fixed behavior of V3 sample that previously returned sender connection for receiver endpoint and vice versa.
> Fix for multi instance so that satellite queues are created using the correct instance

- nservicebus/ravendb/index.md
Fixes #1252 
Now that we want users to specify a RavenDB document store so they can also configure DTC settings, ordering the options from most basic (default localhost:8080) to most complex (DocumentStore) is the wrong order.
Moved the DocumentStore options to the top, connection strings / params in the middle, default at the end.
Also wrote some information to route people to the configuring DTC settings manually article, but mostly this is just a move-around.
> Reorder Raven connection options in recommendability order

- samples/scaleout/distributor/Distributor_4.3/Sender/OrderPlacedHandler.cs
- samples/scaleout/distributor/Distributor_4.3/Worker.Handlers/ProcessOrderCommandHandler.cs
- samples/scaleout/distributor/Distributor_4/Sender/OrderPlacedHandler.cs
- samples/scaleout/distributor/Distributor_4/Worker.Handlers/ProcessOrderCommandHandler.cs
- samples/scaleout/distributor/Distributor_5/Sender/OrderPlacedHandler.cs
- samples/scaleout/distributor/Distributor_5/Worker.Handlers/ProcessOrderCommandHandler.cs
- samples/scaleout/distributor/Distributor_6/Sender/OrderPlacedHandler.cs
- samples/scaleout/distributor/Distributor_6/Worker1/Program.cs
- samples/scaleout/distributor/Distributor_6/Worker2/Program.cs
- samples/scaleout/distributor/Distributor_6/Worker2/app.config
- samples/scaleout/distributor/sample.md
Simplified the V6 distributor scenario by removing the concept of instance IDs from the picture and replacing it with address translation exceptions.
> Removed usage of instance IDs in favor of address translation exception

- samples/step-by-step/sample.md
Adjusted guide to make the sequence of steps more logical and give MSMQ installation instructions directly to avoid having to move away from this page. This is also to prevent the requirement of having to run the Platform Installer which doesn't really seem to simplify the set up of MSMQ.
Note: In order for this PR to be effective:
- the NuGet section at the top should be omitted (because the NuGet package installation is not the first thing the guide should start with, it's just a step in the guide).
- the "Download" and "Browse on GitHub" buttons should be hidden to discourage readers from straying away from following the guide
> Adjusted guide to make sequence of steps more logical

- servicecontrol/installation-powershell.md
- servicecontrol/license.md
Update ServiceControl licensing to specify that the registry is the place we expect licenses and that the file based approach shouldn't be used.
@mikeminutillo  @SimonCropp  please review
> Rework licensing  info

- Snippets/Common/SomeLibrary.cs
- Snippets/Core/Core_6/Core_6.csproj
- Snippets/Core/Core_6/Handlers/AsyncHandler.cs
- Snippets/Core/Core_6/Handlers/IntegrationWithNonTaskBasedAPI.cs
- menu/menu.yaml
- nservicebus/handlers/async-handlers.md
Relates to #1563
This PR serves as a discussion startet about what kind of snippets we'd like to introduce to show async and sync code usage inside async handlers. Discussed this proposal approach with @SimonCropp and @weralabaj 
Using a bunch of simulations to show the difference between the approaches. Of course those simulations are not 100% accurate. They are also using `Task.Yield()` instead of a real IO bound operation.
```ini
BenchmarkDotNet=v0.9.6.0
OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz, ProcessorCount=8
Frequency=2728071 ticks, Resolution=366.5594 ns, Timer=TSC
HostCLR=MS.NET 4.0.30319.42000, Arch=32-bit RELEASE
JitModules=clrjit-v4.6.1055.0
Type=BatchedVsImmediateSimulated  Mode=Throughput  TargetCount=1  
```
Method | Platform | …
> Standard async patterns including concurrency

- servicepulse/index.md
I recommend making the presentation of "See also" links consistent for all sections and rename to "Learn more" to indicate it would be follow up documentation. I also think it's easier to scan links to related pages in a bulleted list.
> Organized "See also" links in "Learn more" list

- nservicebus/logging/common-logging.md
- nservicebus/logging/log4net.md
- nservicebus/logging/nlog.md
Routing is a keyword and has other meanings in NServiceBus, such as adding routing information to the endpoints for sending messages. Therefore the use of the word routing can be confusing in how to integrate with Logging in NServiceBus articles.
> Removed the usage of the keyword routing in Logging

- nservicebus/upgrades/5to6.md
I went looking for this link and couldn't find it, in part because the section "Message handlers" that I thought should have linked to it did not contain the link. There's no reason for a separate heading containing one line of text.
> Don't hide upgrading existing handlers under a separate heading

- nservicebus/upgrades/5to6.md
BinarySerializer is deprecated based on http://docs.particular.net/nservicebus/serialization/binary
> BinarySerializer is deprecated

- Snippets/Callbacks/Callbacks_1/Callbacks_1.csproj
- Snippets/Callbacks/Callbacks_1/Cancellation/Usage.cs
- Snippets/Callbacks/Callbacks_1/Enum/Usage.cs
- Snippets/Callbacks/Callbacks_1/Int/Usage.cs
- Snippets/Callbacks/Callbacks_1/Object/Usage.cs
- Snippets/Callbacks/Callbacks_1/UpgradeGuides/5to6/Callbacks.cs
- Snippets/Callbacks/Callbacks_1/packages.config
- nservicebus/messaging/handling-responses-on-the-client-side.md
- nservicebus/messaging/handling-responses-on-the-client-side_cancellation_callbacks_1.partial.md
- samples/callbacks/Callbacks_1/Receiver/Program.cs
- samples/callbacks/Callbacks_1/Receiver/Receiver.csproj
- samples/callbacks/Callbacks_1/Receiver/packages.config
- samples/callbacks/Callbacks_1/Sender/Program.cs
- samples/callbacks/Callbacks_1/Sender/Sender.csproj
- samples/callbacks/Callbacks_1/Sender/packages.config
- samples/callbacks/Callbacks_1/Shared/Shared.csproj
- samples/callbacks/Callbacks_1/Shared/packages.config
- samples/callbacks/Callbacks_1/WebSender/Global.asax.cs
- samples/callbacks/Callbacks_1/WebSender/WebSender.csproj
- samples/callbacks/Callbacks_1/WebSender/packages.config
@Particular/docs-maintainers this shows the new way of callback cancellation introduced in
https://github.com/Particular/NServiceBus.Callbacks/pull/27
Those changes haven't been released yet!
While reviewing the documentation here I also sent in
https://github.com/Particular/NServiceBus.Callbacks/pull/34
Should we change the snippets to only show `SendOptions` overload when really necessary?
> Showing new way of callback cancellation and update to NSB.Callbacks 1.0.0-Beta2

- nservicebus/pipeline/features.md
The differences of internal details of implementation between version 5 and 6 should not matter. Final result to the users is the same. In v6, we're awaiting for all the `FeatureStartupTask`s to complete, so in essence delaying the endpoint startup. Just like in v5.
@Particular/nservicebus-maintainers please confirm and let know if the change makes sense.
> FeatureStartupTask note clarification

- nservicebus/azure-service-bus/message-lock-renewal.md
- nservicebus/azure-service-bus/namespace-hierarchy.md
- nservicebus/azure-service-bus/publisher-names-configuration.md
- nservicebus/azure-service-bus/retries.md
- nservicebus/azure-service-bus/sanitization.md
- nservicebus/azure-service-bus/sanitization_auto_asb_[,7).partial.md
- nservicebus/azure-service-bus/sanitization_auto_asb_[7,).partial.md
- nservicebus/azure-service-bus/securing-connection-strings.md
- nservicebus/azure-service-bus/token-provider.md
- nservicebus/outbox/index.md
And added version range to component pages where it did make sense. 
This is required for https://github.com/Particular/DocsEngine/pull/229 to generate all the doco without errors.
> Removed component tag from pages where it did not make sense.

- Snippets/CloudServicesHost/CloudServicesHost_7/CloudServicesHost_7.csproj
- Snippets/CloudServicesHost/CloudServicesHost_7/EndpointNameInCode.cs
- Snippets/Host/Host_7/EndpointNameInCode.cs
- Snippets/Host/Host_7/Host_7.csproj
- nservicebus/endpoints/specify-endpoint-name.md
For
* Azure Cloud Service Host
* NSB Host
Issue raised https://github.com/Particular/NServiceBus.Host.AzureCloudService/issues/57
Related PRs
* https://github.com/Particular/NServiceBus.Host/pull/92
* https://github.com/Particular/NServiceBus.Host.AzureCloudService/pull/58
Interestingly I could not find a specific configuration page which explains how the Azure host works and how things like conventions, endpoint name attribute etc. are applied. So my assumption was that we assume customers make the mental leap to connect the functionality to the NSB Host. If that assumption was wrong we need to do a lot more work than outlined here in this PR.
The two linked PRs need to go in first.
Thoughts @Particular/docs-maintainers ?
// cc @Particular/azure-host-maintainers
> Show snippet for DefineEndpointname

- nservicebus/messaging/delayed-delivery.md
relates to https://github.com/Particular/NServiceBus/issues/2710
Do transports support native deferral behave the same? @andreasohlund
> Add note about reply behavior when using bus.defer

- nservicebus/operations/tuning.md
I removed the part that talked about "allow the transport to optimize" since that isn't true.
The current statement isn't 100% correct but perhaps close enough?
Related to https://github.com/Particular/NServiceBus/pull/4092
> Update to new core default for concurrency

- nservicebus/gateway/index.md
- samples/servicecontrol/events-subscription/Core_V6/index.md
Attempting to document Gateway version compatibility, related to https://github.com/Particular/NServiceBus.Gateway/issues/55#issuecomment-240630778.
I admit, it gets awkward when describing about the versions, especially since Gateway got split out from Core V5.
The last paragraph is also a bit of hand-wavyness on my part. Please bash freely.
//cc @Particular/docs-maintainers @Particular/nservicebus-maintainers @indualagarsamy @andreasohlund @johnsimons @boblangley
> Gateway version compatibility

- samples/step-by-step/sample.md
The Getting Started is linked from a lot of places and is geared for the new user. When a user gets here, the user can have the impression that NServiceBus only works with MSMQ as the pre-requisite says install MSMQ. This can put off users who dislike MSMQ and/or already using other transports.
> Adding the info that NServiceBus does work with other transports.

- samples/step-by-step/Core_6/Server/PlaceOrderHandler.cs
- samples/step-by-step/Core_6/Subscriber/OrderCreatedHandler.cs
Removed redundant implementations of `void Handle` from the v6 step-by-step sample code
> Removed redundant implementations of `void Handle`

- nservicebus/messaging/routing.md
Intentionally did not add the same not to command routing. I failed to explain why somebody would add route for `DerivedCommand` and then send `BaseCommand`.
> Added note on route inheritence.

- nservicebus/gateway/index.md
Running multiple gateways is unfortunately not possible ATM. Gateways currently route to their local input queues only. If you run multiple versions with the same endpoint name on the same machine, they will all put the incoming messages on the same queue. The different versions will then use competing consumer against this queue, meaning you have no control if the incoming vX message will have handlers run on the vX endpoint or the vX+1 endpoint. This is not safe, as there is no guarantee that vX and vX+1 will handle the same message type and if they do, will not necessarily have the same handlers.
> Remove paragraph about running multiple versions of the same gateway

- nservicebus/upgrades/support-policy.md
According to our support policy, v4 is deprecated. If there is no decision to do otherwise, I think we should make this more obvious here.
I already pinged @Particular/customer-success @Particular/customersuccess-squad  (which one is the right group?) if we need to taker further actions (e.g. announcements or otherwise), but I did not get any response so far. Maybe they want to chime in here.
> Mark v4 as unsupported

- nservicebus/hosting/expose-an-endpoint-as-a-web-wcf-service.md
- nservicebus/upgrades/host-6to7.md
relates to https://github.com/Particular/NServiceBus.Host/pull/103
Further plans as stated [here](https://github.com/Particular/V6Launch/issues/122#issuecomment-245542817) are to make a wcf integration package available under the particular labs repository. At that point we can point to this repository on this section. /cc @danielmarbach
> Add section documenting the deprecated WCF integration

- nservicebus/upgrades/5to6/recoverability.md
Instead we pass the "real" exception object to notifications.
> Exception details no longer available as headers

- Snippets/Core/Core_6/Routing/MSMQ/InstanceMappingFile.xml
@timbussmann @SzymonPobiega should we consider making the comparison case insensetive to avoid issues with casing? (see https://groups.google.com/d/msgid/particularsoftware/a3312514-c2bf-4f5c-aa6e-d9f988441f41%40googlegroups.com?utm_medium=email&utm_source=footer)
> Fix casing in msmq routing file snippet

- menu/menu.yaml
There was an inconsistency in the titles regarding the upgrade documents for NServiceBus. The 5to6 upgrade guide was called `NServiceBus 6`, the 4to5 Version guide was called `NServiceBus 4` etc.
> Clarifying menu titles for upgrade section

- nservicebus/azure-service-bus/configuration/full.md
- nservicebus/azure-service-bus/retries.md
- nservicebus/upgrades/asb-6to7.md
ASB is now setting default `MaxDeliveryCount` to match the value of Immediate Retries since message cannot be processed more than that.
> Modified doco to match ASB RC4 change

- nservicebus/sqlserver/deployment-options.md
I added example to illustrate how queue tables may be distributed among different database objects.
@Particular/sqlserver-transport-maintainers @Particular/docs-maintainers Please have a look if this adds any value. 
The motivation is [this](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/particularsoftware/3BDC7ev1lio/THo4ch57CAAJ) Google Group post.
I first tried to visualize this but failed to produce readable diagrams. Too many embedded boxes did not make it clear to me. Perhaps such a tabular form will be better.
> Add example queue table names for different deployment options

- nservicebus/messaging/delayed-delivery_caveatsnote_core_[6,).partial.md
This note is incorrect. Only ASB supports delayed delivery natively.
> Correct the v6 Delayed Delivery caveat

- nservicebus/rabbitmq/callbacks_queue_rabbit_[4,].partial.md
- nservicebus/upgrades/rabbitmq-3to4.md
This makes sure the upgrade guide will point to the v3 version of the settings page, even when v4 becomes the default.
It also removes an invalid anchor from the callbacks link became invalid when the version partial split happened.
> Fix rabbit links

- nservicebus/upgrades/5to6/extension-seams.md
We also use screenshots of performance counters in the related sample here: https://docs.particular.net/samples/performance-counters/
is there value in providing update screenshots for v6 which do not contain the satellite instances? @Particular/docs-maintainers
> Mention removed satellite pipeline performance counters

- nservicebus/transports/transactions.md
Previous formulation was misleading.
> caveat emptor for distributed transactions

- nservicebus/hosting/nservicebus-host/installation.md
relates to https://github.com/Particular/docs.particular.net/issues/2078
* Split the installation and uninstallation parts to make the specific sections easier to read.
* added a section for each installation argument
* removed `/installInfrastructure` since it doesn't seem to be around in supported versions
* I didn't find the `instance` parameter in the code of the host at a quick glance. Maybe I didn't look close enough, but can somebody help me to understand whether this is still supported and how to document it? /cc @ramonsmits @sfarmar
> Review installation.md

- servicecontrol/backup-sc-database.md
- servicecontrol/configure-non-privileged-service-account.md
- servicecontrol/configure-ravendb-location.md
- servicecontrol/creating-config-file.md
- servicecontrol/db-compaction.md
- servicecontrol/errorlog-auditlog-behavior.md
- servicecontrol/how-purge-expired-data.md
- servicecontrol/installation-powershell.md
- servicecontrol/installation-silent.md
- servicecontrol/installation.md
- servicecontrol/license.md
- servicecontrol/logging.md
- servicecontrol/setting-custom-hostname.md
- servicecontrol/troubleshooting.md
- servicecontrol/use-ravendb-studio.md
Relates to  https://github.com/Particular/ServiceControl/issues/833
In ServceControl 1.26 the word "Utility" was removed from the Management application's name and we've decided to refer to it as just ServiceControl Management.  This PR updates the doco to reflect that change
> Refer to ServiceControl Management consistently

- nservicebus/azure-storage-persistence/configuration.md
- nservicebus/azure-storage-persistence/configuration_code_asp_[1,].partial.md
- nservicebus/azure-storage-persistence/configuration_code_azure_[6,].partial.md
- nservicebus/azure-storage-persistence/configuration_sections_asp_[1,].partial.md
- nservicebus/azure-storage-persistence/configuration_sections_azure_[,6.2].partial.md
Connects to #2157
This PR introduced `component: ASP` to `configuration.md`. This enabled me to use versioning with three effective ranges and split configuration to the partials to have one, properly versioned page and remove all the `In version x ...` and leave it as intro in the beginning of the article.
|Package | config sections | config via code|
|---|:---:|:---:|
|`NServiceBus.Azure [,6)`| 👍 | |
|`NServiceBus.Azure [6,]` | 👍 | 👍 |
|`NServiceBus.Persistence.AzureStorage [1.)` | | 👍|
> [WIP] Azure Storage Persistence - configuration.md review & update

- nservicebus/upgrades/release-policy.md
It seems to me that the release frequency is not something we are following as described, so it probably makes sense to remove that section from the table?
> Remove frequency from release policy

- tutorials/nservicebus-101/lesson-2/Solution/ClientUI/Program.cs
- tutorials/nservicebus-101/lesson-2/tutorial.md
- tutorials/nservicebus-101/lesson-3/Solution/ClientUI/Program.cs
- tutorials/nservicebus-101/lesson-4/Solution/ClientUI/Program.cs
- tutorials/nservicebus-101/lesson-5/Solution/ClientUI/Program.cs
By keeping the static logger as part of the existing snippet, it reduces the overall number of steps, which should make it easier to follow. The only downside is the static logger winds up in the middle of the file, which makes my OCD twitch just a little bit, but I think the tradeoff might be worth it.
@SimonCropp you OK with that?
Added the link to https://docs.particular.net/nservicebus/logging/usage where the first instance of a logger appears.
> Restore static loggers, within snippet, add note

- nservicebus/rabbitmq/routing-topology.md
fixes https://github.com/Particular/NServiceBus.RabbitMQ/issues/274
> improve direct routing topology warning

- nservicebus/recoverability/configure-delayed-retries_legacy_core_[6.1,7].partial.md
- nservicebus/recoverability/configure-delayed-retries_legacy_core_[6].partial.md
- nservicebus/upgrades/5to6/recoverability.md
Updated the notes for DisableLegacyRetriesSatellite obsoleted method. Resolves #2272
@Particular/docs-maintainers Please review. Wasn't sure if I should extract the notes into its own partial or leave it as is.
> Updating delayed retries

- nservicebus/pipeline/unit-of-work.md
- nservicebus/pipeline/unit-of-work_access-to-context_core_[6.0,].partial.md
- nservicebus/uow-access-to-context.include.md
- nservicebus/upgrades/5to6/extension-seams.md
- samples/unit-of-work/sample.md
Unsure where in the upgrade guide to put a note?
@Particular/docs-maintainers can I use included in the samples like I do?
> [WIP]Clarify that UOW can't access message context in v6

- samples/ravendb/simple/Raven_4/Server/Server.csproj
- samples/ravendb/simple/Raven_4/Server/packages.config
- samples/saga/ravendb-custom-sagafinder/Raven_4/Sample/RavenHost.cs
- samples/saga/ravendb-custom-sagafinder/Raven_4/Sample/Sample.csproj
- samples/saga/ravendb-custom-sagafinder/Raven_4/Sample/packages.config
* Raven 3.5 server package requires Microsoft.Owin.Host.HttpListener NuGet package, but not included in NuGet dependency list
* Raven 3.5 requires magic string to allow bundles (unique constraints) to work server-side
> Fixing Raven samples broken by Raven 3.5

- get-started.md
The purpose of this PR is to put "Samples" on the same level as "Tutorials".
The "Go straight to runnable code" language pushes the reader much more strongly to the samples than to the tutorials.
> Changed "Go straight to runnable code" to "Samples"

- samples/errorhandling/Core_4/WithDelayedRetries/MyMessageHandler.cs
- samples/errorhandling/Core_4/WithoutDelayedRetries/MyMessageHandler.cs
- samples/errorhandling/Core_5/WithDelayedRetries/MyMessageHandler.cs
- samples/errorhandling/Core_5/WithoutDelayedRetries/MyMessageHandler.cs
- samples/errorhandling/Core_6/WithDelayedRetries/MyMessageHandler.cs
- samples/errorhandling/Core_6/WithoutDelayedRetries/MyMessageHandler.cs
- samples/errorhandling/sample.md
This sample uses `log.Info` to write the output which is stated in the docs page but the program is configured to use log level `Warn` so it will actually never show the documented output as described here: https://docs.particular.net/samples/errorhandling/#the-output
I switched to use `Console.WriteLine` because it makes the output easily visible.
* changing to log level info will drown the input in logged exceptions from immediate retries
* changing the log statements to use warn instead of info will make the logged lines hardly visible as they are the same color as the warnings from delayed retries which dumps the full stacktrace.
thoughts @Particular/docs-maintainers ?
> Make handler output visible.

- servicepulse/index.md
Adding a note to the ServicePulse index page which points the user to the default servicepulse url
Closes #2330
> Add default url to servicepulse index

- Snippets/Testing/Testing_6/Saga/Tests.cs
ExpectPublish() needs to be called before WhenSagaTimesOut(), otherwise it doesn't appear to be evaluated.
> Fix TestSaga() to reflect proper usage

- nservicebus/transports/queuecreation.md
- nservicebus/transports/queuecreation_scripts_core_[4,].partial.md
- nservicebus/transports/queuecreation_warning_core_[4,5].partial.md
- Separated the script from warning.
- Warning won't show for v6 as the `IWantQueuesCreated` interface is obsoleted.
Resolves #2354
> Separated the warning from script content. Resolves #2356

- nservicebus/operations/performance-counters.md
Have removed the following sentence:
> Monitors the age of the oldest message in the queue. 
The entire paragraph now might need to be re-written.
Could someone with a bit more of b/g knowledge (or perhaps historical knowledge of how this perf counter used to be exercised) chime in?
@Particular/nservicebus-maintainers 
PS: I heard @andreasohlund ❤️  perf counters 😺
> Critical time perf counter - confusing description

- samples/saga/migration/Core_6/Client/Client.csproj
- samples/saga/migration/Core_6/Client/Program.cs
- samples/saga/migration/Core_6/Client/ReplyHandler.cs
- samples/saga/migration/Core_6/Client/packages.config
- samples/saga/migration/Core_6/Contracts/Contracts.csproj
- samples/saga/migration/Core_6/Contracts/CorrelatedMessage.cs
- samples/saga/migration/Core_6/Contracts/ReplyFollowUpMessage.cs
- samples/saga/migration/Core_6/Contracts/ReplyMessage.cs
- samples/saga/migration/Core_6/Contracts/StartingMessage.cs
- samples/saga/migration/Core_6/Contracts/TestTimeout.cs
- samples/saga/migration/Core_6/Contracts/packages.config
- samples/saga/migration/Core_6/PersistenceMigration.sln
- samples/saga/migration/Core_6/PersistenceMigration.sln.DotSettings
- samples/saga/migration/Core_6/Server.New/Program.cs
- samples/saga/migration/Core_6/Server.New/Server.New.csproj
- samples/saga/migration/Core_6/Server.New/packages.config
- samples/saga/migration/Core_6/Server/App.config
- samples/saga/migration/Core_6/Server/DummyMessage.cs
- samples/saga/migration/Core_6/Server/NotFoundHandler.cs
- samples/saga/migration/Core_6/Server/Program.cs
- samples/saga/migration/Core_6/Server/Server.csproj
- samples/saga/migration/Core_6/Server/TestSaga.cs
- samples/saga/migration/Core_6/Server/packages.config
- samples/saga/migration/sample.md
Shows how to migrate saga persistences without an off-line migration procedure/script by using a pair of endpoints where existing sagas are continued to be handled by an "old" version of the endpoint while new sagas are started in the "new" version of the endpoint, using the new persistence.
It covers:
* Routing of messages with correlation property value
* Routing of messages with saga ID header
* Re-routing of timeouts after the temp endpoint is decomissioned
> A sample showing how to gradually migrate saga persistence

- nservicebus/containers/autofac.md
Adds a note to explain that the container passed in to the `ExistingLifetimeScope` method will not be updated by any of the NServiceBus registrations.
Relates to https://github.com/Particular/NServiceBus.Autofac/issues/36
> Add warning about Autofac Update obsoletion

- samples/encryption/basic-encryption/sample.md
A description is missing e.g. when looking at the encryption samples page: https://docs.particular.net/samples/encryption/
> Add description to sample

- nservicebus/rabbitmq/callbacks.md
- nservicebus/rabbitmq/callbacks_queue_rabbit_[,3].partial.md
This moves the paragraph that is redundant for the 4.x page into the 3.x and older partial.
> Remove redundant paragraph from 4.x callbacks page

- Snippets/Core/Core_3/CriticalErrors.cs
- Snippets/Core/Core_4/CriticalErrors.cs
- Snippets/Core/Core_5/CriticalErrors.cs
- Snippets/Core/Core_6/CriticalErrors.cs
- nservicebus/hosting/critical-errors.md
- nservicebus/hosting/index.md
- nservicebus/hosting/nservicebus-host/index.md
Based on https://particularsoftware.slack.com/files/ramon/F3ZJCG747/double_finaly_on_critical_error_to_flush_configured_custom_logger_before_failfast.md
> Improvements on critical error callback

- samples/saga/simple/Core_5/Sample/Program.cs
- samples/saga/simple/Core_6/Sample/Program.cs
- samples/saga/simple/sample.md
Fixed the simple saga to use the correct endpoint name and also fixed minor typos in the guidance.
> Fixing minor typos and copy paste errors

- samples/pipeline/audit-filtering/sample.md
- samples/pipeline/audit-filtering/sample_filtering_core[6.0,).partial.md
- samples/pipeline/audit-filtering/sample_filtering_core_[5.0,6.0).partial.md
Adjust the samples docs to work better with the v5 sample provided by @indualagarsamy in the target branch which replaces the complete audit behavior instead of registering additional pipeline behaviors.
@Particular/docs-maintainers thoughts?
> Rework custom audit sample doc

- servicecontrol/installation.md
Related to https://github.com/Particular/ServiceControl/issues/923
We need to tell users up front that RavenDB Management Studio requires Silverlight
> Add Silverlight Info

- samples/web/send-from-mvc-controller/Core_6/WebApplication/Global.asax.cs
The endpoint no longer needs a custom container because we aren't updating it.
The MVC application container was still called updated based on when we were updating the Endpoint container. If we are no longer doing that, it should be called something else.
> Tidy up MVC Send sample

- nservicebus/testing/index_teststructure_testing_[4,6).partial.md
Had a couple of cases where people complained about Test Fluent API in V5 being susceptible to method invocation order. In our doco it is specified https://docs.particular.net/nservicebus/testing/?version=testing_5#structure that order is important, but probably it is not enough highlighted.
Adding a `NOTE: ` to make it bolder.
> Highlights method order invocation is importat

- nservicebus/operations/installers.md
Ping @Particular/nservicebus-maintainers.
In relation to a support case the customer was not aware of this behavior. This PR adds a quick note to explain that this occurs whenever the debugger is attached.
> Clarify that installers always run with debugger attached

- samples/routing/custom/Core_6/Shared/AutomaticRouting/AutomaticRoutingFeature.cs
- samples/routing/custom/Core_6/Shared/AutomaticRouting/RoutingInfoCommunicator.cs
- samples/routing/custom/Core_6/Shared/ICircuitBreaker.cs
- samples/routing/custom/Core_6/Shared/RepeatedFailuresOverTimeCircuitBreaker.cs
- samples/routing/custom/Core_6/Shared/Shared.csproj
Current implementation crashed when there is a temporary error on the database. Also have execution overlap protection added in case the refresh operation duration is larger then the timer interval period.
> Custom routing refresh exception handling

- Snippets/Core/Core_3/InstancePerUnitOfWorkRegistration.cs
- Snippets/Core/Core_4/InstancePerUnitOfWorkRegistration.cs
- Snippets/Core/Core_5/InstancePerUnitOfWorkRegistration.cs
- Snippets/Core/Core_6/InstancePerUnitOfWorkRegistration.cs
Update the snippets to show `InstancePerUnitOfWork` instead of `InstancePerCall`.
> Update InstancePerUnitOfWorkRegistration to use InstancePerUnitOfWork lifecycle

- Snippets/NHibernate/NHibernate_6/Concurrency/SagaDataWithRowVersion.cs
- Snippets/NHibernate/NHibernate_7/Concurrency/SagaDataWithRowVersion.cs
- nservicebus/nhibernate/saga-concurrency.md
NHibernate saga concurrency can be implemented using the `RowVersion` attribute, `RowVersion` is not supported when used on derived classes. The only option is to implement the `IContainSagaData` interface directly.
@Particular/nhibernate-persistence-maintainers @Particular/docs-maintainers please review
> WIP: fix RowVersion usage

- samples/web/send-from-aspnetcore-webapi/sample.md
Note that a lot of these changes are fixes for obvious typos. I'm surprised the document made it in with so many obvious typos, e.g.
> Howeve it is not required for this sample anc can be remove.
> fixes and improvements to samples/web/send-from-aspnetcore-webapi/sample.md

- nservicebus/pipeline/steps-stages-connectors_extra_core_[6.0,).partial.md
**Changes**:
1. `Ancillary Actions` moved to the bottom to show that message processing is taking the place first
1. Assigned step numbers to highlight the dependency on the message processing before auditing and forwarding can take place
The new rendering looks like the following
**Reason for the change**:
While reviewing the [Audit filter pipeline extension sample](https://docs.particular.net/samples/pipeline/audit-filtering/) it was not clear how it would work if `"AuditFilter.Rules"` is connected to the expected next execution of the `"AuditFilter.Filter"` behavior if they are not "connected" in any shape or form on the diagram.
> Clarify order of pipeline execution

- Snippets/Core/Core_6/Core_6.csproj
- Snippets/Core/Core_6/Outbox/EnablingInConfig.xml
- nservicebus/outbox/index.md
- nservicebus/outbox/index_enable-outbox_core_[5, 5].partial.md
- nservicebus/outbox/index_enable-outbox_core_[6,).partial.md
relates to https://github.com/Particular/NServiceBus/pull/4440
Is the partial version [5,5] correct?
> [Core 6.2] Remove double-opt-in doc for v6

- Snippets/SagaAudit/SagaAudit6_2/SagaAudit.cs
- Snippets/SagaAudit/SagaAudit6_3/SagaAudit.cs
- servicecontrol/plugins/Plugin_ServiceControl_Queue_CodeConfig.include.md
- servicecontrol/plugins/saga-audit.md
- servicecontrol/plugins/saga-audit_config_SagaAudit6_[2,].partial.md
After customer remark that it wasn not clear how to uninstall the saga audit plugin for production, these changes were proposed.
> Modifications to uninstall saga audit plugin

- menu/menu.yaml
- nservicebus/pipeline/events.md
This adds the new pipeline events pages to the menu, and I also made some changes to the text of the page.
As I was adding a title to the menu, I released that "subscribing to events" is a phrase that already has a lot of meaning, so I added "notification events" in a couple places to help distinguish what's being talked about here.
CC: @Particular/nservicebus-maintainers
> Improve pipeline events page

- nservicebus/azure/index.md
PR provides a landing content page for Azure that currently is displayed in multiple places like:
- referenced articles under https://docs.particular.net/nservicebus/
- google search for [NServiceBus Azure](https://www.google.pl/?q=NServiceBus+Azure)
Previous version was empty, but still visible. After discussing it under PR hiding this page #2583 it was  agreed to deliver some content in there.
> Azure landing page with a short intro and links

- samples/azure/azure-service-fabric-routing/Core_6/Shared/EndpointPartitioning/EndpointPartitioningExtensions.cs
- samples/azure/azure-service-fabric-routing/Core_6/Shared/EndpointPartitioning/HardcodeReplyToAddressToLogicalAddressFeature.cs
- samples/azure/azure-service-fabric-routing/Core_6/Shared/Shared.csproj
Moved the `HardcodeReplyToAddressToLogicalAddress `behavior addition into a feature which gets enabled by `RegisterPartitionsForThisEndpoint`. The problem is we cannot do it in the endpoint configuration extension because that is too early for the instance specific queue to be read.
> Move HardcodeReplyToAddressToLogicalAddress into a feature 

- nservicebus/nhibernate/scripting.md
@Particular/nhibernate-persistence-maintainers I think the snippet should use `subscriberAddress` and not `distributorAddress`. Please confirm/merge. Thanks.
> snippet is mentioning distributor

- menu/menu.yaml
It seems like an omission from yesterday's release.
@ramonsmits @Particular/docs-maintainers Can you have a look and merge when green?
> Add NH timeout index resolution guide to menu

- samples/hosting/self-hosting/sample.md
Suggested by a support case, as they were working off the self-hosting sample but didn't ever find out about the critical error guidance.
Decided actually implementing critical error in the sample (both V5/V6) would be distracting and instead added a WARNING to the markdown. Open to suggestions on better wording.
> Mention critical error in self-hosting sample

- Snippets/Core/Core_6/Core_6.csproj
- Snippets/Core/Core_6/ServiceFabricHosting/EndpointCommunicationListener.cs
- Snippets/Core/Core_6/ServiceFabricHosting/Gateway.config.xml
- Snippets/Core/Core_6/project.json
- Snippets/Gateway/Gateway_2/Channels/Wildcard.config.xml
- Snippets/Gateway/Gateway_2/Gateway_2.csproj
- Snippets/Gateway/Gateway_2/ServiceFabric.cs
- Snippets/Gateway/Gateway_2/ServiceFabric/ServiceManifest.xml
- Snippets/Gateway/Gateway_2/Usage.cs
- Snippets/Gateway/Gateway_2/project.json
- menu/menu.yaml
- nservicebus/hosting/index.md
- nservicebus/hosting/service-fabric-hosting/hosting-gateway.md
- nservicebus/hosting/service-fabric-hosting/index.md
- samples/azure/azure-service-fabric-routing/sample.md
Connects to https://github.com/Particular/PlatformDevelopment/issues/1112
SF hosting options (replaces PR #2594)
**TODO:**
> Service Fabric hosting

- nservicebus/azure-service-bus/configuration/full.md
Small typo (missing `Subscriptions` before configuration method call)
> Small typo for ASB transport

- nservicebus/recoverability/custom-recoverability-policy.md
@SimonCropp I checked the `recoverability.AddUnrecoverableException<MyBusinessException>();` part and it makes sense. If you look closer the 6.2 snippet custom policy is only dealing with the delayed case because of that line.
fixes #2541
> Slight restructuring of custom recoverability policy

- nservicebus/operations/auditing.md
- platform/servicecontrol.include.md
- serviceinsight/index.md
- servicepulse/index.md
Completes #2531 
- [Note added to ServiceInsight index](https://github.com/Particular/docs.particular.net/pull/2653/files#diff-64f51c7ee0e998ad4611a1870370d25cR21)
- [Note added to ServicePulse index](https://github.com/Particular/docs.particular.net/pull/2653/files#diff-5eea945ad2b91dc2b70ef1475ce4a5feR28)
- [Note added to Audit feature doco](https://github.com/Particular/docs.particular.net/pull/2653/files#diff-13962c69f23c09efc3f7c439de6048f1R16)
- [Note added to ServiceControl index](https://github.com/Particular/docs.particular.net/pull/2653/files#diff-6fa3ad603af6bfeabca4ac626169b9d1R13)
- [Note added to ServiceControl index](https://github.com/Particular/docs.particular.net/pull/2653/files#diff-6fa3ad603af6bfeabca4ac626169b9d1R15)
> Clarify SC/SP/SI Audit behavior

- Snippets/Rabbit/Rabbit_4/Usage.cs
- nservicebus/rabbitmq/delayed-delivery.md
This removes the references to the deprecated `AllEndpointsSupportDelayedDelivery` setting and revises the backwards compatibility section in light of this change.
@Particular/rabbitmq-transport-maintainers
> Revise RabbitMQ delayed delivery backwards compatibility section

- Snippets/Core/Core_6/Lifecycle/INeedInitialization.cs
- Snippets/Core/Core_6/Scanning/ScanningPublicApi.cs
- nservicebus/hosting/assembly-scanning_wildcard_core_[6,].partial.md
- nservicebus/upgrades/6to6.2.md
Fixes #2627 
Addresses feedback around changes to the assembly scanning API introduced in NServiceBus 6.2
> Clarify changes to assembly scanning in 6.2

- nservicebus/messaging/headers.md
A custom conversation id can only be set when a new message flow is started (messages sent from `IMessageSession`). When the header is set in a message handler it would overwrite an existing conversation id and throw instead.
We currently don't offer a proper API to set a custom conversation id and the removed statement is also not backed by any snippet code so I propose to remove it entirely. If we really think this is a case we should support, we should provide an option on `SendOptions` (which can't differentiate between sends from the message session or the handler context)
@andreasohlund @indualagarsamy thoughts?
> Remove the documentation about custom conversation ids

- nservicebus/msmq/index.md
- nservicebus/recoverability/configure-error-handling.md
- nservicebus/recoverability/configure-error-handling_errorqueuedefault_core_[3.0,6.2).partial.md
- nservicebus/recoverability/configure-error-handling_errorqueuedefault_core_[6.3,).partial.md
As of 6.3 most transports won't need a error queue defined
> Adjust for new error queue default

- samples/show-case/cloud-azure/Core_6/Store.ContentManagement/App.config
- samples/show-case/cloud-azure/Core_6/Store.ContentManagement/Program.cs
- samples/show-case/cloud-azure/Core_6/Store.ContentManagement/Properties/webjob-publish-settings.json
- samples/show-case/cloud-azure/Core_6/Store.ContentManagement/Store.ContentManagement.csproj
- samples/show-case/cloud-azure/Core_6/Store.ContentManagement/packages.config
- samples/show-case/cloud-azure/Core_6/Store.CustomerRelations/App.config
- samples/show-case/cloud-azure/Core_6/Store.CustomerRelations/Program.cs
- samples/show-case/cloud-azure/Core_6/Store.CustomerRelations/Properties/webjob-publish-settings.json
- samples/show-case/cloud-azure/Core_6/Store.CustomerRelations/Store.CustomerRelations.csproj
- samples/show-case/cloud-azure/Core_6/Store.CustomerRelations/packages.config
- samples/show-case/cloud-azure/Core_6/Store.ECommerce/Global.asax.cs
- samples/show-case/cloud-azure/Core_6/Store.ECommerce/Properties/webjobs-list.json
- samples/show-case/cloud-azure/Core_6/Store.ECommerce/Store.ECommerce.csproj
- samples/show-case/cloud-azure/Core_6/Store.ECommerce/Web.config
- samples/show-case/cloud-azure/Core_6/Store.ECommerce/packages.config
- samples/show-case/cloud-azure/Core_6/Store.Operations/Properties/webjob-publish-settings.json
- samples/show-case/cloud-azure/Core_6/Store.Operations/Store.Operations.csproj
- samples/show-case/cloud-azure/Core_6/Store.Operations/packages.config
- samples/show-case/cloud-azure/Core_6/Store.Sales/Properties/webjob-publish-settings.json
- samples/show-case/cloud-azure/Core_6/Store.Sales/Store.Sales.csproj
- samples/show-case/cloud-azure/Core_6/Store.Sales/packages.config
- samples/show-case/cloud-azure/Core_6/Store.Shared/CommonConfiguration.cs
- samples/show-case/cloud-azure/Core_6/Store.Shared/Store.Shared.csproj
- samples/show-case/cloud-azure/Core_6/Store.Shared/packages.config
- samples/show-case/cloud-azure/sample.md
**Changes**
- Replacing MEM with Routing API
- Replace hard-coded connection string with an argument to support real world usage
- Connect webjob projects to the webapp to be able to deploy all together
- The sample can be now deployed to Azure using updated deployment notes
With Core 6.3 MEM is obsoleted with warning.
Removing red scary messages from the show case by replacing MEM with Routing API.
Hard-coded connection string is not a good starting point for anyone who'd like to base their tryout (azure deployment) on this sample. Switched to a parameter which can be passed into `ApplyCommonConfiguration()` extension method.
Before the change, deploying webapp would not deploy the webjobs. Now with a publishing settings file, webdeploy pushes webapp and webjobs to Azure hosting plan. …
> Update to the cloud show case

- nservicebus/rabbitmq/routing-topology.md
Still in progress, but take a look @Particular/rabbitmq-transport-maintainers.
Fixes #2486
> Update RabbitMQ  conventional routing topology info

- samples/servicecontrol/adapter-sqlserver/sample.md
Removed this:
> In order to do so, the adapter provides a ServiceControl interface to the business endpoints. 
It isn't clear to me what this means or how this would help me, as a user, understand the sample. Could be just me, though. I'm not as technical as I used to be.
> Removed sentence from opening

- nservicebus/upgrades/6to7/index.md
Scanner now throws instead of exluding x64 assemblies
https://github.com/Particular/NServiceBus/pull/4779
> Scanner now throw for x86 trying to scan x64 asm

- nservicebus/recoverability/configure-delayed-retries_legacy_core_[6,7).partial.md
- nservicebus/upgrades/6to7/index.md
Updates for the 6 to 7 upgrade guide.
Adds entries for https://github.com/Particular/NServiceBus/pull/4745 and https://github.com/Particular/NServiceBus/pull/4768.
CC: @Particular/nservicebus-maintainers
> Upgrade guide updates

- nservicebus/msmq/index.md
- nservicebus/msmq/index_default_core_(,6].partial.md
- nservicebus/upgrades/6to7/index.md
I also added a partial to the MSMQ index around the wording of MSMQ being the default transport.
> Msmq and default transport removal added to upgrade guide

- README.md
Set out to document engine changes made in https://github.com/Particular/DocsEngine/pull/303 in relation to https://github.com/Particular/DeveloperEducation/issues/910, but ended up documenting tutorials more generally.
> Tutorials readme additions

- README.md
We're no longer dropping snippets in the root folder. Snippets are under components.
@Particular/docs-maintainers please review. 
Also, should @Particular/docs-maintainers review readme.md to see if there were more changes?
> Updating path to include component part

- samples/containers/autofac/Autofac_6/Sample/Program.cs
- samples/containers/autofac/sample.md
- samples/containers/autofac/sample_assignment_autofac_[6,).partial.md
The current recomended approach that we have on our autofac sample can lead to a deadlock.  Example
```
builder.Register(x =>
{
return Endpoint.Start(endpointConfiguration).GetAwaiter().GetResult();
}).As<IEndpointInstance>().SingleInstance();
```
The code above registers as a lambda the endpoint start. Endpoint start returns a task. You use `GetAwaiter().GetResult()` to execute the task in a blocking manner. The lambda itself is lazy evaluated when the first resolve on `IEndpointInstance` happens. 
```
Timeout.Execute(() =>
{                
IEndpointInstance endpoint = container.Resolve<IEndpointInstance>();
var msg = new StartTestSaga() { MsgId = 1 };
endpoint.Publish(msg);
}, 2000);
```
The timer execute enters on a background thread the lambda which then calls into resolve. Resolve …
> Switching to closure access in lambda to avoid deadlocks in lifetime scope

- nservicebus/upgrades/6to7/index.md
Registry based config options for the error and audit queue are no longer supported. (see https://github.com/Particular/NServiceBus/pull/4741)
> Add registry based config options to list deprecated options

- samples/msmq/sql-bridge/Core_5/SqlBridge/MsmqReceiver.cs
- samples/msmq/sql-bridge/Core_5/SqlBridge/SqlBridge.csproj
- samples/msmq/sql-bridge/sample.md
Also, add a note that in general this might be required when using `TransportMessage` objects coming from different transports.
> Translate MSMQ transport message to SQL transport message

- samples/sqltransport-sqlpersistence/Core_6/Receiver/EntityFramework/SubmittedOrderDbContext.cs
- samples/sqltransport-sqlpersistence/Core_6/Receiver/Program.cs
- samples/sqltransport-sqlpersistence/sample.md
It allows to remove the warning override in EF while maintaining the same guarantees.
> Switch to native ADO transactions

- nservicebus/messaging/headers.md
Based on feedback provided in https://github.com/Particular/docs.particular.net/issues/2547
I tried to clarify the relationships between `Correlation Id`, `Conversation Id`, and `RelatedTo`
> Explain relationship between `ConversationId` and `CorrelationId`

- transports/sql/connection-settings.md
- transports/sql/connection-settings_pool-size_sqltransport_[3,3.1).partial.md
- transports/sql/connection-settings_pool-size_sqltransport_[3.1,).partial.md
To be merged when SQL transport 3.1 is released.
> [SQL transport 3.1] Updated the connection-settings to include 3.1 changes in pool size warning

- servicecontrol/plugins/heartbeat.md
Heartbeat are supported both in V5 and V6 even for Send-Only endpoints.
> Removes the heartbeat not support for send-only

- transports/sqs/index.md
Fix incorrect "PutBucket" permission. 
Change case of S3 and SQS prefices to be consistent with what AWS uses (all lower case)
> Fix incorrect SQS/S3 permissions

- samples/routing/file-based-routing/FileBasedRouting_1/Billing/Billing.csproj
- samples/routing/file-based-routing/FileBasedRouting_1/Billing/Program.cs
- samples/routing/file-based-routing/FileBasedRouting_1/Billing/packages.config
- samples/routing/file-based-routing/FileBasedRouting_1/Client/Client.csproj
- samples/routing/file-based-routing/FileBasedRouting_1/Client/Program.cs
- samples/routing/file-based-routing/FileBasedRouting_1/Client/packages.config
- samples/routing/file-based-routing/FileBasedRouting_1/Sales/Program.cs
- samples/routing/file-based-routing/FileBasedRouting_1/Sales/Sales.csproj
- samples/routing/file-based-routing/FileBasedRouting_1/Sales/packages.config
- samples/routing/file-based-routing/FileBasedRouting_1/Shipping/Program.cs
- samples/routing/file-based-routing/FileBasedRouting_1/Shipping/Shipping.csproj
- samples/routing/file-based-routing/FileBasedRouting_1/Shipping/packages.config
* Updated to NServiceBus.FileBasedRouting 1.2
* Switched back transport to MSMQ: Learning transport doesn't make much sense in here as the sample demonstrates routing config of commands and events, whereas the "event routes" will be ignored as the learning transport provides native pub/sub.
* Switched back to InMemoryPersistence, as MSMQ requires a persistence which provides a timeout storage.
> Update FileBasedRouting sample

- Snippets/Metrics/Metrics_1.1/Configuration.cs
- Snippets/Metrics/Metrics_1/Configuration.cs
i think this makes the snippets more readable. since without the param names the timespan is ambiguous
> add named params to metrics

- menu/menu.yaml
- servicecontrol/installation-powershell.md
- servicecontrol/monitoring-instances/index.md
- servicecontrol/monitoring-instances/installation/creating-config-file.md
- servicecontrol/monitoring-instances/installation/index.md
- servicecontrol/monitoring-instances/installation/installation-powershell.md
- servicecontrol/monitoring-instances/installation/setting-custom-hostname.md
- servicecontrol/powershell.md
Replaces https://github.com/Particular/docs.particular.net/pull/2835 and builds on top of https://github.com/Particular/docs.particular.net/pull/2936
The idea was to split the SC doco into SC instance doco and Monitoring instance doco. This allows us to add the Monitoring instance doco as new doco that can be merged before we're ready to put it in the menu and officially publish it.
> SC monitoring instances (take 2)

- nservicebus/operations/metrics.md
Moved the "Messages received performance statistics" section underneath the "Processing time" section as it appears more related to it than to the "Critical Time" section it was under before.
I think some more clarity is in order, though.
> Metrics cleanup/review

- samples/azure/storage-persistence/ASP_1/Client/Client.csproj
- samples/azure/storage-persistence/ASP_1/Client/Program.cs
- samples/azure/storage-persistence/ASP_1/Client/app.config
- samples/azure/storage-persistence/ASP_1/Client/packages.config
- samples/azure/storage-persistence/ASP_1/Server/Program.cs
- samples/azure/storage-persistence/ASP_1/Server/Server.csproj
- samples/azure/storage-persistence/ASP_1/Server/packages.config
- samples/azure/storage-persistence/Azure_6/Client/Client.csproj
- samples/azure/storage-persistence/Azure_6/Client/Program.cs
- samples/azure/storage-persistence/Azure_6/Client/packages.config
- samples/azure/storage-persistence/Azure_6/Server/Program.cs
- samples/azure/storage-persistence/Azure_6/Server/Server.csproj
- samples/azure/storage-persistence/Azure_6/Server/packages.config
@Particular/docs-maintainers I've decided to switch from Learning transport to ASQ.
Learning transport has native pub/sub and in a way breaks the sample by now exercising persistence to store subscriptions.
In addition to that, I've switched the previous major version of the sample to also use ASQ transport. It allows easier testing/verification of an upgrade when needed (/cc @ramonsmits).
/cc @Particular/azure-maintainers
> Switch storage persistence sample to ASQ transport

- nservicebus/recoverability/configure-immediate-retries_config_core_[3.0,4.0).partial.md
- nservicebus/recoverability/configure-immediate-retries_config_core_[4.0,6.0).partial.md
- nservicebus/recoverability/configure-immediate-retries_config_core_[6.0,).partial.md
The general [recoverability documentation](https://docs.particular.net/nservicebus/recoverability/) speaks about retries and the default maximum number, but the default number of retries is not stated in the specific page for [immediate retries](https://docs.particular.net/nservicebus/recoverability/configure-immediate-retries) the way it's done for [delayed retries](https://docs.particular.net/nservicebus/recoverability/configure-delayed-retries?#configuring-delayed-retries).
This PR adds that info.
@Particular/nservicebus-maintainers please review
> Add default number of retries for Immediate retries

- servicecontrol/transport-adapter/incompatible-features.md
4th feature of ASB incompatible with the "classic" SC and addressed by SC adapter.
A [sample PR](https://github.com/Particular/docs.particular.net/pull/3028) is also added
@Particular/servicecontrol-maintainers please review
> namespace hierarchy added to the list

- samples/servicecontrol/adapter-asb-multi-namespace/SCTransportAdapter_1/Adapter/Program.cs
- samples/servicecontrol/adapter-asb-multi-namespace/SCTransportAdapter_1/Sales/Program.cs
- samples/servicecontrol/adapter-asb-multi-namespace/SCTransportAdapter_1/Shipping/Program.cs
- samples/servicecontrol/adapter-asb-multi-namespace/sample.md
Connects to https://github.com/Particular/NServiceBus.AzureServiceBus/issues/593
Namespace hierarchy is the 4th SC unsupported transport feature.
Adding it to the sample to show that adapter can handle it as well.
Documentation for SC Adapter will be updated separately.
> Update the ASB SC adapter sample to use namespace hierarchy

- README.md
- tutorials/message-replay/tutorial.md
- tutorials/quickstart/tutorial.md
**DO NOT MERGE**: Requires https://github.com/Particular/DocsEngine/pull/327 to be deployed first.
Adds the markup to place the inline download buttons in the Quick Start and Message Replay tutorials, removing the downloadAtTop metadata used previously.
Also removes deprecated downloadAtTop info from README.
> [DO NOT MERGE] Tutorial inline download buttons

- samples/scheduling/Core_5/Sample/ScheduleStarter.cs
Since system messages might not be registered earlier in the startup
sequence for v5
Fixes #3062
> Use IWantToRunWhenBusStartsAndStops to schedule messages

- Snippets/SqlPersistence/SqlPersistence_3/ScriptWriter.cs
- Snippets/SqlPersistence/SqlPersistence_3/Usage.cs
- persistence/sql/index.md
- persistence/sql/index_scriptlocation_sqlpersistence_[1.3).partial.md
- persistence/sql/index_scriptlocation_sqlpersistence_[3,).partial.md
- samples/sql-persistence/saga-rename/SqlPersistence_2/EndpointVersion2/Program.cs
- samples/sql-persistence/saga-rename/SqlPersistence_3/EndpointVersion2/Program.cs
- samples/sql-persistence/saga-rename/SqlPersistence_3/Shared/SharedConfiguration.cs
- samples/sql-persistence/simple/SqlPersistence_3/EndpointMySql/Program.cs
- samples/sql-persistence/simple/SqlPersistence_3/EndpointOracle/Program.cs
- samples/sql-persistence/simple/SqlPersistence_3/EndpointSqlServer/Program.cs
- samples/sql-persistence/transitioning-correlation-ids/SqlPersistence_3/Phase1/EndpointMySql/Program.cs
- samples/sql-persistence/transitioning-correlation-ids/SqlPersistence_3/Phase1/EndpointOracle/Program.cs
- samples/sql-persistence/transitioning-correlation-ids/SqlPersistence_3/Phase1/EndpointSqlServer/Program.cs
Didn't have time to get to started on an upgrade guide, which doesn't exist yet. I'm concerned that because a breaking changes alpha is on MyGet, it can get picked up by version wildcards, and that could be breaking docs in various ways. So I think this should get merged first anyway.
While updating samples I smoke tested them. Caught an unrelated error in the saga rename sample caused by having 2 non-matching connection strings with different catalog names. Fixed that in the V2 and V3 versions.
I punted a little bit on the doco for Schema, and just specified that it was MSSQL-specific, which I think is technically true for all versions, which let me get away without doing a partial in that case.
@Particular/sqlpersistence-maintainers please have a look.
> Updating SQL Persistence doco/samples/snippets

- nservicebus/sagas/saga-not-found.md
Messages for a saga that arrive without a saga instance _and_ no implementation of a IHandleSagaNotFound just disappear. This wasn't documented.
> Messages without saga disappear when not handled explicitly 

- tools/supportedVersions.linq
Tabs, not space, is the default in LINQPad, so not much point fighting against it.
> fix white space in supportedVersions.linq

- nservicebus/operations/tuning_throttling_core_[,5].partial.md
The default is not spelled out, which leave questions.
After looking at the override, it might feel that max throughput needs to be overridden as well when changing settings.
With this change it states clearly that throughput is **not** throttled.
@Particular/nservicebus-maintainers please review
> clarifications for endpoint tuning defaults

- nservicebus/sagas/index.md
Connects to https://github.com/Particular/NServiceBus/issues/4943
How to handle scenario when transaction doesn't span transport and persistence.
@andreasohlund here's an initial stub at it.
> Saga completion - addition

- samples/scaleout/senderside-and-distributor/Core_6/Worker1/Program.cs
- samples/scaleout/senderside-and-distributor/Core_6/Worker2/Program.cs
Pass PushRuntimeSettings.Default.MaxConcurrency to align capacity with the default maximum concurrency instead of using 1.
> Pass PushRuntimeSettings.Default.MaxConcurrency

- samples/azure/storage-persistence/ASP_2/Client/Program.cs
- samples/azure/storage-persistence/ASP_2/Server/Program.cs
The sample is already packed with persistence configuration. No need to add to the complexity with ASQ transport sanitization.
@yvesgoeleven please review
> Remove sanitization to simplify ASP sample

- nservicebus/messaging/timeout-manager.md
Fixes #3176 
Taking out mentions of NH and RavenDB from this persistence article.
* Not really necessary. Details of each persistence are not really in scope on such a general article.
* Too difficult to keep these details up-to-date on this page. You wouldn't think to come here when updating doco for a specific persister.
* RavenDB no longer will support DTC transactions in latest major.
* Doesn't mention SQL Persistence, but if you did, you'd have to talk about the difference between each dialect, how it stores timeouts, and how it supports transactions.
Any objections?
> Remove specific persistence support claims from TimeoutManager article

- samples/nhibernate/simple/NHibernate_8/Server/Program.cs
the sample needs installers to be explicitly enabled so the saga table is created when running the sample.
> Enable installer

- nservicebus/upgrades/6to7/index.md
`RegisterStep.IsEnabled` was never documented and as far as we can tell never used so it was removed. This add this fact to the upgrade guide.
See https://github.com/Particular/NServiceBus/issues/4118 for details
> Upgrade guide entry for the removal of RegisterStep.IsEnabled

- nservicebus/sagas/message-correlation.md
Some changes that should make clear that:
- All messages mappings MUST map to the same saga property
- A saga can only have a single mapping property
If multiple saga properties need to be mapped or messages needed to be mapped to different saga data properties that a customer saga finder must be used.
/cc: @DavidBoike
> Only use a single saga property for correlation

- nservicebus/upgrades/testing-6to7.md
`ExpectHandleCurrentMessageLater` was available for both Saga and Handler tests, so I removed the Saga category for now.
> Document obsoleted ExpectHandleCurrentMessageLater

- samples/azure/storage-persistence/ASP_2/Server/Program.cs
- samples/azure/storage-persistence/sample.md
- samples/azure/storage-persistence/sample_sagadata_asp_[1,).partial.md
- samples/azure/storage-persistence/sample_sagadata_azure_6.partial.md
- samples/azure/storage-persistence/sample_subscriptions_asp_[1,).partial.md
- samples/azure/storage-persistence/sample_subscriptions_azure_6.partial.md
- samples/azure/storage-persistence/sample_timeouts_asp_[1,).partial.md
- samples/azure/storage-persistence/sample_timeouts_azure_6.partial.md
Depends on #3308 
Markdown needed to be updates as we no longer produce the data as it shows.
- For timeouts, ASQ has native delayed delivery infrastructure and persistence is not used in v1,v2 of ASP
- Saga data is different in v1,2
- Subscriptions data is different in v1,2
> ASP sample storage data fixes

- transports/azure-service-bus/configuration/full.md
- transports/azure-service-bus/configuration/full_queues_asb_[,8).partial.md
- transports/azure-service-bus/configuration/full_queues_asb_[8,).partial.md
- transports/azure-service-bus/configuration/full_topics_asb_[,8).partial.md
- transports/azure-service-bus/configuration/full_topics_asb_[8,).partial.md
Connects to https://github.com/Particular/NServiceBus.AzureServiceBus/pull/646
@Particular/azure-maintainers looks like DescriptionFactory was replaced when we needed to split it into the old doco.
> splitting version specific settings into partials

- nservicebus/upgrades/5to6/handlers-and-sagas.md
as this was supported in v5 and we're patching v6 to throw an exception when HandleCurrentMessageLater is used in conjunction with the Outbox (as this would cause a message loss in v6), we concluded that we should add this to the v6 upgrade guide as well.
related issue: https://github.com/Particular/NServiceBus/issues/4993
> Add HandleCurrentMessageLater changes to v6 upgrade guide

- Snippets/Core/Core_6/Scheduling/Scheduling.cs
- Snippets/Core/Core_7/Scheduling/Scheduling.cs
fixes https://github.com/Particular/docs.particular.net/issues/2931 by adding a comment to underline that you should use the context parameter to send messages instead of using the endpointInstance.
> Add note about context parameter

- samples/hosting/windows-service/sample_netcore_core_[7.0,).partial.md
@SimonCropp got feedback from a customer that the path is incorrect. Can you confirm?
> Use correct output path

- transports/sql/concurrency_content_sqltransport_2.partial.md
- transports/sql/concurrency_content_sqltransport_[,2).partial.md
- transports/sql/concurrency_content_sqltransport_[2,3).partial.md
- transports/sql/concurrency_content_sqltransport_[2].partial.md
- transports/sql/concurrency_content_sqltransport_[3,).partial.md
SQL Transport [3,) concurrency documentation was referring to old API. Result was that customer on NSBv6 and SQL Transport v3 was unable to find how to change concurrency with current documentation.
Change API reference and added link to documentation on how to change concurrency.
> Updated reference to updated API

- transports/sql/concurrency_content_sqltransport_[3,).partial.md
This PR slightly changes the phrasing of a description for sql transport concurrency. It removes the notion of a thread replacing it with a task
> Removed notion of non-existing thread

- Directory.Build.props
Having the `Configurations` property in Directory.Build.props like this breaks Visual Studio's ability to add existing projects to a solution or create new projects.
> Remove Configurations property

- transports/rabbitmq/transactions-and-delivery-guarantees.md
While reading through the docs for RabbitMQ, I noticed that there was a missing word. It read "which allows the broker know" so I updated it to "which allows the broker *to* know".
I'm not sure the bottom paragraph is being marked as edited. I made no changes to it whatsoever.
> Fixes typo in documentation.

- Snippets/ASQ/ASQ_8/Sanitization.cs
- Snippets/ASQ/ASQ_8/Usage.cs
- samples/azure/storage-queues/ASQ_8/Shared/BackwardsCompatibleQueueNameSanitizer.cs
- transports/azure-storage-queues/sanitization.md
- transports/upgrades/asq-7to8.md
Fixes #3255 
Connects to https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/282
Closes https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/282
Have verified the results for v6/7/8 of the transport.
**v8**
Samples.Azure.StorageQueues.Endpoint1.With.A.Very.Long.Name.And.Invalid.Characters
`samples-azure-storagequeue-fa38d2dd-3521-3b52-012a-481912b5addc`
**v7**
Samples.Azure.StorageQueues.Endpoint1.With.A.Very.Long.Name.And.Invalid.Characters
`samples-azure-storagequeue-fa38d2dd-3521-3b52-012a-481912b5addc`
Samples.Azure.StorageQueues.Endpoint1.With.A.Very.Long.Name.And.Invalid.Characters-retries
`samples-azure-storagequeue-bdb4edc7-74cc-65c2-5f65-a49ed3032070`
**v6**
Samples.Azure.StorageQueues.Endpoint1.With.A.Very.Long.Name.And.Invalid.Characters …
> Fix to ASQ shortening/sanitization backwards compatible code

- nservicebus/messaging/callbacks_route_callbacks_[1,).partial.md
As part of https://discuss.particular.net/t/how-do-i-configure-iis-for-use-with-callbacks/131 we realized that our guidance for callbacks are not accurate for endpoints running MSMQ. This tries to clarify that you can hardcode the instance id under certain circumstances
> Clarify callbacks and unique queues

- samples/sqs/simple/sample.md
- transports/sqs/configuration-options_source_sqs_[4,).partial.md
- transports/upgrades/amazonsqs-3to4.md
It seems that using AWS_REGION is the more commonly used approach over AWS_DEFAULT_REGION which is mostly used by CLI.
> Use AWS_REGION instead of AWS_DEFAULT_REGION

- tutorials/intro-to-nservicebus/3-multiple-endpoints/tutorial.md
- tutorials/intro-to-nservicebus/4-publishing-events/Solution/ClientUI/Program.cs
- tutorials/intro-to-nservicebus/5-retrying-errors/Solution/Sales/PlaceOrderHandler.cs
- tutorials/message-replay/Solution/Sales/PlaceOrderHandler.cs
Hi again :)
@weralabaj I read tutorials to checking out Platform new features and yes the reason for changes is to be consistent about transport usage across all tutorial lessons.
@weralabaj @DavidBoike Thanks for approval previous pull requests!
I don't read [step-by-step](https://docs.particular.net/samples/step-by-step/) tutorial yet but in quick review I see that **LearningTransport** is use and there are two maybe not necessary endpoint configuration features:
- endpointConfiguration.EnableInstallers();
- endpointConfiguration.SendFailedMessagesTo("error");
Let me know what you think and I can change the code and doc content to practice pull requests :)
I'm hope that I don't give you additional work.
Regards
Michał
> Yet another small changes

- Snippets/UniformSession/UniformSession_1/EnableUniformSession.cs
- Snippets/UniformSession/UniformSession_2/EnableUniformSession.cs
- nservicebus/messaging/uniformsession.md
The plugin is no longer auto enabled and needs to be explicitly enabled instead. 
This PR does not compile as the required updated packages are not on myget yet.
> UniformSession plugin needs to be enabled now

- samples/logging/prometheus-grafana/nservicebus.rules.txt
- samples/logging/prometheus-grafana/sample.md
Prometheus 2.0 was released and contained a breaking change to the rules files. I converted the rules by using the provided promtool and smoke tested it
> Upgrade rules to prometheus 2.0

- nservicebus/sagas/index.md
In the main saga guidance it is not really clear that the default behavior is that message are discarded if the message does not start a saga, but a saga instance does not exist. A lot of customers might not expect this behavior and can cause message/data loss.
> Added note about default saga not found behavior

- nservicebus/operations/metrics/index.md
This PR adds a note, clarifying that 
> depending on the version of the reporting package and the way metrics are gathered, the set of available metrics may vary.
> A note added about different sets of metrics.

- samples/web/asp-mvc-application/Core_5/AsyncPagesMVC/Web.config
- samples/web/asp-mvc-application/Core_6/AsyncPagesMVC/Web.config
- samples/web/asp-mvc-application/Core_7/AsyncPagesMVC/Web.config
- samples/web/send-from-mvc-controller/Core_5/WebApplication/Web.config
- samples/web/send-from-mvc-controller/Core_6/WebApplication/Web.config
- samples/web/send-from-mvc-controller/Core_7/WebApplication/Web.config
Hi,
Quick fixes.
When press F5 there is an exception:
Could not load file or assembly 'Autofac, Version=4.0.1.0, Culture=neutral, PublicKeyToken=17863af14b0044da' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
After upgrade Autofac to version 4.6.2.0 everything works as expected.
> Upgrade Autofac version

- servicepulse/intro-pending-retries.md
Connects to https://github.com/Particular/platformdevelopment/issues/1552
Adds a note stating that a message could be in the pending state forever if it ends up in SC's DLQ
> Add note about dlq

- nservicebus/operations/metrics/service-control.md
This PR captures the name of the described component as the first mentioned package. Not mentioning it could have been confusing for users reading doco and noticing `NServiceBus.Metrics` as the first name.
> Explicit mention of NSB.Metrics.ServiceControl

- transports/azure-storage-queues/configuration_parallelismdegree_asq_[7,].partial.md
@Particular/azure-maintainers 
I think this is a left over from the area when the core set the concurrency to 100 by default which then set the maximum degree of parallelism to 10.
https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Transports/PushRuntimeSettings.cs#L15
> Remove mentioning of default since it is not true

- Snippets/MetricsServiceControl/MetricsServiceControl.sln
- Snippets/MetricsServiceControl/MetricsServiceControl_1.2/Configuration.cs
- Snippets/MetricsServiceControl/MetricsServiceControl_1.2/MetricsServiceControl_1.2.csproj
- Snippets/MetricsServiceControl/MetricsServiceControl_2/Configuration.cs
- nservicebus/operations/metrics/service-control.md
- nservicebus/operations/metrics/service-control_ttbr_metricsservicecontrol_[1.2,3).partial.md
This PR handles a wave of `NSB.Metrics.ServiceControl` packages. In particular, it does the following:
- adds additional `1.2` snippets and TTBR for `1.2` and `2.0`
- removes `prerelease` from 1.0-2.0 of this package
It leaves 3.0 as it requires porting back TTBR and updating samples as soon as this is done
> NSB.Metrics.ServiceControl bump up

- Snippets/Raven/Raven_5/Configure.cs
This PR amends an overload used for `.UseSharedAsyncSession` that was obsoleted with `TreatAsError = true` in this release: https://github.com/Particular/NServiceBus.RavenDB/releases/tag/5.0.0-Beta6
> RavenDB fix - proper overload used for UseSharedAsyncSession

- transports/sqs/configuration-options.md
- transports/sqs/configuration-options_nativeDeferral_sqs_[2,).partial.md
A warning about delays longer than 15 mins should stand out and not blend with the rest of the description.
> NativeDeferral clarifications

- samples/routing/file-based-routing/FileBasedRouting_1/Billing/OrderAcceptedHandler.cs
- samples/routing/file-based-routing/FileBasedRouting_2/Billing/OrderAcceptedHandler.cs
- samples/routing/file-based-routing/sample.md
* improve the log statement to contain the order ID similar to the other endpoints in the sample.
* remove information about round-robin processing. @SzymonPobiega any idea why this was added? I don't see any hint of multiple instances or other sources which would explain round-robin processing?
> Improve file based routing sample

- transports/azure-storage-queues/configuration_aliases_asq_[7,].partial.md
Slight modification in light of hotfix 5.3.2
Please review and merge
> Adding a note about ASQ default connection string and aliases

- samples/sql-persistence/simple/SqlPersistence_4/EndpointPostgreSql/EndpointPostgreSql.Core.csproj
- samples/sql-persistence/simple/SqlPersistence_4/EndpointSqlServer/EndpointSqlServer.Core.csproj
- samples/sql-persistence/simple/SqlPersistence_4/ServerShared/ServerShared.Core.csproj
the .net framework projects were correctly referencing 4.0.0-* but the .net core projects weren't updated.
I wonder whether this could have happened on other samples as well
> Fix persistence dependencies on core sample

- samples/gateway/Gateway_3/WebClient.Core/wwwroot/Index.html
Since the shared assembly is differently named
> Remove asm part in header to make it work for both netcore and fullfx

- monitoring/metrics/definitions.md
Based on https://github.com/Particular/LaunchWave.DevOpsAdvancedMonitoring/issues/517
> Documenting queue length estimate not working for SF

- persistence/ravendb/outbox.md
According to XML the cleanup task can be disabled:
https://github.com/Particular/NServiceBus.RavenDB/blob/master/src/NServiceBus.RavenDB/Outbox/RavenDBOutboxExtensions.cs#L34
> The frequency to run the deduplication data cleanup task. By specifying a negative time span (-1) the cleanup task will never run.
> Disable the RavenDB outbox cleanup task

- monitoring/heartbeats/install-plugin.md
- transports/msmq/transportconfig_enablejournaling_msmqtransport_[1,).partial.md
Incorrect label used, not rendered as a warning callout.
> WARN to WARNING

- monitoring/metrics/definitions.md
Based on https://github.com/Particular/LaunchWave.DevOpsAdvancedMonitoring/issues/531
> Documented known limitation that queue length for satellite queues isn't reported

- samples/show-case/on-premise/Core_6/Store.ECommerce/Store.ECommerce.csproj
- samples/show-case/on-premise/Core_6/Store.ECommerce/Web.config
- samples/show-case/on-premise/Core_7/Store.ContentManagement/Store.ContentManagement.csproj
- samples/show-case/on-premise/Core_7/Store.CustomerRelations/Store.CustomerRelations.csproj
- samples/show-case/on-premise/Core_7/Store.ECommerce/Store.ECommerce.csproj
- samples/show-case/on-premise/Core_7/Store.ECommerce/Web.config
- samples/show-case/on-premise/Core_7/Store.Messages/Store.Messages.csproj
- samples/show-case/on-premise/Core_7/Store.Operations/Store.Operations.csproj
- samples/show-case/on-premise/Core_7/Store.Sales/Store.Sales.csproj
- samples/show-case/on-premise/Core_7/Store.Shared/DebugFlagMutator.cs
- samples/show-case/on-premise/Core_7/Store.Shared/Store.Shared.csproj
* Referenced the correct RC compatible 2.0-rc1 package of NServiceBus.Encryption.MessageProperty
* Updated the Assembly redirects to the newer dependency versions
* Fixed the dependency versions to avoid misaligned redirects on the next patch release. @Particular/docs-maintainers thoughts about that approach? Other samples use wildcard dependencies but in this case there seems to be a big risk in regards to the required assembly redirects?
> Fix on-premise showcase sample

- nservicebus/upgrades/6to7/index.md
This adds a note to the upgrade guide to cover the change from https://github.com/Particular/NServiceBus/pull/4648.
> Add note about unobtrusive mode assembly scanner change

- servicecontrol/servicecontrol-instances/distributed-instances.md
The reason for this PR is to disucc possible changes in the way we introduce multi-instance support for SC.
The main assumptions that I made are:
* Multi-instance is about sharding/partitioning audit data,
* Error data sharding/partitioning is not supported,
* The topology is always  single master (error+ optional audit) and number of slaves (audits only)
* Multi-region is partially supported.
All the changes made in the doco are result of those assumptions.
> Multi-instance doco tweaks

- nservicebus/serialization/xml.md
While reproducing https://github.com/Particular/NServiceBus/issues/5124 I realized that we never documented this. This feature has been present since the dawn of time and is demoed by https://docs.particular.net/samples/rabbitmq/native-integration/
> Document the XMLSerializers ability to infer message type from root node

- nservicebus/licensing/index_license-management_core_[7,].partial.md
References:
Well, mostly LinqPad, but [this is source for both](https://github.com/dotnet/corefx/blob/v2.0.6/src/System.Runtime.Extensions/src/System/Environment.Win32.cs#L65-L70).
* [LocalApplicationData](https://github.com/dotnet/corefx/blob/v2.0.6/src/System.Runtime.Extensions/src/System/Environment.Unix.cs#L139-L147)
* [CommonApplicationData](https://github.com/dotnet/corefx/blob/v2.0.6/src/System.Runtime.Extensions/src/System/Environment.Unix.cs#L101)
> Be explicit about netcore license locations

- nservicebus/upgrades/supported-platforms.md
Connects to https://github.com/Particular/NServiceBus.AmazonSQS/pull/204
Do **NOT** merge until SQS PR https://github.com/Particular/NServiceBus.AmazonSQS/pull/204 is merged and released.
Linux / .NET Core ban has been lifted desptive [AWS SDK bug](https://github.com/aws/aws-sdk-net/issues/796). There's no message loss, so we're good releasing it with .NET Core support.
> Remove SQS from the list

- transports/sqs/delayed-delivery.md
- Added an explicit callout for the older versions
- Reorganized the content
- Expanded and clarified how things work
- Two scenarios for message duplication
- Fixed examples
- Removed redundant content
@mauroservienti and @danielmarbach please review these awesome changes to the document 🙂
> SQS delayed delivery clarifications

- samples/pubsub/sample.md
I removed the message flow diagrams. v7 is using the learning transport with native pubsub and showing a diagram related to message driven pubsub is highly confusing, even if the note mentions this.
> tweak pubsub sample readme

- samples/callbacks/Callbacks_2/WebSender/Web.config
- samples/callbacks/Callbacks_2/WebSender/WebSender.csproj
- samples/callbacks/Callbacks_3/WebSender/Web.config
- samples/callbacks/Callbacks_3/WebSender/WebSender.Core.csproj
- samples/callbacks/Callbacks_3/WebSender/WebSender.csproj
we need to lock the ASP package dependencies as it breaks the assembly redirects otherwise. The v2 version of the sample was also affected.
> Fix callbacks sample

- samples/outbox/multi-tenant/Core_7/Receiver/Receiver.csproj
- samples/outbox/multi-tenant/Core_7/Sender/Sender.csproj
`NHibernate` requires the `Iesi Collections` package. NuGet complains when restoring the dependent package and finding the closest version that matches the one specified by NH package. 
I thought that it could be useful to do not have a Warning in a sample project.
> No nuget warn for outbox

- servicecontrol/creating-config-file.md
Fixes #3700
We [removed the documentation for this setting](https://github.com/Particular/docs.particular.net/pull/1634/files#diff-bb72f827aebf113f1a6918701701dbadL9) when we introduced Maintenance Mode. This PR re-introduces it in the Settings part of the doco and with a few changes.
> Re-introduce ExposeRavenDB settings to doco

- tests/IntegrityTests.sln
- tests/IntegrityTests/IntegrityTests.csproj
- tests/IntegrityTests/ProjectFrameworks.cs
- tests/IntegrityTests/TestRunner.cs
- tests/IntegrityTests/TestSetup.cs
As part of fixing up all the samples and stuff for the V7 launch, @bording discovered a swathe of inconsistencies and other bad things that it would be good to verify before PRs are even merged.
This PR is the start of some integrity tests to verify that. It includes 2 prototype tests:
1. Ensure that the `<TargetFrameworks>` element (plural) is not used
2. Ensure that multiple `<TargetFramework>` (singular) elements (for instance, used within conditional PropertyGroups) are not used
This PR should succeed against our current validation, as it's just a bit of extra code. The next step would be to set up the TeamCity pipeline so that these tests are executed as part of master and PR builds, but do not yet fail the build.
In the future we can use this infrastructure to prevent all sorts of …
> Integrity tests for samples and snippets.

- nservicebus/recoverability/index_unrecoverableexceptions_core_[6.0,).partial.md
Instead of using document url `index_unrecoverableexceptions_core_[6.0,).partial.md` it maybe needs to be `index_unrecoverableexceptions_core_[6.2,).partial.md`. Not sure if that is supported.
@Particular/docs-maintainers
> Added note from which version this is added.

- tests/IntegrityTests/ProjectFrameworks.cs
- tests/IntegrityTests/TestRunner.cs
Also API for easily excluding snippets/samples/tutorials or by wildcard/regex.
> Relax TargetFrameworks rule to exclude Snippets. 

- Snippets/Newtonsoft/Newtonsoft_1/Usage.cs
- Snippets/Newtonsoft/Newtonsoft_2/Usage.cs
- nservicebus/serialization/json.md
- nservicebus/serialization/newtonsoft.md
- samples/sqltransport/native-integration/SqlTransport_4/Receiver/Program.cs
This was discovered when @HEskandari was testing the https://docs.particular.net/samples/sqltransport/native-integration/?version=sqltransport_4 sample
> Difference in $type handling for json.net btw embedded core v6 and the external serializer

- README.md
The integrity test experiment has been very useful during the .NET Core launch, for example, providing an easy way to make sure that we removed the correct prerelease.txt files at launch and ensuring that they'll stay correct.
But that won't work if we don't make them required to merge PRs.
This PR documents existing integrity tests. Assuming we merge this, we can then require the checks on PRs in TeamCity, and then we would also reject any PR that modified the integrity tests without also documenting them in the README.
> Document integrity tests before making them required on TeamCity

- samples/azure/azure-service-bus-msmq-bridge/ASB_7/Bridge/Program.cs
- samples/azure/azure-service-bus-msmq-bridge/ASB_8/Bridge/Program.cs
- samples/azure/azure-service-bus-msmq-bridge/sample.md
This does not change the behavior but is easier to configure.
> Use ReceiveOnly transaction mode to prevent usage of TransactionScope in ASB

- servicecontrol/upgrades/1to2.md
This pre-requisite ensures that the internal data migrations will already be run and completed before the major upgrade is run
> Add a prerequisite step for ServiceControl

- tools/supportedVersions.linq
@DavidBoike there are two commits here. The second is just whitespace (I'm not sure when it became inconsistent). The first commit refactors the static state you added to `PackageMetadataResourceExtensions`. Are you OK with the change?
> Refactor supported versions script

- persistence/sql/saga-concurrency.md
- persistence/sql/saga-concurrency_implementation_sqlpersistence_[,4.1).partial.md
I've moved the blue box so it is only included for versions that don't support `select for update`
> Clarify SQLP saga concurrency

- transports/rabbitmq/delayed-delivery.md
@Particular/rabbitmq-transport-maintainers I was trying to better understand the mechanics behind our RabbitMQ delayed messages, and found the documentation lacking.
This is what I came up with. So:
1. Are my additions accurate?
2. Do my additions help to create understanding?
3. If Yes and Yes, are there any parts of the surrounding text that should be removed as duplicative?
> More explanation around RabbitMQ delayed messages

- Directory.Build.props
When smoke-tested changes for Core v6.5, have used one of the samples.
Because samples remove all analyzers, Particular Analyzer was removed as well, causing confusion and unnecessary "bug" hunting with @timbussmann and @bording.
Unless there's a reason to do so, I recommend to remove this task from samples.
> Remove analyzers removal in Directory.Build.props

- servicecontrol/installation.md
- transports/azure-service-bus/publisher-names-configuration.md
- transports/azure-service-bus/topologies/index.md
- transports/upgrades/asb-7to8.md
- transports/upgrades/rabbitmq-4.0to4.1.md
These are not proper nouns, so they should be lower case. They should also be preceded with the definite article ("the") (can be excluded for section titles).
In most instances, the casing and definite article usage is correct. This fixes the outliers.
> align topology casing and definite articles

- samples/logging/stack-trace-cleaning/sample.md
Fixes #4004 
@timbussmann please review?
> Add note that .NET Core 2.1 already makes stack traces better.

- nservicebus/pipeline/message-mutators.md
As part of fixing the recent issue with mutators and DI we concluded that since the API requires you to pass an instance of the mutator that you would like to register there is no point in mentioning DI since at that point users would have already "new"'ed up the instance or pulled it from their container of choice.
See https://github.com/Particular/NServiceBus/issues/5257
> Remove uneeded note about mutators and DI

- Snippets/Gateway/Gateway_2/Channels/Wildcard.config.xml
- Snippets/Gateway/Gateway_3/Channels/Wildcard.config.xml
Need to have a non wildcard default for replies to be routed properly
> Correct gateway receive channel docs when wildcards are used

- transports/azure-storage-queues/configuration.md
- transports/azure-storage-queues/configuration_batchsize_asq_[,6].partial.md
- transports/azure-storage-queues/configuration_batchsize_asq_[7,].partial.md
- transports/azure-storage-queues/configuration_maximumwaittimewhenidle_asq_[,6].partial.md
- transports/azure-storage-queues/configuration_maximumwaittimewhenidle_asq_[7,].partial.md
- transports/azure-storage-queues/configuration_peekinterval_asq_[,6].partial.md
- transports/azure-storage-queues/configuration_peekinterval_asq_[7,].partial.md
Fixes #4060
Change to defaults occurred for v7 release of ASQ: https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/141
> Document ASQ PeekInterval and MaximumWaitTimeWhenIdle defaults by version

- nservicebus/recoverability/subscribing-to-error-notifications.md
This doesn't appear to be true. An attempt to retrieve `Notifications` from container will always throw. Instead, it's only possible to get it via `Settings` (separate PR?).
> Remove incorrect information

- samples/routing/file-based-routing/FileBasedRouting_2/Billing/Program.cs
- samples/routing/file-based-routing/FileBasedRouting_2/Client/Program.cs
- samples/routing/file-based-routing/FileBasedRouting_2/Sales/Program.cs
- samples/routing/file-based-routing/FileBasedRouting_2/Shipping/Program.cs
- samples/routing/file-based-routing/sample.md
an alternative would be to use the learning transport instead but the LT supports native pub/sub and therefore isn't the best option to demonstrate the capabilities of FileBasedRouting
> Enable installers on FileBasedRouting sample

- transports/rabbitmq/cluster.md
* Included the section in the RabbitMQ doco link
* Removed the information about old 2.x multiple host API
> Legacy review of RabbitMQ clustering doco

- transports/index.md
Moves the transport selection section right after the list of supported transports, as it sounds more important than community transports and WebSphere
> Move transport selection section up

- Snippets/MsLogging/MsLogging_1/MsLogging_1.csproj
- Snippets/MsLogging/MsLogging_1/ProgramService.cs
- Snippets/MsLogging/MsLogging_1/Usage.cs
- samples/logging/mslogging-custom/MsLogging_1/Sample/Program.cs
- samples/logging/mslogging-custom/MsLogging_1/Sample/Sample.Core.csproj
- samples/logging/mslogging-custom/MsLogging_1/Sample/Sample.csproj
Hey @SimonCropp,
Microsoft.Extensions.Logging 2.2.0 made some APIs obsolete and wants them declared on an ILoggingBuilder instead of ILoggerFactory, the problem is how to generate that. In a previous commit I temporarily fixed the build by locking the versions to 2.1.*, but this is my attempt to fix it for real.
Does this look OK?
> Fix MsLogging sample/snippets from 2.2.0 obsoletes

- samples/azure-service-bus-netstandard/native-integration/ASBS_1/NativeSender/Program.cs
- samples/azure-service-bus-netstandard/native-integration/ASBS_1/Receiver/Program.cs
This PR includes a few fixes for samples:
- aligning names of environmental variables in the exceptions to the ones used by system
- lower-casing the entity name for the native sender, as the queue name created by NSB endpoint is lowered as well
> Azure Service Bus Standard sample fixes

- samples/azure-service-bus-netstandard/native-integration/ASBS_1/NativeSender/Program.cs
Undoing wrongly understood endpoint casing introduced in #4165
> Azure Service Bus Standard - fixup

- menu/menu.yaml
Upgrade guides for the legacy ASB needs to call out that it's the old transport.
> ASB Legacy upgrade guides section title

- README.md
The guidance suggest how to deal with forcing transitive dependencies to be on the latest version.
This PR highlights _what_ those dependencies are and shows how to standardize on grouping those to make it clear and explicit.
> Making forced transitive dependencies outstand

- samples/web/sql-http-passthrough/SqlHttpPassthrough_2/SampleEndpoint/Program.cs
- samples/web/sql-http-passthrough/SqlHttpPassthrough_2/SampleWeb/Properties/launchSettings.json
Works fine in netcoreapp2.1 since the sample doesn't need to escalate to DTC. Tested with attachments as well
Closes #4199
> Remove unneeded ifdef in SQL pass through sample

- samples/router/update-and-publish/Router_3/Frontend/AcceptOrderController.cs
It wasn't actually using the same transaction/connection.
> Pass in the publish options created to the Publish method

- samples/hosting/docker/Core_7/docker-compose.yml
- Remove network new because it is unnecessary
- Specify hostname rabbitmq and connection port to allow other containers to connect to broker
> Fix docker sample

- persistence/msmq/subscription.md
Based on forum post https://discuss.particular.net/t/msmq-persistence/1014/21
> Add note about duplicate entries in subscription queue

- tests/IntegrityTests/ValidatePrereleaseTxt.cs
investigating why the build fails on this PR: https://github.com/Particular/docs.particular.net/pull/4302 it seems the regex can't match for packages with version number > 9. With my limited regex skills, my only idea was to allow multiple digits per version segment. 🤷‍♂️
> Allow package versions >9

- nservicebus/messaging/message-identity.md
Since it only makes sense to transport implementors and also is a bit questionable since using the MessageId can be dangerous since its not guaranteed to be unique since users can set it
> Remove transport implementation guidance

- nservicebus/hosting/nservicebus-host/installation.md
Removed `installInfrastructure` parameter since it's been removed from code entirely.
As can be seen here: https://github.com/Particular/NServiceBus.Host/search?q=installInfrastructure&type=Code
There is no PR/commit that shows this, it's gone _that long_
> Removed `installInfrastructure` parameter

- Snippets/SqlPersistence/SqlPersistence_4/OutboxSettings.cs
`TimeToKeepDeduplicationData` is related to in memory outbox. The article where the snipped is shown is about Sql Outbox and talks about cleanup frequency.
> Replace TimeToKeepDeduplicationData with RunDeduplicationDataCleanupEvery

- Snippets/Core/Core_5/Installers.cs
- Snippets/Core/Core_6/Installers.cs
- Snippets/Core/Core_7/Installers.cs
Fix the comparison, as it always evaluated to false.
Also use OrdinalIgnoreCase comparison instead of culture-specific ToLower().
> fix string comparison in Installers sample code

- nservicebus/messaging/databus/azure-blob-storage.md
Adding a third option to clean up Azure DataBus attachments based on [customer feedback](https://particularsoftware.slack.com/files/U03241PMC/FJ0QX2X4Z/TAM_call_with_Pharmerica).
1. Add lifecycle management policy section
1. Warn about potential costs associated with the built-in method
> Update Azure DataBus cleanup section to include policy reference

- nservicebus/recoverability/configure-error-handling.md
- nservicebus/security/generating-encryption-keys.md
- transports/index.md
This removes references to the Labs projects that we archived.
Note, there is still a reference to `MsmqReturnToSourceQueue` [here](https://docs.particular.net/nservicebus/upgrades/5to6/tools-and-helpers), but since it was in an upgrade guide, I thought it made sense to keep it.
> Remove references to archived Labs projects

- servicecontrol/errorlog-auditlog-behavior.md
Fixes https://github.com/Particular/ServiceControl/issues/1568 where there was some confusion with respect to forwarding _to_ the log queues, versus the queues being called forwarding queues. The queues are forwarded _to_, they are not doing the forwarding themselves.
However, I also asked the question as to whether or not the SCMU UI should also be updated to better reflect the nature of the queue to be created? E.g. change _ERROR FORWARDING QUEUE NAME_ to _ERROR FORWARDING LOG QUEUE NAME_.
> Update doc to reference audit/error log queues

- nservicebus/messaging/messages-events-commands.md
- transports/rabbitmq/routing-topology.md
I've also changed => defined to "identified" to avoid confusing users that might think defined as in "defined using a c# class".
The page now clarifies that we can receive messages that don't match conventions but needs the conventions for autosubscribe and commamnd routing to work
> Clarify when messages needs to be identified up front

- menu/menu.yaml
Message replay tutorial is not visible in the menu. The only way to view the content is to click button 'Next: Replaying failed messages' in the tutorial 'Introduction to NServiceBus' lesson ''Retrying errors'.
> add tutorial to the menu

- samples/azure-service-bus-netstandard/native-integration/sample.md
The namespace must always be present AFAIK but the assembly does not. This depends I think on the configured serializer.
> Namespace instead of fully qualified name

- nservicebus/messaging/reply-to-a-message.md
This is based on a support case where the customer send a reply but rolled back the transaction.
> Use immediate dispatch to reply non transient failures

- servicecontrol/creating-config-file.md
The default value for LogLevel I observe in reality is `Info` and not, as documented, `Warn`.
Not sure if the docs are wrong, or it's a bug. Log excerpt below.
2019-07-03 07:58:02.7225|4|Info|Particular.ServiceControl.Bootstrapper|
-------------------------------------------------------------
ServiceControl Version:             3.0.0.0
Audit Retention Period:             30.00:00:00
Error Retention Period:             15.00:00:00
Ingest Error Messages:              True
Ingest Audit Messages:              True
Forwarding Error Messages:          False
Forwarding Audit Messages:          False
Database Size:                      41943040 bytes
ServiceControl Logging Level:       Info
RavenDB Logging Level:              Warn
Selected Transport Customization: …
> Fix default value for ServiceControl/LogLevel

- samples/showcase/on-premises/Core_6/Store.ECommerce/Store.ECommerce.csproj
The ECommerce.csproj wouldn't load in VS19 because of the hardcoded VS version.
> Make ECommerce project loadable from VS19

- samples/index.md
Related to https://github.com/Particular/docs.particular.net/issues/4427
Adding a section to our samples documentation to indicate that we're using ConfigureAwait(false) consistently and why we're doing that.
cc @gbiellem
> Add section about usage of ConfigureAwait(false)

- dummy
- nservicebus/dependency-injection/ninject.md
Added remark on how to use a shared Ninject kernel between multiple NServiceBus endpoint instances
> How to use a shared Ninject kernel between instances

- Snippets/Router/Router_2/API.cs
Should second transport not be of type RabbitMQTransport?
> Use correct transport for TwoWayRouterConfig

- tests/IntegrityTests/Infrastructure/TestRunner.cs
- tests/IntegrityTests/Infrastructure/TestSetup.cs
- tests/IntegrityTests/ProjectLangVersion.cs
- tests/IntegrityTests/ValidatePrereleaseTxt.cs
VS2019 changes the default for LangVersion to latest, so you could presumably create a sample in VS2019 with `async Main` that works great but bombs in VS2017.
> Ensure LangVersion = 7.1 for VS2017-style projects

- samples/azure/functions/storage-queues/ASQFunctions_0.1/AzureFunctions.ASQTrigger/AzureStorageQueueTriggerFunction.cs
- samples/azure/functions/storage-queues/ASQFunctions_0.1/AzureFunctions.Console/Program.cs
- samples/azure/functions/storage-queues/ASQFunctions_0.1/local.settings.json
With ASQ (ASB is broken for now) it's possible to use the default connection string rather than specify one. This PR updates the ASQ sample to remove the requirement to specify the connection string.
> Azure Functions - ASQ - remove required connection string

- Snippets/Core/Core_5/Hosting/Hosting.cs
- Snippets/Core/Core_6/Hosting/Hosting.cs
- Snippets/Core/Core_7/Hosting/Hosting.cs
Docs Link: https://docs.particular.net/nservicebus/hosting/?
The code snippet that shows how to configure the send only endpoint implies that no other configuration is required for configuring the endpoint as send-only. However the user still needs to supply the needed configuration such as transport, etc.
This was reported by a customer.
> Added a comment in the snippets for SendOnly endpoints to clear up ambiguity

- samples/azure/functions/service-bus/ASBFunctions_0.1/AzureFunctions.ASBTrigger/AzureFunctions.ASBTrigger.csproj
- samples/azure/functions/service-bus/ASBFunctions_0.1/AzureFunctions.ASBTrigger/AzureServiceBusTriggerFunction.cs
- samples/azure/functions/storage-queues/ASQFunctions_0.1/AzureFunctions.ASQTrigger/AzureFunctions.ASQTrigger.csproj
- samples/azure/functions/storage-queues/ASQFunctions_0.1/AzureFunctions.ASQTrigger/AzureStorageQueueTriggerFunction.cs
To contrast with PR #4482 
Specifically, this PR is using `FunctionExecutionContext` exposing `ILogger`:
https://github.com/Particular/docs.particular.net/blob/3358576500883f66158eb9e798dd578d48e29ba3/samples/azure/functions/service-bus/ASBFunctions_0.1/AzureFunctions.ASBTrigger/AzureServiceBusTriggerFunction.cs#L35-L39
> Update to the latest Functions (fixed logging and re-added FunctionExecutionContext)

- nservicebus/operations/dotnet-framework-version-requirements.md
Improvements on the .net framework compatibility after a customer raised questions on if NServiceBus would be compatible if they targeted .net 4.7.2 with their assemblies.
> Added info on .net framework compatibility

- tutorials/monitoring-setup/index.md
This is the simplest variant of the fix. Just to point user to the list of releases that is sorted by latest version.
Or we should implement something to automatically identify the latest release, to prepare the latest *.exe link. Something like we have for SC on this page. In this case it's better to ignore this PR and to create an issue.
> Tutorials --> monitoring-setup --> sp url fix

- samples/dependency-injection/aspnetcore/Core_7.2/Sample/Sample.Core.csproj
- samples/dependency-injection/aspnetcore/Core_7.2/SampleAutofac/SampleAutofac.Core.csproj
- samples/gateway/Gateway_3/WebClient.Core/Properties/launchSettings.json
- samples/gateway/Gateway_3/WebClient.Core/WebClient.Core.csproj
- samples/showcase/on-premises/Core_7/Store.ECommerce.Core/Properties/launchSettings.json
- samples/showcase/on-premises/Core_7/Store.ECommerce.Core/Store.ECommerce.Core.csproj
- samples/web/asp-mvc-application/Core_7/AsyncPagesMVC.Core/AsyncPagesMVC.Core.csproj
- samples/web/asp-mvc-application/Core_7/AsyncPagesMVC.Core/Properties/launchSettings.json
- samples/web/asp-mvc-application/Core_7/AsyncPagesMVC.Core/Startup.cs
- samples/web/asp-web-application/Core_7/WebApplication.Core/Properties/launchSettings.json
- samples/web/asp-web-application/Core_7/WebApplication.Core/Startup.cs
- samples/web/asp-web-application/Core_7/WebApplication.Core/WebApplication.Core.csproj
- samples/web/send-from-aspnetcore-webapi/Core_7.2/WebApplication/WebApplication.Core.csproj
- samples/web/send-from-mvc-controller/Core_7/WebApplication.Core/Properties/launchSettings.json
- samples/web/send-from-mvc-controller/Core_7/WebApplication.Core/Startup.cs
- samples/web/send-from-mvc-controller/Core_7/WebApplication.Core/WebApplication.Core.csproj
- samples/web/send-from-nancy-module/Core_7/WebApplication.Core/Properties/launchSettings.json
- samples/web/send-from-nancy-module/Core_7/WebApplication.Core/WebApplication.Core.csproj
- samples/web/sql-http-passthrough/SqlHttpPassthrough_4/SampleEndpoint/SampleEndpoint.Core.csproj
- samples/web/sql-http-passthrough/SqlHttpPassthrough_4/SampleWeb/SampleWeb.Core.csproj
- samples/web/sql-http-passthrough/SqlHttpPassthrough_4/SampleWeb/SampleWeb.csproj
- samples/web/sql-http-passthrough/SqlHttpPassthrough_4/Shared/Shared.Core.csproj
- samples/web/sql-http-passthrough/SqlHttpPassthrough_4/Tests/Tests.Core.csproj
- samples/web/sql-http-passthrough/SqlHttpPassthrough_4/Tests/Tests.csproj
Now that the DocsEngine fix has been deployed, we can properly update the ASP.NET Core samples.
This updates the projects to use the `Microsoft.AspNetCore.App` package.
> Fix ASP.NET Core samples

- nservicebus/hosting/azure-functions/index.md
- samples/azure/functions/index.md
- samples/azure/functions/service-bus/ASBFunctions_0.1/AzureFunctions.ASBTrigger/AzureFunctions.ASBTrigger.csproj
- samples/azure/functions/service-bus/ASBFunctions_0.1/AzureFunctions.ASBTrigger/AzureServiceBusTriggerFunction.cs
- samples/azure/functions/service-bus/ASBFunctions_0.1/AzureFunctions.Console/Program.cs
- samples/azure/functions/service-bus/ASBFunctions_0.1/local.settings.json
- samples/azure/functions/service-bus/sample.md
- samples/azure/functions/storage-queues/ASQFunctions_0.1/AzureFunctions.ASQTrigger/AzureFunctions.ASQTrigger.csproj
- samples/azure/functions/storage-queues/sample.md
- Removed the need to specify Service Bus Connection string setting name, following the same model as Storage Queues sample.
- Removed constraint from the [constraints and limitation document](https://docs.particular.net/nservicebus/hosting/azure-functions/) 
> - While the Azure Functions runtime uses the default connection string in the app setting that is named "AzureWebJobsServiceBus" (ASB) or "AzureWebJobsStorage" (ASQ), there's a bug with the Service Bus and the trigger connection has to be specified.
> Azure Functions bug fix

- servicecontrol/audit-instances/creating-config-file.md
Update the casing of the HostName app settings key to match the same case ServiceControl created automatically in the ServiceControl.exe.config file
> Update the casing of the HostName

- servicecontrol/configure-non-privileged-service-account.md
member was misspelled in the performance counter section.
> Fix spelling mistake

- servicecontrol/creating-config-file.md
Update the casing of the HostName app settings key to match the same case ServiceControl created automatically in the ServiceControl.exe.config file
> Fixing HostName casing

- servicecontrol/creating-config-file.md
Documenting that the setting was removed in [v2.0](https://github.com/Particular/ServiceControl/blob/2.0.0/src/ServiceControl/Infrastructure/Settings/Settings.cs) 
Closes https://github.com/Particular/ServiceControl/issues/1768
> MaximumMessageThroughputPerSecond removed in SC 2.0

- Snippets/Core/Core_6/Routing/Extensibility.cs
- Snippets/Core/Core_7/Routing/Extensibility.cs
use `GetOrCreate` instead of `Get` as the `UnicastRoutingTable` hasn't been set on the endpoint configuration settings yet. Other snippets for routing extensibility are fine as they happen as part of a feature setup where those classes have been added to the settings.
> Fix routing extensibility doco snippet

- menu/menu.yaml
- servicecontrol/bcdr.md
This is a potential configuration for ServiceControl which allows for business continuity / disaster recovery without the use of Windows Clusters, for instance in the case of using multiple availability zones in a cloud provider.
> Business Continuity / Disaster Recovery configuration for SC

- nservicebus/licensing/index_license-management_core_[7,].partial.md
Documenting the changes made in https://github.com/Particular/NServiceBus/pull/5453
I did not mention anything about this being shipped only as part of 7.2 as the discussion in https://github.com/Particular/NServiceBus/pull/5453 evolved around the assumption of this being a bug fixed in 7.2 so it's fair to state this as the expected behavior in v7. Thoughts?
> Document code-first license API behavior

- Snippets/InMemoryPersistence/Core_7.2/Usage.cs
Not sure why this comment is there, that API seems to be only available in 7.2.
> Remove incorrect comment

- persistence/mongodb/migrating-from-tekmaven.md
Based on the walkthrough with @HEskandari , the current documentation is not very clear on how to migrate the connection settings.
I also moved the document versioning section to the end of the document as it's a fairly large section which seems to be less important than the compatibility settings.
> Clarify connection string migration for NServiceBus.Persistence.MongoDB

- servicecontrol/upgrades/2to3.md
- servicecontrol/upgrades/3to4/index.md
* Note explicitly that there are no lengthy data migrations
* Be more specific about how original SC database can be compacted after 1 retention period has elapsed.
> Clarify ServiceControl 3to4 upgrade guide

- persistence/mongodb/migrating-from-sbmako.md
- persistence/mongodb/migrating-from-tekmaven.md
some more feedback based on the migration walkthroughs.
Mention in the upgrade guides that a migration to NServiceBus 7 is currently mandatory as this is non-obvious otherwise.
This isn't true for the `NServiceBus.MongoDB` package as it supports v7 of NSB by now.
> Add recommendations for upgrade procedure due to major version upgrade

- nservicebus/hosting/extensions-hosting.md
See https://github.com/Particular/NServiceBus.Extensions.Hosting/issues/23
Looking at the implementation, the asp.net web hosting is also using an `IHostedService`. Given those are Started in order and the web host seems to start accepting requests right after that, there is a race condition which might lead to the message session not being available yet (and therefore breaking the lazy). Ensuring that the NServiceBus hosted service starts first should resolve this problem.
Documenting this behavior for now, going to raise a dedicated issue about this in a bit.
> UseNServiceBus must be specified before ConfigureWebHostDefaults

- README.md
- samples/logging/application-insights/sample.md
- samples/logging/new-relic/sample.md
- samples/logging/prometheus-grafana/sample.md
- tutorials/message-replay/tutorial.md
- tutorials/quickstart/tutorial.md
Since https://github.com/Particular/DocsEngine/pull/429 is deployed, pages that we share on Twitter can have a preview image to go with the other metadata.
> Preview images for tweetable content

- transports/azure-service-bus/compatibility.md
If a customer is upgrading from legacy Azure Service Bus v 7 to the new transport the legacy transport needs to restrict the number of entities in a bundle to one. If it is not restricted the legacy publisher might publish to `bundle-2` which then will never arrive on the new transport side for the subscribers
> Mention NumberOfEntitiesInBundle

- samples/throttling/Core_6/Limited/ThrottlingBehavior.cs
- samples/throttling/Core_7/Limited/ThrottlingBehavior.cs
Without returning at this point, the handler will be invoked, will cause the throttling exception and cause a second delayed message to go out, effectively eliminating the purpose of the first check + creating duplicates.
> Fix throttling sample

- servicepulse/intro-editing-messages.md
The closing tag for the "ServiceControl/AllowMessageEditing" appSetting was missing, which will cause ServiceControl to fail, if you just copy&paste it.
> Fixed missing closing tag

- transports/azure-service-bus/transaction-support.md
Fixes #4659
The note was originally copied from the Legacy ASB transport and is irrelevant for the new ASB transport.
> Remove irrelevant note

- transports/azure-service-bus/index.md
- transports/azure-service-bus/legacy/index.md
- transports/azure-storage-queues/index.md
- transports/msmq/index.md
- transports/sql/index.md
The work on `Transport at a glance` started before data bus name was standardized.
This PR fixes it.
> Data bus name fix

- servicecontrol/logging.md
Fixes #4166
ServiceControl contains code to select a default logging location if none is specified in the configuration file. The two supported mechanisms for creating a new instance (ServiceControl Management and Powershell) both result in an explicit log file location being set up. For powershell, it is a mandatory install-time parameter. For SCMU it defaults to the location listed.
> Simplify default logging

- nservicebus/dependency-injection/extensions-dependencyinjection.md
Adds a note to the NServiceBus.Extensions.DependencyInjection doco page to recommend the generic host instead. The generic host should be the better choice generally as it gives users the benefit of an externally managed container (access to the `IServiceProvider` in their code) while not having to configure the externally managed container mode manually
> Recommend generic host instead of using an internal DI container

- tutorials/quickstart/tutorial.md
In addition to the suggested changes, additional things I noticed while working on the tutorial:
1) 5 clicks of orders results in a "Get Extended Trial License" message (even when I already have a license).
2) I wonder if the comment about the "portable version of the Particular Service Platform" needs to be higher up in the Tutorial? I don't know what it looks like for a person on a non-Windows machine to do the other parts, so I am not sure what/how much to explain.
3) The dialog for adding a new project has changed significantly from what is illustrated.
4) The Pro-Tip is confusing to me because it seems to suggest that the Console App (.NET Framework) option is the backup to the option of Console App (.NET Core), but I *think* the instructions prior to that section tell you to do .NET …
> Attempts at better clarity

- persistence/ravendb/outbox.md
This makes the users aware that they need to handle outbox cleanup manually when using the multi-tenant support of the RavenDB persister.
> Add warning about outbox cleanup when running RavenDB in multi-tenant mode

- nservicebus/sagas/saga-audit.md
The reasons behind why the SagaAudit plugin was not supported in production are no longer completely valid. The SagaAudit plugin put pressure on both the endpoint as well as ServiceControl. ServiceControl has undergone a number of changes that make it less of a concern (specifically: there have been lots of performance improvements, and ServiceControl itself can be scaled out horizontally). Based on this, I propose changing out stance from "Not supported in production" to a warning stating "Use with caution as this will add pressure to your endpoint and will reduce the processing throughput."
> Change support stance of SagaAudit plugin

- persistence/upgrades/ravendb-5to6.md
Mentioning when and why manual migration for timeout data is required.
During review of #4738 this existing section seemed incorrect.
> When and why manual migration is required

- nservicebus/messaging/timeout-manager.md
Based on https://discuss.particular.net/t/duplicate-messages-for-delayed-retries-when-scaled-out-using-sql-transport-with-native-delayed-delivery/1763
> Improve awareness of generating timeout manager duplicates 

- Snippets/SqlPersistence/SqlPersistence_1/UsingSaga/OrderSaga.cs
- Snippets/SqlPersistence/SqlPersistence_1/UsingSaga/SagaWithCorrelation.cs
- Snippets/SqlPersistence/SqlPersistence_1/UsingSaga/SagaWithCorrelationAndTransitional.cs
- Snippets/SqlPersistence/SqlPersistence_2/UsingSaga/OrderSaga.cs
- Snippets/SqlPersistence/SqlPersistence_2/UsingSaga/SagaWithCorrelation.cs
- Snippets/SqlPersistence/SqlPersistence_2/UsingSaga/SagaWithCorrelationAndTransitional.cs
- Snippets/SqlPersistence/SqlPersistence_3/UsingSaga/OrderSaga.cs
- Snippets/SqlPersistence/SqlPersistence_3/UsingSaga/SagaWithCorrelation.cs
- Snippets/SqlPersistence/SqlPersistence_3/UsingSaga/SagaWithCorrelationAndTransitional.cs
- Snippets/SqlPersistence/SqlPersistence_4/UsingSaga/OrderSaga.cs
- Snippets/SqlPersistence/SqlPersistence_4/UsingSaga/SagaWithCorrelation.cs
- Snippets/SqlPersistence/SqlPersistence_4/UsingSaga/SagaWithCorrelationAndTransitional.cs
- Snippets/SqlPersistence/SqlPersistence_5/UsingSaga/OrderSaga.cs
- Snippets/SqlPersistence/SqlPersistence_5/UsingSaga/SagaWithCorrelation.cs
- Snippets/SqlPersistence/SqlPersistence_5/UsingSaga/SagaWithCorrelationAndTransitional.cs
- persistence/sql/sqlsaga.md
Avoid `_` since that is associated with the [discard syntax in C# 7](https://docs.microsoft.com/en-us/dotnet/csharp/discards). Technically, discard syntax is not supported in lamdas so this doesn't cause any issues but it might be confusing and in general `_` stands for values which aren't used, so the naming doesn't align with that convention.
> Avoid discard syntax when value is used

- transports/rabbitmq/routing-topology_mandatory_rabbit_[5,).partial.md
I had an LC visitor today who was confused between versions of NServiceBus and NServiceBus.RabbitMQ.
> mention package name in note on RabbitMQ conventional routing topology

- nservicebus/recoverability/index_retrycount_core_[6.0,).partial.md
After merging, update https://discuss.particular.net/t/duplicate-messages-for-delayed-retries-when-scaled-out-using-sql-transport-with-native-delayed-delivery/1763
> Retry counting when scaled-out

- servicecontrol/license.md
This is helpful to know for people who are automating the license upgrade and are okay with waiting out for the cache to be refreshed to pick up the new license.
/cc @WilliamBZA
> Add details on license cache for servicecontrol

- Snippets/Core/Core_7/Conventions/Usage.cs
@seanfarmar 
Can you confirm if this docs fix is correct?
Example reproduction:
```csharp
using NServiceBus;
using System;
namespace NSBConventions
{
class Program
{
static void Main(string[] args)
{
var ourType = typeof(TestNSBClass);
Console.WriteLine($"NSB Docs way, is assignable: {ourType.IsAssignableFrom(typeof(ICommand))}");
Console.WriteLine($"My way, is assignable: {typeof(ICommand).IsAssignableFrom(ourType)}");
}
}
public class TestNSBClass : ICommand
{
}
}
```
> Fix conventions inheritance example

- Snippets/ServicePulse/ServicePulse_All/web.config
OPTIONS is used against the /monitoring and /api/endpoints and needs to be allowed.
I kept getting 401 errors and tracked it down to these verbs not being allowed.
> Add OPTIONS verbs to web.config

- nservicebus/messaging/evolving-contracts.md
Refer to unobstrusive mode as the second option proposed from the solution structure might seem plausible but can also be solved by conventions.
This change is a reaction to [this question](https://discuss.particular.net/t/sharing-message-contracts/1943/2) asked on discourse.
> Refer to unobstrusive mode as a possible way to solve dependency on Message contracts

- persistence/index.md
Customer feedback, unclear if storage was required when using Azure Service Bus.
> Added note to storage types that storage type is only needed if transport is missing the feature natively

- Snippets/Ninject/Ninject.sln
- Snippets/Ninject/Ninject_5/Ninject_5.csproj
- Snippets/Ninject/Ninject_5/Usage.cs
- Snippets/Ninject/Ninject_6/Ninject_6.csproj
- Snippets/Ninject/Ninject_6/Usage.cs
- Snippets/Ninject/Ninject_7/Ninject_7.csproj
- Snippets/Ninject/Ninject_7/Usage.cs
- nservicebus/dependency-injection/ninject.md
Has an example for conserving the context between scopes. This allows for the context of the NamedScope to be used when resolving Func's
> Add note about context funcs

- transports/azure-service-bus/legacy/legacy-asb-warning.include.md
Given that Microsoft is working on another Azure SDK, it will become more confusing to users to correlate our transports to the target Azure SDK.
The current azure service bus transport refers to the nuget package used: Microsoft.Azure.ServiceBus, but the legacy one didn't  (WindowsAzure.ServiceBus).
Related to https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/149 and https://github.com/Particular/NServiceBus.AzureServiceBus/pull/902
> Added reference to the Azure client library used in the legacy warning

- nservicebus/dependency-injection/extensions-dependencyinjection.md
- nservicebus/dependency-injection/index_ownership_core_[7.2,).partial.md
based on the feedback on https://github.com/Particular/NServiceBus/issues/5700 we need to be more clear that sharing containers across endpoints is not supported.
I've also updated the note about the ASP.NET Core sample because that sample uses the generic host extension and therefore doesn't show how to do externally managed mode.
> Add additional notes about externally managed mode

- nservicebus/recoverability/index_retrycount_core_[6.0,).partial.md
I'm pretty sure the table headers have been mixed up. The default number of immediate retries is **five** and the default number of delayed retries is **three**. By swapping the table headers, the last row makes much more sense.
> Swap headers in table of total number of retries

- nservicebus/dependency-injection/index_ownership_core_[8.0,).partial.md
- nservicebus/hosting/extensions-hosting.md
- nservicebus/upgrades/7to8/dependency-injection.md
only added lamar, autofac and unity as the other previously supported containers (structuremap & castle windsor) don't seem to play perfectly with the generic host.
> Add generic host to the DI upgrade guide

- nservicebus/dependency-injection/index.md
- samples/dependency-injection/externally-managed-mode/Core_8/ExternallyManagedContainer.DotSettings
- samples/dependency-injection/externally-managed-mode/Core_8/ExternallyManagedContainer.sln
- samples/dependency-injection/externally-managed-mode/Core_8/Sample/MessageSenderService.cs
- samples/dependency-injection/externally-managed-mode/Core_8/Sample/MyHandler.cs
- samples/dependency-injection/externally-managed-mode/Core_8/Sample/MyMessage.cs
- samples/dependency-injection/externally-managed-mode/Core_8/Sample/MyService.cs
- samples/dependency-injection/externally-managed-mode/Core_8/Sample/Program.cs
- samples/dependency-injection/externally-managed-mode/Core_8/Sample/Sample.csproj
- samples/dependency-injection/externally-managed-mode/sample.md
Adds a sample for the externally managed mode in NServiceBus version 8. I did not add a v7 sample as v7 would require custom adapters to integrate with the v7 NSB DI abstractions and that's what the NServiceBus.Extensions.DependencyInjection package (and sample) is for.
> Add externally managed mode sample

- Snippets/Core/Core_7.4/Conventions/AttributeMessageConvention.cs
Tie Namespace strings to appropriate types
> Tie Namespace strings to appropriate types in MessageConventions code snippet

- nservicebus/sagas/index.md
Based on (critical) support case where the user uses the saga ID in messages emitted from the saga. Although NServiceBus does exactly the same via the `OriginatingSagaId` and `ServiceBus.SagaId` headers it is considered a value only to be used internally by the framework.
> Do not use saga Id for correlation

- Snippets/Core/Core_6/Recoverability/Delayed/CustomPolicies/FullyCustomizedPolicy.cs
- Snippets/Core/Core_7.2/Recoverability/Delayed/CustomPolicies/FullyCustomizedPolicy.cs
- Snippets/Core/Core_7/Recoverability/Delayed/CustomPolicies/FullyCustomizedPolicy.cs
- Snippets/Core/Core_8/Recoverability/Delayed/CustomPolicies/FullyCustomizedPolicy.cs
- nservicebus/recoverability/custom-recoverability-policy.md
- nservicebus/recoverability/index_retrycount_core_[6.0,).partial.md
The [documentation for the Default Recoverability Policy](https://docs.particular.net/nservicebus/recoverability/custom-recoverability-policy?) is correct when it describes Immediate Retries:
> If the ImmediateProcessingFailures value is less or equal to the configured MaxNumberOfRetries for Immediate Retries, then the ImmediateRetry action is returned.
[Relevant code](https://github.com/Particular/NServiceBus/blob/c936c938c76f6a2e2e98a2849a9f029bb530e09b/src/NServiceBus.Core/Recoverability/DefaultRecoverabilityPolicy.cs#L30-L33):
```c#
if (errorContext.ImmediateProcessingFailures <= config.Immediate.MaxNumberOfRetries)
{
return RecoverabilityAction.ImmediateRetry();
}
```
But it incorrectly uses "less or equal" when describing Delayed Retires:
> If the DelayedDeliveriesPerformed is less …
> Correct description of how many Delayed Retries are performed

- nservicebus/community/index.md
Replaces https://github.com/Particular/docs.particular.net/pull/4818 and brings back links (with descriptions) to stuff lost in merge of https://github.com/Particular/docs.particular.net/pull/4548.
> Add NSBExtensions to community page

- .github/stale.yml
After merge, the [probot-stale](https://github.com/probot/stale) app will be added to only this repository (not the organization) which requires only the following permissions:
* Read access to files located at `.github/stale.yml` (the config being added by this PR)
* Read access to this repo's metadata
* Read and write access to issues and pull requests in this repo (to add/remove labels and close issues)
> Configuration for Probot: Stale

- Snippets/Core/Core.sln
- Snippets/Core/Core_7.4/Scanning/ScanningPublicApi.cs
- Snippets/Core/Core_8/Scanning/ScanningPublicApi.cs
- nservicebus/hosting/assembly-scanning.md
- nservicebus/hosting/assembly-scanning_additional-path_core_[7.4,].partial.md
Document a new feature added to the Core ([support for setting an additional assembly scanning path](https://github.com/Particular/NServiceBus/pull/5653)) that hasn't been released yet.
> Document assembly scanning AdditionalAssemblyScanningPath feature

- components/components.yaml
As the older plugin repos are all archived and deprecated
> Link directly to plugin repos

- nservicebus/upgrades/7to8/dependency-injection.md
Feedback that has been provided by @aleksandr-samila was that it wasn't clear what methods one should use if not familiar with the IServiceCollection API yet. Added a list of the typical replacement methods and a docs link to other available extension methods.
@aleksandr-samila does that address the concerns you raised? (sorry it has been a while already)
> Mention IServiceCollection methods on DI upgrade guide

- samples/consumer-driven-contracts/Core_7/Consumer1/Consumer1.csproj
- samples/consumer-driven-contracts/Core_7/Consumer2/Consumer2.csproj
- samples/consumer-driven-contracts/Core_7/Producer/Producer.csproj
- samples/pipeline/audit-filtering/Core_7/AuditFilter/AuditFilter.csproj
- samples/pipeline/session-filtering/Core_7/Receiver/Receiver.csproj
- samples/pipeline/session-filtering/Core_7/Sender/Sender.csproj
- samples/pipeline/session-filtering/Core_7/SessionFilter/Shared.csproj
- samples/routing-slips/MessageRouting_3/Messages/Messages.csproj
- samples/routing-slips/MessageRouting_3/ResultHost/ResultHost.csproj
- samples/routing-slips/MessageRouting_3/Sender/Sender.csproj
- samples/routing-slips/MessageRouting_3/StepA/StepA.csproj
- samples/routing-slips/MessageRouting_3/StepB/StepB.csproj
- samples/routing-slips/MessageRouting_3/StepC/StepC.csproj
- samples/serializers/newtonsoft/Newtonsoft_2/Sample/Sample.csproj
```
warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.CSharp". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
```
> Resolves build warnings "Could not locate the assembly "Microsoft.CSharp""

- Snippets/Gateway/Gateway.sln
- Snippets/Gateway/Gateway_1/Gateway_1.csproj
- Snippets/Gateway/Gateway_2/Gateway_2.csproj
- Snippets/Gateway/Gateway_3.1/Gateway_3.1.csproj
- Snippets/Gateway/Gateway_3/Gateway_3.csproj
- Snippets/Gateway/Gateway_4/Gateway_4.csproj
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2084,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "C:\Users\Ramon\.nuget\packages\microsoft.servicefabric.data\2.8.232\lib\net45\Microsoft.ServiceFabric.Data.dll", "AMD64". This mismatch may cause runtime failures. Please consider changing the targ
eted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project. …
```
> Resolve build warning by targeting x64 Platform

- samples/servicecontrol/monitoring3rdparty/CustomChecks_3/Sample/Sample.csproj
Resolved build warning because System.Net.Http should not be included for .net core.
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2084,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.Net.Http". Check to make sur
e the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\Users\Ramon\src\particular\docs.particular.net\samples\servicecontrol\monitoring3rdparty\CustomChecks_3\Sample\Sample.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2084,5): warning MSB3243: No way to resolve conflict between "System.Net.Http, Version=4.2.2.0, …
```
> Resolved build warning because System.Net.Http should not be included

- menu/menu.yaml
The page seems to use "Data Bus" consistently, only the menu showed "Databus".
> Align Data Bus menu title with page title

- tests/IntegrityTests/ValidatePrereleaseTxt.cs
Prior to this change:
```
A total of 1 test files matched the specified pattern.
Failed VerifyPrereleaseTxtHasPrereleaseComponent [295 ms]
Error Message:
System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.
Stack Trace:
at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
at IntegrityTests.ValidatePrereleaseTxt.<VerifyPrereleaseTxtHasPrereleaseComponent>b__0_0(String path) in C:\github\nsb\docs.particular.net\tests\IntegrityTests\ValidatePrereleaseTxt.cs:line 26
at IntegrityTests.TestRunner.Run(Func`2 testDelegate) in C:\github\nsb\docs.particular.net\tests\IntegrityTests\Infrastructure\TestRunner.cs:line 40
at IntegrityTests.ValidatePrereleaseTxt.VerifyPrereleaseTxtHasPrereleaseComponent() in …
```
> Show component name when failing the test

- servicecontrol/powershell.md
Behavior of `Import-ServiceControlLicense` isn't aligned with the docs. Cmdlet writes to file-system and not the registry. Might have been introduced by 214c2e63acea74ce1dd99a0edefb062750a623e9
> Import-ServiceControlLicense docs writes to filesystem, not registry

- README.md
Add some guidance to sample building so that all samples targeting .NET Core run across Windows, Linux and macOs or explain why they don't.
> Samples targeting .Net core should run across platforms

- servicecontrol/logging.md
The documentation can be a bit misleading when trying to change the log levels for audit or monitoring instances as it's not clear on this documentation page about logging in ServiceControl that the Audit and Monitoring instances use different config keys.
> Link to Audit and Monitoring log configration

- transports/sql/connection-settings.md
- transports/sql/native-publish-subscribe.md
Some clarification about using a shared subscription table when using multiple schemas across pub-sub endpoints.
> SQLT Multi-schema doco updates

- nservicebus/tools/migrate-to-native-delivery.md
@WojcikMike and I discussed this and don't really see the value of keeping the examples.
We explored adding examples for each target keeping the source "undefined" so to speak, but even so, we wonder how meaningful this is. Leaving in a few only helps move forward a part of the users, adding all permutations is noisy.
Thoughts?
> Remove the examples

- nservicebus/sagas/index.md
It may be obvious to you but I was very confused that it's not explicitly stated, that `IAmStartedByMessage` messages automatically initializes the correlation property on the `SagaData` which is mapped in the `ConfigureHowToFindSaga()` method.
> IAmStartedByMessage initializes mapped correlation property

- nservicebus/upgrades/all-versions.md
- nservicebus/upgrades/support-policy.md
- nservicebus/upgrades/supported-versions.js
- nservicebus/upgrades/supported-versions.md
Does not require the version script to run only for applying strikethrough styling.
> Dynamic strikethrough for unsupported versions

- nservicebus/sagas/concurrency.md
I saw this optimization is missing in the concurrency guidance.
> Reduce concurrency by applying sequential scatter/gather

- Snippets/ASQ/ASQN_10/Usage.cs
While reviewing the docs for pub/sub I've noticed the name of the event described and used in the snippet not matching.
> Fix the event name published by Publisher 1

- transports/azure-service-bus/native-message-access.md
Documents that native message customization is not supported when the Outbox is enabled.
> ASB native customization not supported with Outbox

- tools/build-samples-and-snippets.ps1
Makes the following changes:
- Removes `nodeReuse` from both commands since the default value is `true`
- Changes `dotnet` verbosity to the correct syntax for the command
- Removes `dotnet` property:RestorePackagesConfig because that doesn't do anything.
Default `dotnet` verbosity is already `minimal`, but I left it there for now.
> Clean up command line parameters

- samples/hosting/generic-multi-hosting/Core_7/Sample.MultiHosting/Program.cs
- samples/hosting/generic-multi-hosting/sample.md
Workaround for a single endpoint failing scenario to take down the host to ensure no endpoint is reported as active.
Related to a support case that was a result of a public issue https://github.com/Particular/NServiceBus.Heartbeat/issues/121.
> Multi-hosting with generic host - workaround for a failing endpoint

- servicecontrol/servicecontrol-instances/remotes.md
The _after_ images use the colour schemes of each component:
> editorial review of SC remotes

- servicepulse/containerization/index.md
The [Linux image exposes port 90](https://github.com/Particular/ServicePulse/blob/master/src/dockerfile.nginx#L17), so the port mapping command needs to be updated to work properly.
> Fix Linux port mapping

- samples/logging/datadog/Core_7/Endpoint/DatadogFeature.cs
We are using NServiceBus and DataDog and found that the original implementation of this integration created far too many metrics and was nearly impossible to create usable dashboards. What wound up really helping is using the common APM names for specific metrics, and then added things liked EndpointName and MessageType as tags on that metric. This allows you to aggregate all of a single metric for all messages combined (e.g. total cluster throughput), as well as break things down by individual endpoints (e.g. endpoint failure rate), or to the fine grained message type (e.g. processed message count by message).
> Use common APM names with tagged metadata

- nservicebus/sagas/index.md
Record types can't be deserialized when they're used as immutable properties. Added a note.
> Added note about record type

- nservicebus/architecture/scaling.md
The `Be aware of idempotency` note seems to be confusing as there is no specific reason stated why idempotency would be specifically relevant for competing consumers. Also the link points to a page about transactions in Azure which seems even more confusing.
> Remove link to azure transactions

- nservicebus/handlers/index.md
Based on a support case where a customer expected that already successfully invoked handler would not be invoked again.
> Retrying a single message will invoke all matching handlers again

- previews/azure-functions-storage-queues.md
Based on customer feedback, the one-second maximum polling interval can lead to a perceived high latency on message processing.
> Document polling interval settings

- persistence/nhibernate/outbox_transactionisolation_nhibernate_[8.5,).partial.md
I noticed a new section https://github.com/Particular/docs.particular.net/pull/5395 and I think it could use a little argumentation.
> Clarification why outbox does not support snapshot isolation

- samples/pipeline/stream-properties/Core_7/Receiver/Program.cs
- samples/pipeline/stream-properties/Core_7/Sender/Program.cs
This didn't work anyway (behavior was not registered on the receiver) and this gets it ready for .NET 6 when WebClient is obsolete.
> Fix stream properties sample

- nservicebus/upgrades/supported-platforms.md
Adding text to https://docs.particular.net/nservicebus/upgrades/supported-platforms clarifying the meaning of "supported". Work done as part of issue https://github.com/Particular/DeveloperExperience/issues/1475
> dotnet-support-policy-issue-1475

- transports/upgrades/asbs-1.7to1.8.md
When migrating from `RuleNameShortener` which is a `Func<string, string>` to the recommended `SubscriptionRuleNamingConvention` function, which is `Func<Type, string>` it's not clear what `Type` property to use for shortening. Clarifies the upgrade guide that by default, the naming convention is to use `Type.FullName`
> Clarify migration from SubscriptionNameShortener

- Snippets/ASBFunctions/ASBFunctions_1.1/FunctionsHostBuilderUsage.cs
- Snippets/ASBFunctions/ASBFunctions_1.2/FunctionsHostBuilderUsage.cs
- nservicebus/hosting/azure-functions/custom-triggers.md
- nservicebus/hosting/azure-functions/custom-triggers_content_ASBFunctions_[1.1,1.3).partial.md
- nservicebus/hosting/azure-functions/custom-triggers_content_ASBFunctions_[1.3,).partial.md
- nservicebus/hosting/azure-functions/service-bus_configuration_ASBFunctions_[1.3,).partial.md
- nservicebus/hosting/azure-functions/service-bus_message-consistency_ASBFunctions_[,1.3).partial.md
- nservicebus/hosting/azure-functions/service-bus_message-consistency_ASBFunctions_[1.3,).partial.md
- nservicebus/hosting/azure-functions/service-bus_queue-trigger-wiring_ASBFunctions_[1.1,1.2].partial.md
- nservicebus/hosting/azure-functions/service-bus_queue-trigger-wiring_ASBFunctions_[1.3,).partial.md
Some minor word teaks + extracts the custom trigger documentation into a dedicated page to simplify the main page
> Extract custom trigger definition docs page

- Snippets/ASBFunctions/ASBFunctions_1.3/MessageConsistency.cs
- Snippets/ASBFunctions/ASBFunctions_1.3/TriggerDefinition.cs
There is no binding for the interface. There is an open feature request for it here https://github.com/Azure/azure-functions-servicebus-extension/issues/124
> Use concrete message receiver

- samples/azure/native-integration-asq/ASQN_11/Receiver/Receiver.csproj
- samples/azure/storage-queues/ASQN_11/Endpoint1/Endpoint1.csproj
- samples/azure/storage-queues/ASQN_11/Endpoint2/Endpoint2.csproj
Those two samples seem to fail to build due to mismatching dependencies. There is a wildcard dependency on the JSON serializer package of which there seems to be a new PR being pushed to the myget feed that is picked up by the wildcard dependency.
> Fix azure samples

- .github/workflows/build-solutions.yml
- tools/build-samples-and-snippets.ps1
While reading `build-samples-and-snippets.ps1`, I got confused because I couldn't work out where the snippets were being built, until I realised that `$samples` actually refers to _all_ solutions, whether samples or snippets.
In turn that led me to some more places where we are currently using "solution", "project", and "sample" interchangeably, where all the references actually mean "solution" (which could be a sample or a snippet).
> call solutions "solutions"

- nservicebus/hosting/azure-functions-service-bus/isolated-worker.md
Documents the minimum required version of the .NET SDK and Visual Studio for the source generator to be able to load correctly. Failure to do so will cause the trigger to not be generated.
> Document .NET SDK version requirements

- servicecontrol/upgrades/supported-versions.md
Based on a customer asking if upgrading their SC v1.x version to v4.x would cause compatibility issues with their NServiceBus 4.x and 5.x endpoints.
> ServiceControl NServiceBus version compatibility

- samples/unit-testing/sample.md
add a note that the interface message has to be manually implemented for testing.
based on the feedback from https://github.com/Particular/docs.particular.net/issues/5538
> Add note about interface messages

- Snippets/Testing/Testing_6/Handlers/InterfaceMessageTests.cs
- Snippets/Testing/Testing_7/Handlers/InterfaceMessageTests.cs
- Snippets/Testing/Testing_8/Handlers/InterfaceMessageTests.cs
- nservicebus/testing/index_content_testing_[6,).partial.md
- samples/unit-testing/sample.md
followup on #5551 to document using the `MessageMapper` instead, [as suggested by Udi](https://github.com/Particular/docs.particular.net/pull/5551#issuecomment-974793759)
Removed the interface message related note on the sample and instead moved it to the actual docs page.
> Show usage of using message mapper

- Snippets/ASP/ASTP_3/Usage.cs
- Snippets/ASP/ASTP_4/Usage.cs
This is a snippet for [this page](https://docs.particular.net/persistence/azure-table/#enable-azure-table-persistence-supported-saga-properties-types-customization) on how to configure the JSON serializer but there is no direct need to configure TypeNameHandling.Auto so we can also just remove it here.
> Remove TypenameHandling.Auto from the example configuration

- samples/azure-service-bus-netstandard/lock-renewal/ASBS_1/LockRenewal/Program.cs
Fixes #5568
Prevents the sample from overwiting unaffected queue details (such as description).
> Do not overwrite other queue details (ASB Sample)

- monitoring/metrics/definitions.md
Related to https://discuss.particular.net/t/queue-length-metric-is-not-available/2524
> Clarify queue length is not monitored via NServiceBus.Metrics

- samples/previews/aws-lambda/sqs/SQSLambda_0/AwsLambda.SQSTrigger/serverless.template
The policy name previously used has been [deprecated](https://docs.aws.amazon.com/lambda/latest/dg/access-control-identity-based.html)
> Fix the policy name in CloudFormation template

- nservicebus/recoverability/index_consecutive-failures_core_[7.6,).partial.md
I would suggest not using the phrasing "single threaded". It is not correct. Maybe talk about processing one message at a time, vs processing multiple messages at the same time? I think this is the more precise and yet simpler to understand explanation of what is going on.
> Remove single threaded

- menu/menu.yaml
based on the additions to the docs-menu for previews made by Travis, we can add AWS Lambda to the hosting menu entry with some nice indication of it's preview status.
> Adding AWS preview to hosting menu

- Snippets/ASP/ASTP_3/Usage.cs
- Snippets/ASP/ASTP_4/Usage.cs
- Snippets/CosmosDB/CosmosDB_1/Usage.cs
- persistence/azure-table/index.md
- persistence/azure-table/index_ratelimiting_astp_[3,].partial.md
- persistence/cosmosdb/index.md
Relates to https://github.com/Particular/NServiceBus.Persistence.CosmosDB/issues/170
This PR adds documentation about provisioned throughput throttling and how to configure the SDK throttling settings using the CosmosClient and provides a link to Microsoft's troubleshooting guide as well as a sample.
> Document throttling retry configuration for CosmosDB

- servicepulse/health-check-notifications.md
The current document confusing, causing users to think SC can email about failed messages.
> SC health checks email clarification 

- persistence/sql/operational-scripting.md
Trying to add clarity that "--dialect" and "--output-dir" require "=value". The parser does not seem to look for arg+1 for the value like some command line tools do.
```sql-persistence script .\bin\...\Endpoint.dll --clean --dialect SqlServer --output-dir C:\Temp\sqlpersistence_out```
> sql-persistence failed: Unrecognized command or argument 'SqlServer'
> Update operational-scripting.md for clarity about specifying values for certain script command options

- nservicebus/sagas/concurrency.md
The documentation seems incorrect/outdated given RavenDB is supporting "pessimistic locking"
> Document RavenDB pessimistic locking support

- transports/upgrades/asbs-2to3.md
There is no `CustomTokenProvider` API in v7 and no `TokenProvider` property in v8. This changes things to match the public API
- [V8](https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/blob/master/src/Tests/ApprovalFiles/APIApprovals.Approve.approved.txt#L16)
- [V7](https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/blob/release-2.0/src/Tests/ApprovalFiles/APIApprovals.Approve.approved.txt#L13)
> ASB Upgrade Guide - Match existing API name

- tutorials/quickstart/Solution/ClientUI/wwwroot/Content/app.js
- tutorials/quickstart/tutorial.md
Because Kissmetrics users are stored in cookies and the Quickstart solution doesn't run with the same domain as the tutorial page, we are currently unable to see to which variant of the A/B test do users of the solution belong to. This PR proposes tracking the default solution with events specific to this test and having users of the variant download a separate solution with different events. When analyzing funnels we can manually stitch tutorial page views and downloads with solution runs and send message events.
> Different zip's for control and variant in the Quickstart A/B test

- nservicebus/messaging/headers.md
Added `OriginatingEndpoint` and `ProcessingEndpoint` to comment which headers are used by SI to link messages.
> SI also uses OriginatingEndpoint and ProcessingEndpoint headers

- menu/menu.yaml
- nservicebus/upgrades/7to8/index.md
- nservicebus/upgrades/7to8/message-contracts.md
Adds more details to the upgrade guide about shared message contract assemblies and how to multi-target
> Message contracts upgrade guidance

- servicecontrol/db-compaction.md
Compacting only makes sense when:
- Retention period is reduced and that retention period actually passed and all data purged
- Huge sets of errors have been retried or archived
- The (audit) message throughput is lower
- The average message size is lower
> Factors that prevent SC database compacting

- samples/dependency-injection/aspnetcore/Core_8/ASPNetCore.StartupProjects.txt
- samples/dependency-injection/aspnetcore/Core_8/ASPNetCore.sln
- samples/dependency-injection/aspnetcore/Core_8/Sample/MyHandler.cs
- samples/dependency-injection/aspnetcore/Core_8/Sample/MyMessage.cs
- samples/dependency-injection/aspnetcore/Core_8/Sample/MyService.cs
- samples/dependency-injection/aspnetcore/Core_8/Sample/Program.cs
- samples/dependency-injection/aspnetcore/Core_8/Sample/Properties/launchSettings.json
- samples/dependency-injection/aspnetcore/Core_8/Sample/Sample.csproj
- samples/dependency-injection/aspnetcore/Core_8/Sample/Startup.cs
- samples/dependency-injection/aspnetcore/Core_8/SampleAutofac/MyHandler.cs
- samples/dependency-injection/aspnetcore/Core_8/SampleAutofac/MyMessage.cs
- samples/dependency-injection/aspnetcore/Core_8/SampleAutofac/MyService.cs
- samples/dependency-injection/aspnetcore/Core_8/SampleAutofac/Program.cs
- samples/dependency-injection/aspnetcore/Core_8/SampleAutofac/Properties/launchSettings.json
- samples/dependency-injection/aspnetcore/Core_8/SampleAutofac/SampleAutofac.csproj
- samples/dependency-injection/aspnetcore/Core_8/SampleAutofac/Startup.cs
v8 sample for https://docs.particular.net/samples/dependency-injection/aspnetcore/
> Add ASP.NET Core 3 DI sample targeting NSB v8

- nservicebus/upgrades/release-policy.md
Our branching strategy make it nearly impossible to define a beta as feature complete. This PR updates the release policy to match our branching strategy.
> Match the feature complete state to our process

- samples/azure-service-bus-netstandard/lock-renewal/ASBS_2/LockRenewal/LockRenewal.csproj
- samples/azure-service-bus-netstandard/lock-renewal/ASBS_3/LockRenewal/LockRenewal.csproj
Explicitly target Azure.Messaging.ServiceBus 7.* due to fixed bug that affected long running handlers.
> Lock renewal examples explicitly target Azure.Messaging.ServiceBus 7.* due to fixed bug

- nservicebus/bridge/migrating-from-router.md
The current text sounds like we are making a statement about the level of support provided for the router. That is out of our control. For example, however unlikely it may be, the community may even provide _better_ support for router than we do for bridge. It's up to the community to decide that. The only difference we can absolutely state is that the bridge is _our_ package, and router is someone else's.
> clarify support difference between Bridge vs Router

- samples/routing/fair-distribution/Core_7/Shared/FairDistribution/FairDistribution.cs
- samples/routing/fair-distribution/Core_7/Shared/FairDistribution/FairDistributionStrategy.cs
- samples/routing/fair-distribution/Core_8/Shared/FairDistribution/FairDistributionStrategy.cs
The sample is currently broken on v7 because access to the `FlowManager` created by a `Feature` happens too early. It seems this has already been addressed for the v8 sample and I went with the same approach using a `Lazy` to delay access until the feature has ran its default configuration. Not ideal but there is currently no better way to share settings from a Feature with outside code. Also added a small comment for clarity.
> Fix fair distribution sample for v7

- previews/index.md
Fixed note that was added to the wrong Preview + clarify Preview availability.
> Fix AF ASQ planned archival note, more clear Preview status

- .gitignore
- menu/menu.yaml
- nservicebus/tools/migrate-to-native-delivery.md
This only re-organizes the global nav menu to prevent sections from linking directly to pages. Now they should just expand or collapse a section. The exception is the Getting Started section, which from some reason doesn't work yet. This probably requires a docs engine update, and main sections (e.g. transports) also seem to need a docs engine update to stop linking.
> Re-org nav IA to enable better menu UX

- servicecontrol/transports.md
- transports/azure-service-bus/configuration.md
- transports/azure-service-bus/configuration_custom-token-credentials_asbs_[2,].partial.md
- transports/azure-service-bus/index.md
Moved ASBS "Configuring an endpoint" from index to configuration page close to connectivity information to improve visibility of Azure Active Directory information on usage of `TokenCredential`.
While smoke testing https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/599 to validate if it resolves https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/issues/588 I discovered that the connection string should only contain the namespace identifier. This was even mentioned in the docs but not very visible.
> ASBS configuration/connectivity restructured regarding usage of `TokenCredential`

- samples/logging/new-relic/sample.md
Hi dev team,
We have many users on our platform who are using NServiceBus and would like to instrument it. We’d love to provide a smooth experience for NServiceBus users who need to use commercial monitoring solutions, such as New Relic. Please see our documentation[ here](https://newrelic.com/instant-observability/nservicebus/f3f28a00-8cea-41f1-a6fe-ebf5eae5791e).
Please consider adding a link for your direct users to provide an option for New Relic.  For your convenience, we have submitted this PR with our proposed content.
Please feel free to let us know if you have any questions or concerns.
Thank you for your consideration.
> Added NServiceBus's NewRelic quickstart link

- samples/logging/new-relic/sample.md
Split the existing link from the previous paragraph into a dedicated to make it more easily recognizable and repeat the link in the dashboard section.
> Make New Relic links more prominent

- README.md
This seems to be a bit outdated since most samples have been updated to use `net6.0` already. 3.1 shouldn't be required anymore, I left .NET Framework 4.8 in there for now.
Also removed the recommendation to use `.netstandard` for shared message contracts projects since this doesn't really work anymore with NServiceBus v8 since we don't target .NET Standard anymore and shared message contracts now need to use multi-targeting as well (see [existing docs](https://docs.particular.net/nservicebus/messaging/sharing-contracts#sharing-contracts-nservicebus-dependency) on this).
> Update sample target framework recommendations

- Snippets/Core/Core_7/CriticalErrors.cs
- Snippets/Core/Core_8/CriticalErrors.cs
- nservicebus/hosting/critical-errors.md
be more clear that this does never impact the host process. Also adds a snippet for the Stop method.
> Clarify CriticalErrorContext.Stop behavior

- menu/menu.yaml
- servicecontrol/audit-instances/persistence.md
- servicecontrol/how-purge-expired-data.md
- servicecontrol/persistence.md
Added the following pages:
- persistence page for SC.Audit
- Modified the page defining expiration
When we agree on the wording we should create a page describing persistence for the error instance
> Adding documentation related to raven 5 persistence for Audit

- nservicebus/messaging/send-a-message.md
- Made sections from warnings
- Indicating that using `RequireImmediateDispatch` with a regular `IMessageSession` or send-only endpoint does not have any impact
- Expanded for readability
> Improved guidance on usage of `RequireImmediateDispatch`

- nservicebus/outbox/index.md
- nservicebus/outbox/index_configuration_core_[,7].partial.md
- nservicebus/outbox/index_configuration_core_[8,).partial.md
The current documentation still states that enabling the Outbox automatically configured the transport transaction mode to `ReceiveOnly` [which is not true anymore](https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Reliability/Outbox/OutboxConfigExtensions.cs) and is also stated in the [upgrade guide](https://docs.particular.net/nservicebus/upgrades/7to8/#outbox-configuration).
> Fix note when configuring outbox on NSB v8

- nservicebus/compliance/gdpr.md
- nservicebus/compliance/index.md
The index page only lists the GDPR document but then repeats the same document with the rest of the documents in this category in the related section which looks weird:
This PR changes this to:
and also adds a little section introducing the GDPR abbreviations, similar to the FIPS document.
> Tweak compliance documentation

- README.md
This section is no longer valid as [the test was changed](https://github.com/Particular/docs.particular.net/pull/4816) from prohibiting multi-target samples to ensuring that if the `<TargetFrameworks>` (plural) element is used then more than one framework is listed. 
In the same PR a [section was added to the readme file](https://github.com/Particular/docs.particular.net#target-frameworks) stating that samples can be multi-targeted.
> Update integrity tests section

- nservicebus/hosting/azure-functions-service-bus/index.md
- nservicebus/hosting/azure-functions-service-bus/index_no-use-transport_ASBFunctions_[,4.1].partial.md
- nservicebus/hosting/azure-functions-service-bus/isolated-worker.md
- nservicebus/hosting/azure-functions-service-bus/isolated-worker_no-use-transport_ASBFunctionsWorker_[,4.1].partial.md
Calling `UseTransport` in the Azure functions host may cause the endpoint to be unable to process messages successfully. This explicitly calls it out as unsupported for the affected versions. Newer versions are able to handle `UseTransport` gracefully.
- https://github.com/Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus/pull/614
- https://github.com/Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus/issues/615
- https://github.com/Particular/NServiceBus.AzureFunctions.Worker.ServiceBus/pull/263
- https://github.com/Particular/NServiceBus.AzureFunctions.Worker.ServiceBus/issues/264
> Warn against UseTransport for ASB Functions

- samples/serializers/newtonsoft/Newtonsoft_3/Sample/Program.cs
The mutator registration is using the MS DI API which doesn't register the interface type of the mutator, causing it to not be registered and invoked correctly. The correct registration would be to use `components.AddTransient<IMutateIncomingTransportMessage, MessageBodyWriter>();` but by default, the sample should rather use the explicit mutator registration API
> Fix mutator registration for Newtonsoft sample

- servicecontrol/powershell.md
This updates the documentation for the PowerShell module to point to the PowerShell Gallery version as the primary version that should be used, but also retains some info about the legacy version that is still currently included in the installer.
> Update documentation for PowerShell Gallery version of module

- menu/menu.yaml
Instead of being very redundant with the current menu entries, e.g.
* Persistence
* SQL
* SQL Persistence
* MongoDB
* MongoDB Persistence
this changes the menu entry to just "Overview" to be more clear that this is intended to be the "intro page" for the specific persister. The titles of the pages have not been changed.
> Change persistence main page menu name

- .github/workflows/validate-pull-requests.yml
- .github/workflows/verify-master.yml
- nservicebus/sagas/message-correlation_note_core_[6,7.4).partial.md
- persistence/cosmosdb/index_glance_CosmosDB_[,1].partial.md
- persistence/cosmosdb/saga-concurrency_sagaconcurrency_CosmosDB_[,1].partial.md
- transports/azure-service-bus/configuration_subscription-rule-customization_asbs_[1.0,1.7].partial.md
As long as there is no new docstool version pushed this improves the docs tool installation process by 24-25 times.
> Cache the docs tool to speed up content verification

- servicecontrol/installation.md
The PR is to update the installation doc by  adding in a note that internet connectivity is required during the installation to facilitate the download of related packages
> Add internet requirement to ServiceControl Installation

- samples/sql-persistence/injecting-services/sample.md
- samples/sql-prereq.include.md
Docker reference was removed in a [previous editorial PR](https://github.com/Particular/docs.particular.net/commit/4c1dd273cbe1f5d69b03fbec2cca05a02931e5f4). This adds it back with slightly different language.
> Add docker sample

- servicecontrol/upgrades/zero-downtime.md
The old audit instance must be removed from the ServiceControl (Primary) instance.
> Use correct instance name in script

- samples/bridge/azure-service-bus-msmq-bridge/Bridge_1/AsbEndpoint/AsbEndpoint.csproj
- samples/bridge/azure-service-bus-msmq-bridge/Bridge_1/Shared/Shared.csproj
- samples/bridge/azure-service-bus-msmq-bridge/sample.md
remove .net core as taget framework in msmsq bridge sample
> remove .net core as taget framework in msmsq bridge sample

- Snippets/Core/Core_8.1/Core_8.1.csproj
- Snippets/Core/Core_8.1/Installers.cs
- nservicebus/operations/installers.md
- nservicebus/operations/installers_installer-api_core_[8.1,).partial.md
- persistence/upgrades/nhibernate-8to8.1.md
Adds documentation for the new installer APIs introduced via https://github.com/Particular/NServiceBus/pull/6563 in NServiceBus 8.1.
The core reference in the 8.1 csproj file is a reference to a local build since we don't have any 8.1 builds available yet.
> Documentation for new installers API

- nservicebus/throughput-tool/index.md
making tool usage descriptions the same. Instead of "arguments" use "command options" as described in other places.
> Replace arguments with command options when describing how to execute the tool

- nservicebus/outbox/index.md
Modify the chart and text to match the way the code handles the outbox where the check for deduplication happens first and begin transaction is invoked only if no entry is found.
Reference: https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Pipeline/Incoming/TransportReceiveToPhysicalMessageConnector.cs#L25
> Outbox handling of deduplication and transaction

- Snippets/MetricsServiceControl/MetricsServiceControl_3/Configuration.cs
- Snippets/MetricsServiceControl/MetricsServiceControl_4/Configuration.cs
- monitoring/metrics/install-plugin.md
- monitoring/metrics/install-plugin_interval_metricsservicecontrol_[1,).partial.md
Based on a support case
Also updated:
- https://github.com/Particular/NServiceBus.Metrics.ServiceControl/pull/454
> Using 1 minute in the SendMetricDataToServiceControl snippet with guidance to what interval to use

- servicecontrol/upgrades/3to4/index.md
Updating minor detail in the documentation for updating Service Control from version 3 to 4. The latest version of 3.x is 3.8.3 not 3.8.2.
> SC upgrade guide minor correction

- .devcontainer/devcontainer.json
Related to #6141, let's specify the port explicitly, to match the container settings. Otherwise, we're effectively spreading the knowledge of what the default port is over this repo and the docstool.
> specify docstool port in devcontainer

- Snippets/SqlPersistence/SqlPersistence_4/MsSqlServer_OutboxCleanup.sql
- Snippets/SqlPersistence/SqlPersistence_5/MsSqlServer_OutboxCleanup.sql
- Snippets/SqlPersistence/SqlPersistence_6/MsSqlServer_OutboxCleanup.sql
- Snippets/SqlPersistence/SqlPersistence_7/MsSqlServer_OutboxCleanup.sql
- nservicebus/handlers/async-handlers.md
```sql
WHILE 1 = 1
BEGIN
DELETE TOP (@BatchSize) FROM [dbo].[EndpointNameOutboxData]
WHERE Dispatched = 'true' AND DispatchedAt < @DispatchedBefore;
IF @@ROWCOUNT < @BatchSize -- Important that @@ROWCOUNT is read immediately after the DELETE
BREAK
END
```
Inspired by https://www.sqlserver-dba.com/2016/03/how-to-delete-millions-of-rows-in-batches.html
> Outbox cleanup to continue deleting batches until no old entries are left

- transports/rabbitmq/index_broker-compatibility_rabbit_[,7).partial.md
- transports/rabbitmq/index_broker-compatibility_rabbit_[7,).partial.md
It turns out that Amazon MO does not support quorum queues or streams, so we should not be saying that the RabbitMQ transport can run on it.
> Remove saying that we support Amazon MQ

- nservicebus/hosting/nservicebus-host/troubleshooting.md
This PR adds another troubleshoot section on how to resolve "Service fails to start due to reaching the timeout period"
> Add how to handle service not started to troubleshoot doc

- menu/menu.yaml
- servicecontrol/audit-instances/creating-config-file.md
- servicecontrol/audit-instances/index.md
- servicecontrol/audit-instances/installation-powershell.md
- servicecontrol/db-compaction.md
- servicecontrol/installation-powershell.md
- servicecontrol/monitoring-instances/installation/index.md
- servicecontrol/servicecontrol-instances/hardware.md
- servicecontrol/servicecontrol-instances/index.md
- servicecontrol/servicecontrol-instances/remotes.md
- servicecontrol/troubleshooting.md
- servicecontrol/upgrades/3to4/index.md
- servicecontrol/upgrades/zero-downtime.md
The terms "Primary instance",  "Main instance", and "ServiceControl Error instance" all refer to the same thing. This PR aligns the language to always use the term "ServiceControl Error instance" which is consistent with the menu headings.
NOTE: This does not completely remove the use of the term primary from the [ServiceControl remote instances](https://docs.particular.net/servicecontrol/servicecontrol-instances/remotes) page which uses the term with a different meaning.
> Switch to ServiceControl Error instance naming convention

- nservicebus/outbox/index.md
Minor wording tweaks on the outbox, with two "major" changes:
* Removed the note about sending messages in the outbox dispatch phase.
* This note was very prominently placed at the beginning of the document but touches an extreme edge case that seems to be related to extending the pipeline in very specific stages to do message dispatches. This note should be further down, probably in the `Important design considerations` section. However:
* "outbox dispatch phase" is not something that is defined or documented anywhere. Afaik, there is no dispatch stage which even allows sending messages. So I'm not even sure what this tries to say.
* Added a link to the TX session in the note about using the outbox without an incoming message as this is exactly what the tx session is designed for.
> Outbox tweaks

- nservicebus/messaging/header-manipulation.md
When changing some NServiceBus headers via SendOptions, the changes are overwritten by NServiceBus (ie this applies to CorrelationId). 
Adding a note to make the user aware that this method should be used for their own custom headers.
> Add note about changing headers via sendoptions

- nservicebus/community/index.md
- nservicebus/messaging/databus/index.md
As the [DataBusProperty](https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/DataBus/DataBusProperty.cs) does not restrict the databus property to be only a `byte[]` and there are other samples in the docs site that use other types, this PR removes that restriction.
This PR also adds in other alternatives for sending messages with large data as listed below
> Remove the DataBus  property type restriction and add other alternates for large data

- nservicebus/transactional-session/index.md
The transactional session commit operation can fail for various reasons. Users should be aware that an exception is a possible and valid outcome and that this might require additional logic in the user code to determine the appropriate reaction to such a failure. This is currently barely mentioned.
> Warn about tx session commit exceptions

- nservicebus/hosting/startup-diagnostics.md
Based on a support case where a customer was not guided to the azure function pages.
> Regular diagnostics docs do not apply to azure functions

- nservicebus/messaging/messages-events-commands.md
Having messages as interfaces have benefits, and the documentation should nudge the developer to always think of messages as interface types.
> Steer developer to use interfaces

- nservicebus/cancellation-and-catching-exceptions.md
As I stumbled upon this property I had to look up why this isn't being used and it seems this is some information that is worthwhile pointing out because it's not very self-explanatory.
btw. is there a reason this page isn't being linked from anywhere?
> Add note about OperationCanceledException.CancellationToken

- Snippets/Sqs/Sqs.sln
- Snippets/Sqs/Sqs_7/AccessToAmazonSqsNativeMessage.cs
- Snippets/Sqs/Sqs_7/Sqs_7.csproj
- Snippets/Sqs/Sqs_7/Usage.cs
- menu/menu.yaml
- transports/upgrades/amazonsqs-5to6.md
- transports/upgrades/amazonsqs-6to7.md
There is no upgrade guide for v7 and there is a breaking change that is documented [here](https://docs.particular.net/transports/sqs/configuration-options#v1-compatibility-mode), should we create one?
> Add SQS snippets for v7

- samples/netcore-reference/Core_7/BackEnd/BackEnd.csproj
- samples/netcore-reference/Core_7/BackEnd/Program.cs
- samples/netcore-reference/Core_8/BackEnd/BackEnd.csproj
- samples/netcore-reference/Core_8/BackEnd/Program.cs
- samples/netcore-reference/sample.md
Addresses 
- #6240
Since the sample uses [NServiceBus.Extensions.Hosting](https://docs.particular.net/nservicebus/hosting/extensions-hosting) there is no need to use [NServiceBus.MicrosoftLogging](https://github.com/NServiceBusExtensions/NServiceBus.MicrosoftLogging)
> Removing reference to 'NServiceBus.MicrosoftLogging' in Building endpoints with ASP.NET Core sample

- samples/aws/sagas/DynamoDB_1/Sales/serverless.template
[Using NServiceBus Sagas with AWS Lambda, SQS, and DynamoDB](https://docs.particular.net/samples/aws/sagas/) sample was not working correctly, the following error was being logged in Cloudwatch. 
`NServiceBus.Features.AutoSubscribe. Error. AutoSubscribe was unable to subscribe to an event:. Exception: System.Exception: Topic CustomerBilled not found. Call endpointConfiguration.EnableInstallers() to create the topic at startup, or create them manually`
> Fixing Lambda+DynamoDB Sagas sample

- .editorconfig
I've been noticing some inconsistent formatting recently, especially as the TF I'm on has been working on updating snippets, so I've brought over the formatting entries we have defined in our RepoStandards .`editorconfig`.
> Add formatting defined in RepoStandards .editorconfig

- tests/IntegrityTests/assembly.cs
Improves execution duration from 2.8s to 0.7s
> Run all integrity tests in parallel

- nservicebus/messaging/message-type-detection.md
- nservicebus/messaging/third-party-integration.md
Clarifying [how](https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Pipeline/Incoming/InferredMessageTypeEnricherBehavior.cs#L13C59-L13C59) NServiceBus.EnclosedMessageTypes header is automatically populated when missing. Feedback from 
- https://github.com/Particular/docs.particular.net/issues/6246
> Clarification on type inference - Receiving messages from external systems

- samples/aws/sagas/DynamoDB_1/Sales/serverless.template
Adding missing comma to cloud formation template. The sample still works even when this comma is not present.
> Updating AWS Sagas+DynamoDB sample - Adding a missing comma to cloud formation template

- samples/aws/lambda-sqs/SQSLambda_0/RegularEndpoint/Program.cs
- samples/aws/lambda-sqs/SQSLambda_0/RegularEndpoint/RegularEndpoint.csproj
The sample for NSB 7 was referencing NServiceBus.AmazonSQS 4.* instead of NServiceBus.AmazonSQS 5.*, which made it require `endpointConfiguration.UsePersistence<InMemoryPersistence>();`
> Updating Lambda SQS sample for NSB 7 to  NServiceBus.AmazonSQS 5.*

- nservicebus/upgrades/supported-platforms_content_core_[9,10).partial.md
November 10, 2026 is a guess, but it follows the pattern for the other versions, the second Tuesday of the month where support expires.
> Update supported platforms for NSB 9

- samples/web/asp-mvc-application/Core_9/AsyncPagesMVC/AsyncPagesMVC.csproj
- samples/web/asp-mvc-application/Core_9/AsyncPagesMVC/Program.cs
- samples/web/asp-web-application/Core_9/WebApp/Pages/Index.cshtml.cs
- samples/web/asp-web-application/Core_9/WebApp/Program.cs
- samples/web/asp-web-application/Core_9/WebApp/WebApp.csproj
- samples/web/blazor-server-application/Core_9/WebApp/Program.cs
- samples/web/blazor-server-application/Core_9/WebApp/WebApp.csproj
- samples/web/send-from-aspnetcore-webapi/Core_9/WebApp/Program.cs
- samples/web/send-from-aspnetcore-webapi/Core_9/WebApp/SendMessageController.cs
- samples/web/send-from-aspnetcore-webapi/Core_9/WebApp/WebApp.csproj
This gets the web samples closer to the .NET 8 templates for each of these options, and uses the new IApplicationBuilder UseNServiceBus overload in the latest NServiceBus.Extensions.Hosting version.
> Update the web samples to use the new hosting package

- samples/hosting/generic-host/Core_7/GenericHost/Program.cs
- samples/hosting/generic-host/Core_8/GenericHost/Program.cs
- samples/hosting/generic-host/sample.md
Applying the same [changes](https://github.com/Particular/docs.particular.net/pull/6247) made to ASP.NET core sample
> Removing reference to 'NServiceBus.MicrosoftLogging' in 'Endpoint hosting with the Generic Host' sample

- menu/menu.yaml
- persistence/upgrades/asp-6to7.md
Since the changes to the compatibility mode is mandatory starting in v7 and not in v6
> Rename upgrade guide for Azure Table persistence

- tutorials/quickstart/Solution/ClientUI/Properties/launchSettings.json
- Related to https://github.com/Particular/docs.particular.net/issues/6381
It looks like port 5000 on macOS might be reserved for AirPlay. On my Mac, the port is bound to the ControlCE App, and that crashes the ClientUI web project when started from the IDE.
> Update the ClientUI web server port to avoid possible conflicts on macOS

- samples/azure-functions/service-bus/sample.md
It looks like the resources created by the Azure CLI work fine for the example. If the example is modified by adding an event and the corresponding handler, it fails to create the required subscription, even if the `bundle-1` topic exists. Using the `asb-transport` CLI it works as expected.
> Use the asb-transport CLI instead of the Azure CLI

- nservicebus/licensing/index_license-management_core_[7,8).partial.md
- nservicebus/licensing/index_license-management_core_[8,].partial.md
For .net 8 there's a new LocalApplicationData location:
https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/8.0/getfolderpath-unix
This appears to change the license location for nservicebus.
> Document path for .net 8 license location

- servicecontrol/troubleshooting.md
Based on a support case. Guidance on what options there are when the database expands too much or when on a drive that is not provisioned with enough storage.
> ServiceControl troubleshooting - Low on storage

- tutorials/nservicebus-step-by-step/1-getting-started/tutorial.md
- tutorials/nservicebus-step-by-step/3-multiple-endpoints/tutorial.md
- Similar to #6457, this PR updates the step-by-step tutorials to use the .NET CLI for package management.
> Update Step by Step Tutorials to Use .NET CLI for Package Management

- transports/azure-storage-queues/transaction-support.md
- transports/upgrades/asb-9to10.md
There was a leading space on the closing `---` of these front-matter blocks that prevented them from being parsed properly.
This probably does not matter as [the code to read header info](https://github.com/Particular/DocsEngine/blob/master/src/ParticularDocsCore/YamlHeader/YamlHeaderExtractor.cs#L350-L353) trims the line.
> Removing leading space from front-matter headers

- transports/upgrades/sqlserver-6to7.md
> Fix a couple typos in SQL Server 6 to 7 migration doc

- menu/menu.yaml
- monitoring/metrics/performance-counters-install-powershell.include.md
- monitoring/metrics/performance-counters.md
- nservicebus/operations/transactions-message-processing.md
- nservicebus/upgrades/3to4.md
- nservicebus/upgrades/4to5.md
- samples/performance-counters/sample.md
- transports/msmq/index.md
- transports/msmq/management-using-powershell.md
- transports/msmq/uninstalling-msmq.md
NServiceBus.PowerShell package is for Windows-only and only has cmdlets for managing MSMQ infrastructure and Windows performance counters, and so is more at home under the MSMQ transport than as a general NServiceBus topic.
> Move Powershell page into MSMQ transport

- nservicebus/serialization/index.md
- nservicebus/serialization/index_configuring_core_[,9).partial.md
- nservicebus/serialization/index_configuring_core_[9,).partial.md
- nservicebus/upgrades/8to9/index.md
This PR adds a section to the upgrade guide about how choosing a serializer is now mandatory and also updates the relevant docs section for the change.
> Add info about mandatory serialization

- samples/logging/new-relic/Metrics_3/Endpoint/Endpoint.csproj
- samples/logging/new-relic/Metrics_4/Endpoint/Endpoint.csproj
I also bumped the version for NewRelic.Agent.Api as the previous one wasn't compatible with .net6 thru .net8
> Adds net8.0;net7.0;net6.0;net48 to New Relic samples

- samples/entity-framework/SqlPersistence_6/Endpoint.SqlPersistence/Endpoint.SqlPersistence.csproj
- samples/entity-framework/SqlPersistence_6/Messages/Messages.csproj
- samples/entity-framework/SqlPersistence_7/Endpoint.SqlPersistence/Endpoint.SqlPersistence.csproj
- samples/entity-framework/SqlPersistence_7/Messages/Messages.csproj
Adds net8, net7 and net 8 to the samples.
I also unpinned the language version to see if they still compiled, and they do.
> Update ef sql persistence sample

- nservicebus/upgrades/7to8/pipeline.md
Message mutators will still be resolved from the container in version 8
Resolves #6523
> Remove incorrect statement from guidance

- menu/menu.yaml
- Related to  https://github.com/Particular/docs.particular.net/issues/4676
In this PR 
- the NSB support policy has been moved up to its own level and the support policy of ServiceControl has moved under the "Introduction" sub menu.
> Reorder support policy left nav

- architecture/aws/observability.md
This is our first editorial review of the `observability.md` page.
There are still samples missing in this document that need to be completed.
To do (do not merge until blocking items have been addressed) :
> Editorial review of observability page

- menu/menu.yaml
- servicecontrol/queues.md
ServiceControl instances rely on a number of different queues.
This PR attempts to document all of them, along with their access requirements.
> Document ServiceControl queues

- tutorials/quickstart/tutorial-extending-the-system.md
- tutorials/quickstart/tutorial-reliability.md
Missed removing these 2 pages from the learning path in https://github.com/Particular/docs.particular.net/pull/6437
> remove all quickstart pages from learning path

- Snippets/ServicePulse/ServicePulse_All/web.config
- servicepulse/install-servicepulse-in-iis.md
With 1.38.3 release, SignalR(websockets) and AngularJS are no longer used. This PR removes everything related to these technologies.
> Updating ServicePulse IIS install instructions for 1.38.3 release

- menu/menu.yaml
This PR adds in the missing left menu link for [NServiceBus and Azure](https://docs.particular.net/nservicebus/azure/)
> add  missing left menu link for azure

- transports/azure-storage-queues/configuration.md
- transports/azure-storage-queues/configuration_config_asq_[7,8].partial.md
- transports/azure-storage-queues/configuration_config_asqn_[11,).partial.md
- transports/azure-storage-queues/configuration_config_asqn_[9,10].partial.md
The ASQ transport has a code-only mode that is already documented. That snippets currently favors the connection string approach in the snippet. Since the clients have multiple constructors, showing all of them could be confusing. I have decided to mention that they should use whatever ctor overload that makes sense for their authentication scenarios.
> Mention token credentials in ASQ

- samples/showcase/on-premises/Core_7/Store.Shared/CommonConfiguration.cs
- samples/showcase/on-premises/Core_8/Store.Shared/CommonConfiguration.cs
- samples/showcase/on-premises/Core_9/Store.Shared/CommonConfiguration.cs
Fix incorrect property encryption configuration in the showcase sample
Ref: https://docs.particular.net/nservicebus/security/property-encryption
> Fix incorrect property encryption configuration in the showcase sample

- menu/menu.yaml
- nservicebus/logging/common-logging.md
- nservicebus/logging/extensions-logging.md
- nservicebus/logging/index.md
- nservicebus/logging/log4net.md
- nservicebus/logging/nlog.md
- nservicebus/logging/usage.md
This PR adds in a note to all the logging docs by recommending the usage of Microsoft.Extension.Logging directly instead of using the following abstractions as these provide an abstraction over another abstraction
- [NServiceBus.Extensions.Logging](https://www.nuget.org/packages/NServiceBus.Extensions.Logging/) or
- [NServiceBus.Log4Net](https://www.nuget.org/packages/NServiceBus.Log4Net/) or 
- [NServiceBus.CommonLogging](https://www.nuget.org/packages/NServiceBus.CommonLogging/) 
Also, in this PR the left menu links for logging have been rearranged.
> Add a note to recommend usage of microsoft.extensions.logging directly

- nservicebus/operations/opentelemetry_content_core_[8,).partial.md
This PR adds in a recommendation to align the instance identifier between NServiceBus and OpenTelemetry so that  all logs, metrics, traces and audit messages can be correlated by the same  host (instance).
> OpenTelemetry: Align host (instance) identifier

- servicepulse/install-servicepulse-in-iis.md
Fixes #6116
- #6116
Correcting the guidance for installing ServicePulse on IIS to include installing the "Application Request Routing" module and the corresponding settings to enable
> ServicePulse with ServiceControl reverse proxy guidance improvements

- persistence/sql/index.md
Currently, the default and only concurrency mode that is supported for SQL-P is pessimistic.
There's no configuration API to switch to optimistic.
> Adjusts SQL-P at a glance - concurrency mode

- menu/menu.yaml
- persistence/cosmosdb/saga-timeouts.md
This PR added some guidance on embedding partition keys in saga timeouts, as partition information is not automatically added to the timeout message and cannot be extracted from the incoming saga timeout message.
> CosmosDB: Guidance on embedding partition keys in saga timeouts state

- samples/open-telemetry/application-insights/Core_8/Endpoint/Program.cs
- samples/open-telemetry/application-insights/Core_9/Endpoint/Program.cs
Remove reference to TelemetryConfiguration as properties to identify the endpoint are added by the NServiceBus OpenTelemetry logic.
> OpenTelemetry ApplicationInsights remove unneeded init of TelemetryConfiguration

- menu/menu.yaml
- tutorials/nservicebus-step-by-step/1-getting-started/tutorial.md
- tutorials/nservicebus-step-by-step/2-sending-a-command/tutorial.md
- tutorials/nservicebus-step-by-step/3-multiple-endpoints/tutorial.md
- tutorials/nservicebus-step-by-step/4-publishing-events/tutorial.md
- tutorials/nservicebus-step-by-step/5-retrying-errors/tutorial.md
- tutorials/nservicebus-step-by-step/index.md
I'm reviewing the Getting started section as part of my onboarding.
This PR is for changes to the Introduction to ServiceBus tutorial. 
- What is the name of the tutorial? NServiceBus Step-by-step or Introduction to NServiceBus
- The parts were called Lessons, I decided to follow the other tutorials and renamed them Parts
- There is a partial for the introduction text that is repeated on the first part, I'm tempted to remove it
- This line on part 2 confused me: 'Since the handlers in the tutorials are very simple and mostly just log information, they don't need to have the `async` keyword in the method definition. However, it's possible to add it and modify the handler to not return a `Task`'
- Part 2 takes more time to read than 15-20 minutes
- On Part 3, we could remove the note about …
> Improvements to the Step by step tutorial

- transports/msmq/delayed-delivery_content_msmqtransport_[2.0,).partial.md
- transports/upgrades/msmq-2to2.0.4.md
Includes instructions for how to update custom delayed delivery message store implementations.
NOTES:
- The SQL Delayed Delivery Message store included in the package is already updated. If using it, no further action is needed.
- If a custom delayed delivery message store is being used in an endpoint with installers enabled, it is already being initialized. No further action is needed.
> Add documentation for MSMQ 2.0.4

- .github/workflows/build-samples-and-snippets.yml
We have discovered that the time frame when we rebuild the doc site happens to coincide with the time that AWS updates their packages, which makes our pipeline fail because it is not able to find the right versions for those packages.
By updating the cron expression we will shift the time it gets trigger and ideally we will be able to prevent those transient errors.
> Update the frequency when the whole site is built

- nservicebus/scheduling/index_content_core_[8,).partial.md
- samples/scheduling/periodictimer/Core_9/PeriodicTimerScheduler.sln
- samples/scheduling/periodictimer/Core_9/Receiver/MyMessageHandler.cs
- samples/scheduling/periodictimer/Core_9/Receiver/Program.cs
- samples/scheduling/periodictimer/Core_9/Receiver/Receiver.csproj
- samples/scheduling/periodictimer/Core_9/Scheduler/Program.cs
- samples/scheduling/periodictimer/Core_9/Scheduler/Scheduler.csproj
- samples/scheduling/periodictimer/Core_9/Scheduler/SendMessageJob.cs
- samples/scheduling/periodictimer/Core_9/Shared/MyMessage.cs
- samples/scheduling/periodictimer/Core_9/Shared/Shared.csproj
- samples/scheduling/periodictimer/sample.md
Adds a sample showing how to schedule messages with a [PeriodicTimer](https://learn.microsoft.com/en-us/dotnet/api/system.threading.periodictimer).
It has been deliberately added to the top of the list of options as this is probably the preferred in a modern system.
> Add PeriodicTimer sample

- nservicebus/messaging/message-type-detection.md
It was actually [discussed a while ago already](https://github.com/Particular/docs.particular.net/pull/6169#discussion_r1284302973) and there was no clear conclusion on how this option would differ from the `FullName`. I ran into this again today, as the wording could make one think that the "name" stands for just the type's name without the namespace (as the fullname option is already mentioned explicitly before), which is not the case (would be nice though...).
> Remove ambiguous mapping rule

- .devcontainer/devcontainer.json
Unfortunately, MS latest PS update broke the devcontainers for a lot of people!
This is a workaround for now.
See https://github.com/PowerShell/PowerShell/issues/23975
> Fix for devcontainer

- samples/scheduling/hangfire/Core_7/Scheduler/Program.cs
- samples/scheduling/hangfire/Core_8/Scheduler/Program.cs
- samples/scheduling/hangfire/Core_9/Scheduler/Program.cs
- samples/scheduling/hangfire/sample.md
- samples/scheduling/scheduler-drawbacks.include.md
remove references to timeout manager for versions where it is no longer supported and msmq
> docs review of hangfire sample

- transports/sqs/index.md
- transports/sqs/index_sns-permissions_sqs_[5,).partial.md
Improving documentation based on feedback given on our support case
> Add missing permissions on AmazonSQS Transport

- transports/rabbitmq/index_broker-compatibility_rabbit_[7,).partial.md
Amazon MQ now supports quorum queues. See https://aws.amazon.com/about-aws/whats-new/2024/07/amazon-mq-quorum-queues-rabbitmq-3-13/
> Update compatibility information for RabbitMQ transport

- Snippets/MsmqTransport/MsmqTransport_2/SqlStore/DelayedMessageStore.cs
- Snippets/MsmqTransport/MsmqTransport_2/SqlStore/SqlConstants.cs
- Snippets/MsmqTransport/MsmqTransport_2/SqlStore/SqlNameHelper.cs
- Snippets/MsmqTransport/MsmqTransport_2/SqlStore/TimeoutTableCreator.cs
- transports/msmq/delayed-delivery_content_msmqtransport_[2.0,).partial.md
Since `SqlServerDelayedMessageStore` only exists on the 2.0 release branch of the MSMQ transport, and not on master, it is not easily found by people trying to implement custom stores. This change adds the logic from `SqlServerDelayedMessageStore` to the delayed messages documentation for visibility
> include SqlServer message store methods in documentation

- nservicebus/messaging/messages-as-interfaces.md
- nservicebus/messaging/messages-events-commands.md
This PR improves the message contract guidance by:
- De-emphasizing the importance of interface as messages since they require complicated runtime type generation and are rarely ever beneficial
- Remove the hint to apply "inheritance" and hints at messages should rather be straightforward "flat" types, and it is perfectly fine to relax a bit the object-oriented thinking there because then you get contracts that are way easier to evolve.
> Message Contract Guidance Improvements

- samples/databus/blob-storage-databus-cleanup-function/ABSDataBus_5/DataBusBlobCleanupFunctions/DataBusBlobCleanupFunctions.csproj
Prevents nuget error as a version 1.19.0 of Microsoft.Azure.Functions.Worker.Core does not exist on nuget yet
> Use lower version of Microsoft.Azure.Functions.Worker.ApplicationInsights

- menu/menu.yaml
- nservicebus/upgrades/azure-functions-service-bus-in-process-isolated-worker.md
- This PR is to address the #6781 by providing a migration guide for Azure functions isolated worker host model from an in-process model
> Add migration guide for Azure functions in-process to isolated worker host model

- nservicebus/transactional-session/index.md
This mentions the improvements done in 3.2.0 without being version-specific. I have decided against updating the already complex sequence diagram with conditionals since it would pretty much make that one unreadable
Should be squashed.
> Transactional Session: Skip 7 and 8 when there are no outgoing operations

- tutorials/nservicebus-step-by-step/1-getting-started/Solution/ClientUI/ClientUI.csproj
- tutorials/nservicebus-step-by-step/2-sending-a-command/Solution/ClientUI/ClientUI.csproj
- tutorials/nservicebus-step-by-step/2-sending-a-command/Solution/Messages/Messages.csproj
- tutorials/nservicebus-step-by-step/3-multiple-endpoints/Solution/ClientUI/ClientUI.csproj
- tutorials/nservicebus-step-by-step/3-multiple-endpoints/Solution/Sales.Messages/Sales.Messages.csproj
- tutorials/nservicebus-step-by-step/3-multiple-endpoints/Solution/Sales/Sales.csproj
- tutorials/nservicebus-step-by-step/4-publishing-events/Solution/Billing.Messages/Billing.Messages.csproj
- tutorials/nservicebus-step-by-step/4-publishing-events/Solution/Billing/Billing.csproj
- tutorials/nservicebus-step-by-step/4-publishing-events/Solution/ClientUI/ClientUI.csproj
- tutorials/nservicebus-step-by-step/4-publishing-events/Solution/Sales.Messages/Sales.Messages.csproj
- tutorials/nservicebus-step-by-step/4-publishing-events/Solution/Sales/Sales.csproj
- tutorials/nservicebus-step-by-step/4-publishing-events/Solution/Shipping/Shipping.csproj
- tutorials/nservicebus-step-by-step/5-retrying-errors/Solution/Billing.Messages/Billing.Messages.csproj
- tutorials/nservicebus-step-by-step/5-retrying-errors/Solution/Billing/Billing.csproj
- tutorials/nservicebus-step-by-step/5-retrying-errors/Solution/ClientUI/ClientUI.csproj
- tutorials/nservicebus-step-by-step/5-retrying-errors/Solution/Sales.Messages/Sales.Messages.csproj
- tutorials/nservicebus-step-by-step/5-retrying-errors/Solution/Sales/Sales.csproj
- tutorials/nservicebus-step-by-step/5-retrying-errors/Solution/Shipping/Shipping.csproj
As a part of this [issue](https://github.com/Particular/DeveloperEducation/issues/4954)
All step-by-step tutorials have been upgraded to NServiceBus v9 and dotnet 8
> Update step by step tutorial to NServiceBus 9 and dotnet 8.0

- samples/pipeline/masstransit-messages/Core_7/MTEndpoint/MTEndpoint.csproj
- samples/pipeline/masstransit-messages/Core_7/Messages/Messages.csproj
- samples/pipeline/masstransit-messages/Core_7/NServiceBusSubscriber/NServiceBusSubscriber.csproj
- samples/pipeline/masstransit-messages/Core_8/NServiceBusSubscriber/Program.cs
- samples/pipeline/masstransit-messages/Core_9/NServiceBusSubscriber/Program.cs
- samples/pipeline/masstransit-messages/sample.md
- Add .NET Framework 4.8 sample to NSB 7 samples
- Use Quorum queues in NSB 8 and NSB 9 samples to prevent errors if using an instance of rabbitMQ with an error queue configured with type Quorum (ServiceControl will configure the error queue as Qurum). 
- _'The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=406, text='PRECONDITION_FAILED - inequivalent arg 'x-queue-type' for queue 'error' in vhost '/': received none but current is the value 'quorum' of type 'longstr'', classId=50, methodId=10'_
> Masstransit messages sample doco review

- Snippets/PostgreSqlTransport/PostgreSqlTransport_8/MultiSchema.cs
- Snippets/PostgreSqlTransport/PostgreSqlTransport_8/PostgreSqlTransport_8.csproj
- servicecontrol/monitoring-instances/configuration.md
- servicecontrol/servicecontrol-instances/configuration.md
- servicecontrol/transports.md
- servicepulse/usage-config.md
- transports/index.md
- transports/postgresql/addressing.md
Part of https://github.com/Particular/ServiceControl/issues/4254
> Add information about Postgres for SC

- samples/hosting/docker/Core_7/Receiver/Receiver.csproj
- samples/hosting/docker/Core_7/Sender/Sender.csproj
- samples/hosting/docker/Core_7/docker-compose.yml
- samples/hosting/docker/Core_8/Receiver/Receiver.csproj
- samples/hosting/docker/Core_8/Sender/Sender.csproj
- samples/hosting/docker/Core_8/docker-compose.yml
- samples/hosting/docker/Core_9/Receiver/Receiver.csproj
- samples/hosting/docker/Core_9/Sender/Sender.csproj
- samples/hosting/docker/Core_9/docker-compose.yml
- samples/hosting/docker/sample.md
Addressing feedback 
- https://github.com/Particular/docs.particular.net/issues/6848
Changes:
- removing version attribute from docker-compose files - no longer required
- adding prerequisites section 
- removing explicit package reference (Microsoft.Net.Build.Containers) since it is now included in the SDK
- adding required attribute to projects now that an explicit reference to the package is not required
> Updating hosting docker sample

- monitoring/custom-checks/index.md
- nservicebus/recoverability/pipeline.md
- persistence/nhibernate/accessing-data.md
- persistence/nhibernate/accessing-data_direct-access_nhibernate_[8.4,9).partial.md
- persistence/nhibernate/accessing-data_direct-access_nhibernate_[9,).partial.md
- transports/msmq/troubleshooting.md
part of https://github.com/Particular/GeneralPlatformExperience/issues/3320
> Docs  review

- samples/pipeline/masstransit-messages/sample.md
This links the integration docs to the corresponding MassTransit docs.
It is a corresponding PR to https://github.com/MassTransit/MassTransit/pull/5606 to make sure that both integration angles connect to each other.
> Link to masstransit integration docs

- transports/types.md
- tutorials/nservicebus-step-by-step/1-getting-started/Snippets/Core_9/Lesson1.cs
- tutorials/nservicebus-step-by-step/1-getting-started/Solution/ClientUI/Program.cs
- tutorials/nservicebus-step-by-step/1-getting-started/tutorial.md
- tutorials/nservicebus-step-by-step/2-sending-a-command/Snippets/Core_9/Exercise.cs
- tutorials/nservicebus-step-by-step/2-sending-a-command/Solution/ClientUI/InputLoopService.cs
- tutorials/nservicebus-step-by-step/2-sending-a-command/Solution/ClientUI/Program.cs
- tutorials/nservicebus-step-by-step/2-sending-a-command/tutorial.md
- tutorials/nservicebus-step-by-step/3-multiple-endpoints/Snippets/Core_9/Lesson3.cs
- tutorials/nservicebus-step-by-step/3-multiple-endpoints/Solution/ClientUI/InputLoopService.cs
- tutorials/nservicebus-step-by-step/3-multiple-endpoints/Solution/ClientUI/Program.cs
- tutorials/nservicebus-step-by-step/3-multiple-endpoints/Solution/Sales/Program.cs
- tutorials/nservicebus-step-by-step/3-multiple-endpoints/tutorial.md
- tutorials/nservicebus-step-by-step/4-publishing-events/Solution/Billing/Program.cs
- tutorials/nservicebus-step-by-step/4-publishing-events/Solution/ClientUI/InputLoopService.cs
- tutorials/nservicebus-step-by-step/4-publishing-events/Solution/ClientUI/Program.cs
- tutorials/nservicebus-step-by-step/4-publishing-events/Solution/Sales/Program.cs
- tutorials/nservicebus-step-by-step/4-publishing-events/Solution/Shipping/Program.cs
- tutorials/nservicebus-step-by-step/4-publishing-events/tutorial.md
- tutorials/nservicebus-step-by-step/5-retrying-errors/Snippets/Core_9/PlaceOrderHandler.cs
- tutorials/nservicebus-step-by-step/5-retrying-errors/Solution/Billing/Program.cs
- tutorials/nservicebus-step-by-step/5-retrying-errors/Solution/ClientUI/InputLoopService.cs
- tutorials/nservicebus-step-by-step/5-retrying-errors/Solution/ClientUI/Program.cs
- tutorials/nservicebus-step-by-step/5-retrying-errors/Solution/Sales/PlaceOrderHandler.cs
- tutorials/nservicebus-step-by-step/5-retrying-errors/Solution/Sales/Program.cs
- tutorials/nservicebus-step-by-step/5-retrying-errors/Solution/Shipping/Program.cs
- tutorials/nservicebus-step-by-step/5-retrying-errors/tutorial.md
As part of preparing to run the 2-day NSB course, I went through the tutorials and found some things to clean up.
All solutions have been smoke-tested
I will make corresponding changes to https://github.com/Particular/Workshop.NServiceBus
Related cleanup of the saga tutorial https://github.com/Particular/docs.particular.net/pull/6898
> NServiceBus step by step tutorial cleanup

- servicecontrol/logging.md
This PR removes the logging wording related to long unsupported versions of ServiceControl.
> Remove outdated version information for SC logging

- nservicebus/upgrades/release-policy.md
This PR documents that undocumented APIs are unsupported and deviate from SemVer. Public unsupported APIs are also identified by the [`Experimental` attribute](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-12.0/experimental-attribute) to allow compilers to report the unsupported nature of the referenced member.
> Document public unsupported APIs

- nservicebus/usage/index.md
(Proposed new version)
**While customers are not currently required to use ServicePulse, starting 1 January 2026, it will become mandatory for all projects in active development. If you have any issues installing ServicePulse in your environment, please reach out so we can help find a path forward.**
> updated the comment regarding mandatory service pulse usage

- nservicebus/bridge/configuration_failed-messages_bridge_[4,).partial.md
Add a note to warn users that not translating replyTo addresses can cause shoveling errors.
> Add note about DoNotTranslateReplyToAddressForFailedMessages

- samples/sql-persistence/injecting-services/SqlPersistence_7/Endpoint/Program.cs
- samples/sql-persistence/injecting-services/SqlPersistence_8/Endpoint/Program.cs
- samples/sql-persistence/saga-rename/SqlPersistence_7/Shared/SharedConfiguration.cs
- samples/sql-persistence/saga-rename/SqlPersistence_8/Shared/SharedConfiguration.cs
- samples/sql-persistence/simple/SqlPersistence_7/EndpointMySql/Program.cs
- samples/sql-persistence/simple/SqlPersistence_7/EndpointOracle/Program.cs
- samples/sql-persistence/simple/SqlPersistence_7/EndpointPostgreSql/Program.cs
- samples/sql-persistence/simple/SqlPersistence_7/EndpointSqlServer/Program.cs
- samples/sql-persistence/simple/SqlPersistence_8/EndpointMySql/Program.cs
- samples/sql-persistence/simple/SqlPersistence_8/EndpointOracle/Program.cs
- samples/sql-persistence/simple/SqlPersistence_8/EndpointPostgreSql/Program.cs
- samples/sql-persistence/simple/SqlPersistence_8/EndpointSqlServer/Program.cs
- samples/sql-persistence/simple/sample.md
- samples/sql-persistence/sqlpersistence-prereqs.include.md
- samples/sql-persistence/transitioning-correlation-ids/SqlPersistence_7/Phase1/EndpointMySql/Program.cs
- samples/sql-persistence/transitioning-correlation-ids/SqlPersistence_7/Phase1/EndpointOracle/Program.cs
- samples/sql-persistence/transitioning-correlation-ids/SqlPersistence_7/Phase1/EndpointPostgreSql/Program.cs
- samples/sql-persistence/transitioning-correlation-ids/SqlPersistence_7/Phase1/EndpointSqlServer/Program.cs
- samples/sql-persistence/transitioning-correlation-ids/SqlPersistence_8/Phase1/EndpointMySql/Program.cs
- samples/sql-persistence/transitioning-correlation-ids/SqlPersistence_8/Phase1/EndpointOracle/Program.cs
- samples/sql-persistence/transitioning-correlation-ids/SqlPersistence_8/Phase1/EndpointPostgreSql/Program.cs
- samples/sql-persistence/transitioning-correlation-ids/SqlPersistence_8/Phase1/EndpointSqlServer/Program.cs
This pull request updates the SQL persistence configuration for various database types by removing the dependency on environment variables for credentials and instead hard-coding the connection strings. Additionally, it updates documentation to reflect these changes and provides Docker commands for setting up database instances.
> Simplify postgresql samples

- .github/workflows/build-samples-and-snippets.yml
- .github/workflows/validate-pull-requests.yml
- samples/hosting/aspire/Core_9/AspireDemo.AppHost/AspireDemo.AppHost.csproj
- samples/hosting/aspire/Core_9/AspireDemo.AppHost/Program.cs
- samples/hosting/aspire/Core_9/AspireDemo.ServiceDefaults/AspireDemo.ServiceDefaults.csproj
- samples/hosting/aspire/Core_9/AspireDemo.ServiceDefaults/Extensions.cs
- samples/hosting/aspire/Core_9/Billing/Billing.csproj
- samples/hosting/aspire/Core_9/ClientUI/ClientUI.csproj
- samples/hosting/aspire/Core_9/Messages/Messages.csproj
- samples/hosting/aspire/Core_9/Sales/Sales.csproj
- samples/hosting/aspire/Core_9/Shipping/Shipping.csproj
- samples/hosting/aspire/sample.md
This PR updates the Aspire sample to 9, which no longer uses the SDK workload feature.
> Aspire fixes

- menu/menu.yaml
It seems the following PR broken the menu item for raw messaging:
- https://github.com/Particular/docs.particular.net/pull/6533
> Fix indentation for raw messaging meny item

- Snippets/TransactionalSession/TransactionalSession_3/Api.cs
- nservicebus/transactional-session/index.md
- nservicebus/transactional-session/index_config_transactionalsession_[,3.1).partial.md
It looks like the auto-numbering behavior of Mermaid changed at some point which altered the table.
There is a lot of magic between markdown auto-numbers the ordered list and the diagram deciding number. I wonder if we should find a better way to correlate these two things.
> Review transactional session

- persistence/ravendb/index.md
In the past we have a nice table:
- https://github.com/Particular/docs.particular.net/commit/4a744f63d3c51135fd47416c6651f41229837b0e
Somewhere that got removed...
Maybe we should restore that and include RavenDB Server:
NServiceBus.RavenDB 9.0 uses RavenDB.Client v5.4.116.* which is compatible with RavenDB Server 5.4, 6.0, 6.1.x, 6.2.x, 7.0.x, and future newer versions of RavenDB Server
| NServiceBus | RavenDB Persistence | RavenDB Client | RavenDB Server|
|:-----------:|:-------------------:|:--------------:|:--------------:|
|     9.x     |        9.0.x        |       5.4      | 5.4, 6.x, 7.x |
|     8.x     |        ?        |       ?     | ?
|     7.x     |        ?        |       ?      |?
> Added example about compatibility with RavenDB Server versions

- Snippets/Core/Core_7/HandlerOrdering.cs
- Snippets/Core/Core_8/HandlerOrdering.cs
- Snippets/Core/Core_9/HandlerOrdering.cs
- nservicebus/handlers/handler-ordering.md
- persistence/sql/subscriptions.md
- persistence/sql/subscriptions_connection_sqlpersistence_[4,).partial.md
- samples/dependency-injection/extensions-dependency-injection/sample.md
Part of https://github.com/Particular/GeneralPlatformExperience/issues/3443
Removed `HandlerOrderingWithCode` snippet as it is a duplicate of `HandlerOrderingWithMultiple` and two the same code snippets were being displayed on the page.
> Docs Review

- tutorials/nservicebus-sagas/2-timeouts/Snippets/Core_9/BuyersRemorsePolicyMapping/BuyersRemorsePolicyMapping.cs
- tutorials/nservicebus-sagas/2-timeouts/Snippets/Core_9/EmptyBuyersRemorsePolicy/EmptyBuyersRemorsePolicy.cs
If code suppressions appear within the snippet region, they will be included in the docs. In most cases, such as with saga timeouts, the doc reads better without suppressions in the snippets.
You can review the existing behaviour here; https://docs.particular.net/tutorials/nservicebus-sagas/2-timeouts/#exercise-buyersremorsepolicy-saga.
> Move suppression to outside of snippet region (keep docs clean)

- Snippets/SqlPersistence/SqlPersistence_8/MySql_OutboxCreate.sql
Derek Comartin pointed out in an email that:
The MySQL Outbox Create Table SQL produces an error in MySQL8.
[](https://docs.particular.net/persistence/sql/mysql-scripts)
Running the code manually in MySQL produces the error when: prepare script from @createTable;
Error Code: 1064. You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NULL' at line 1
However, in code, the MySqlException is
(0x80004005): Parameter '@tableNameQuoted' must be defined
Tried it locally, and this is the fix I came up with.
> fix for running the script

- tutorials/quickstart/tutorial.md
The current "promise" covers topics that are only dealt with in subsequent pages. As far as developers know when reading this text at the top of the page, the "one hour" promise is "monolithic" and covers the whole page - which might turn them away (as they might not have an hour to devote to it right then).
Making a smaller and more specific promise for just the first page is probably better.
> Update the "opening promise" of the quickstart

- tutorials/nservicebus-step-by-step/3-multiple-endpoints/tutorial.md
This pull request correct mistakes within the **NServiceBus Step-by-step** | **Multiple Endpoints** | [**Sending to another endpoint**](https://docs.particular.net/tutorials/nservicebus-step-by-step/3-multiple-endpoints/#exercise-sending-to-another-endpoint) section.
> Fix incorrect references to files / variable names

- nservicebus/messaging/claimcheck/index.md
This PR addresses https://github.com/Particular/docs.particular.net/issues/7017. Documentation was still using outdated `DataBusProperty<T>` instead of the new `ClaimCheckProperty<T>`.
> Update claimcheck documentation

- nservicebus/upgrades/support-policy.md
The existing statement about wire compatibility is too broad, so we should remove it for now.
It will be replaced with a more complete wire compatibility policy at a later date.
> Remove reference to wire compatibility

- transports/azure-service-bus/topology.md
- transports/azure-service-bus/topology_description_asbs_[5,).partial.md
Fixed Typo in Azure Service Bus Topology v5 docs
> Fix a grammar error/typo

- servicecontrol/upgrades/6.4to6.5.md
- transports/rabbitmq/connection-settings.md
There are some edge cases around the use of amqp connection strings, so let's call that out in the upgrade guide.
> Add amqp connection string info  to upgrade guide

- servicecontrol/audit-instances/configuration.md
Docs update for:
- https://github.com/Particular/ServiceControl/pull/4858
> Document `ServiceControl.Audit/IngestAuditMessages`

- nservicebus/logging/nlog.md
- nservicebus/logging/nlog_obsolete-warning_NLog_[3,).partial.md
> Moved the NServiceBus.NLog obsolete warning

- transports/azure-service-bus/topology_description_asbs_[5,).partial.md
Closes #7052 
There might be some overlap with https://github.com/Particular/docs.particular.net/pull/7055 and some existing content, but I think that would be fine. We can always do another pass on the documentation to consolidate it a bit.
We used inline snippets here because it felt like overkill to have those snippets
> Multiplexing with the Azure Service Bus topology

- transports/rabbitmq/index.md
- transports/rabbitmq/index_broker-compatibility_rabbit_[,7).partial.md
- transports/rabbitmq/index_broker-compatibility_rabbit_[10,).partial.md
- transports/rabbitmq/index_broker-compatibility_rabbit_[7,10).partial.md
Amazon reached out to confirm that despite their documentation implying otherwise (which they've said they're going to work on clarifying), Amazon MQ does work with our transport, so I've updated the index page to reflect that.
> Update hosted broker options to include Amazon MQ

- tutorials/quickstart/Snippets/Core_9/Messages/OrderPlaces.cs
- tutorials/quickstart/Snippets/Core_9/OrderPlacedHandler.cs
- tutorials/quickstart/Snippets/Core_9/ShippingProgram.cs
Slight improvement of https://github.com/Particular/docs.particular.net/pull/7075 further reducing indentation by not using namespace in a scope and wrap hostbuilder methods on a new line.
> Using `namespace` without scope to remove indentation for quickstart snippets

- transports/sqs/native-integration.md
- transports/sqs/native-integration_native-message-attributes-promotion_sqs_[7.3,).partial.md
- depends on https://github.com/Particular/NServiceBus.AmazonSQS/pull/2774
> [SQS] Document how native message attributes are promoted to NServiceBus headers

- Directory.Build.props
This would allow us to detect transitive CVE issues in sample dependencies.
> Set  NuGetAuditMode to all by default

- nservicebus/licensing/index_license-management_core_[7,8).partial.md
- nservicebus/licensing/index_license-management_core_[8,].partial.md
- nservicebus/upgrades/7to8/index.md
NServiceBus 8 removed the Registry as a license source location, but the docs weren't updated to reflect that.
This PR fixes that and also updates the upgrade guide to make it clear that it was removed.
> Update docs to remove Registry license location for NSB 8+

- tutorials/quickstart/tutorial-extending-the-system.md
The code snippet accepts the logger as a parameter. The code description wasn't aligned with the snippet
> Update code description to match the snippet

- tutorials/nservicebus-step-by-step/2-sending-a-command/tutorial.md
Fixing a typo in InputLoopService name
> Fixing a typo in InputLoopService

- transports/sqs/topology.md
- transports/sqs/topology_pub-sub_sqs_[5,).partial.md
This documentation attempts to make explicit how the transport uses SNS topics, subscriptions, and SQS queues.
> Update SQS topology documentation

- Snippets/SqlTransport/SqlTransport_All/Operations/QueueCreation/QueueCreation.ps1
Relates to https://github.com/Particular/docs.particular.net/issues/7186
Update the PowerShell scripts to create nonclustered indexes and align the script with the [C# code for queue creation](https://docs.particular.net/transports/sql/operations-scripting#create-queues-the-create-queue-helper-methods-in-c).
> Update create-queues-powershell snippet to create nonclustered index

- nservicebus/messaging/headers.md
Added a partial class to support version-specific rendering of the Timestamp format block. This resolves incorrect references to the non-existent DateTimeExtensions helper.
Reference : https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/DateTimeOffsetHelper.cs
> Fix Timestamp format block in headers based on version 

- nservicebus/messaging/headers.md
- Issue - https://github.com/Particular/docs.particular.net/issues/7193
Added a partial class to support version-specific rendering of the Timestamp format block. This resolves incorrect references to the non-existent DateTimeExtensions helper.
Reference : https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/DateTimeOffsetHelper.cs
> Fix Timestamp format block in headers based on version

- platform/throughput-report/index.md
- servicecontrol/servicecontrol-instances/deployment/platform-container-examples.include.md
With the introduction of Helm charts as part of https://github.com/Particular/PlatformContainerExamples/pull/18, this PR updates the docs to mention it instead of the kubernetes example.
> Update docs to refer to helm chart example

- nservicebus/upgrades/index.md
Introduce guidance on handling deprecated APIs during major NServiceBus upgrades, emphasizing the importance of addressing compile-time warnings and following upgrade guides for a smooth transition.
> Add section on public API deprecation for major NServiceBus upgrades

- samples/aws/dynamodb-simple/DynamoDB_2/Client/OrderCompletedHandler.cs
- samples/aws/dynamodb-simple/DynamoDB_2/Server/OrderSaga.cs
- samples/aws/dynamodb-simple/DynamoDB_2/Server/ShipOrderHandler.cs
- samples/aws/dynamodb-simple/DynamoDB_3/Client/OrderCompletedHandler.cs
- samples/aws/dynamodb-simple/DynamoDB_3/Server/OrderSaga.cs
- samples/aws/dynamodb-simple/DynamoDB_3/Server/ShipOrderHandler.cs
- samples/aws/dynamodb-transactions/DynamoDB_2/Client/OrderCompletedHandler.cs
- samples/aws/dynamodb-transactions/DynamoDB_2/Server/OrderSaga.cs
- samples/aws/dynamodb-transactions/DynamoDB_2/Server/ShipOrderHandler.cs
- samples/aws/dynamodb-transactions/DynamoDB_3/Client/OrderCompletedHandler.cs
- samples/aws/dynamodb-transactions/DynamoDB_3/Server/OrderSaga.cs
- samples/aws/dynamodb-transactions/DynamoDB_3/Server/ShipOrderHandler.cs
- samples/aws/lambda-sqs/SQSLambda_2/RegularEndpoint/ResponseMessageHandler.cs
- samples/aws/lambda-sqs/SQSLambda_2/ServerlessEndpoint/TriggerMessageHandler.cs
- samples/aws/lambda-sqs/SQSLambda_3/RegularEndpoint/ResponseMessageHandler.cs
- samples/aws/lambda-sqs/SQSLambda_3/ServerlessEndpoint/TriggerMessageHandler.cs
- samples/aws/sagas-lambda-aurora/SQSLambda_2/ClientUI/OrderDelayedHandler.cs
- samples/aws/sagas-lambda-aurora/SQSLambda_2/ClientUI/OrderShippedHandler.cs
- samples/aws/sagas-lambda-aurora/SQSLambda_2/Sales/BillCustomerHandler.cs
- samples/aws/sagas-lambda-aurora/SQSLambda_2/Sales/OrderSaga.cs
- samples/aws/sagas-lambda-aurora/SQSLambda_2/Sales/StageInventoryHandler.cs
- samples/aws/sqs-native-integration/Sqs_7/Receiver/AccessToAmazonSqsNativeMessageBehavior.cs
- samples/aws/sqs-native-integration/Sqs_7/Receiver/SomeNativeMessageHandler.cs
- samples/aws/sqs-native-integration/Sqs_8/Receiver/AccessToAmazonSqsNativeMessageBehavior.cs
- samples/aws/sqs-native-integration/Sqs_8/Receiver/SomeNativeMessageHandler.cs
- samples/aws/sqs-simple/Sqs_7/Receiver/MyCommandHandler.cs
- samples/aws/sqs-simple/Sqs_7/Receiver/MyEventHandler.cs
- samples/aws/sqs-simple/Sqs_8/Receiver/MyCommandHandler.cs
- samples/aws/sqs-simple/Sqs_8/Receiver/MyEventHandler.cs
Part of
https://github.com/Particular/GeneralPlatformExperience/issues/3482
Updated all logger.LogInformation and similar calls in the AWS samples to use structured logging message templates and named parameters.
No functional changes
> Refactor logger calls in aws samples to use structured logging

- samples/bridge/service-control/TransportBridge_1/Endpoint/MyMessageHandler.cs
- samples/bridge/simple/Bridge_3/LeftReceiver/OrderReceivedHandler.cs
- samples/bridge/simple/Bridge_3/RightReceiver/OrderReceivedHandler.cs
- samples/bridge/simple/Bridge_3/RightReceiver/PlaceOrderHandler.cs
- samples/bridge/simple/TransportBridge_1/LeftReceiver/OrderReceivedHandler.cs
- samples/bridge/simple/TransportBridge_1/LeftSender/OrderResponseHandler.cs
- samples/bridge/simple/TransportBridge_1/RightReceiver/OrderReceivedHandler.cs
- samples/bridge/simple/TransportBridge_1/RightReceiver/PlaceOrderHandler.cs
- samples/bridge/sql-multi-instance/TransportBridge_1/Receiver/OrderHandler.cs
- samples/bridge/sql-multi-instance/TransportBridge_1/Sender/ClientOrderResponseHandler.cs
- samples/bridge/sql-multi-instance/sample.md
Part of
https://github.com/Particular/GeneralPlatformExperience/issues/3482
Updated all logger.LogInformation and similar calls in the bridge samples to use structured logging message templates and named parameters.
No functional changes
> Refactor logger calls in bridge samples to use structured logging

- nservicebus/messaging/claimcheck/index.md
This update clarifies in the DataBus documentation that, in addition to byte[], any data type is supported as long as it is serializable. This addresses feedback from issue [Feedback: 'NServiceBus DataBus feature' #7233
](https://github.com/Particular/docs.particular.net/issues/7233) and helps users understand that they can use types such as string, custom classes, or other serializable types as DataBus properties.
> Clarify that DataBus supports any serializable type, not just byte arrays

- samples/entity-framework/sample.md
Minor Updates:
- Add Entity Framework 6 and .NET Framework 4 support warnings
- Link to [Entity Framework Core](https://docs.particular.net/samples/entity-framework-core/) example.
- Clarify a few steps.
- Update `reviewed` date
> NCS Documentation Update - Entity Framework

- samples/hosting/aspire/Core_10/AspireDemo.AppHost/AspireDemo.AppHost.csproj
- samples/hosting/aspire/Core_10/AspireDemo.AppHost/ExtensionMethods.cs
- samples/hosting/aspire/Core_10/AspireDemo.AppHost/Program.cs
- samples/hosting/aspire/Core_10/AspireDemo.AppHost/Properties/launchSettings.json
- samples/hosting/aspire/Core_10/AspireDemo.AppHost/appsettings.Development.json
- samples/hosting/aspire/Core_10/AspireDemo.AppHost/appsettings.json
- samples/hosting/aspire/Core_10/AspireDemo.ServiceDefaults/AspireDemo.ServiceDefaults.csproj
- samples/hosting/aspire/Core_10/AspireDemo.ServiceDefaults/Extensions.cs
- samples/hosting/aspire/Core_10/AspireDemo.sln
- samples/hosting/aspire/Core_10/Billing/Billing.csproj
- samples/hosting/aspire/Core_10/Billing/OrderPlacedHandler.cs
- samples/hosting/aspire/Core_10/Billing/Program.cs
- samples/hosting/aspire/Core_10/ClientUI/ClientUI.csproj
- samples/hosting/aspire/Core_10/ClientUI/MessageSenderService.cs
- samples/hosting/aspire/Core_10/ClientUI/Program.cs
- samples/hosting/aspire/Core_10/Messages/Messages.csproj
- samples/hosting/aspire/Core_10/Messages/OrderBilled.cs
- samples/hosting/aspire/Core_10/Messages/OrderPlaced.cs
- samples/hosting/aspire/Core_10/Messages/PlaceOrder.cs
- samples/hosting/aspire/Core_10/Messages/ShipOrder.cs
- samples/hosting/aspire/Core_10/Sales/PlaceOrderHandler.cs
- samples/hosting/aspire/Core_10/Sales/Program.cs
- samples/hosting/aspire/Core_10/Sales/Sales.csproj
- samples/hosting/aspire/Core_10/Shipping/Program.cs
- samples/hosting/aspire/Core_10/Shipping/ShipOrderHandler.cs
- samples/hosting/aspire/Core_10/Shipping/Shipping.csproj
- samples/hosting/aspire/Core_10/Shipping/ShippingPolicy.cs
- samples/hosting/aspire/Core_10/Shipping/ShippingPolicyData.cs
- samples/hosting/aspire/Core_9/AspireDemo.AppHost/ExtensionMethods.cs
- samples/hosting/aspire/Core_9/AspireDemo.AppHost/Program.cs
- fixes #7314 
* Updated the NET9 project because the ServiceControlMonitor does not accept the amqp:// format connection string.
* Copied the `Core_9` sample to `Core_10`
* Updated csproj files
* TargetFrameworks: NET10.0
* LangVersion: preview
* NServiceBus.* dependencies updated to `alpha.1`.
> Aspire sample net10

- samples/databus/file-share-databus/DataBus_2/Receiver/MessageWithLargePayloadHandler.cs
- samples/databus/file-share-databus/DataBus_2/Receiver/Program.cs
- samples/databus/file-share-databus/DataBus_2/Receiver/Receiver.csproj
Amend to #7512
Update file-share-databus sample to add MS extension hosting in the receiver endpoint. In order to add back usage of structured logging in the message handler, just like DataBus_1.
> Update file-share-databus sample to add MS extension hosting in the receiver endpoint

- samples/dependency-injection/externally-managed-mode/Core_10/ExternallyManagedContainer.sln
- samples/dependency-injection/externally-managed-mode/Core_10/Sample/Greeter.cs
- samples/dependency-injection/externally-managed-mode/Core_10/Sample/MessageSender.cs
- samples/dependency-injection/externally-managed-mode/Core_10/Sample/MyHandler.cs
- samples/dependency-injection/externally-managed-mode/Core_10/Sample/MyMessage.cs
- samples/dependency-injection/externally-managed-mode/Core_10/Sample/Program.cs
- samples/dependency-injection/externally-managed-mode/Core_10/Sample/Sample.csproj
Implement 
- https://github.com/Particular/docs.particular.net/issues/7298
This adds a new Core_10 sample demonstrating external dependency injection container integration with NServiceBus 10 using modern C# features.
Key features:
- .NET 10 targeting with preview features enabled
- NServiceBus 10.0.0-alpha.1 integration
- Microsoft.Extensions.DependencyInjection container
- EndpointWithExternallyManagedContainer.Create API usage
- Modern C# 12+ language features:
* Primary constructors for clean dependency injection
* Record types for immutable messages
* Top-level program structure
* Target-typed new expressions
Components:
- MyMessage: Record type implementing IMessage
- Greeter: Service using NServiceBus.Logging for output
- MyHandler: Message handler with primary constructor for DI
- …
> Add NServiceBus 10 dependency injection externally managed mode sample

- samples/aws/sagas-lambda-aurora/SQSLambda_2/ClientUI/ClientUI.csproj
- samples/aws/sagas-lambda-aurora/SQSLambda_2/DeployDatabase/DeployDatabase.csproj
- samples/aws/sagas-lambda-aurora/SQSLambda_2/Messages/Messages.csproj
- samples/aws/sagas-lambda-aurora/SQSLambda_2/Sales/Sales.csproj
switching from multi target to single target in order to match the CloudFormation template framework value in aws-lambda-tools-defaults.json (since docs engine cannot dynamically inject the target framework when generating different zip files for each targeted framework)
> Update aws/sagas-lambda-aurora sample target framework to match the CloudFormation template

- nservicebus/gateway/multi-site-deployments.md
- nservicebus/gateway/multi-site-deployments_dedup_gateway_[1.0,].partial.md
NServiceBus persistence no longer supports gateway. There is a specific gateway de-duplication persistence abstraction instead. SQL and RavenDB are supported.
> Review gateway multi-site deployment

- samples/hosting/aspire/Core_10/AspireDemo.AppHost/Program.cs
- samples/hosting/aspire/Core_10/AspireDemo.AppHost/appsettings.json
- samples/hosting/aspire/Core_10/Billing/Program.cs
- samples/hosting/aspire/Core_10/ClientUI/Program.cs
- samples/hosting/aspire/Core_10/Sales/Program.cs
- samples/hosting/aspire/Core_10/Shipping/Program.cs
- samples/hosting/aspire/Core_10/Shipping/Shipping.csproj
- samples/hosting/aspire/Core_9/AspireDemo.AppHost/Program.cs
- samples/hosting/aspire/Core_9/AspireDemo.AppHost/appsettings.json
- samples/hosting/aspire/Core_9/Billing/Program.cs
- samples/hosting/aspire/Core_9/ClientUI/Program.cs
- samples/hosting/aspire/Core_9/Sales/Program.cs
- samples/hosting/aspire/Core_9/Shipping/Program.cs
- samples/hosting/aspire/Core_9/Shipping/Shipping.csproj
This enables message and saga auditing for the Aspire demo, making the ServiceInsight features now available in ServicePulse accessible:
> Enable saga and message audit to the .NET Aspire demo

- persistence/sql/dialect-oracle.md
SqlVarient was [replaced by SqlDialect](https://docs.particular.net/persistence/upgrades/sql-2to3#variant-renamed-to-dialect) in v3
> Remove old reference to SqlVarient

- samples/databus/redis/Core_10/BasicRedis.sln
- samples/databus/redis/Core_10/Receiver/ProcessTextHandler.cs
- samples/databus/redis/Core_10/Receiver/Program.cs
- samples/databus/redis/Core_10/Receiver/Receiver.csproj
- samples/databus/redis/Core_10/Sender/Program.cs
- samples/databus/redis/Core_10/Sender/Sender.csproj
- samples/databus/redis/Core_10/Sender/TextSenderHostedService.cs
- samples/databus/redis/Core_10/Shared/Messages/ProcessText.cs
- samples/databus/redis/Core_10/Shared/RedisClaimCheck.cs
- samples/databus/redis/Core_10/Shared/Shared.csproj
- samples/databus/redis/Core_10/docker-compose.yml
- Migrate from .NET 9 to .NET 10 preview
- Update to NServiceBus.Extensions.Hosting 4.0.0-alpha.1
- Update to NServiceBus.ClaimCheck 2.0.0-alpha.1
- Apply modern C# features (async Main methods)
- Add prerelease.txt marker for alpha package usage
Fixes #7292
> Update databus/redis sample to NServiceBus 10

- servicepulse/intro-failed-message-retries.md
This pull request updates the review date in the ServicePulse documentation and makes a minor wording change for clarity.
> Docs review for ServicePulse Intro to Failed Message Retries

- servicepulse/intro-editing-messages.md
Fixing https://github.com/Particular/DeveloperEducation/issues/5723 
From this, 
to this:
> Added the warning instead of caution blurb

- samples/bridge/simple/Bridge_4/Bridge.sln
- samples/bridge/simple/Bridge_4/Bridge/Bridge.csproj
- samples/bridge/simple/Bridge_4/Bridge/Program.cs
- samples/bridge/simple/Bridge_4/LeftReceiver/LeftReceiver.csproj
- samples/bridge/simple/Bridge_4/LeftReceiver/OrderReceivedHandler.cs
- samples/bridge/simple/Bridge_4/LeftReceiver/Program.cs
- samples/bridge/simple/Bridge_4/LeftSender/LeftSender.csproj
- samples/bridge/simple/Bridge_4/LeftSender/OrderResponseHandler.cs
- samples/bridge/simple/Bridge_4/LeftSender/Program.cs
- samples/bridge/simple/Bridge_4/RightReceiver/OrderReceivedHandler.cs
- samples/bridge/simple/Bridge_4/RightReceiver/PlaceOrderHandler.cs
- samples/bridge/simple/Bridge_4/RightReceiver/Program.cs
- samples/bridge/simple/Bridge_4/RightReceiver/RightReceiver.csproj
- samples/bridge/simple/Bridge_4/Shared/LearningTransportInfrastructure.cs
- samples/bridge/simple/Bridge_4/Shared/OrderReceived.cs
- samples/bridge/simple/Bridge_4/Shared/OrderResponse.cs
- samples/bridge/simple/Bridge_4/Shared/PlaceOrder.cs
- samples/bridge/simple/Bridge_4/Shared/Shared.csproj
- Upgraded from .NET 9/8 multi-targeting to .NET 10 (net10.0)
- Updated LangVersion from 12.0 to preview to support latest C# features
- NServiceBus: 9.* → 10.0.0-alpha.1
- NServiceBus.MessagingBridge: 3.* → 4.0.0-alpha.1
- NServiceBus.Extensions.Hosting: 3.0.1 → 4.0.0-alpha.1
- Microsoft.Extensions.Hosting: 8.* → 10.0.0-preview.5.25277.114
- Microsoft.Extensions.Logging.Console: 9.0.2 → 10.0.0-preview.5.25277.114
- Added 'required' modifier to message properties for better null safety
- Added prerelease.txt file to mark this as a prerelease sample
- Updated all project files to use single target framework (net10.0)
- Fixes: #7278
> Update bridge simple sample to NServiceBus 10

- menu/menu.yaml
- transports/upgrades/rabbitmq-10to11.md
This PR adds the RabbitMQ transport 10 to 11 upgrade guide.
Closes #7792
> Add RabbitMQ transport 10 to 11 upgrade guide

- Snippets/ABSDataBus/ABSDataBus_7/ABSDataBus_7.csproj
- Snippets/ASBS/ASBS_3/ASBS_3.csproj
- Snippets/ASBS/ASBS_4/ASBS_4.csproj
- Snippets/ASBS/ASBS_5/ASBS_5.csproj
- Snippets/ASBS/ASBS_6/ASBS_6.csproj
- Snippets/Bridge/Bridge_5/Bridge_5.csproj
- Snippets/GatewaySql/GatewaySql_4/GatewaySql_4.csproj
- Snippets/LearningPersistence/Core_10/Core_10.csproj
- Snippets/LearningTransport/Core_10/Core_10.csproj
- Snippets/PostgreSqlTransport/PostgreSqlTransport_8/PostgreSqlTransport_8.csproj
- Snippets/PostgreSqlTransport/PostgreSqlTransport_9/PostgreSqlTransport_9.csproj
- Snippets/RawMessaging/Core_10/Core_10.csproj
- Snippets/SystemJson/Core_10/Core_10.csproj
- Snippets/TransactionalSession.MongoDB/MongoTS.sln
- Snippets/TransactionalSession.MongoDB/MongoTS_6/MongoTS_6.csproj
- Snippets/TransactionalSession.MongoDB/MongoTS_7/MongoDBConfig.cs
- Snippets/TransactionalSession.MongoDB/MongoTS_7/MongoTS_7.csproj
- Snippets/TransactionalSession.MongoDB/MongoTS_7/MyMessage.cs
- Snippets/Xml/Core_10/Core_10.csproj
This pull request corrects package references in Snippets projects that were using explicit references in lieu of relative (wildcard) references, and updates existing Particular/NServiceBus package references to their latest versions. 
Additionally, NServiceBus.TransactionalSession.MongoDB had a major release (v6) which pushed the NSB 10 version up a major (to v7). The corresponding snippet was not updated, so I fixed the v6 snippets version and created a new v7 version.
> Snippets reference update

- tutorials/quickstart/Solution/ClientUI/wwwroot/Content/app.js
- tutorials/quickstart/tutorial-extending-the-system.md
For
- https://github.com/Particular/DeveloperEducation/issues/4537
> Remove all Universal Analytics (UA) code and event calls
